export const ID_ALREADY_EXISTS = 'ID_ALREADY_EXISTS'
export const ID_NOT_FOUND = 'ID_NOT_FOUND'
export const RELATED_ID_NOT_FOUND = 'RELATED_ID_NOT_FOUND'
export const ORIGIN_USER_ID_NOT_FOUND = 'ORIGIN_USER_ID_NOT_FOUND'
export const DESTINATION_USER_ID_NOT_FOUND = 'DESTINATION_USER_ID_NOT_FOUND'
export const DUPLICATE_ID_IN_BATCH = 'DUPLICATE_ID_IN_BATCH'
export type BatchImportErrorReason =
  | typeof ID_ALREADY_EXISTS
  | typeof DUPLICATE_ID_IN_BATCH
  | typeof RELATED_ID_NOT_FOUND
  | typeof ID_NOT_FOUND
  | typeof ORIGIN_USER_ID_NOT_FOUND
  | typeof DESTINATION_USER_ID_NOT_FOUND
