export const countryMapping: Record<string, string> = {
  russia: 'russia',
  ofac: 'united states of america',
  china: 'china',
  'el salvador': 'el salvador',
  usa: 'united states of america',
  indonesia: 'indonesia',
  australia: 'australia',
  federal: 'united states of america',
  brazil: 'brazil',
  malaysia: 'malaysia',
  india: 'india',
  honduras: 'honduras',
  colombia: 'colombia',
  'south africa': 'south africa',
  singapore: 'singapore',
  'usa state insurance departments': 'united states of america',
  ecuador: 'ecuador',
  international: 'european union',
  chile: 'chile',
  bangladesh: 'bangladesh',
  kenya: 'kenya',
  'united kingdom': 'united kingdom',
  nigeria: 'nigeria',
  turkey: 'turkey',
  nicaragua: 'nicaragua',
  'korea, south': 'south korea',
  'northern macedonia': 'northern macedonia',
  bolivia: 'bolivia',
  pakistan: 'pakistan',
  'hong kong': 'hong kong',
  'iraq national list of terrorist names': 'iraq',
  tajikistan: 'tajikistan',
  france: 'france',
  ukraine: 'ukraine',
  'dominican republic': 'dominican republic',
  philippines: 'philippines',
  canada: 'canada',
  monaco: 'monaco',
  "un security council committee established pursuant to resolution 1718 (2006) concerning democratic people's republic of korea":
    'united nations',
  'european union': 'european union',
  switzerland: 'switzerland',
  'global affairs, government of canada': 'canada',
  sweden: 'sweden',
  italy: 'italy',
  estonia: 'estonia',
  mexico: 'mexico',
  slovakia: 'slovakia',
  spain: 'spain',
  namibia: 'namibia',
  vietnam: 'vietnam',
  netherlands: 'netherlands',
  ireland: 'ireland',
  poland: 'poland',
  japan: 'japan',
  malta: 'malta',
  thailand: 'thailand',
  cyprus: 'cyprus',
  belgium: 'belgium',
  portugal: 'portugal',
  brunei: 'brunei',
  bulgaria: 'bulgaria',
  liechtenstein: 'liechtenstein',
  'british virgin islands financial services commission':
    'british virgin islands',
  finland: 'finland',
  'saudi arabia': 'saudi arabia',
  kazakhstan: 'kazakhstan',
  'new zealand': 'new zealand',
  argentina: 'argentina',
  'chinese ministry of foreign affairs. sanction list': 'china',
  'sanctions based on anti': 'china',
  'cayman islands, the': 'cayman islands',
  austria: 'austria',
  lithuania: 'lithuania',
  taiwan: 'taiwan',
  hungary: 'hungary',
  'bahamas,the': 'bahamas',
  'decisions (rozhodnutí)': 'slovakia',
  germany: 'germany',
  'czech republic': 'czech republic',
  denmark: 'denmark',
  luxembourg: 'luxembourg',
  andorra: 'andorra',
  greece: 'greece',
  state: 'united states of america',
  'united arab emirates': 'united arab emirates',
  egypt: 'egypt',
  'new zealand ministry of foreign affairs & trade': 'new zealand',
  'uk sanctions list': 'united kingdom',
  'australia dfat consolidated list': 'australia',
  'hmt financial sanctions': 'united kingdom',
  rwanda: 'rwanda',
  guatemala: 'guatemala',
  'bosnia and herzegovina': 'bosnia and herzegovina',
  iceland: 'iceland',
  'japan ministry of finance economic sanctions': 'japan',
  romania: 'romania',
  panama: 'panama',
  zambia: 'zambia',
  fiji: 'fiji',
  zimbabwe: 'zimbabwe',
  'usa state security and exchange comissions': 'united states of america',
  latvia: 'latvia',
  'brunei darussalam': 'brunei',
  'designation under section 7031 (c) of the department of state, foreign operations, and related programs appropriations act':
    'united states of america',
  'us department of state': 'united states of america',
  gibraltar: 'gibraltar',
  uzbekistan: 'uzbekistan',
  botswana: 'botswana',
  cases: 'united nations',
  armenia: 'armenia',
  kyrgyzstan: 'kyrgyzstan',
  'azerbaijan financial markets supervision chamber': 'azerbaijan',
  'israel ministry of defence': 'israel',
  slovenia: 'slovenia',
  peru: 'peru',
  iran: 'iran',
  'poland ministry of the interior and administration': 'poland',
  israel: 'israel',
  samoa: 'samoa',
  'south korea': 'south korea',
  'un security council committee established pursuant to resolution 1988 (2011) concerning taliban and associated individuals and entities':
    'united nations',
  'usa state gaming commissions': 'united states of america',
  securities: 'international',
  jamaica: 'jamaica',
  'world bank other sanctions': 'international',
  uganda: 'uganda',
  jordan: 'jordan',
  'japan national public safety commission': 'japan',
  'indonesian list of suspected terrorists and terrorist organizations (dttot)':
    'indonesia',
  mozambique: 'mozambique',
  ethiopia: 'ethiopia',
  'malaysia ministry of home affairs sanction list': 'malaysia',
  qatar: 'qatar',
  'sanctions based on article 4, counter': 'taiwan',
  'warnings and sanctions': 'france',
  'isle of man': 'isle of man',
  'sri lanka': 'sri lanka',
  uae: 'united arab emirates',
  mauritius: 'mauritius',
  belize: 'belize',
  'san marino': 'san marino',
  albania: 'albania',
  'bahrain terrorist list': 'bahrain',
  'public safety, government of canada': 'canada',
  venezuela: 'venezuela',
  ghana: 'ghana',
  tanzania: 'tanzania',
  'trinidad and tobago': 'trinidad and tobago',
  'australian national security': 'australia',
  'list of companies, in accordance with section 1237 of fy99 ndaa':
    'united states of america',
  azerbaijan: 'azerbaijan',
  "un security council committee pursuant to resolutions 1267 (1999) 1989 (2011) and 2253 (2015) concerning isil (da'esh) al":
    'united nations',
  'press releases': 'united states of america',
  'un security council committee established pursuant to resolution 1737 (2006) concerning iran':
    'united nations',
  'list of persons and entities funding the proliferation of weapons of mass destruction (proliferasi wmd)':
    'indonesia',
  norway: 'norway',
  afghanistan: 'afghanistan',
  lesotho: 'lesotho',
  gambia: 'gambia',
  'usa state security and exchange commissions': 'united states of america',
  'public notices of administrative monetary penalties':
    'united states of america',
  algeria: 'algeria',
  malawi: 'malawi',
  paraguay: 'paraguay',
  angola: 'angola',
  'nigeria sanctions committee': 'nigeria',
  moldova: 'moldova',
  tunisia: 'tunisia',
  'list of chinese military companies in accordance with section 1260h of the national defense authorization act for fiscal year 2021':
    'united states of america',
  facfo: 'ukraine',
  lebanon: 'lebanon',
  insurance: 'united states of america',
  'puerto rico': 'puerto rico',
  'list of foreign entities that have been confirmed as engaging in problematic activity as described in section 1286 of the fiscal year 2019 national defense authorization act':
    'united states of america',
  'arrest warrants': 'bosnia and herzegovina',
  'news and media': 'australia',
  'press releases (comunicate de presă)': 'romania',
  'solomon islands': 'solomon islands',
  liberia: 'liberia',
  'netherlands national terrorism sanctions': 'netherlands',
  'sierra leone': 'sierra leone',
  news: 'united states of america',
  'costa rica': 'costa rica',
  'thailand anti': 'thailand',
  'central bank of bangladesh': 'bangladesh',
  'un security council committee established pursuant to resolution 1518 (2003) concerning iraq and kuwait':
    'united nations',
  'new zealand police designated terrorists': 'new zealand',
  'vatican/holy see': 'vatican',
  'news (aktuelt)': 'norway',
  'cook islands': 'cook islands',
  georgia: 'georgia',
  'united kingdom home office list of proscribed terrorist groups':
    'united kingdom',
  bhutan: 'bhutan',
  non: 'united states of america',
  'general licences': 'united kingdom',
  czechia: 'czech republic',
  'security council committee established pursuant to resolution 1521 (2003) concerning liberia (terminated pursuant to resolution 2288 (2016) of 25 may 2016)':
    'united nations',
  'un security council committee established pursuant to resolution 2140 (2014) concerning yemen':
    'united nations',
  'news (noticias)': 'bolivia',
  'bahamas, the': 'bahamas',
  'eswatini (swaziland)': 'eswatini',
  morocco: 'morocco',
  bermuda: 'bermuda',
  'blocked illegal remote gambling sites': 'estonia',
  seychelles: 'seychelles',
  'press release (communiqué de presse), sanctions': 'west african states',
  iraq: 'iraq',
  'the usa': 'united states of america',
  'central bank of the turkish republic of north cyprus': 'cyprus',
  'un security council committee established pursuant to resolution 2374 (2017) concerning mali':
    'united nations',
  'burkina faso': 'burkina faso',
  'news (nieuws)': 'netherlands',
  madagascar: 'madagascar',
  fines: 'european union',
  croatia: 'croatia',
  serbia: 'serbia',
  'international criminal court (icc)': 'international',
  'asian development bank': 'international',
  'judgments (rozsudkov)': 'slovakia',
  tonga: 'tonga',
  bahrain: 'bahrain',
  'un security council committee established pursuant to resolution 2653 (2022) concerning haiti':
    'united nations',
  'un security council committee established pursuant to resolution 1970 (2011) concerning libya':
    'united nations',
  'un security council committee pursuant to resolution 751 (1992) concerning somalia':
    'united nations',
  maldives: 'maldives',
  'un security council committee established pursuant to resolution 2127 (2013) concerning the central african republic':
    'united nations',
  kuwait: 'kuwait',
  'un security council committee established pursuant to resolution 1533 (2004) concerning the democratic republic of the congo':
    'united nations',
  'un security council committee established pursuant to resolution 1591 (2005) concerning the sudan':
    'united nations',
  'cayman islands': 'cayman islands',
  'un security council committee established pursuant to resolution 2048 (2012) concerning guinea':
    'united nations',
  'turks and caicos islands': 'turks and caicos islands',
  other: 'other',
}
