import { TEST_DYNAMODB_TABLE_NAMES } from './src/test-utils/dynamodb-test-utils'

jest.mock('@cdk/constants', () => ({
  StackConstants: {
    TARPON_DYNAMODB_TABLE_NAME: TEST_DYNAMODB_TABLE_NAMES[0],
    TARPON_RULE_DYNAMODB_TABLE_NAME: TEST_DYNAMODB_TABLE_NAMES[1],
    HAMMERHEAD_DYNAMODB_TABLE_NAME: TEST_DYNAMODB_TABLE_NAMES[2],
    TRANSIENT_DYNAMODB_TABLE_NAME: TEST_DYNAMODB_TABLE_NAMES[3],
  },
}))

process.env.RETRY_KINESIS_STREAM_NAME = 'mock-retry-stream'
