version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tarpon"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wl05bmlk5bp"
s3_prefix = "tarpon"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
