#!/usr/bin/env ts-node
/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * This script injects AWS API Gateway specific settings into our internal openapi and output to dist/openapi/openapi-internal-autogenerated.yaml
 */

import * as fs from 'fs'
import * as yaml from 'js-yaml'
import mkdirp from 'mkdirp'
import { StackConstants } from '../constants'
import { getAugmentedOpenapi } from './openapi-augmentor-util'
import { ALLOWED_ORIGINS } from './openapi-internal-constants'

// We don't care about region
const env = (process.env.ENV || 'prod').split(':')[0]

export const ConsoleApiPathToLambda: any = {
  '/tenants': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/settings': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/seed': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/accounts': StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/accounts/{accountId}/change_tenant':
    StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/accounts/{accountId}/settings':
    StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/accounts/{accountId}': StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/me': StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/roles': StackConstants.CONSOLE_API_ROLE_FUNCTION_NAME,
  '/roles/{roleId}': StackConstants.CONSOLE_API_ROLE_FUNCTION_NAME,
  '/apikey': StackConstants.CONSOLE_API_API_KEY_GENERATOR_FUNCTION_NAME,
  '/rules': StackConstants.CONSOLE_API_RULE_FUNCTION_NAME,
  '/rule-filters': StackConstants.CONSOLE_API_RULE_FUNCTION_NAME,
  '/rules/{ruleId}': StackConstants.CONSOLE_API_RULE_FUNCTION_NAME,
  '/rule_instances': StackConstants.CONSOLE_API_RULE_INSTANCE_FUNCTION_NAME,
  '/rule_instances/{ruleInstanceId}':
    StackConstants.CONSOLE_API_RULE_INSTANCE_FUNCTION_NAME,
  '/import': StackConstants.CONSOLE_API_FILE_IMPORT_FUNCTION_NAME,
  '/import/{importId}': StackConstants.CONSOLE_API_FILE_IMPORT_FUNCTION_NAME,
  '/files/getPresignedUrl':
    StackConstants.CONSOLE_API_GET_PRESIGNED_URL_FUNCTION_NAME,
  '/lists': StackConstants.CONSOLE_API_LISTS_FUNCTION_NAME,
  '/lists/{listId}': StackConstants.CONSOLE_API_LISTS_FUNCTION_NAME,
  '/lists/{listId}/items': StackConstants.CONSOLE_API_LISTS_FUNCTION_NAME,
  '/lists/{listId}/items/{key}': StackConstants.CONSOLE_API_LISTS_FUNCTION_NAME,
  '/merchant-monitoring/summary':
    StackConstants.CONSOLE_API_MERCHANT_MONITORING_FUNCTION_NAME,
  '/merchant-monitoring/history':
    StackConstants.CONSOLE_API_MERCHANT_MONITORING_FUNCTION_NAME,
  '/merchant-monitoring/scrape':
    StackConstants.CONSOLE_API_MERCHANT_MONITORING_FUNCTION_NAME,
  '/transactions': StackConstants.CONSOLE_API_TRANSACTIONS_VIEW_FUNCTION_NAME,
  '/transactions/action':
    StackConstants.CONSOLE_API_TRANSACTIONS_VIEW_FUNCTION_NAME,
  '/transactions/stats/by-types':
    StackConstants.CONSOLE_API_TRANSACTIONS_VIEW_FUNCTION_NAME,
  '/transactions/stats/by-time':
    StackConstants.CONSOLE_API_TRANSACTIONS_VIEW_FUNCTION_NAME,
  '/transactions/export':
    StackConstants.CONSOLE_API_TRANSACTIONS_VIEW_FUNCTION_NAME,
  '/transactions/uniques':
    StackConstants.CONSOLE_API_TRANSACTIONS_VIEW_FUNCTION_NAME,
  '/transactions/{transactionId}':
    StackConstants.CONSOLE_API_TRANSACTIONS_VIEW_FUNCTION_NAME,
  '/copilot/narrative': StackConstants.CONSOLE_API_COPILOT_FUNCTION_NAME,
  '/users/{userId}': StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/consumer/users':
    StackConstants.CONSOLE_API_CONSUMER_USERS_VIEW_FUNCTION_NAME,
  '/consumer/users/{userId}':
    StackConstants.CONSOLE_API_CONSUMER_USERS_VIEW_FUNCTION_NAME,
  '/business/users':
    StackConstants.CONSOLE_API_BUSINESS_USERS_VIEW_FUNCTION_NAME,
  '/business/users/{userId}':
    StackConstants.CONSOLE_API_BUSINESS_USERS_VIEW_FUNCTION_NAME,
  '/users/uniques':
    StackConstants.CONSOLE_API_BUSINESS_USERS_VIEW_FUNCTION_NAME,
  '/users': StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/crm':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/entity':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/txn-links':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/screening-status':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/dashboard_stats/transactions':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/drs-distribution':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/hits_per_user':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/rule_hit':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/team':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/overview':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/slack/oauth_redirect': StackConstants.CONSOLE_API_SLACK_APP_FUNCTION_NAME,
  '/webhooks': StackConstants.CONSOLE_API_WEBHOOK_CONFIGURATION_FUNCTION_NAME,
  '/webhooks/{webhookId}':
    StackConstants.CONSOLE_API_WEBHOOK_CONFIGURATION_FUNCTION_NAME,
  '/webhooks/{webhookId}/secret':
    StackConstants.CONSOLE_API_WEBHOOK_CONFIGURATION_FUNCTION_NAME,
  '/webhooks/{webhookId}/deliveries':
    StackConstants.CONSOLE_API_WEBHOOK_CONFIGURATION_FUNCTION_NAME,
  '/pulse/risk-classification':
    StackConstants.CONSOLE_API_RISK_CLASSIFICATION_FUNCTION_NAME,
  '/pulse/risk-assignment':
    StackConstants.CONSOLE_API_MANUAL_USER_RISK_ASSIGNMENT_FUNCTION_NAME,
  '/pulse/risk-parameter':
    StackConstants.CONSOLE_API_PARAMETER_RISK_ASSIGNMENT_FUNCTION_NAME,
  '/pulse/krs-value':
    StackConstants.CONSOLE_API_RISK_LEVEL_AND_SCORE_FUNCTION_NAME,
  '/pulse/ars-value':
    StackConstants.CONSOLE_API_RISK_LEVEL_AND_SCORE_FUNCTION_NAME,
  '/pulse/drs-value':
    StackConstants.CONSOLE_API_RISK_LEVEL_AND_SCORE_FUNCTION_NAME,
  '/auditlog': StackConstants.CONSOLE_API_AUDIT_LOG_FUNCTION_NAME,
  '/cases': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/users/{userId}/caseIds':
    StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/{caseId}/transactions': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/tenant/usageData': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenant/apiKeys': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/cases/assignments': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/reviewAssignments': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/statusChange': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/statusChange': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/assignments': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/reviewAssignments': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/{alertId}/transactions':
    StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/new-case': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/{alertId}': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/{alertId}/comments': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/{alertId}/comments/{commentId}':
    StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/{caseId}': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/{caseId}/comments': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/{caseId}/comments/{commentId}':
    StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/{caseId}/escalate': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/users/{userId}/comments':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/comments/{commentId}':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/webhooks/complyadvantage':
    StackConstants.CONSOLE_API_INCOMING_WEBHOOKS_FUNCTION_NAME,
  '/sanctions/search': StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/sanctions/search/{searchId}':
    StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/sanctions/whitelist': StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/simulation': StackConstants.CONSOLE_API_SIMULATION_FUNCTION_NAME,
  '/simulation/jobs/{jobId}':
    StackConstants.CONSOLE_API_SIMULATION_FUNCTION_NAME,
  '/simulation/tasks/{taskId}/results':
    StackConstants.CONSOLE_API_SIMULATION_FUNCTION_NAME,
  '/simulation/stats': StackConstants.CONSOLE_API_SIMULATION_FUNCTION_NAME,
  '/device-data/transactions':
    StackConstants.CONSOLE_API_DEVICE_DATA_FUNCTION_NAME,
  '/device-data/users': StackConstants.CONSOLE_API_DEVICE_DATA_FUNCTION_NAME,
  '/narrative-template':
    StackConstants.CONSOLE_API_NARRATIVE_TEMPLATE_FUNCTION_NAME,
  '/narrative-template/{narrativeTemplateId}':
    StackConstants.CONSOLE_API_NARRATIVE_TEMPLATE_FUNCTION_NAME,
  '/narrative-templates':
    StackConstants.CONSOLE_API_NARRATIVE_TEMPLATE_FUNCTION_NAME,
  '/report-types': StackConstants.CONSOLE_API_SAR_FUNCTION_NAME,
  '/reports/draft': StackConstants.CONSOLE_API_SAR_FUNCTION_NAME,
  '/reports': StackConstants.CONSOLE_API_SAR_FUNCTION_NAME,
  '/reports/{reportId}': StackConstants.CONSOLE_API_SAR_FUNCTION_NAME,
  '/reports/{reportId}/draft': StackConstants.CONSOLE_API_SAR_FUNCTION_NAME,
  '/checklist-templates':
    StackConstants.CONSOLE_API_CHECKLIST_TEMPLATE_FUNCTION_NAME,
  '/checklist-templates/{checklistTemplateId}':
    StackConstants.CONSOLE_API_CHECKLIST_TEMPLATE_FUNCTION_NAME,
}

const openapi = getAugmentedOpenapi(
  './dist/openapi/internal/openapi-internal-original.yaml',
  ConsoleApiPathToLambda,
  'JWT',
  {
    iamAuthorizedPaths: ['/apikey'],
    publicPaths: ['/slack/oauth_redirect', '/webhooks/complyadvantage'],
    allowedOrigins: ['dev', 'local'].includes(env as string)
      ? ALLOWED_ORIGINS.dev
      : env === 'sandbox'
      ? ALLOWED_ORIGINS.sandbox
      : ALLOWED_ORIGINS.prod,
  }
)

mkdirp.sync(`./dist/openapi`)
fs.writeFileSync(
  `./dist/openapi/openapi-internal-autogenerated-${env}.yaml`,
  yaml.dump(openapi)
)
