#!/usr/bin/env ts-node
/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * This script injects AWS API Gateway specific settings into our internal openapi and output to dist/openapi/openapi-internal-autogenerated.yaml
 */

import * as fs from 'fs'
import * as yaml from 'js-yaml'
import mkdirp from 'mkdirp'
import { StackConstants } from '../constants'
import { getAugmentedOpenapi } from './openapi-augmentor-util'
import { getAllowedOrigins } from './openapi-internal-constants'

// We don't care about region
const env = (process.env.ENV || 'prod').split(':')[0]

export const ConsoleApiPathToLambda: any = {
  '/tenants': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/settings': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/nango-connections': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/settings/narrative-template':
    StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/settings/narrative-template/{narrativeTemplateId}':
    StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/settings/narrative-templates':
    StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/settings/checklist-templates':
    StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/settings/checklist-templates/{checklistTemplateId}':
    StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/settings/sla': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/settings/sla/{slaId}':
    StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/settings/sla/new-sla-id':
    StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/settings/action-reason':
    StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/settings/action-reason/{reasonId}':
    StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/settings/bulk-action-reason':
    StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/delete': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/deletion-data': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/settings/rule-queues':
    StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/settings/rule-queues/{ruleQueueId}':
    StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/batch-job': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/features': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/bulk-rerun-risk-scoring':
    StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenants/secondary-queue-tenants':
    StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/accounts': StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/accounts/{accountId}/change_tenant':
    StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/accounts/{accountId}/settings':
    StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/accounts/{accountId}/resend-invite':
    StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/accounts/{accountId}/reset-password':
    StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/accounts/{accountId}/deactivate':
    StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/accounts/{accountId}': StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/accounts/{accountId}/reset-mfa':
    StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/me': StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/post-login': StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/roles': StackConstants.CONSOLE_API_ROLE_FUNCTION_NAME,
  '/roles/by-name/statements': StackConstants.CONSOLE_API_ROLE_FUNCTION_NAME,
  '/roles/{roleId}': StackConstants.CONSOLE_API_ROLE_FUNCTION_NAME,
  '/permissions': StackConstants.CONSOLE_API_ROLE_FUNCTION_NAME,
  '/apikey': StackConstants.CONSOLE_API_API_KEY_GENERATOR_FUNCTION_NAME,
  '/logic-config': StackConstants.CONSOLE_API_RULE_FUNCTION_NAME,
  '/rule-ml-models': StackConstants.CONSOLE_API_RULE_FUNCTION_NAME,
  '/rule-ml-model/{modelId}': StackConstants.CONSOLE_API_RULE_FUNCTION_NAME,
  '/rules-search': StackConstants.CONSOLE_API_RULE_FUNCTION_NAME,
  '/rules': StackConstants.CONSOLE_API_RULE_FUNCTION_NAME,
  '/rule-instances/import':
    StackConstants.CONSOLE_API_RULE_INSTANCE_FUNCTION_NAME,
  '/rule-filters': StackConstants.CONSOLE_API_RULE_FUNCTION_NAME,
  '/rules/{ruleId}': StackConstants.CONSOLE_API_RULE_FUNCTION_NAME,
  '/rule_instances': StackConstants.CONSOLE_API_RULE_INSTANCE_FUNCTION_NAME,
  '/rule_instances/{ruleInstanceId}':
    StackConstants.CONSOLE_API_RULE_INSTANCE_FUNCTION_NAME,
  '/rule_instances/{ruleInstanceId}/stats':
    StackConstants.CONSOLE_API_RULE_INSTANCE_FUNCTION_NAME,
  '/rule_instance/{ruleInstanceId}/recommendations':
    StackConstants.CONSOLE_API_RULE_INSTANCE_FUNCTION_NAME,
  '/rule-instances/new-rule-id':
    StackConstants.CONSOLE_API_RULE_INSTANCE_FUNCTION_NAME,
  '/version-history/new-version-id/{type}':
    StackConstants.CONSOLE_API_VERSION_HISTORY_FUNCTION_NAME,
  '/version-history': StackConstants.CONSOLE_API_VERSION_HISTORY_FUNCTION_NAME,
  '/version-history/{versionId}':
    StackConstants.CONSOLE_API_VERSION_HISTORY_FUNCTION_NAME,
  '/rule-instances/{ruleInstanceId}/transaction-users-hit':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/rule-instances/rules-with-alerts':
    StackConstants.CONSOLE_API_RULE_INSTANCE_FUNCTION_NAME,
  '/files/getPresignedUrl':
    StackConstants.CONSOLE_API_GET_PRESIGNED_URL_FUNCTION_NAME,
  '/files/getPresignedDownloadUrl/{bucket}/{key}':
    StackConstants.CONSOLE_API_GET_PRESIGNED_URL_FUNCTION_NAME,
  '/lists': StackConstants.CONSOLE_API_LISTS_FUNCTION_NAME,
  '/whitelist': StackConstants.CONSOLE_API_LISTS_FUNCTION_NAME,
  '/whitelist/{listId}': StackConstants.CONSOLE_API_LISTS_FUNCTION_NAME,
  '/whitelist/{listId}/import-csv':
    StackConstants.CONSOLE_API_LISTS_FUNCTION_NAME,
  '/whitelist/{listId}/items': StackConstants.CONSOLE_API_LISTS_FUNCTION_NAME,
  '/whitelist/{listId}/items/{key}':
    StackConstants.CONSOLE_API_LISTS_FUNCTION_NAME,
  '/blacklist': StackConstants.CONSOLE_API_LISTS_FUNCTION_NAME,
  '/blacklist/{listId}': StackConstants.CONSOLE_API_LISTS_FUNCTION_NAME,
  '/blacklist/{listId}/import-csv':
    StackConstants.CONSOLE_API_LISTS_FUNCTION_NAME,
  '/blacklist/{listId}/items': StackConstants.CONSOLE_API_LISTS_FUNCTION_NAME,
  '/blacklist/{listId}/items/{key}':
    StackConstants.CONSOLE_API_LISTS_FUNCTION_NAME,
  '/transactions': StackConstants.CONSOLE_API_TRANSACTIONS_VIEW_FUNCTION_NAME,
  '/transactions/action':
    StackConstants.CONSOLE_API_TRANSACTIONS_VIEW_FUNCTION_NAME,
  '/transactions/stats/by-types':
    StackConstants.CONSOLE_API_TRANSACTIONS_VIEW_FUNCTION_NAME,
  '/transactions/stats/by-time':
    StackConstants.CONSOLE_API_TRANSACTIONS_VIEW_FUNCTION_NAME,
  '/transactions/export':
    StackConstants.CONSOLE_API_TRANSACTIONS_VIEW_FUNCTION_NAME,
  '/transactions/uniques':
    StackConstants.CONSOLE_API_TRANSACTIONS_VIEW_FUNCTION_NAME,
  '/transactions/{transactionId}':
    StackConstants.CONSOLE_API_TRANSACTIONS_VIEW_FUNCTION_NAME,
  '/transactions/{transactionId}/events':
    StackConstants.CONSOLE_API_TRANSACTIONS_VIEW_FUNCTION_NAME,
  '/copilot/narrative': StackConstants.CONSOLE_API_COPILOT_FUNCTION_NAME,
  '/copilot/format': StackConstants.CONSOLE_API_COPILOT_FUNCTION_NAME,
  '/copilot/sources': StackConstants.CONSOLE_API_COPILOT_FUNCTION_NAME,
  '/alert/{alertId}/questions':
    StackConstants.CONSOLE_API_COPILOT_FUNCTION_NAME,
  '/questions/autocomplete': StackConstants.CONSOLE_API_COPILOT_FUNCTION_NAME,
  '/questions/{questionId}/{variableKey}/autocomplete':
    StackConstants.CONSOLE_API_COPILOT_FUNCTION_NAME,
  '/users/{userId}': StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/attachment/{personType}/{userId}/{personId}':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/consumer/users':
    StackConstants.CONSOLE_API_CONSUMER_USERS_VIEW_FUNCTION_NAME,
  '/consumer/users/{userId}':
    StackConstants.CONSOLE_API_CONSUMER_USERS_VIEW_FUNCTION_NAME,
  '/business/users':
    StackConstants.CONSOLE_API_BUSINESS_USERS_VIEW_FUNCTION_NAME,
  '/business/users/{userId}':
    StackConstants.CONSOLE_API_BUSINESS_USERS_VIEW_FUNCTION_NAME,
  '/users/uniques':
    StackConstants.CONSOLE_API_BUSINESS_USERS_VIEW_FUNCTION_NAME,
  '/users': StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users-preview': StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/crm':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/entity':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/entity/linked-users':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/entity/child-users':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/entity/parent-user':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/events':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/txn-links':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/screening-status':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/edd-reviews':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/edd-reviews/{eddReviewId}':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/dashboard_stats/transactions':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/transactions/total':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/users/by_time':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/hits_per_user':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/rule_hit':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/team':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/overview':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/latest_team':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/closing_reason_distribution':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/alert_priority_distribution':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/alert_and_case_status_distribution':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/qa/alerts-by-rule-hit':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/qa/overview':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/qa/alerts-stats-by-checklist-reason':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/qa/alerts-by-assignee':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/transactions/transaction-type-distribution':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/dashboard_stats/team_sla':
    StackConstants.CONSOLE_API_DASHBOARD_STATS_FUNCTION_NAME,
  '/slack/oauth_redirect': StackConstants.CONSOLE_API_SLACK_APP_FUNCTION_NAME,
  '/webhooks': StackConstants.CONSOLE_API_WEBHOOK_CONFIGURATION_FUNCTION_NAME,
  '/webhooks/{webhookId}':
    StackConstants.CONSOLE_API_WEBHOOK_CONFIGURATION_FUNCTION_NAME,
  '/webhooks/{webhookId}/secret':
    StackConstants.CONSOLE_API_WEBHOOK_CONFIGURATION_FUNCTION_NAME,
  '/webhooks/{webhookId}/deliveries':
    StackConstants.CONSOLE_API_WEBHOOK_CONFIGURATION_FUNCTION_NAME,
  '/webhook-deliveries/{deliveryTaskId}/resend':
    StackConstants.CONSOLE_API_WEBHOOK_CONFIGURATION_FUNCTION_NAME,
  '/pulse/risk-classification':
    StackConstants.CONSOLE_API_RISK_CLASSIFICATION_FUNCTION_NAME,
  '/pulse/risk-classification/workflowProposal':
    StackConstants.CONSOLE_API_RISK_CLASSIFICATION_FUNCTION_NAME,
  '/pulse/risk-classification/workflowAction':
    StackConstants.CONSOLE_API_RISK_CLASSIFICATION_FUNCTION_NAME,
  '/risk-factors':
    StackConstants.CONSOLE_API_PARAMETER_RISK_ASSIGNMENT_FUNCTION_NAME,
  '/risk-factors/import':
    StackConstants.CONSOLE_API_PARAMETER_RISK_ASSIGNMENT_FUNCTION_NAME,
  '/risk-factors/{riskFactorId}':
    StackConstants.CONSOLE_API_PARAMETER_RISK_ASSIGNMENT_FUNCTION_NAME,
  '/risk-factors/bulk':
    StackConstants.CONSOLE_API_PARAMETER_RISK_ASSIGNMENT_FUNCTION_NAME,
  '/risk-factors/new-risk-factor-id':
    StackConstants.CONSOLE_API_PARAMETER_RISK_ASSIGNMENT_FUNCTION_NAME,
  '/risk-factors/workflowProposal':
    StackConstants.CONSOLE_API_PARAMETER_RISK_ASSIGNMENT_FUNCTION_NAME,
  '/risk-factors/workflowAction':
    StackConstants.CONSOLE_API_PARAMETER_RISK_ASSIGNMENT_FUNCTION_NAME,
  '/risk-factors/logic':
    StackConstants.CONSOLE_API_PARAMETER_RISK_ASSIGNMENT_FUNCTION_NAME,
  '/pulse/risk-assignment':
    StackConstants.CONSOLE_API_MANUAL_USER_RISK_ASSIGNMENT_FUNCTION_NAME,
  '/pulse/krs-value':
    StackConstants.CONSOLE_API_RISK_LEVEL_AND_SCORE_FUNCTION_NAME,
  '/pulse/average-ars-value':
    StackConstants.CONSOLE_API_RISK_LEVEL_AND_SCORE_FUNCTION_NAME,
  '/pulse/ars-value':
    StackConstants.CONSOLE_API_RISK_LEVEL_AND_SCORE_FUNCTION_NAME,
  '/pulse/drs-value':
    StackConstants.CONSOLE_API_RISK_LEVEL_AND_SCORE_FUNCTION_NAME,
  '/pulse/drs-values':
    StackConstants.CONSOLE_API_RISK_LEVEL_AND_SCORE_FUNCTION_NAME,
  '/auditlog': StackConstants.CONSOLE_API_AUDIT_LOG_FUNCTION_NAME,
  '/cases': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/users/{userId}/caseIds':
    StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/{caseId}/transactions': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/{caseId}/report': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/{caseId}/edd-report': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/tenant/usageData': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/tenant/apiKeys': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/cases/assignments': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/reviewAssignments': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/statusChange': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/comments': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/statusChange': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/assignments': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/reviewAssignments': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/{alertId}/transactions':
    StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/{alertId}/transactions/stats':
    StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/new-case': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/{alertId}': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/{alertId}/comments': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/{alertId}/comments/{commentId}':
    StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/qaSampling': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/qa/{sampleId}/sampling':
    StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/qa-sample-ids': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/{caseId}': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/{caseId}/comments': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/{caseId}/comments/{commentId}':
    StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/cases/{caseId}/escalate': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/users/{userId}/comments':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/comments/{commentId}':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/update-proposal':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/update-proposals':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/update-proposal/{id}':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/users/{userId}/update-proposal/{id}/action':
    StackConstants.CONSOLE_API_ALL_USERS_VIEW_FUNCTION_NAME,
  '/webhooks/auth0': StackConstants.CONSOLE_API_INCOMING_WEBHOOKS_FUNCTION_NAME,
  '/webhooks/nango': StackConstants.CONSOLE_API_INCOMING_WEBHOOKS_FUNCTION_NAME,
  '/sanctions/search': StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/sanctions/search/{searchId}':
    StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/sanctions/hits/search': StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/sanctions/whitelist': StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/sanctions/hits/status': StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/sanctions/activity/stats':
    StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/sanctions/activity/details':
    StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/search-profiles': StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/search-profiles/{searchProfileId}':
    StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/screening-profiles': StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/screening-profiles/{screeningProfileId}':
    StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/default-manual-screening-filters':
    StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/sanctions/sources': StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
  '/simulation': StackConstants.CONSOLE_API_SIMULATION_FUNCTION_NAME,
  '/simulation/jobs/{jobId}':
    StackConstants.CONSOLE_API_SIMULATION_FUNCTION_NAME,
  '/simulation/tasks/{taskId}/results':
    StackConstants.CONSOLE_API_SIMULATION_FUNCTION_NAME,
  '/simulation/stats': StackConstants.CONSOLE_API_SIMULATION_FUNCTION_NAME,
  '/report-types': StackConstants.CONSOLE_API_SAR_FUNCTION_NAME,
  '/reports/draft': StackConstants.CONSOLE_API_SAR_FUNCTION_NAME,
  '/reports': StackConstants.CONSOLE_API_SAR_FUNCTION_NAME,
  '/reports/{reportId}': StackConstants.CONSOLE_API_SAR_FUNCTION_NAME,
  '/reports/{reportId}/draft': StackConstants.CONSOLE_API_SAR_FUNCTION_NAME,
  '/reports/{reportId}/status': StackConstants.CONSOLE_API_SAR_FUNCTION_NAME,
  '/alerts/{alertId}/qa': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/qaStatusChange': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/{alertId}/qaAssignment':
    StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/alerts/{alertId}/checklist': StackConstants.CONSOLE_API_CASE_FUNCTION_NAME,
  '/clueso/token': StackConstants.CONSOLE_API_ACCOUNT_FUNCTION_NAME,
  '/notifications': StackConstants.CONSOLE_API_NOTIFICATIONS_FUNCTION_NAME,
  '/notifications/mark-all-read':
    StackConstants.CONSOLE_API_NOTIFICATIONS_FUNCTION_NAME,
  '/notifications/{notificationId}/read':
    StackConstants.CONSOLE_API_NOTIFICATIONS_FUNCTION_NAME,
  '/crm-records': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/crm-records-search': StackConstants.CONSOLE_API_TENANT_FUNCTION_NAME,
  '/webhooks/internal-proxy':
    StackConstants.CONSOLE_API_INCOMING_WEBHOOKS_FUNCTION_NAME,
  '/workflows/{workflowType}/{workflowId}':
    StackConstants.CONSOLE_API_WORKFLOWS_CASE_FUNCTION_NAME,
  '/workflows': StackConstants.CONSOLE_API_WORKFLOWS_CASE_FUNCTION_NAME,
  '/workflows/{workflowType}':
    StackConstants.CONSOLE_API_WORKFLOWS_CASE_FUNCTION_NAME,
  '/workflows/history/{workflowType}/{workflowId}':
    StackConstants.CONSOLE_API_WORKFLOWS_CASE_FUNCTION_NAME,
  '/workflows/{workflowType}/{workflowId}/{version}':
    StackConstants.CONSOLE_API_WORKFLOWS_CASE_FUNCTION_NAME,
  '/workflows/versions':
    StackConstants.CONSOLE_API_WORKFLOWS_CASE_FUNCTION_NAME,
  '/workflows/{workflowType}/statuses':
    StackConstants.CONSOLE_API_WORKFLOWS_CASE_FUNCTION_NAME,
  '/flat-files/generate-template':
    StackConstants.CONSOLE_API_FLAT_FILES_FUNCTION_NAME,
  '/flat-files/progress': StackConstants.CONSOLE_API_FLAT_FILES_FUNCTION_NAME,
  // TODO: rename CONSOLE_API_WORKFLOWS_CASE_FUNCTION_NAME to make it generic
  '/sanctions/acuris-copywrited-source/download':
    StackConstants.CONSOLE_API_SANCTIONS_FUNCTION_NAME,
}

const openapi = getAugmentedOpenapi(
  './dist/openapi/internal/openapi-internal-original.yaml',
  ConsoleApiPathToLambda,
  'JWT',
  {
    iamAuthorizedPaths: ['/apikey'],
    publicPaths: [
      '/slack/oauth_redirect',
      '/webhooks/auth0',
      '/webhooks/nango',
      '/webhooks/internal-proxy',
    ],
    allowedOrigins: getAllowedOrigins(),
  }
)

mkdirp.sync(`./dist/openapi`)
fs.writeFileSync(
  `./dist/openapi/openapi-internal-autogenerated-${env}.yaml`,
  yaml.dump(openapi)
)
