/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address2 } from './Address2'
export class ACHDetails {
  'method': string
  'routingNumber': string
  'accountNumber': string
  'bankName'?: string
  'name'?: string
  'bankAddress'?: Address2
  'beneficiaryName'?: string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'method',
      baseName: 'method',
      type: 'string',
      format: '',
    },
    {
      name: 'routingNumber',
      baseName: 'routingNumber',
      type: 'string',
      format: '',
    },
    {
      name: 'accountNumber',
      baseName: 'accountNumber',
      type: 'string',
      format: '',
    },
    {
      name: 'bankName',
      baseName: 'bankName',
      type: 'string',
      format: '',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
      format: '',
    },
    {
      name: 'bankAddress',
      baseName: 'bankAddress',
      type: 'Address2',
      format: '',
    },
    {
      name: 'beneficiaryName',
      baseName: 'beneficiaryName',
      type: 'string',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return ACHDetails.attributeTypeMap
  }

  public constructor() {}
}
