/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Business } from './Business'
export class BusinessUsersListResponse {
  'total': number
  'data': Array<Business>

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'total',
      baseName: 'total',
      type: 'number',
      format: '',
    },
    {
      name: 'data',
      baseName: 'data',
      type: 'Array<Business>',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return BusinessUsersListResponse.attributeTypeMap
  }

  public constructor() {}
}
