/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ParameterAttributeRiskValues } from './ParameterAttributeRiskValues'
export class ChangeTenantPayload1 {
  'parameterAttributeRiskValues': ParameterAttributeRiskValues

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'parameterAttributeRiskValues',
      baseName: 'parameterAttributeRiskValues',
      type: 'ParameterAttributeRiskValues',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return ChangeTenantPayload1.attributeTypeMap
  }

  public constructor() {}
}
