/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Amount } from './Amount'
import { Tag } from './Tag'
export class CompanyFinancialDetails {
  'expectedTransactionAmountPerMonth'?: Amount
  'expectedTurnoverPerMonth'?: Amount
  /**
   * Additional information that can be added via tags
   */
  'tags'?: Array<Tag>

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'expectedTransactionAmountPerMonth',
      baseName: 'expectedTransactionAmountPerMonth',
      type: 'Amount',
      format: '',
    },
    {
      name: 'expectedTurnoverPerMonth',
      baseName: 'expectedTurnoverPerMonth',
      type: 'Amount',
      format: '',
    },
    {
      name: 'tags',
      baseName: 'tags',
      type: 'Array<Tag>',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return CompanyFinancialDetails.attributeTypeMap
  }

  public constructor() {}
}
