/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InternalBusinessUser } from './InternalBusinessUser'
import { InternalConsumerUser } from './InternalConsumerUser'
export class DashboardStatsHitsPerUserData {
  'originUserId': string
  'rulesHit': number
  'user'?: InternalConsumerUser | InternalBusinessUser

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'originUserId',
      baseName: 'originUserId',
      type: 'string',
      format: '',
    },
    {
      name: 'rulesHit',
      baseName: 'rulesHit',
      type: 'number',
      format: '',
    },
    {
      name: 'user',
      baseName: 'user',
      type: 'InternalConsumerUser | InternalBusinessUser',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return DashboardStatsHitsPerUserData.attributeTypeMap
  }

  public constructor() {}
}
