/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class DashboardStatsTransactionsCountData {
  '_id': string
  'totalTransactions'?: number
  'flaggedTransactions'?: number
  'stoppedTransactions'?: number

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: '_id',
      baseName: '_id',
      type: 'string',
      format: '',
    },
    {
      name: 'totalTransactions',
      baseName: 'totalTransactions',
      type: 'number',
      format: '',
    },
    {
      name: 'flaggedTransactions',
      baseName: 'flaggedTransactions',
      type: 'number',
      format: '',
    },
    {
      name: 'stoppedTransactions',
      baseName: 'stoppedTransactions',
      type: 'number',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return DashboardStatsTransactionsCountData.attributeTypeMap
  }

  public constructor() {}
}
