/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FileImportStatusChange } from './FileImportStatusChange'
export class FileImport {
  '_id'?: string
  'type': FileImportTypeEnum
  's3Key': string
  'filename': string
  'importedRecords'?: number
  'error'?: string
  'statuses': Array<FileImportStatusChange>

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: '_id',
      baseName: '_id',
      type: 'string',
      format: '',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'FileImportTypeEnum',
      format: '',
    },
    {
      name: 's3Key',
      baseName: 's3Key',
      type: 'string',
      format: '',
    },
    {
      name: 'filename',
      baseName: 'filename',
      type: 'string',
      format: '',
    },
    {
      name: 'importedRecords',
      baseName: 'importedRecords',
      type: 'number',
      format: '',
    },
    {
      name: 'error',
      baseName: 'error',
      type: 'string',
      format: '',
    },
    {
      name: 'statuses',
      baseName: 'statuses',
      type: 'Array<FileImportStatusChange>',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return FileImport.attributeTypeMap
  }

  public constructor() {}
}

export type FileImportTypeEnum = 'TRANSACTION' | 'USER' | 'BUSINESS'
