/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class ImportRequest {
  'type': ImportRequest.TypeEnum
  'format': ImportRequest.FormatEnum
  's3Key': string

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'type',
      baseName: 'type',
      type: 'ImportRequest.TypeEnum',
    },
    {
      name: 'format',
      baseName: 'format',
      type: 'ImportRequest.FormatEnum',
    },
    {
      name: 's3Key',
      baseName: 's3Key',
      type: 'string',
    },
  ]

  static getAttributeTypeMap() {
    return ImportRequest.attributeTypeMap
  }
}

export namespace ImportRequest {
  export enum TypeEnum {
    Transaction = <any>'TRANSACTION',
    User = <any>'USER',
    Business = <any>'BUSINESS',
  }
  export enum FormatEnum {
    Flagright = <any>'flagright',
    Custom = <any>'custom',
  }
}
