/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ManualRiskAssignmentUserStateRiskLevel } from './ManualRiskAssignmentUserStateRiskLevel'
export class ManualRiskAssignmentUserState {
  'isManualOverride': boolean
  'isUpdatable': boolean
  'riskLevel': ManualRiskAssignmentUserStateRiskLevel

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'isManualOverride',
      baseName: 'isManualOverride',
      type: 'boolean',
      format: '',
    },
    {
      name: 'isUpdatable',
      baseName: 'isUpdatable',
      type: 'boolean',
      format: '',
    },
    {
      name: 'riskLevel',
      baseName: 'riskLevel',
      type: 'ManualRiskAssignmentUserStateRiskLevel',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return ManualRiskAssignmentUserState.attributeTypeMap
  }

  public constructor() {}
}
