/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class RuleInstance {
  'id'?: string
  'ruleId': string
  'parameters': object
  'status'?: RuleInstance.StatusEnum
  'createdAt'?: number
  'updatedAt'?: number
  'runCount'?: number
  'hitCount'?: number

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
    },
    {
      name: 'ruleId',
      baseName: 'ruleId',
      type: 'string',
    },
    {
      name: 'parameters',
      baseName: 'parameters',
      type: 'object',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'RuleInstance.StatusEnum',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'number',
    },
    {
      name: 'updatedAt',
      baseName: 'updatedAt',
      type: 'number',
    },
    {
      name: 'runCount',
      baseName: 'runCount',
      type: 'number',
    },
    {
      name: 'hitCount',
      baseName: 'hitCount',
      type: 'number',
    },
  ]

  static getAttributeTypeMap() {
    return RuleInstance.attributeTypeMap
  }
}

export namespace RuleInstance {
  export enum StatusEnum {
    Active = <any>'ACTIVE',
    Inactive = <any>'INACTIVE',
  }
}
