/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class RuleInstance {
  'id'?: string
  'ruleId': string
  'parameters': any
  'status'?: RuleInstanceStatusEnum
  'createdAt'?: number
  'updatedAt'?: number
  'runCount'?: number
  'hitCount'?: number

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
      format: '',
    },
    {
      name: 'ruleId',
      baseName: 'ruleId',
      type: 'string',
      format: '',
    },
    {
      name: 'parameters',
      baseName: 'parameters',
      type: 'any',
      format: '',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'RuleInstanceStatusEnum',
      format: '',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'number',
      format: '',
    },
    {
      name: 'updatedAt',
      baseName: 'updatedAt',
      type: 'number',
      format: '',
    },
    {
      name: 'runCount',
      baseName: 'runCount',
      type: 'number',
      format: '',
    },
    {
      name: 'hitCount',
      baseName: 'hitCount',
      type: 'number',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return RuleInstance.attributeTypeMap
  }

  public constructor() {}
}

export type RuleInstanceStatusEnum = 'ACTIVE' | 'INACTIVE'
