/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class TransactionImportRequest {
  'type': TransactionImportRequest.TypeEnum
  'format': TransactionImportRequest.FormatEnum
  's3Key': string

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'type',
      baseName: 'type',
      type: 'TransactionImportRequest.TypeEnum',
    },
    {
      name: 'format',
      baseName: 'format',
      type: 'TransactionImportRequest.FormatEnum',
    },
    {
      name: 's3Key',
      baseName: 's3Key',
      type: 'string',
    },
  ]

  static getAttributeTypeMap() {
    return TransactionImportRequest.attributeTypeMap
  }
}

export namespace TransactionImportRequest {
  export enum TypeEnum {
    Transaction = <any>'TRANSACTION',
  }
  export enum FormatEnum {
    Flagright = <any>'flagright',
    ShPayment = <any>'sh-payment',
  }
}
