/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExecutedRulesResult } from './ExecutedRulesResult'
import { HitRulesResult } from './HitRulesResult'
export class TransactionWithRulesResultAllOf {
  'executedRules': Array<ExecutedRulesResult>
  'hitRules': Array<HitRulesResult>

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'executedRules',
      baseName: 'executedRules',
      type: 'Array<ExecutedRulesResult>',
      format: '',
    },
    {
      name: 'hitRules',
      baseName: 'hitRules',
      type: 'Array<HitRulesResult>',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return TransactionWithRulesResultAllOf.attributeTypeMap
  }

  public constructor() {}
}
