/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Tag } from './Tag'
/**
 * Standardized model for a Generic wallet transaction
 */
export class WalletDetails {
  /**
   * Type: WALLET
   */
  'method': string
  'walletType': string
  /**
   * Unique ID of the wallet
   */
  'walletId'?: string
  /**
   * Payment Channel used through wallet
   */
  'paymentChannel'?: string
  'name'?: string
  'tags'?: Tag
  'walletPhoneNumber'?: string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'method',
      baseName: 'method',
      type: 'string',
      format: '',
    },
    {
      name: 'walletType',
      baseName: 'walletType',
      type: 'string',
      format: '',
    },
    {
      name: 'walletId',
      baseName: 'walletId',
      type: 'string',
      format: '',
    },
    {
      name: 'paymentChannel',
      baseName: 'paymentChannel',
      type: 'string',
      format: '',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
      format: '',
    },
    {
      name: 'tags',
      baseName: 'tags',
      type: 'Tag',
      format: '',
    },
    {
      name: 'walletPhoneNumber',
      baseName: 'walletPhoneNumber',
      type: 'string',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return WalletDetails.attributeTypeMap
  }

  public constructor() {}
}
