import { useMemo, useState } from 'react';
import { humanizeConstant } from '@flagright/lib/utils/humanize';
import NumberInput from '../../../../library/NumberInput';
import Label from '../../../../library/Label';
import TextInput from '../../../../library/TextInput';
import { H4 } from '../../../../ui/Typography';
import { COLORS_V2_ALERT_CRITICAL } from '../../../../ui/colors';
import Checkbox from '../../../../library/Checkbox';
import { CreateTenantModal } from './CreateTenantModal';
import s from './styles.module.less';
import { useQuery } from '@/utils/queries/hooks';
import {
  TENANT_SETTINGS_UNMASK,
  TENANTS_LIST,
  TENANTS_DELETION_DATA,
  SECONDARY_QUEUE_TENANTS,
} from '@/utils/queries/keys';
import Modal from '@/components/library/Modal';
import { message } from '@/components/library/Message';
import { useApi } from '@/api';
import Button from '@/components/library/Button';
import EyeOutlined from '@/components/ui/icons/Remix/system/eye-line.react.svg';
import Tooltip from '@/components/library/Tooltip';
import {
  BatchJobNames,
  ChatbotNames,
  CrmIntegrationNames,
  Feature,
  Tenant,
  TenantData,
  TenantSettings,
} from '@/apis';
import { clearAuth0LocalStorage, useAccountRole, useAuth0User } from '@/utils/user-utils';
import {
  useFeatures,
  useSettings,
  useUpdateTenantSettings,
  useReloadTenantSettings,
} from '@/components/AppWrapper/Providers/SettingsProvider';
import { BATCH_JOB_NAMESS } from '@/apis/models-custom/BatchJobNames';
import Confirm from '@/components/utils/Confirm';
import { getWhiteLabelBrandingByHost, isWhiteLabeled } from '@/utils/branding';
import Select, { Option } from '@/components/library/Select';
import Tag from '@/components/library/Tag';
import { isSuccess } from '@/utils/asyncResource';
import ExpandContainer from '@/components/utils/ExpandContainer';
import ExpandIcon from '@/components/library/ExpandIcon';
import { CRM_INTEGRATION_NAMESS } from '@/apis/models-custom/CrmIntegrationNames';
import { useSARReportCountries } from '@/components/Sar/utils';
import AsyncResourceRenderer from '@/components/utils/AsyncResourceRenderer';
import { CHATBOT_NAMESS } from '@/apis/models-custom/ChatbotNames';

export enum FeatureTag {
  ENG = 'Eng',
  WIP = 'WIP',
}

export const featureDescriptions: Record<
  Feature,
  { title: string; description: string; tag?: FeatureTag }
> = {
  RISK_LEVELS: {
    title: 'Risk levels',
    description:
      'Enable risk level configuration and display risk levels for users and transactions.',
  },
  RISK_SCORING: {
    title: 'Risk scoring',
    description: 'Calculate and display user and transaction risk scores using configured factors.',
  },
  SLACK_ALERTS: {
    title: 'Slack alerts',
    description: 'Send notifications of new cases to Slack channels.',
  },
  NARRATIVE_COPILOT: {
    title: 'Narrative copilot',
    description: 'AI-assisted drafting and editing of narratives within case management workflows.',
  },
  AI_FORENSICS: {
    title: 'AI forensics',
    description: 'Investigative AI tool for transaction and entity analysis. Requires ClickHouse.',
  },
  SANCTIONS: {
    title: 'Screening',
    description: 'Enable sanctions screening and provider configuration in the console.',
  },
  FALSE_POSITIVE_CHECK: {
    title: 'False positive check',
    description:
      'Widget that shows the estimated likelihood of an alert being a false positive within Case management. Visible in demo mode only.',
  },
  DEMO_MODE: {
    title: 'Demo mode',
    description: 'Enable demo mode with sample data generated by Flagright.',
  },
  SIMULATOR: {
    title: 'Simulator',
    description: 'Run what-if simulations for rules and risk levels without affecting production.',
  },
  CRM: {
    title: 'CRM (Demo use only)',
    description:
      'Show demo CRM data for selected CRM providers (choose CRM provider from Super admin panel). When enabled in production, enables to integrate with CRM providers via Settings -> Add-ons',
  },
  ENTITY_LINKING: {
    title: 'Ontology',
    description:
      'Trace transactional links and pinpoint how funds move across different users and entities',
  },
  ADVANCED_WORKFLOWS: {
    title: 'Advanced workflows',
    description: 'Enable escalations and review workflows in case management.',
  },
  SAR: {
    title: 'SAR',
    description:
      'Generate and manage SAR reports for supported jurisdictions. Once enabled, select desired jurisdiction from Super admin panel.',
  },
  QA: {
    title: 'QA',
    description: 'Enable Quality Assurance workflows and sampling for alert reviews.',
  },
  RULES_ENGINE_V8: {
    title: 'Rules engine V8',
    description: 'Use the latest rules engine for improved performance.',
  },
  NOTIFICATIONS: {
    title: 'Console notifications',
    description: 'Enable in-app notifications and subscription management.',
  },
  RULES_ENGINE_V8_FOR_V2_RULES: {
    title: 'Rules engine V8 for V2 Rules',
    description: 'Run V2 rules on Rules Engine V8 (experimental).',
    tag: FeatureTag.WIP,
  },
  FILES_AI_SUMMARY: {
    title: 'AI attachment summarization',
    description: 'Summarize uploaded attachments using AI (PDF files supported).',
  },
  CLICKHOUSE_ENABLED: {
    title: 'Clickhouse (Beta)',
    description: 'Use ClickHouse as the data store for analytics and forensics (beta).',
  },
  CLICKHOUSE_MIGRATION: {
    title: 'Clickhouse migration',
    description:
      'Enable tooling and UI required to migrate tenants to ClickHouse (engineering only).',
    tag: FeatureTag.ENG,
  },
  MACHINE_LEARNING: {
    title: 'Machine learning',
    description: 'Enable ML models and predictions configured in the Rules module. Demo mode only.',
  },
  ALERT_SLA: {
    title: 'Alerts SLA',
    description: 'Configure and enforce SLA timers for alerts.',
  },
  DOW_JONES: {
    title: 'Dow Jones',
    description: 'Use Dow Jones as the sanctions data provider.',
  },
  LSEG: {
    title: 'LSEG',
    description: 'Enables using LSEG for sanctions',
  },
  OPEN_SANCTIONS: {
    title: 'Open sanctions',
    description: 'Use OpenSanctions as the sanctions data provider.',
  },
  ACURIS: {
    title: 'Acuris',
    description: 'Use KYC6 as the sanctions data provider.',
  },
  ASYNC_RULES: {
    title: 'Async rules',
    description: 'Execute eligible rules asynchronously to reduce processing latency.',
  },
  CONCURRENT_ASYNC_RULES: {
    title: 'Concurrent async rules',
    description: 'Allow multiple async rules to process concurrently (engineering only).',
    tag: FeatureTag.ENG,
  },
  RULES_ENGINE_V8_SYNC_REBUILD: {
    title: 'Rules engine V8 sync rebuild',
    description: 'Enable synchronous rebuild for Rules Engine V8 (engineering only).',
    tag: FeatureTag.ENG,
  },
  PNB: {
    title: 'PNB',
    description: 'Enable PNB-specific capabilities and UI toggles.',
  },
  PNB_DAY_2: {
    title: 'PNB Day 2',
    description: 'Enable additional PNB Day 2 features.',
  },
  NEW_FEATURES: {
    title: 'New features',
    description:
      'Enable globally released features that are hidden due to tenant-specific overrides.',
  },
  MULTI_LEVEL_ESCALATION: {
    title: 'Multi level escalation',
    description: 'Escalate cases through multiple approver levels.',
  },
  STRICT_FILE_SECURITY: {
    title: 'Strict file security',
    description:
      'Block risky file extensions from being uploaded: .xlsx, .xlsm, .xltm. (engineering only)',
    tag: FeatureTag.ENG,
  },
  MANUAL_PRE_AGGREGATION: {
    title: 'Manual pre-aggregation',
    description: 'Require manual triggering of pre-aggregation jobs (engineering only).',
    tag: FeatureTag.ENG,
  },
  MANUAL_DASHBOARD_REFRESH: {
    title: 'Manual dashboard refresh',
    description:
      'Disable auto-refresh on dashboards; refresh must be triggered manually (engineering only)',
    tag: FeatureTag.ENG,
  },
  '314A': {
    title: '314A',
    description: 'Enable 314(a) related rules. Applicable to US customers.',
  },
  CHAINALYSIS: {
    title: 'Chainalysis',
    description: 'Integrate with Chainalysis for blockchain investigations. Demo mode only.',
  },
  EDD: {
    title: 'EDD Rules',
    description: 'Generates EDD alerts in demo mode',
    tag: FeatureTag.ENG,
  },
  WORKFLOWS_BUILDER: {
    title: 'Workflows builder',
    description: 'Design and manage custom workflows in a visual builder (WIP).',
    tag: FeatureTag.WIP,
  },
  TRANSLITERATION: {
    title: "Transliteration (Don't use)",
    description: 'Experimental transliteration for screening names (engineering only).',
    tag: FeatureTag.ENG,
  },
  OPEN_SEARCH: {
    title: 'Opensearch',
    description: 'Use OpenSearch to power screening search queries (engineering only).',
    tag: FeatureTag.ENG,
  },
  CONSOLE_MIGRATION: {
    title: 'Console migration',
    description: 'Migrate case and alert experiences to the new console (WIP).',
    tag: FeatureTag.WIP,
  },

  APPROVAL_WORKFLOWS: {
    title: 'Approval workflows',
    description: 'Require approvals for sensitive actions using configurable workflows.',
    tag: FeatureTag.WIP,
  },
  USER_CHANGES_APPROVAL: {
    title: 'User changes approval',
    description: 'Route user profile changes through approval workflows (WIP).',
    tag: FeatureTag.WIP,
  },
  DISABLE_GLOBAL_AGGREGATIONS: {
    title: 'Disable global aggregations',
    description: 'Turn off global aggregations (use only for tenants not on Rules Engine V2).',
    tag: FeatureTag.ENG,
  },
  EDD_REPORT: {
    title: 'EDD Report',
    description: 'Generate Enhanced Due Diligence reports (WIP).',
    tag: FeatureTag.WIP,
  },
  CRA_LOCK_TIMER: {
    title: 'CRA Lock Timer',
    description: 'Enables automatic CRA lock expiration with user-specified durations',
  },
  CHATBOT: {
    title: 'Chatbot',
    description: 'Enable the embedded chatbot assistant (engineering only).',
    tag: FeatureTag.ENG,
  },
  CUSTOM_AGGREGATION_FIELDS: {
    title: 'Custom aggregation fields',
    tag: FeatureTag.ENG,
    description: 'Aggregate on custom fields such as name, email, or address.',
  },
  FLAT_FILES_IMPORT_TRANSACTIONS: {
    title: 'Flat files import for transactions (WIP)',
    tag: FeatureTag.FLAT_FILES_IMPORT_TRANSACTIONS,
    description: 'Enables button for importing transactions from  flat files',
  },
  MULTIPLEX_ASYNC_RULES_TX: {
    title: 'Multiplex async rules',
    description: 'Multiplex transaction/ transaction events for async rules',
    tag: FeatureTag.ENG,
  },
};

export default function SuperAdminPanel() {
  const [isModalVisible, setIsModalVisible] = useState(false);
  const [showCreateTenantModal, setShowCreateTenantModal] = useState(false);
  const [unmaskDowJonesPassword, setUnmaskDowJonesPassword] = useState<boolean>(false);
  const [saveClicked, setSaveClicked] = useState(false);
  const settings = useSettings();
  const initialFeatures = useFeatures();
  const [features, setFeatures] = useState<Feature[] | undefined>(settings.features?.sort());
  const [limits, setLimits] = useState<TenantSettings['limits']>(settings.limits || {});
  const [tenantIdToDelete, setTenantIdToDelete] = useState<string | undefined>(undefined);
  const [instantDelete, setInstantDelete] = useState<boolean>(false);
  const [containerCollapssed, setContainerCollapssed] = useState<{
    deletionContainer: boolean;
    markedForDeletionContainer: boolean;
    failedToDeleteContainer: boolean;
  }>({
    deletionContainer: true,
    markedForDeletionContainer: true,
    failedToDeleteContainer: true,
  });
  const [downloadFeatureLoading, setDownloadFeatureState] = useState(false);
  const secondaryQueueTenants = useQuery(SECONDARY_QUEUE_TENANTS(), async () => {
    const tenants = await api.getTenantsSecondaryQueueTenants();
    return tenants;
  });
  const isDowJonesToBeEnabled = features?.includes('DOW_JONES');
  const isLSEGToBeEnabled = features?.includes('LSEG');
  const hasExternalSanctionsProvider =
    features?.includes('ACURIS') ||
    features?.includes('OPEN_SANCTIONS') ||
    features?.includes('DOW_JONES') ||
    features?.includes('LSEG');
  const isSanctionsToBeEnabled = features?.includes('SANCTIONS');
  const isCrmToBeEnabled = features?.includes('CRM');
  const isSARToBeEnabled = features?.includes('SAR');
  const isChatbotToBeEnabled = features?.includes('CHATBOT');
  const [sanctionsSettings, setSanctionsSettings] = useState(settings.sanctions);
  const SARCountries = useSARReportCountries(true);
  const [batchJobName, setBatchJobName] = useState<BatchJobNames>('DEMO_MODE_DATA_LOAD');
  const [crmIntegrationName, setCrmIntegrationName] = useState<CrmIntegrationNames | undefined>(
    settings.crmIntegrationName ?? undefined,
  );
  const [sarJurisdictions, setSarJurisdictions] = useState<Array<string>>(
    settings.sarJurisdictions ?? [],
  );
  const [chatbot, setChatbot] = useState<ChatbotNames | undefined>(
    settings.chatbotName ?? undefined,
  );

  const user = useAuth0User();
  const api = useApi();
  const queryResult = useQuery(TENANTS_LIST(), () => api.getTenantsList(), {
    enabled: isModalVisible,
  });

  // Query to fetch settings with unmasked Dow Jones password when needed
  const settingsWithUnmaskQuery = useQuery(
    TENANT_SETTINGS_UNMASK(unmaskDowJonesPassword),
    async () => await api.getTenantsSettings({ unmaskDowJonesPassword }),
    {
      enabled: unmaskDowJonesPassword,
      retry: false,
    },
  );
  const tenants: Array<Tenant & { whitelabel?: { host: string; name: string } }> = useMemo(() => {
    if (isSuccess(queryResult.data)) {
      return (
        queryResult.data.value.map((tenant) => {
          const whitelabelBranding =
            !isWhiteLabeled() && tenant.host ? getWhiteLabelBrandingByHost(tenant.host) : undefined;
          return {
            ...tenant,
            whitelabel: whitelabelBranding
              ? { host: tenant.host as string, name: whitelabelBranding.companyName }
              : undefined,
          };
        }) ?? []
      );
    }
    return [];
  }, [queryResult.data]);
  const tenantOptions: Option<string>[] = useMemo(
    () =>
      tenants.map((tenant) => {
        const tags = [
          <Tag key="id" color="blue">
            id: {tenant.id}
          </Tag>,
          <Tag key="region" color="orange">
            region: {tenant.region || 'eu-1'}
          </Tag>,
          !isWhiteLabeled() && tenant.whitelabel && (
            <Tag key="whitelabel" color="cyan">
              white-label: {tenant.whitelabel.name}
            </Tag>
          ),
        ];

        const option: Option<string> = {
          value: tenant.id,
          label: (
            <div className={s.horizontalSpace}>
              {tenant.name} {tags} {tenant.isProductionAccessDisabled ? '🔒' : ''}
            </div>
          ),
          isDisabled:
            user.allowedRegions?.length && !user.allowedRegions.includes(tenant.region || '')
              ? true
              : false,
          labelText: `${tenant.name} ${tenant.id} ${tenant.region} ${tenant.whitelabel?.name}`,
        };

        return option;
      }),
    [tenants, user.allowedRegions],
  );

  const handleContainerCollapse = (
    container: 'deletionContainer' | 'markedForDeletionContainer' | 'failedToDeleteContainer',
  ) => {
    setContainerCollapssed((prev) => ({ ...prev, [container]: !prev[container] }));
  };
  const handleChangeTenant = async (newTenantId: string) => {
    if (user.tenantId === newTenantId) {
      return;
    }
    const tenant = tenants.find((t) => t.id === newTenantId);
    if (tenant?.whitelabel) {
      window.open(`https://${tenant.whitelabel.host}`, '_blank');
      return;
    }

    const unsetDemoMode = api.accountChangeSettings({
      accountId: user.userId,
      AccountSettings: {
        demoMode: false,
      },
    });
    const hideMessage = message.loading('Changing Tenant...');
    try {
      await api.accountsChangeTenant({
        accountId: user.userId,
        ChangeTenantPayload: {
          newTenantId,
        },
      });
      await unsetDemoMode;
      clearAuth0LocalStorage();
      window.location.reload();
    } catch (e) {
      message.fatal('Failed to switch tenant', e);
    } finally {
      hideMessage();
    }
  };

  const handlePullAllTenantsFeatures = async () => {
    const features = await api.getTenantsFeatures();

    const csvContent =
      `Tenant ID, Tenant Name, Region, ${Object.entries(featureDescriptions)
        .map(([_, value]) => value.title)
        .join(',')}\n` +
      // if feature is enabled, add Y, otherwise add N
      features
        .map(
          (feature) =>
            `${feature.tenantId},${feature.tenantName},${feature.region},${Object.entries(
              featureDescriptions,
            )
              .map(([featureKey]) => (feature.features.includes(featureKey as Feature) ? 'Y' : 'N'))
              .join(',')}`,
        )
        .join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `tenant_features-${new Date().toISOString()}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const tenantsDeletionQueryResult = useQuery(TENANTS_DELETION_DATA(), async () => {
    return await api.getTenantsDeletionData();
  });

  const { tenantsDeletedRecently, tenantsFailedToDelete, tenantsMarkedForDelete } = useMemo(() => {
    if (isSuccess(tenantsDeletionQueryResult.data)) {
      return tenantsDeletionQueryResult.data.value;
    }
    return {};
  }, [tenantsDeletionQueryResult.data]);
  const mutateTenantSettings = useUpdateTenantSettings();
  const reloadUpdatedSettings = useReloadTenantSettings();
  const handleSave = async () => {
    setSaveClicked(true);
    mutateTenantSettings.mutate({
      ...(features && { features }),
      ...(limits && { limits }),
      sanctions: sanctionsSettings,
      crmIntegrationName,
      sarJurisdictions,
      chatbotName: chatbot,
    });
  };
  const showModal = () => {
    setIsModalVisible(true);
  };

  const handleCancel = () => {
    setIsModalVisible(false);
    if (saveClicked) {
      reloadUpdatedSettings.mutate({
        ...(features && { features }),
        ...(limits && { limits }),
        sanctions: sanctionsSettings,
        crmIntegrationName,
        sarJurisdictions,
      });
    }
    setSaveClicked(false);
    setFeatures(settings.features?.sort());
    setLimits(settings.limits || {});
    setTenantIdToDelete(undefined);
    setInstantDelete(false);
    setContainerCollapssed({
      deletionContainer: true,
      markedForDeletionContainer: true,
      failedToDeleteContainer: true,
    });
    setDownloadFeatureState(false);
    setSanctionsSettings(settings.sanctions);
    setCrmIntegrationName(settings.crmIntegrationName ?? undefined);
    setSarJurisdictions(settings.sarJurisdictions ?? []);
    setBatchJobName('DEMO_MODE_DATA_LOAD');
  };

  let batchJobMessage;
  const role = useAccountRole();
  return (
    <>
      <Button size="SMALL" onClick={showModal} testName="superadmin-panel-button">
        {user.tenantName}
      </Button>
      <Modal
        title="Super admin panel"
        width="L"
        isOpen={isModalVisible}
        okText={role === 'root' ? 'Save' : undefined}
        onCancel={handleCancel}
        onOk={role === 'root' ? handleSave : undefined}
        destroyOnClose
      >
        <Label label="Tenant" testId="tenant-name">
          <Select
            isDisabled={tenantOptions.length === 0}
            options={tenantOptions}
            onChange={(v) => v && handleChangeTenant(v)}
            value={user.tenantId}
          />
          <div>
            Current tenant ID: <b>{`${user.tenantId}`}</b>
          </div>
        </Label>
        {role === 'root' && (
          <div className={s.rootSettingsContainer}>
            <br />
            <div className={s.buttonWrapper}>
              <Button
                type="PRIMARY"
                size="MEDIUM"
                onClick={() => {
                  setShowCreateTenantModal(true);
                  handleCancel();
                }}
              >
                Create new tenant
              </Button>
            </div>

            {tenantsDeletedRecently?.length ? (
              <ListTenants
                tenants={tenantsDeletedRecently}
                label="Tenants recently deleted in last 30 days"
                containerCollapsed={containerCollapssed.deletionContainer}
                onClick={() => handleContainerCollapse('deletionContainer')}
              />
            ) : (
              <></>
            )}
            {tenantsMarkedForDelete?.length ? (
              <ListTenants
                tenants={tenantsMarkedForDelete}
                label="Tenants marked for delete"
                containerCollapsed={containerCollapssed.markedForDeletionContainer}
                onClick={() => handleContainerCollapse('markedForDeletionContainer')}
              />
            ) : (
              <></>
            )}
            {tenantsFailedToDelete?.length ? (
              <ListTenants
                tenants={tenantsFailedToDelete}
                label="Tenants failed to delete "
                containerCollapsed={containerCollapssed.failedToDeleteContainer}
                onClick={() => handleContainerCollapse('failedToDeleteContainer')}
              />
            ) : (
              <></>
            )}
            <div className={s.divider} />
            <Label
              label="Features"
              description="Enabled features of the tenant"
              testId="features-select"
            >
              <Select<Feature>
                mode="MULTIPLE"
                onChange={(v) => setFeatures(v ?? [])}
                allowClear
                isDisabled={!initialFeatures}
                options={Object.entries(featureDescriptions)
                  .sort(([, a], [, b]) => a.title.trim().localeCompare(b.title.trim()))
                  .map(([key, { title, tag, description }]) => ({
                    value: key as Feature,
                    label: (
                      <span title={description}>
                        {title}
                        {tag ? ` (${tag})` : ''}
                      </span>
                    ),
                    labelText: description,
                    title: description,
                  }))}
                value={features || initialFeatures}
                onDropdownVisibleChange={(visible) => {
                  if (!visible) {
                    setFeatures((f) => f?.sort() ?? []);
                  }
                }}
              />
            </Label>

            <Label
              label="Max Seats"
              description="The maximum number of seats allowed for this tenant"
            >
              <NumberInput
                value={limits?.seats ?? 0}
                onChange={(value) => setLimits({ ...limits, seats: value })}
                isDisabled={false}
              />
            </Label>

            {isCrmToBeEnabled && (
              <Label label="Select a CRM">
                <Select
                  options={CRM_INTEGRATION_NAMESS.map((name) => ({
                    label: humanizeConstant(name),
                    value: name,
                  }))}
                  value={crmIntegrationName}
                  onChange={(v) => v && setCrmIntegrationName(v)}
                />
              </Label>
            )}

            {isSARToBeEnabled && (
              <Label label="Select SAR jurisdictions">
                <Select<string>
                  mode="MULTIPLE"
                  options={SARCountries.map((sarCountry) => ({
                    label: humanizeConstant(sarCountry.country),
                    value: sarCountry.countryCode,
                  }))}
                  value={
                    sarJurisdictions.length === 0
                      ? SARCountries?.map((country) => country.countryCode)
                      : sarJurisdictions
                  }
                  onChange={(v) => v && setSarJurisdictions(v)}
                />
              </Label>
            )}

            {isChatbotToBeEnabled && (
              <Label label="Select chatbot">
                <Select
                  options={CHATBOT_NAMESS.map((chatbot) => ({
                    label: humanizeConstant(chatbot),
                    value: chatbot,
                  }))}
                  value={chatbot}
                  onChange={(v) => v && setChatbot(v)}
                />
              </Label>
            )}

            {isSanctionsToBeEnabled && !hasExternalSanctionsProvider ? (
              <></>
            ) : isLSEGToBeEnabled ? (
              <Label label="LSEG settings">
                <Label level={2} label="Username" required={{ value: true, showHint: true }}>
                  <TextInput
                    value={sanctionsSettings?.lsegCreds?.username}
                    onChange={(value) => {
                      setSanctionsSettings({
                        ...sanctionsSettings,
                        lsegCreds: {
                          ...sanctionsSettings?.lsegCreds,
                          username: value || '',
                        },
                      });
                    }}
                  />
                </Label>
                <Label level={2} label="Password" required={{ value: true, showHint: true }}>
                  <TextInput
                    value={sanctionsSettings?.lsegCreds?.password}
                    onChange={(value) => {
                      setSanctionsSettings({
                        ...sanctionsSettings,
                        lsegCreds: {
                          ...sanctionsSettings?.lsegCreds,
                          password: value || '',
                        },
                      });
                    }}
                  />
                </Label>
              </Label>
            ) : isDowJonesToBeEnabled ? (
              <Label label="Dow Jones settings">
                <Label level={2} label="Username" required={{ value: true, showHint: true }}>
                  <TextInput
                    value={sanctionsSettings?.dowjonesCreds?.username}
                    onChange={(value) => {
                      setSanctionsSettings({
                        ...sanctionsSettings,
                        dowjonesCreds: {
                          ...sanctionsSettings?.dowjonesCreds,
                          username: value || '',
                        },
                      });
                    }}
                  />
                </Label>
                <Label level={2} label="Password" required={{ value: true, showHint: true }}>
                  <div className={s.passwordFieldContainer}>
                    <TextInput
                      className={s.passwordInput}
                      value={
                        unmaskDowJonesPassword && isSuccess(settingsWithUnmaskQuery.data)
                          ? settingsWithUnmaskQuery.data.value.sanctions?.dowjonesCreds?.password
                          : sanctionsSettings?.dowjonesCreds?.password
                      }
                      onChange={(value) => {
                        // Only allow editing when password is masked (not unmasked)
                        if (!unmaskDowJonesPassword || !isSuccess(settingsWithUnmaskQuery.data)) {
                          setSanctionsSettings({
                            ...sanctionsSettings,
                            dowjonesCreds: {
                              ...sanctionsSettings?.dowjonesCreds,
                              password: value || '',
                            },
                          });
                        }
                      }}
                      htmlAttrs={{
                        type:
                          unmaskDowJonesPassword && isSuccess(settingsWithUnmaskQuery.data)
                            ? 'text'
                            : 'password',
                        readOnly: unmaskDowJonesPassword && isSuccess(settingsWithUnmaskQuery.data),
                      }}
                    />
                    {sanctionsSettings?.dowjonesCreds?.password?.includes('*') && (
                      <div className={s.eyeIconWrapper}>
                        <Tooltip
                          title={
                            unmaskDowJonesPassword
                              ? 'Click to hide password'
                              : 'Click to view password'
                          }
                          placement="top"
                        >
                          <EyeOutlined
                            className={s.eyeIcon}
                            height={16}
                            width={16}
                            onClick={() => {
                              setUnmaskDowJonesPassword(!unmaskDowJonesPassword);
                            }}
                          />
                        </Tooltip>
                      </div>
                    )}
                  </div>
                </Label>
              </Label>
            ) : (
              <></>
            )}
            <div className={s.divider} />
            <Label label="Run batch job">
              <Select
                options={BATCH_JOB_NAMESS.map((name) => ({
                  label: humanizeConstant(name),
                  value: name,
                }))}
                value={batchJobName}
                onChange={(v) => v && setBatchJobName(v)}
              />
            </Label>
            <Confirm
              title={`Run ${humanizeConstant(batchJobName)}?`}
              onConfirm={async () => {
                batchJobMessage = message.loading(`Starting ${humanizeConstant(batchJobName)}...`);
                try {
                  await api.postTenantsTriggerBatchJob({
                    TenantTriggerBatchJobRequest: {
                      jobName: batchJobName,
                    },
                  });
                  message.success(process.env.ENV_NAME === 'local' ? 'Done' : 'Submitted');
                } catch (e) {
                  message.fatal(e);
                } finally {
                  batchJobMessage();
                }
              }}
              text={`Are you sure you want to run ${humanizeConstant(batchJobName)} batch job?`}
              onSuccess={() => {
                batchJobMessage();
                message.success(`${humanizeConstant(batchJobName)} started successfully`);
              }}
            >
              {(props) => (
                <div className={s.buttonWrapper}>
                  <Button isDisabled={!batchJobName} type={'PRIMARY'} onClick={props.onClick}>
                    Run
                  </Button>
                </div>
              )}
            </Confirm>

            <div className={s.divider} />
            <Label
              label="Simulation limit"
              description="The maximum number of simulations that can be run by a tenant"
            >
              <NumberInput
                value={limits?.simulations ?? 0}
                onChange={(value) => setLimits({ ...limits, simulations: value })}
                isDisabled={false}
              />
            </Label>

            <Label
              label="Maximum times api key can be viewed"
              description="The maximum number of times the api key can be viewed by a tenant"
            >
              <NumberInput
                value={limits?.apiKeyView ?? 0}
                onChange={(value) => setLimits({ ...limits, apiKeyView: value })}
                isDisabled={false}
              />
            </Label>
            <div className={s.buttonWrapper}>
              <Button
                type="PRIMARY"
                onClick={() =>
                  mutateTenantSettings.mutate({
                    apiKeyViewData: [],
                  })
                }
              >
                Reset current API key view count
              </Button>
            </div>
            <Label label="Rerun risk scoring limit">
              <NumberInput
                value={limits?.rerunRiskScoringLimit ?? 0}
                onChange={(value) => setLimits({ ...limits, rerunRiskScoringLimit: value })}
                isDisabled={false}
              />
            </Label>

            <div className={s.divider} />
            <Label label="Secondary queue tenants">
              <AsyncResourceRenderer resource={secondaryQueueTenants.data}>
                {(data) => (
                  <Select
                    mode="MULTIPLE"
                    options={tenantOptions}
                    onChange={async (value) => {
                      if (value) {
                        await api.postTenantsSecondaryQueueTenants({
                          SecondaryQueueTenants: { tenants: value },
                        });
                        message.success('Tenants added to secondary queue');
                        secondaryQueueTenants.refetch();
                      }
                    }}
                    value={data?.tenants?.map((tenant) => tenant)}
                    placeholder="Select tenant to add to secondary queue"
                    width="100%"
                  />
                )}
              </AsyncResourceRenderer>
            </Label>
            <br />
            {user.allowTenantDeletion && (
              <>
                <H4 style={{ color: COLORS_V2_ALERT_CRITICAL }}>Danger Zone</H4>
                <div style={{ display: 'flex', gap: '1rem' }}>
                  <Label
                    label="Tenant to delete"
                    description="Please go to the respective tenant region to delete the tenant (for example if tenant is in `us-1` region, go to `us-1` region you need to be in a different tenant then the tenant you want to delete)"
                  >
                    <Select
                      width={'20rem'}
                      options={tenantOptions}
                      onChange={(value) => setTenantIdToDelete(value)}
                      value={tenantIdToDelete}
                      placeholder="Select tenant to delete"
                    />
                  </Label>
                  <Label label="Instant delete">
                    <Checkbox
                      value={instantDelete}
                      onChange={(value) => {
                        if (value != null) {
                          setInstantDelete(value);
                        }
                      }}
                    />
                  </Label>
                </div>
                <Confirm
                  title="Delete tenant?"
                  onConfirm={async () => {
                    batchJobMessage = message.loading(`Deleting tenant...`);
                    if (!tenantIdToDelete) {
                      message.error('No tenant selected');
                      return;
                    }

                    if (tenantIdToDelete === user.tenantId) {
                      message.error('Cannot delete current tenant');
                      return;
                    }

                    if (tenantIdToDelete?.includes('flagright')) {
                      message.error('Cannot delete tenant');
                      return;
                    }

                    try {
                      await api.deleteTenant({
                        DeleteTenant: {
                          tenantId: tenantIdToDelete,
                          notRecoverable: instantDelete,
                        },
                      });
                    } catch (e) {
                      message.error(
                        `Failed to delete tenant ${tenantIdToDelete}: Message: ${
                          (e as Error).message
                        }`,
                      );
                      batchJobMessage();
                      return;
                    }

                    batchJobMessage();
                    window.location.reload();
                  }}
                  text={`Are you sure you want to delete ${tenantIdToDelete} tenant?`}
                  onSuccess={() => {
                    batchJobMessage();
                    message.success(`${tenantIdToDelete} deleted successfully`);
                  }}
                >
                  {(props) => (
                    <Button isDisabled={!tenantIdToDelete} type={'DANGER'} onClick={props.onClick}>
                      Delete
                    </Button>
                  )}
                </Confirm>
                <br />
                <Confirm
                  title={`${settings.isAccountSuspended ? 'Unsuspend' : 'Suspend'} tenant: ${
                    user.tenantName
                  } (${user.tenantId})`}
                  onConfirm={async () => {
                    mutateTenantSettings.mutate({
                      isAccountSuspended: !(settings.isAccountSuspended ?? false),
                    });
                  }}
                  text={`Are you sure you want to ${
                    settings.isAccountSuspended ? 'unsuspend' : 'suspend'
                  } tenant: ${user.tenantName} (${user.tenantId})?`}
                  onSuccess={() => {
                    message.success(
                      `${user.tenantName} (${user.tenantId}) ${
                        settings.isAccountSuspended ? 'unsuspended' : 'suspended'
                      }`,
                    );
                  }}
                >
                  {(props) => (
                    <Button type={'DANGER'} onClick={props.onClick}>
                      {settings.isAccountSuspended ? 'Unsuspend' : 'Suspend'} account
                    </Button>
                  )}
                </Confirm>
                <br />
              </>
            )}
            <div className={s.buttonWrapper}>
              <Button
                type={'PRIMARY'}
                onClick={async () => {
                  try {
                    setDownloadFeatureState(true);
                    message.info('Pulling features config');
                    await handlePullAllTenantsFeatures();
                  } catch (e) {
                    message.error(`Failed to download features config ${e}`);
                  } finally {
                    setDownloadFeatureState(false);
                  }
                }}
                isLoading={downloadFeatureLoading}
              >
                Download features config
              </Button>
            </div>
          </div>
        )}
      </Modal>
      <CreateTenantModal
        visible={showCreateTenantModal}
        onClose={() => setShowCreateTenantModal(false)}
      />
    </>
  );
}

const ListTenants = ({
  tenants,
  label,
  containerCollapsed,
  onClick,
}: {
  tenants: TenantData[];
  label: string;
  containerCollapsed: boolean;
  onClick: () => void;
}) => {
  return (
    <Label
      label={`${label} (${tenants.length})`}
      iconRight={
        <ExpandIcon
          isExpanded={!containerCollapsed}
          color="BLACK"
          onClick={onClick}
          cursor="pointer"
        />
      }
    >
      <ExpandContainer isCollapsed={containerCollapsed}>
        <div className={s.horizontalSpaceWrap}>
          {tenants.map((tenant, index) => (
            <Tag color={'warning'} key={index}>
              {tenant.tenantName ? tenant.tenantName : tenant.tenantId} ({tenant.tenantId})
            </Tag>
          ))}
        </div>
      </ExpandContainer>
    </Label>
  );
};
