import { CardMerchantDetails } from '@/@types/openapi-public-management/CardMerchantDetails'

export const Merchant: CardMerchantDetails[] = [
  {
    name: 'Arun General Traders',
    category: 'RETAIL',
    mcc: '5311',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    country: 'IN',
    postcode: '221001',
  } as CardMerchantDetails,
  {
    name: 'QuickMart Express',
    category: 'GROCERY',
    mcc: '5411',
    city: 'Toronto',
    state: 'Ontario',
    country: 'CA',
    postcode: 'M5V 2N8',
  } as CardMerchantDetails,
  {
    name: 'FuelNow Station 42',
    category: 'GAS',
    mcc: '5541',
    city: 'Phoenix',
    state: 'Arizona',
    country: 'US',
    postcode: '85001',
  } as CardMerchantDetails,
  {
    name: 'ZonoShop',
    category: 'ECOMMERCE',
    mcc: '5969',
    city: 'Berlin',
    state: 'Berlin',
    country: 'DE',
    postcode: '10117',
  } as CardMerchantDetails,
  {
    name: 'Grand Palace Inn',
    category: 'HOTEL',
    mcc: '7011',
    city: 'Bangkok',
    state: 'Bangkok',
    country: 'TH',
    postcode: '10200',
  } as CardMerchantDetails,
  {
    name: 'Sky High Travels',
    category: 'TRAVEL',
    mcc: '4722',
    city: 'London',
    state: 'England',
    country: 'GB',
    postcode: 'W1B 3AG',
  } as CardMerchantDetails,
  {
    name: 'MetroCab Services',
    category: 'TRANSPORTATION',
    mcc: '4121',
    city: 'New York',
    state: 'NY',
    country: 'US',
    postcode: '10001',
  } as CardMerchantDetails,
  {
    name: 'CineLux Multiplex',
    category: 'ENTERTAINMENT',
    mcc: '7832',
    city: 'Los Angeles',
    state: 'California',
    country: 'US',
    postcode: '90001',
  } as CardMerchantDetails,
  {
    name: 'Everest Outfitters',
    category: 'RETAIL',
    mcc: '5651',
    city: 'Kathmandu',
    state: 'Bagmati',
    country: 'NP',
    postcode: '44600',
  } as CardMerchantDetails,
  {
    name: 'Desert Fuel Ltd',
    category: 'GAS',
    mcc: '5542',
    city: 'Dubai',
    state: 'Dubai',
    country: 'AE',
    postcode: '00000',
  } as CardMerchantDetails,
  {
    name: 'GreenGrocery Mart',
    category: 'GROCERY',
    mcc: '5411',
    city: 'Sydney',
    state: 'New South Wales',
    country: 'AU',
    postcode: '2000',
  } as CardMerchantDetails,
  {
    name: 'JetEase Booking',
    category: 'TRAVEL',
    mcc: '4722',
    city: 'Singapore',
    state: 'Central Region',
    country: 'SG',
    postcode: '018989',
  } as CardMerchantDetails,
  {
    name: 'Ocean Drive Hotel',
    category: 'HOTEL',
    mcc: '7011',
    city: 'Miami',
    state: 'Florida',
    country: 'US',
    postcode: '33139',
  } as CardMerchantDetails,
  {
    name: 'GroSnap Online',
    category: 'ECOMMERCE',
    mcc: '5969',
    city: 'Dublin',
    state: 'Leinster',
    country: 'IE',
    postcode: 'D02',
  } as CardMerchantDetails,
  {
    name: 'BuzzMusic Events',
    category: 'ENTERTAINMENT',
    mcc: '7922',
    city: 'Barcelona',
    state: 'Catalonia',
    country: 'ES',
    postcode: '08001',
  } as CardMerchantDetails,
  {
    name: 'StarBus Transport',
    category: 'TRANSPORTATION',
    mcc: '4111',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'IN',
    postcode: '400001',
  } as CardMerchantDetails,
  {
    name: 'Nile River Cruises',
    category: 'TRAVEL',
    mcc: '4411',
    city: 'Cairo',
    state: 'Cairo',
    country: 'EG',
    postcode: '11511',
  } as CardMerchantDetails,
  {
    name: 'CloudGroceries',
    category: 'ECOMMERCE',
    mcc: '5969',
    city: 'Stockholm',
    state: 'Stockholm County',
    country: 'SE',
    postcode: '11120',
  } as CardMerchantDetails,
  {
    name: 'PetrolX',
    category: 'GAS',
    mcc: '5541',
    city: 'Mexico City',
    state: 'CDMX',
    country: 'MX',
    postcode: '01000',
  } as CardMerchantDetails,
  {
    name: 'Arctic Adventures',
    category: 'ENTERTAINMENT',
    mcc: '7999',
    city: 'Reykjavik',
    state: 'Capital Region',
    country: 'IS',
    postcode: '101',
  } as CardMerchantDetails,
]
