// According to https://www.iso.org/iso-3166-country-codes.html
export const COUNTRIES = {
  AF: 'Afghanistan',
  AL: 'Albania',
  DZ: 'Algeria',
  AS: 'American Samoa',
  AD: 'Andorra',
  AO: 'Angola',
  AI: 'Anguilla',
  AQ: 'Antarctica',
  AG: 'Antigua and Barbuda',
  AR: 'Argentina',
  AM: 'Armenia',
  AW: 'Aruba',
  AU: 'Australia',
  AT: 'Austria',
  AZ: 'Azerbaijan',
  BS: 'Bahamas', // original: 'Bahamas (the)'
  BH: 'Bahrain',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BY: 'Belarus',
  BE: 'Belgium',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermuda',
  BT: 'Bhutan',
  BO: 'Bolivia', // original: BO: 'Bolivia (Plurinational State of)'
  BQ: 'Bonaire, Sint Eustatius and Saba',
  BA: 'Bosnia and Herzegovina',
  BW: 'Botswana',
  BV: 'Bouvet Island',
  BR: 'Brazil',
  IO: 'British Indian Ocean Territory', // original: 'British Indian Ocean Territory (the)'
  BN: 'Brunei Darussalam',
  BG: 'Bulgaria',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  CV: 'Cabo Verde',
  KH: 'Cambodia',
  CM: 'Cameroon',
  CA: 'Canada',
  KY: 'Cayman Islands', // original: 'Cayman Islands (the)'
  CF: 'Central African Republic', // original: 'Central African Republic (the)'
  TD: 'Chad',
  CL: 'Chile',
  CN: 'China',
  CX: 'Christmas Island',
  CC: 'Cocos Islands', // original: 'Cocos (Keeling) Islands (the)'
  CO: 'Colombia',
  KM: 'Comoros', // original: 'Comoros (the)'
  CD: 'Congo', // original: 'Congo (the Democratic Republic of the)'
  CG: 'Congo', // original: 'Congo (the)'
  CK: 'Cook Islands', // original: 'Cook Islands (the)'
  CR: 'Costa Rica',
  HR: 'Croatia',
  CU: 'Cuba',
  CW: 'Curaçao',
  CY: 'Cyprus',
  CZ: 'Czechia',
  CI: "Côte d'Ivoire",
  DK: 'Denmark',
  DJ: 'Djibouti',
  DM: 'Dominica',
  DO: 'Dominican Republic', // original: 'Dominican Republic (the)'
  EC: 'Ecuador',
  EG: 'Egypt',
  SV: 'El Salvador',
  GQ: 'Equatorial Guinea',
  ER: 'Eritrea',
  EE: 'Estonia',
  SZ: 'Eswatini',
  ET: 'Ethiopia',
  FK: 'Falkland Islands', // original: 'Falkland Islands (the) [Malvinas]',
  FO: 'Faroe Islands', // original: 'Faroe Islands (the)'
  FJ: 'Fiji',
  FI: 'Finland',
  FR: 'France',
  GF: 'French Guiana',
  PF: 'French Polynesia',
  TF: 'French Southern Territories', // original: 'French Southern Territories (the)'
  GA: 'Gabon',
  GM: 'Gambia', // original: 'Gambia (the)'
  GE: 'Georgia',
  DE: 'Germany',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GR: 'Greece',
  GL: 'Greenland',
  GD: 'Grenada',
  GP: 'Guadeloupe',
  GU: 'Guam',
  GT: 'Guatemala',
  GG: 'Guernsey',
  GN: 'Guinea',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HT: 'Haiti',
  HM: 'Heard Island and McDonald Islands',
  VA: 'Holy See', // original: 'Holy See (the)'
  HN: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungary',
  IS: 'Iceland',
  IN: 'India',
  ID: 'Indonesia',
  IR: 'Iran', // original: IR: 'Iran (Islamic Republic of)'
  IQ: 'Iraq',
  IE: 'Ireland',
  IM: 'Isle of Man',
  IL: 'Israel',
  IT: 'Italy',
  JM: 'Jamaica',
  JP: 'Japan',
  JE: 'Jersey',
  JO: 'Jordan',
  KZ: 'Kazakhstan',
  KE: 'Kenya',
  KI: 'Kiribati',
  KP: "Korea (the Democratic People's Republic of)",
  KR: 'Korea', // original: KR: 'Korea (the Republic of)'
  KW: 'Kuwait',
  KG: 'Kyrgyzstan',
  LA: "Lao People's Democratic Republic", // original: "Lao People's Democratic Republic (the)",
  LV: 'Latvia',
  LB: 'Lebanon',
  LS: 'Lesotho',
  LR: 'Liberia',
  LY: 'Libya',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  MO: 'Macao',
  MG: 'Madagascar',
  MW: 'Malawi',
  MY: 'Malaysia',
  MV: 'Maldives',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Marshall Islands', // original: 'Marshall Islands (the)'
  MQ: 'Martinique',
  MR: 'Mauritania',
  MU: 'Mauritius',
  YT: 'Mayotte',
  MX: 'Mexico',
  FM: 'Micronesia', // original: FM: 'Micronesia (Federated States of)'
  MD: 'Moldova', // original: MD: 'Moldova (the Republic of)'
  MC: 'Monaco',
  MN: 'Mongolia',
  ME: 'Montenegro',
  MS: 'Montserrat',
  MA: 'Morocco',
  MZ: 'Mozambique',
  MM: 'Myanmar',
  NA: 'Namibia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Netherlands', // original: 'Netherlands (the)'
  NC: 'New Caledonia',
  NZ: 'New Zealand',
  NI: 'Nicaragua',
  NE: 'Niger', // original: 'Niger (the)'
  NG: 'Nigeria',
  NU: 'Niue',
  NF: 'Norfolk Island',
  MK: 'North Macedonia',
  MP: 'Northern Mariana Islands', // original: 'Northern Mariana Islands (the)'
  NO: 'Norway',
  OM: 'Oman',
  PK: 'Pakistan',
  PW: 'Palau',
  PS: 'Palestine, State of',
  PA: 'Panama',
  PG: 'Papua New Guinea',
  PY: 'Paraguay',
  PE: 'Peru',
  PH: 'Philippines', // original: 'Philippines (the)'
  PN: 'Pitcairn',
  PL: 'Poland',
  PT: 'Portugal',
  PR: 'Puerto Rico',
  QA: 'Qatar',
  RO: 'Romania',
  RU: 'Russian Federation', // original: 'Russian Federation (the)'
  RW: 'Rwanda',
  RE: 'Réunion',
  BL: 'Saint Barthélemy',
  SH: 'Saint Helena, Ascension and Tristan da Cunha',
  KN: 'Saint Kitts and Nevis',
  LC: 'Saint Lucia',
  MF: 'Saint Martin (French part)',
  PM: 'Saint Pierre and Miquelon',
  VC: 'Saint Vincent and the Grenadines',
  WS: 'Samoa',
  SM: 'San Marino',
  ST: 'Sao Tome and Principe',
  SA: 'Saudi Arabia',
  SN: 'Senegal',
  RS: 'Serbia',
  SC: 'Seychelles',
  SL: 'Sierra Leone',
  SG: 'Singapore',
  SX: 'Sint Maarten (Dutch part)',
  SK: 'Slovakia',
  SI: 'Slovenia',
  SB: 'Solomon Islands',
  SO: 'Somalia',
  ZA: 'South Africa',
  GS: 'South Georgia and the South Sandwich Islands',
  SS: 'South Sudan',
  ES: 'Spain',
  LK: 'Sri Lanka',
  SD: 'Sudan', // original: 'Sudan (the)'
  SR: 'Suriname',
  SJ: 'Svalbard and Jan Mayen',
  SE: 'Sweden',
  CH: 'Switzerland',
  SY: 'Syrian Arab Republic', // original: 'Syrian Arab Republic (the)'
  TW: 'Taiwan', // original: 'Taiwan (Province of China)'
  TJ: 'Tajikistan',
  TZ: 'Tanzania', // original: 'Tanzania, the United Republic of'
  TH: 'Thailand',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad and Tobago',
  TN: 'Tunisia',
  TM: 'Turkmenistan',
  TC: 'Turks and Caicos Islands', // original: 'Turks and Caicos Islands (the)'
  TV: 'Tuvalu',
  TR: 'Türkiye',
  UG: 'Uganda',
  UA: 'Ukraine',
  AE: 'United Arab Emirates', // original: 'United Arab Emirates (the)'
  GB: 'United Kingdom of Great Britain and Northern Ireland', // original: 'United Kingdom of Great Britain and Northern Ireland (the)'
  UM: 'United States Minor Outlying Islands', // original: 'United States Minor Outlying Islands (the)'
  US: 'United States of America', // original: 'United States of America (the)'
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VU: 'Vanuatu',
  VE: 'Venezuela', // original: VE: 'Venezuela (Bolivarian Republic of)'
  VN: 'Viet Nam',
  VG: 'Virgin Islands (British)',
  VI: 'Virgin Islands (U.S.)',
  WF: 'Wallis and Futuna',
  EH: 'Western Sahara*',
  YE: 'Yemen',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
  AX: 'Åland Islands',
  XA: 'Asia ',
  XB: 'Benelux',
  XC: 'Caribbean',
  XD: 'Domestic ',
  XE: 'Europe North',
  XF: 'Americas',
  XG: 'South America',
  XH: 'Central America',
  XI: 'International',
  XJ: 'Eastern Asia',
  XK: 'Kosovo',
  XL: 'Latin America ',
  XM: 'Southern Asia',
  XN: 'North America ',
  XO: 'South-Eastern Asia',
  XP: 'Asia Pacific',
  XQ: 'Central Asia',
  XR: 'Western Asia',
  XS: 'Scandinavia',
  XT: 'Europe',
  XU: 'Europe South',
  XV: 'Eastern Europe',
  XW: 'World Wide',
  XY: 'Western Europe',
}

export type CountryCode = keyof typeof COUNTRIES

export function isCountryCode(val: unknown): val is CountryCode {
  if (val == null || typeof val !== 'string') {
    return false
  }
  return val in COUNTRIES
}
export const COUNTRY_REGIONS = {
  US: {
    AL: 'Alabama',
    AK: 'Alaska',
    AS: 'American Samoa',
    AZ: 'Arizona',
    AR: 'Arkansas',
    CA: 'California',
    CO: 'Colorado',
    CT: 'Connecticut',
    DE: 'Delaware',
    DC: 'District Of Columbia',
    FM: 'Federated States Of Micronesia',
    FL: 'Florida',
    GA: 'Georgia',
    GU: 'Guam',
    HI: 'Hawaii',
    ID: 'Idaho',
    IL: 'Illinois',
    IN: 'Indiana',
    IA: 'Iowa',
    KS: 'Kansas',
    KY: 'Kentucky',
    LA: 'Louisiana',
    ME: 'Maine',
    MH: 'Marshall Islands',
    MD: 'Maryland',
    MA: 'Massachusetts',
    MI: 'Michigan',
    MN: 'Minnesota',
    MS: 'Mississippi',
    MO: 'Missouri',
    MT: 'Montana',
    NE: 'Nebraska',
    NV: 'Nevada',
    NH: 'New Hampshire',
    NJ: 'New Jersey',
    NM: 'New Mexico',
    NY: 'New York',
    NC: 'North Carolina',
    ND: 'North Dakota',
    MP: 'Northern Mariana Islands',
    OH: 'Ohio',
    OK: 'Oklahoma',
    OR: 'Oregon',
    PW: 'Palau',
    PA: 'Pennsylvania',
    PR: 'Puerto Rico',
    RI: 'Rhode Island',
    SC: 'South Carolina',
    SD: 'South Dakota',
    TN: 'Tennessee',
    TX: 'Texas',
    UT: 'Utah',
    VT: 'Vermont',
    VI: 'Virgin Islands',
    VA: 'Virginia',
    WA: 'Washington',
    WV: 'West Virginia',
    WI: 'Wisconsin',
    WY: 'Wyoming',
  },
  CA: {
    AB: 'Alberta',
    BC: 'British Columbia',
    MB: 'Manitoba',
    NB: 'New Brunswick',
    NL: 'Newfoundland and Labrador',
    NS: 'Nova Scotia',
    NT: 'Northwest Territories',
    NU: 'Nunavut',
    ON: 'Ontario',
    PE: 'Prince Edward Island',
    QC: 'Québec',
    SK: 'Saskatchewan',
    YT: 'Yukon',
  },
  MX: {
    DF: 'Distrito Federal',
    AG: 'Aguascalientes',
    BN: 'Baja California',
    BS: 'Baja California Sur',
    CP: 'Campeche',
    CS: 'Chiapas',
    CI: 'Chihuahua',
    CH: 'Coahuila',
    CL: 'Colima',
    DG: 'Durango',
    GJ: 'Guanajuato',
    GE: 'Guerrero',
    HD: 'Hidalgo',
    JA: 'Jalisco',
    MC: 'Michoacán',
    MR: 'Morelos',
    MX: 'México',
    NA: 'Nayarit',
    NL: 'Nuevo León',
    OA: 'Oaxaca',
    PU: 'Puebla',
    QE: 'Querétaro',
    QI: 'Quintana Roo',
    SL: 'San Luis Potosí',
    SI: 'Sinaloa',
    SO: 'Sonora',
    TB: 'Tabasco',
    TA: 'Tamaulipas',
    TL: 'Tlaxcala',
    VC: 'Veracruz',
    YU: 'Yucatán',
    ZA: 'Zacatecas',
  },
  MY: {
    JHR: 'Johor',
    KDH: 'Kedah',
    KTN: 'Kelantan',
    MLK: 'Malacca',
    NSN: 'Negeri Sembilan',
    PHG: 'Pahang',
    PNG: 'Penang',
    PRK: 'Perak',
    PLS: 'Perlis',
    SBH: 'Sabah',
    SWK: 'Sarawak',
    SGR: 'Selangor',
    TRG: 'Terengganu',
  },
}

export const COUNTRY_ALIASES: { [key in CountryCode]?: string[] } = {
  US: ['United States'],
  GB: ['United Kingdom'],
  MD: ['Republic of Moldova'],
  CZ: ['Czech Republic'],
  TR: ['Turkey'],
  RU: ['Russia'],
}

export const COUNTRY_GROUP_LABELS: { [key: string]: string } = {
  EEA: 'European Economic Area',
}

export const COUNTRY_GROUPS: { [key: string]: string[] } = {
  EEA: [
    'AT',
    'BE',
    'BG',
    'HR',
    'CY',
    'CZ',
    'DK',
    'EE',
    'FI',
    'FR',
    'DE',
    'GR',
    'HU',
    'IS',
    'IE',
    'IT',
    'LV',
    'LI',
    'LT',
    'LU',
    'MT',
    'NL',
    'NO',
    'PL',
    'PT',
    'RO',
    'SK',
    'SI',
    'ES',
    'SE',
  ],
}

export const COUNTRY_CODES = Object.keys(COUNTRIES).concat(
  Object.keys(COUNTRY_GROUPS)
)

export const COUNTRY_NAME_TO_CODE = Object.fromEntries([
  ...Object.entries(COUNTRIES).map(([code, name]) => [name, code]),
  ...Object.entries(COUNTRY_ALIASES).flatMap(([code, names]) =>
    names.map((name) => [name, code])
  ),
])

export function expandCountryGroup(countryCodes: string[]) {
  return countryCodes.flatMap(
    (countryCode) => COUNTRY_GROUPS[countryCode] || countryCode
  )
}
