export const CURRENCIES: ReadonlyArray<{
  readonly value: string
  readonly label: string
  readonly symbol: string | null
}> = [
  { value: 'ADA', label: 'Cardano', symbol: null },
  { value: 'AED', label: 'United Arab Emirates Dirham', symbol: 'د.إ' },
  { value: 'AFN', label: 'Afghan afghani', symbol: '؋' },
  { value: 'ALGO', label: 'Algorand', symbol: null },
  { value: 'ALL', label: 'Albanian lek', symbol: 'Lek' },
  { value: 'AMD', label: 'Armenian dram', symbol: null },
  { value: 'ANG', label: 'Netherlands Antillean Guilder', symbol: 'ƒ' },
  { value: 'AOA', label: 'Angolan kwanza', symbol: null },
  { value: 'ARS', label: 'Argentine peso', symbol: '$' },
  { value: 'ATOM', label: 'Atomic Coin', symbol: null },
  { value: 'AUD', label: 'Australian dollar', symbol: '$' },
  { value: 'AVAX', label: 'Avalanche', symbol: null },
  { value: 'AWG', label: 'Aruban florin', symbol: 'ƒ' },
  { value: 'AZN', label: 'Azerbaijani manat', symbol: '₼' },
  {
    value: 'BAM',
    label: 'Bosnia-Herzegovina Convertible Mark',
    symbol: 'KM',
  },
  { value: 'BBD', label: 'Bajan dollar', symbol: '$' },
  { value: 'BCH', label: 'Bitcoin Cash', symbol: null },
  { value: 'BDT', label: 'Bangladeshi taka', symbol: null },
  { value: 'BGN', label: 'Bulgarian lev', symbol: 'лв' },
  { value: 'BHD', label: 'Bahraini dinar', symbol: null },
  { value: 'BIF', label: 'Burundian Franc', symbol: null },
  { value: 'BMD', label: 'Bermudan dollar', symbol: '$' },
  { value: 'BNB', label: 'Binance Coin', symbol: null },
  { value: 'BND', label: 'Brunei dollar', symbol: '$' },
  { value: 'BOB', label: 'Bolivian boliviano', symbol: '$b' },
  { value: 'BRB', label: 'Brazilian real', symbol: null },
  { value: 'BSD', label: 'Bahamian dollar', symbol: '$' },
  { value: 'BTC', label: 'Bitcoin', symbol: null },
  { value: 'BTN', label: 'Bhutan currency', symbol: null },
  { value: 'BUSD', label: 'Binance USD', symbol: null },
  { value: 'BWP', label: 'Botswanan Pula', symbol: 'P' },
  { value: 'BYN', label: 'New Belarusian Ruble', symbol: 'Br' },
  { value: 'BYR', label: 'Belarusian Ruble', symbol: null },
  { value: 'BZD', label: 'Belize dollar', symbol: 'BZ$' },
  { value: 'CAD', label: 'Canadian dollar', symbol: '$' },
  { value: 'CDF', label: 'Congolese franc', symbol: null },
  { value: 'CHF', label: 'Swiss franc', symbol: 'CHF' },
  { value: 'CHZ', label: 'Chiliz', symbol: null },
  { value: 'CLF', label: 'Chilean Unit of UF)', symbol: null },
  { value: 'CLP', label: 'Chilean peso', symbol: '$' },
  { value: 'CNY', label: 'Chinese Yuan', symbol: '¥' },
  { value: 'COP', label: 'Colombian peso', symbol: 'Col$' },
  { value: 'CRC', label: 'Costa Rican Colón', symbol: '₡' },
  { value: 'CRO', label: 'Crypto.com Chain Token', symbol: null },
  { value: 'CUC', label: 'Cuban peso', symbol: null },
  { value: 'CUP', label: 'Cuban Peso', symbol: '₱' },
  { value: 'CVE', label: 'Cape Verdean escudo', symbol: null },
  { value: 'CZK', label: 'Czech koruna', symbol: 'Kč' },
  { value: 'DAI', label: 'Dai', symbol: null },
  { value: 'DIF', label: 'Djiboutian franc', symbol: null },
  { value: 'DKK', label: 'Danish krone', symbol: 'kr' },
  { value: 'DOGE', label: 'Dogecoin', symbol: null },
  { value: 'DOP', label: 'Dominican peso', symbol: 'RD$' },
  { value: 'DOT', label: 'Dotcoin', symbol: null },
  { value: 'DZD', label: 'Algerian dinar', symbol: null },
  { value: 'EGLD', label: 'Elrond', symbol: null },
  { value: 'EGP', label: 'Egyptian pound', symbol: '£' },
  { value: 'ENJ', label: 'Enjin Coin', symbol: null },
  { value: 'ERN', label: 'Eritrean nakfa', symbol: null },
  { value: 'ETB', label: 'Ethiopian birr', symbol: null },
  { value: 'ETC', label: 'Ethereum Classic', symbol: null },
  { value: 'ETH', label: 'Ether', symbol: null },
  { value: 'EUR', label: 'Euro', symbol: '€' },
  { value: 'FIL', label: 'FileCoin', symbol: null },
  { value: 'FJD', label: 'Fijian dollar', symbol: '$' },
  { value: 'FKP', label: 'Falkland Islands pound', symbol: '£' },
  { value: 'FTT', label: 'FarmaTrust', symbol: null },
  { value: 'GBP', label: 'Pound sterling', symbol: '£' },
  { value: 'GEL', label: 'Georgian lari', symbol: null },
  { value: 'GGP', label: 'GGPro', symbol: '£' },
  { value: 'GHS', label: 'Ghanaian cedi', symbol: '¢' },
  { value: 'GIP', label: 'Gibraltar pound', symbol: '£' },
  { value: 'GMD', label: 'Gambian dalasi', symbol: null },
  { value: 'GNF', label: 'Guinean franc', symbol: null },
  { value: 'GRT', label: 'Golden Ratio Token', symbol: null },
  { value: 'GTQ', label: 'Guatemalan quetzal', symbol: 'Q' },
  { value: 'GYD', label: 'Guyanaese Dollar', symbol: '$' },
  { value: 'HKD', label: 'Hong Kong dollar', symbol: '$' },
  { value: 'HNL', label: 'Honduran lempira', symbol: 'L' },
  { value: 'HRK', label: 'Croatian kuna', symbol: 'kn' },
  { value: 'HTG', label: 'Haitian gourde', symbol: null },
  { value: 'HUF', label: 'Hungarian forint', symbol: 'Ft' },
  { value: 'ICP', label: 'Internet Computer', symbol: null },
  { value: 'IDR', label: 'Indonesian rupiah', symbol: 'Rp' },
  { value: 'ILS', label: 'Israeli New Shekel', symbol: '₪' },
  { value: 'IMP', label: 'CoinIMP', symbol: '£' },
  { value: 'INJ', label: 'Injective', symbol: null },
  { value: 'INR', label: 'Indian rupee', symbol: '₹' },
  { value: 'IQD', label: 'Iraqi dinar', symbol: null },
  { value: 'IRR', label: 'Iranian rial', symbol: '﷼' },
  { value: 'ISK', label: 'Icelandic króna', symbol: 'kr' },
  { value: 'JEP', label: 'Jersey Pound', symbol: '£' },
  { value: 'JMD', label: 'Jamaican dollar', symbol: 'J$' },
  { value: 'JOD', label: 'Jordanian dinar', symbol: null },
  { value: 'JPY', label: 'Japanese yen', symbol: '¥' },
  { value: 'KES', label: 'Kenyan shilling', symbol: null },
  { value: 'KGS', label: 'Kyrgystani Som', symbol: 'лв' },
  { value: 'KHR', label: 'Cambodian riel', symbol: '៛' },
  { value: 'KMF', label: 'Comorian franc', symbol: null },
  { value: 'KPW', label: 'North Korean won', symbol: '₩' },
  { value: 'KRW', label: 'South Korean won', symbol: '₩' },
  { value: 'KSM', label: 'Kusama', symbol: null },
  { value: 'KWD', label: 'Kuwaiti dinar', symbol: null },
  { value: 'KYD', label: 'Cayman Islands dollar', symbol: '$' },
  { value: 'KZT', label: 'Kazakhstani tenge', symbol: 'лв' },
  { value: 'LAK', label: 'Laotian Kip', symbol: '₭' },
  { value: 'LBP', label: 'Lebanese pound', symbol: '£' },
  { value: 'LINK', label: 'ChainLink', symbol: null },
  { value: 'LKR', label: 'Sri Lankan rupee', symbol: '₨' },
  { value: 'LRD', label: 'Liberian dollar', symbol: '$' },
  { value: 'LSR', label: 'Lesotho loti', symbol: null },
  { value: 'LTC', label: 'Litecoin', symbol: null },
  { value: 'LTL', label: 'Lithuanian litas', symbol: null },
  { value: 'LVL', label: 'Latvian lats', symbol: null },
  { value: 'LYD', label: 'Libyan dinar', symbol: null },
  { value: 'MAD', label: 'Moroccan dirham', symbol: null },
  { value: 'MATIC', label: 'Polygon', symbol: null },
  { value: 'MDL', label: 'Moldovan leu', symbol: null },
  { value: 'MGA', label: 'Malagasy ariary', symbol: null },
  { value: 'MKD', label: 'Macedonian denar', symbol: 'ден' },
  { value: 'MMK', label: 'Myanmar Kyat', symbol: null },
  { value: 'MNT', label: 'Mongolian tugrik', symbol: '₮' },
  { value: 'MOP', label: 'Macanese pataca', symbol: null },
  { value: 'MRO', label: 'Mauritanian ouguiya', symbol: null },
  { value: 'MUR', label: 'Mauritian rupee', symbol: '₨' },
  { value: 'MVR', label: 'Maldivian rufiyaa', symbol: null },
  { value: 'MWK', label: 'Malawian kwacha', symbol: null },
  { value: 'MXN', label: 'Mexican peso', symbol: '$' },
  { value: 'MYR', label: 'Malaysian ringgit', symbol: 'RM' },
  { value: 'MZN', label: 'Mozambican Metical', symbol: 'MT' },
  { value: 'NAD', label: 'Namibian dollar', symbol: '$' },
  { value: 'NGN', label: 'Nigerian naira', symbol: '₦' },
  { value: 'NIO', label: 'Nicaraguan córdoba', symbol: 'C$' },
  { value: 'NOK', label: 'Norwegian krone', symbol: 'kr' },
  { value: 'NPR', label: 'Nepalese rupee', symbol: '₨' },
  { value: 'NZD', label: 'New Zealand dollar', symbol: '$' },
  { value: 'OMR', label: 'Omani rial', symbol: '﷼' },
  { value: 'ONE', label: 'Menlo One', symbol: null },
  { value: 'PAB', label: 'Panamanian balboa', symbol: 'B/.' },
  { value: 'PEN', label: 'Sol', symbol: 'S/.' },
  { value: 'PGK', label: 'Papua New Guinean kina', symbol: null },
  { value: 'PHP', label: 'Philippine peso', symbol: '₱' },
  { value: 'PKR', label: 'Pakistani rupee', symbol: '₨' },
  { value: 'PLN', label: 'Poland złoty', symbol: 'zł' },
  { value: 'PYG', label: 'Paraguayan guarani', symbol: 'Gs' },
  { value: 'QAR', label: 'Qatari Rial', symbol: '﷼' },
  { value: 'RON', label: 'Romanian leu', symbol: 'lei' },
  { value: 'RSD', label: 'Serbian dinar', symbol: 'Дин.' },
  { value: 'RUB', label: 'Russian ruble', symbol: '₽' },
  { value: 'RWF', label: 'Rwandan Franc', symbol: null },
  { value: 'SAR', label: 'Saudi riyal', symbol: '﷼' },
  { value: 'SBD', label: 'Solomon Islands dollar', symbol: '$' },
  { value: 'SRC', label: 'Seychellois rupee', symbol: null },
  { value: 'SDG', label: 'Sudanese pound', symbol: null },
  { value: 'SEK', label: 'Swedish krona', symbol: 'kr' },
  { value: 'SGD', label: 'Singapore dollar', symbol: '$' },
  { value: 'SHIB', label: 'Shiba Inu', symbol: null },
  { value: 'SHP', label: 'Saint Helena pound', symbol: '£' },
  { value: 'SLL', label: 'Sierra Leonean leone', symbol: null },
  { value: 'SOL', label: 'Sola', symbol: null },
  { value: 'SOS', label: 'Somali shilling', symbol: 'S' },
  { value: 'SRD', label: 'Surinamese dollar', symbol: '$' },
  {
    value: 'STD',
    label: 'São Tomé and Príncipe pre-2018)',
    symbol: null,
  },
  { value: 'SVC', label: 'Salvadoran Colón', symbol: '$' },
  { value: 'SYP', label: 'Syrian pound', symbol: '£' },
  { value: 'SZL', label: 'Swazi lilangeni', symbol: null },
  { value: 'THB', label: 'Thai baht', symbol: '฿' },
  { value: 'THETA', label: 'Theta', symbol: null },
  { value: 'TJS', label: 'Tajikistani somoni', symbol: null },
  { value: 'TMT', label: 'Turkmenistani manat', symbol: null },
  { value: 'TND', label: 'Tunisian dinar', symbol: null },
  { value: 'TOP', label: "Tongan Pa'anga)", symbol: null },
  { value: 'TRX', label: 'TRON', symbol: null },
  { value: 'TRY', label: 'Turkish lira', symbol: '₺' },
  { value: 'TTD', label: 'Trinidad & Tobago Dollar', symbol: 'TT$' },
  { value: 'TWD', label: 'New Taiwan dollar', symbol: 'NT$' },
  { value: 'TZS', label: 'Tanzanian shilling', symbol: null },
  { value: 'UAH', label: 'Ukrainian hryvnia', symbol: '₴' },
  { value: 'UGX', label: 'Ugandan shilling', symbol: null },
  { value: 'UNI', label: 'Universe', symbol: null },
  { value: 'USD', label: 'United States dollar', symbol: '$' },
  { value: 'USDC', label: 'USD Coin', symbol: null },
  { value: 'USDT', label: 'Tether', symbol: null },
  { value: 'UYU', label: 'Uruguayan peso', symbol: '$U' },
  { value: 'UZS', label: 'Uzbekistani som', symbol: 'лв' },
  { value: 'VEF', label: 'Sovereign Bolivar', symbol: 'Bs' },
  { value: 'VET', label: 'Vechain', symbol: null },
  { value: 'VND', label: 'Vietnamese dong', symbol: '₫' },
  { value: 'VUV', label: 'Vanuatu vatu', symbol: null },
  { value: 'WBTC', label: 'Wrapped Bitcoin', symbol: null },
  { value: 'WST', label: 'Samoan tala', symbol: null },
  { value: 'XAF', label: 'Central African CFA franc', symbol: null },
  { value: 'XAG', label: 'Silver Ounce', symbol: null },
  { value: 'XAU', label: 'XauCoin', symbol: null },
  { value: 'XCD', label: 'East Cari,bbean dollar', symbol: '$' },
  { value: 'XDR', label: 'Special Drawing Rights', symbol: null },
  { value: 'XLM', label: 'Stellar', symbol: null },
  { value: 'XMR', label: 'Monero', symbol: null },
  { value: 'XOF', label: 'West African CFA franc', symbol: null },
  { value: 'XPF', label: 'CFP franc', symbol: null },
  { value: 'XRP', label: 'XRP', symbol: null },
  { value: 'YER', label: 'Yemeni rial', symbol: '﷼' },
  { value: 'ZAR', label: 'South African rand', symbol: 'R' },
  { value: 'ZMK', label: 'Zambian kwacha', symbol: null },
  { value: 'ZMW', label: 'Zambian Kwacha', symbol: null },
  { value: 'ZWL', label: 'Zimbabwean Dollar', symbol: null },
  { value: '1INCH', label: '1inch', symbol: null },
  { value: 'AAVE', label: 'Aave', symbol: null },
  { value: 'AMP', label: 'Amp', symbol: null },
  { value: 'AR', label: 'Arweave', symbol: null },
  { value: 'AXS', label: 'Axie Infinity', symbol: null },
  { value: 'BAT', label: 'Basic Attention Token', symbol: null },
  { value: 'BRL', label: 'Brazilian Real', symbol: null },
  { value: 'BSV', label: 'Bitcoin SV', symbol: null },
  { value: 'BTCB', label: 'Bitcoin BEP2', symbol: null },
  { value: 'BTG', label: 'Bitcoin Gold', symbol: null },
  { value: 'CAKE', label: 'PancakeSwap', symbol: null },
  { value: 'CELO', label: 'Celo', symbol: null },
  { value: 'COMP', label: 'Compound', symbol: null },
  { value: 'CRV', label: 'Curve DAO Token', symbol: null },
  { value: 'CVX', label: 'Convex Finance', symbol: null },
  { value: 'DASH', label: 'Digital Cash', symbol: null },
  { value: 'DCR', label: 'Decred', symbol: null },
  { value: 'DFI', label: 'DfiStarter', symbol: null },
  { value: 'DJF', label: 'Djiboutian Franc', symbol: null },
  { value: 'EOS', label: 'EOS', symbol: null },
  { value: 'FEI', label: 'Fei USD', symbol: null },
  { value: 'FLOW', label: 'Flow', symbol: null },
  { value: 'FRAX', label: 'Frax', symbol: null },
  { value: 'FTM', label: 'Fantom', symbol: null },
  { value: 'GALA', label: 'Gala', symbol: null },
  { value: 'GNO', label: 'Gnosis', symbol: null },
  { value: 'GT', label: 'GateToken', symbol: null },
  { value: 'HBAR', label: 'Hedera', symbol: null },
  { value: 'HNT', label: 'Helium', symbol: null },
  { value: 'HOT', label: 'Hydro Protocol', symbol: null },
  { value: 'HT', label: 'Huobi Token', symbol: null },
  { value: 'KAVA', label: 'Kava', symbol: null },
  { value: 'KCS', label: 'Kucoin', symbol: null },
  { value: 'KDA', label: 'Kadena', symbol: null },
  { value: 'KLAY', label: 'Klaytn', symbol: null },
  { value: 'KNC', label: 'Kyber Network Crystals', symbol: null },
  { value: 'LEO', label: 'LEOcoin', symbol: null },
  { value: 'LRC', label: 'Loopring', symbol: null },
  { value: 'LSL', label: 'Basotho Loti', symbol: null },
  { value: 'LUNA', label: 'Terra', symbol: null },
  { value: 'MANA', label: 'Mana Coin Decentraland', symbol: null },
  { value: 'MINA', label: 'Mina', symbol: null },
  { value: 'MIOTA', label: undefined, symbol: null },
  { value: 'MKR', label: 'Maker', symbol: null },
  { value: 'NEAR', label: 'NEAR Protocol', symbol: null },
  { value: 'NEO', label: 'NEO', symbol: null },
  { value: 'NEXO', label: 'NEXO', symbol: null },
  { value: 'OKB', label: 'Okex', symbol: null },
  { value: 'PAXG', label: 'PAX Gold', symbol: null },
  { value: 'QNT', label: 'Quant', symbol: null },
  { value: 'QTUM', label: 'QTUM', symbol: null },
  { value: 'RUNE', label: 'THORChain (ERC20)', symbol: null },
  { value: 'SAND', label: 'The Sandbox', symbol: null },
  { value: 'SCR', label: 'Seychellois Rupee', symbol: null },
  { value: 'SLE', label: 'Sierra Leonean Leone', symbol: null },
  { value: 'STX', label: 'Stacks', symbol: null },
  { value: 'TTT', label: 'Tap Project', symbol: null },
  { value: 'TUSD', label: 'True USD', symbol: null },
  { value: 'USDP', label: 'USDP Stablecoin', symbol: null },
  { value: 'WAVES', label: 'Waves', symbol: null },
  { value: 'WEMIX', label: 'WEMIX', symbol: null },
  { value: 'XCH', label: 'Chia', symbol: null },
  { value: 'XDC', label: 'XDC Network', symbol: null },
  { value: 'XEC', label: 'Eternal Coin', symbol: null },
  { value: 'XEM', label: 'NEM', symbol: null },
  { value: 'XTZ', label: 'Tezos', symbol: null },
  { value: 'ZEC', label: 'ZCash', symbol: null },
  { value: 'ZIL', label: 'Zilliqa', symbol: null },
].map((v) => ({
  value: v.value,
  label: `${v.value} (${v.label})`,
  symbol: v.symbol,
}))

export type CurrencyInfo = (typeof CURRENCIES)[number]
export type Currency = CurrencyInfo['value']

export const CURRENCIES_SELECT_OPTIONS = [...CURRENCIES]
