type CurrencyInfo = {
  readonly label: string
  readonly symbol: string | null
}

export const CURRENCY_OBJ: Readonly<Record<string, CurrencyInfo>> = {
  '1INCH': { label: '1inch', symbol: null },
  AAVE: { label: 'Aave', symbol: null },
  ABT: { label: 'Arcblock', symbol: null },
  ACH: { label: 'Alchemy Pay', symbol: null },
  ACS: { label: 'Access Protocol', symbol: null },
  ADA: { label: 'Cardano', symbol: null },
  AED: { label: 'United Arab Emirates Dirham', symbol: 'د.إ' },
  AERGO: { label: 'Aergo', symbol: null },
  AERO: { label: 'Aerovek Aviation', symbol: null },
  AFN: { label: 'Afghan afghani', symbol: '؋' },
  AGLD: { label: 'Adventure Gold', symbol: null },
  AIOZ: { label: 'AIOZ Network', symbol: null },
  ALCX: { label: 'Alchemix', symbol: null },
  ALEPH: { label: 'Aleph.im', symbol: null },
  ALGO: { label: 'Algorand', symbol: null },
  ALICE: { label: 'MyNeighborAlice', symbol: null },
  ALL: { label: 'Albanian lek', symbol: 'L' },
  AMD: { label: 'Armenian dram', symbol: '֏' },
  AMP: { label: 'Amp', symbol: null },
  ANG: { label: 'Netherlands Antillean Guilder', symbol: 'ƒ' },
  ANKR: { label: 'Ankr', symbol: null },
  ANT: { label: 'Aragon', symbol: null },
  AOA: { label: 'Angolan kwanza', symbol: 'Kz' },
  APE: { label: 'ApeCoin', symbol: null },
  API3: { label: 'API3', symbol: null },
  APT: { label: 'Aptos', symbol: null },
  ARB: { label: 'Arbitrum', symbol: null },
  ARPA: { label: 'ARPA Chain', symbol: null },
  ARS: { label: 'Argentine peso', symbol: '$' },
  ASM: { label: 'Assemble Protocol', symbol: null },
  AST: { label: 'AirSwap', symbol: null },
  ATA: { label: 'Automata', symbol: null },
  ATOM: { label: 'Cosmos', symbol: null },
  AUCTION: { label: 'Bounce Token', symbol: null },
  AUD: { label: 'Australian dollar', symbol: '$' },
  AUDIO: { label: 'Audius', symbol: null },
  AURORA: { label: 'Aurora', symbol: null },
  AVAX: { label: 'Avalanche', symbol: null },
  AVT: { label: 'Aventus', symbol: null },
  AWG: { label: 'Aruban florin', symbol: 'ƒ' },
  AXL: { label: 'Axelar', symbol: null },
  AXS: { label: 'Axie Infinity', symbol: null },
  AZN: { label: 'Azerbaijani manat', symbol: '₼' },
  BADGER: { label: 'Badger', symbol: null },
  BAL: { label: 'Balancer', symbol: null },
  BAM: { label: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM' },
  BAND: { label: 'Band Protocol', symbol: null },
  BAT: { label: 'Basic Attention Token', symbol: null },
  BBD: { label: 'Bajan dollar', symbol: '$' },
  BCH: { label: 'Bitcoin Cash', symbol: null },
  BDT: { label: 'Bangladeshi taka', symbol: '৳' },
  BGN: { label: 'Bulgarian lev', symbol: 'лв' },
  BHD: { label: 'Bahraini dinar', symbol: '.د.ب' },
  BICO: { label: 'Biconomy', symbol: null },
  BIF: { label: 'Burundian Franc', symbol: 'FBu' },
  BIGTIME: { label: 'BigTime', symbol: null },
  BIT: { label: 'BitDAO', symbol: null },
  BLUR: { label: 'Blur', symbol: null },
  BLZ: { label: 'Bluzelle', symbol: null },
  BMD: { label: 'Bermudan dollar', symbol: '$' },
  BND: { label: 'Brunei dollar', symbol: '$' },
  BNT: { label: 'Bancor Network Token', symbol: null },
  BOB: { label: 'Bolivian boliviano', symbol: 'Bs.' },
  BOBA: { label: 'Boba Network', symbol: null },
  BOND: { label: 'BarnBridge', symbol: null },
  BONK: { label: 'Bonk', symbol: null },
  BRL: { label: 'Brazilian real', symbol: 'R$' },
  BSD: { label: 'Bahamian dollar', symbol: '$' },
  BSV: { label: 'Bitcoin SV', symbol: null },
  BTC: { label: 'Bitcoin', symbol: null },
  BTN: { label: 'Bhutan currency', symbol: 'Nu.' },
  BTRST: { label: 'Braintrust', symbol: null },
  BUSD: { label: 'Binance USD', symbol: null },
  BWP: { label: 'Botswanan Pula', symbol: 'P' },
  BYN: { label: 'New Belarusian Ruble', symbol: 'Br' },
  BYR: { label: 'Belarusian Ruble', symbol: 'Br' },
  BZD: { label: 'Belize dollar', symbol: 'BZ$' },
  C98: { label: 'Coin98', symbol: null },
  CAD: { label: 'Canadian dollar', symbol: '$' },
  CBETH: { label: 'Coinbase Wrapped Staked ETH', symbol: null },
  CDF: { label: 'Congolese franc', symbol: 'FC' },
  CELR: { label: 'Celer Network', symbol: null },
  CGLD: { label: 'Celo', symbol: null },
  CHF: { label: 'Swiss franc', symbol: 'CHF' },
  CHZ: { label: 'Chiliz', symbol: null },
  CLF: { label: 'Chilean Unit of UF)', symbol: null },
  CLP: { label: 'Chilean peso', symbol: '$' },
  CLV: { label: 'Clover Finance', symbol: null },
  CNH: { label: 'Chinese Yuan (Offshore)', symbol: null },
  CNY: { label: 'Chinese Yuan', symbol: '¥' },
  COMP: { label: 'Compound', symbol: null },
  COP: { label: 'Colombian peso', symbol: 'Col$' },
  COTI: { label: 'COTI', symbol: null },
  COVAL: { label: 'Circuits of Value', symbol: null },
  CRC: { label: 'Costa Rican Colón', symbol: '₡' },
  CRO: { label: 'Crypto.com Chain Token', symbol: null },
  CRPT: { label: 'Crypterium', symbol: null },
  CRV: { label: 'Curve DAO Token', symbol: null },
  CTSI: { label: 'Cartesi', symbol: null },
  CTX: { label: 'Cryptex Finance', symbol: null },
  CUC: { label: 'Cuban peso', symbol: null },
  CUP: { label: 'Cuban Peso', symbol: '₱' },
  CVC: { label: 'Civic', symbol: null },
  CVE: { label: 'Cape Verdean escudo', symbol: '$' },
  CVX: { label: 'Convex Finance', symbol: null },
  CZK: { label: 'Czech koruna', symbol: 'Kč' },
  DAI: { label: 'Dai', symbol: null },
  DAR: { label: 'Mines of Dalarnia', symbol: null },
  DASH: { label: 'Dash', symbol: null },
  DDX: { label: 'DerivaDAO', symbol: null },
  DESO: { label: 'Decentralized Social', symbol: null },
  DEXT: { label: 'DexTools', symbol: null },
  DIA: { label: 'DIA', symbol: null },
  DIMO: { label: 'DIMO', symbol: null },
  DJF: { label: 'Djiboutian franc', symbol: 'Fdj' },
  DKK: { label: 'Danish krone', symbol: 'kr' },
  DNT: { label: 'district0x', symbol: null },
  DOGE: { label: 'Dogecoin', symbol: null },
  DOP: { label: 'Dominican peso', symbol: 'RD$' },
  DOT: { label: 'Polkadot', symbol: null },
  DREP: { label: 'Drep', symbol: null },
  DYP: { label: 'DeFi Yield Protocol', symbol: null },
  DZD: { label: 'Algerian dinar', symbol: 'د.ج' },
  EEK: { label: 'Estonian kroon', symbol: null },
  EGLD: { label: 'Elrond', symbol: null },
  EGP: { label: 'Egyptian pound', symbol: '£' },
  ELA: { label: 'Elastos', symbol: null },
  ENJ: { label: 'Enjin Coin', symbol: null },
  ENS: { label: 'Ethereum Name Service', symbol: null },
  EOS: { label: 'EOS', symbol: null },
  ERN: { label: 'Ethernity Chain', symbol: null },
  ETB: { label: 'Ethiopian birr', symbol: 'Br' },
  ETC: { label: 'Ethereum Classic', symbol: null },
  ETH: { label: 'Ethereum', symbol: 'Ξ' },
  ETH2: { label: 'Ethereum 2.0', symbol: null },
  EUR: { label: 'Euro', symbol: '€' },
  EURC: { label: 'Euro Backed Stablecoin', symbol: null },
  EUROC: { label: 'Euro Coin', symbol: null },
  ETHFI: { label: 'Ether.fi', symbol: null },
  FARM: { label: 'Harvest Finance', symbol: null },
  FET: { label: 'Fetch.ai', symbol: null },
  FIDA: { label: 'Bonfida', symbol: null },
  FIL: { label: 'Filecoin', symbol: null },
  FIS: { label: 'Stafi', symbol: null },
  FJD: { label: 'Fijian dollar', symbol: '$' },
  FKP: { label: 'Falkland Islands pound', symbol: '£' },
  FLOW: { label: 'Flow', symbol: null },
  FLR: { label: 'Flare', symbol: null },
  FORT: { label: 'Forta', symbol: null },
  FORTH: { label: 'Ampleforth Governance Token', symbol: null },
  FOX: { label: 'ShapeShift FOX Token', symbol: null },
  FX: { label: 'Function X', symbol: null },
  FTM: { label: 'Fantom', symbol: null },
  GAL: { label: 'Galxe', symbol: null },
  GALA: { label: 'Gala', symbol: null },
  GBP: { label: 'British pound', symbol: '£' },
  GEL: { label: 'Georgian lari', symbol: '₾' },
  GFI: { label: 'Goldfinch', symbol: null },
  GGP: { label: 'Guernsey pound', symbol: '£' },
  GHS: { label: 'Ghanaian cedi', symbol: '₵' },
  GHST: { label: 'Aavegotchi', symbol: null },
  GIP: { label: 'Gibraltar pound', symbol: '£' },
  GLM: { label: 'Golem', symbol: null },
  GMD: { label: 'Gambian dalasi', symbol: 'D' },
  GMT: { label: 'STEPN', symbol: null },
  GNF: { label: 'Guinean franc', symbol: 'FG' },
  GNO: { label: 'Gnosis', symbol: null },
  GNT: { label: 'Golem (old)', symbol: null },
  GODS: { label: 'Gods Unchained', symbol: null },
  GRT: { label: 'The Graph', symbol: null },
  GST: { label: 'Green Satoshi Token', symbol: null },
  GTC: { label: 'Gitcoin', symbol: null },
  GTQ: { label: 'Guatemalan quetzal', symbol: 'Q' },
  GUSD: { label: 'Gemini Dollar', symbol: null },
  GYD: { label: 'Guyanaese Dollar', symbol: '$' },
  GYEN: { label: 'GYEN', symbol: null },
  HBAR: { label: 'Hedera', symbol: null },
  HFT: { label: 'Hashflow', symbol: null },
  HIGH: { label: 'Highstreet', symbol: null },
  HKD: { label: 'Hong Kong dollar', symbol: '$' },
  HNL: { label: 'Honduran lempira', symbol: 'L' },
  HNT: { label: 'Helium', symbol: null },
  HONEY: { label: 'Honey', symbol: null },
  HOPR: { label: 'HOPR', symbol: null },
  HRK: { label: 'Croatian kuna', symbol: 'kn' },
  HTG: { label: 'Haitian gourde', symbol: 'G' },
  HUF: { label: 'Hungarian forint', symbol: 'Ft' },
  ICP: { label: 'Internet Computer', symbol: null },
  IDEX: { label: 'IDEX', symbol: null },
  IDR: { label: 'Indonesian rupiah', symbol: 'Rp' },
  ILS: { label: 'Israeli New Shekel', symbol: '₪' },
  ILV: { label: 'Illuvium', symbol: null },
  IMP: { label: 'CoinIMP', symbol: '£' },
  IMX: { label: 'Immutable X', symbol: null },
  INDEX: { label: 'Index Cooperative', symbol: null },
  INJ: { label: 'Injective', symbol: null },
  INR: { label: 'Indian rupee', symbol: '₹' },
  INV: { label: 'Inverse Finance', symbol: null },
  IOTX: { label: 'IoTeX', symbol: null },
  IQD: { label: 'Iraqi dinar', symbol: 'ع.د' },
  IRR: { label: 'Iranian rial', symbol: '﷼' },
  ISK: { label: 'Icelandic króna', symbol: 'kr' },
  JASMY: { label: 'JasmyCoin', symbol: null },
  JEP: { label: 'Jersey Pound', symbol: '£' },
  JMD: { label: 'Jamaican dollar', symbol: 'J$' },
  JOD: { label: 'Jordanian dinar', symbol: null },
  JPY: { label: 'Japanese yen', symbol: '¥' },
  JTO: { label: 'Jito', symbol: null },
  JUP: { label: 'Jupiter', symbol: null },
  KAVA: { label: 'Kava', symbol: null },
  KEEP: { label: 'Keep Network', symbol: null },
  KES: { label: 'Kenyan shilling', symbol: 'KSh' },
  KGS: { label: 'Kyrgystani Som', symbol: 'с' },
  KHR: { label: 'Cambodian riel', symbol: '៛' },
  KMF: { label: 'Comorian franc', symbol: 'CF' },
  KNC: { label: 'Kyber Network Crystal', symbol: null },
  KPW: { label: 'North Korean won', symbol: '₩' },
  KRL: { label: 'Kryll', symbol: null },
  KRW: { label: 'South Korean won', symbol: '₩' },
  KSM: { label: 'Kusama', symbol: null },
  KWD: { label: 'Kuwaiti dinar', symbol: 'د.ك' },
  KYD: { label: 'Cayman Islands dollar', symbol: '$' },
  KZT: { label: 'Kazakhstani tenge', symbol: '₸' },
  LAK: { label: 'Laotian Kip', symbol: '₭' },
  LBP: { label: 'Lebanese pound', symbol: 'ل.ل' },
  LCX: { label: 'LCX', symbol: null },
  LDO: { label: 'Lido DAO', symbol: null },
  LINK: { label: 'ChainLink', symbol: null },
  LIT: { label: 'Litentry', symbol: null },
  LKR: { label: 'Sri Lankan rupee', symbol: '₨' },
  LOKA: { label: 'League of Kingdoms Arena', symbol: null },
  LOOM: { label: 'Loom Network', symbol: null },
  LPT: { label: 'Livepeer', symbol: null },
  LQTY: { label: 'Liquity', symbol: null },
  LRC: { label: 'Loopring', symbol: null },
  LRD: { label: 'Liberian dollar', symbol: 'L$' },
  LSETH: { label: 'Liquid Staked Ethereum', symbol: null },
  LSL: { label: 'Lesotho loti', symbol: 'L' },
  LTC: { label: 'Litecoin', symbol: null },
  LTL: { label: 'Lithuanian litas', symbol: null },
  LVL: { label: 'Latvian lats', symbol: null },
  LYD: { label: 'Libyan dinar', symbol: 'ل.د' },
  MAD: { label: 'Moroccan dirham', symbol: 'د.م.' },
  MAGIC: { label: 'Magic', symbol: null },
  MANA: { label: 'Decentraland', symbol: null },
  MASK: { label: 'Mask Network', symbol: null },
  MATH: { label: 'MATH', symbol: null },
  MATIC: { label: 'Polygon', symbol: null },
  MCO2: { label: 'Moss Carbon Credit', symbol: null },
  MDL: { label: 'Moldovan leu', symbol: 'L' },
  MDT: { label: 'Measurable Data Token', symbol: null },
  MEDIA: { label: 'Media Network', symbol: null },
  METIS: { label: 'MetisDAO', symbol: null },
  MGA: { label: 'Malagasy ariary', symbol: 'Ar' },
  MINA: { label: 'Mina Protocol', symbol: null },
  MIR: { label: 'Mirror Protocol', symbol: null },
  MKD: { label: 'Macedonian denar', symbol: 'ден' },
  MKR: { label: 'Maker', symbol: null },
  MLN: { label: 'Enzyme', symbol: null },
  MMK: { label: 'Myanmar Kyat', symbol: 'K' },
  MNDE: { label: 'Marinade', symbol: null },
  MNT: { label: 'Mongolian tugrik', symbol: '₮' },
  MOBILE: { label: 'Mobilecoin', symbol: null },
  MONA: { label: 'MonaCoin', symbol: null },
  MOP: { label: 'Macanese pataca', symbol: 'MOP$' },
  MPL: { label: 'Maple', symbol: null },
  MRO: { label: 'Mauritanian ouguiya', symbol: 'UM' },
  MRU: { label: 'Mauritanian ouguiya', symbol: 'UM' },
  MSOL: { label: 'Marinade staked SOL', symbol: null },
  MTL: { label: 'Metal', symbol: null },
  MULTI: { label: 'Multichain', symbol: null },
  MUR: { label: 'Mauritian rupee', symbol: '₨' },
  MUSE: { label: 'Muse', symbol: null },
  MVR: { label: 'Maldivian rufiyaa', symbol: '.ރ' },
  MWK: { label: 'Malawian kwacha', symbol: 'MK' },
  MXC: { label: 'MXC', symbol: null },
  MXN: { label: 'Mexican peso', symbol: '$' },
  MYR: { label: 'Malaysian ringgit', symbol: 'RM' },
  MZN: { label: 'Mozambican Metical', symbol: 'MT' },
  NAD: { label: 'Namibian dollar', symbol: 'N$' },
  NCT: { label: 'PolySwarm', symbol: null },
  NEAR: { label: 'NEAR Protocol', symbol: null },
  NEST: { label: 'NEST Protocol', symbol: null },
  NGN: { label: 'Nigerian naira', symbol: '₦' },
  NIO: { label: 'Nicaraguan córdoba', symbol: 'C$' },
  NKN: { label: 'NKN', symbol: null },
  NMR: { label: 'Numeraire', symbol: null },
  NOK: { label: 'Norwegian krone', symbol: 'kr' },
  NPR: { label: 'Nepalese rupee', symbol: '₨' },
  NU: { label: 'NuCypher', symbol: null },
  NZD: { label: 'New Zealand dollar', symbol: '$' },
  OCEAN: { label: 'Ocean Protocol', symbol: null },
  OGN: { label: 'Origin Protocol', symbol: null },
  OMG: { label: 'OMG Network', symbol: null },
  OMR: { label: 'Omani rial', symbol: 'ر.ع.' },
  ONDO: { label: 'Ondo Finance', symbol: null },
  OOKI: { label: 'Ooki', symbol: null },
  OP: { label: 'Optimism', symbol: null },
  ORCA: { label: 'Orca', symbol: null },
  ORN: { label: 'Orion Protocol', symbol: null },
  OSMO: { label: 'Osmosis', symbol: null },
  OXT: { label: 'Orchid', symbol: null },
  PAB: { label: 'Panamanian balboa', symbol: 'B/.' },
  PAX: { label: 'Paxos Standard', symbol: null },
  PEN: { label: 'Sol', symbol: 'S/.' },
  PENGU: { label: 'Pudgy Penguins', symbol: null },
  PEPE: { label: 'Pepe', symbol: null },
  PERP: { label: 'Perpetual Protocol', symbol: null },
  PGK: { label: 'Papua New Guinean kina', symbol: 'K' },
  PHP: { label: 'Philippine peso', symbol: '₱' },
  PKR: { label: 'Pakistani rupee', symbol: '₨' },
  PLA: { label: 'PlayDapp', symbol: null },
  PLN: { label: 'Poland złoty', symbol: 'zł' },
  PLU: { label: 'Pluton', symbol: null },
  PNG: { label: 'Pangolin', symbol: null },
  POL: { label: 'Polygon Ecosystem Token', symbol: null },
  POLS: { label: 'Polkastarter', symbol: null },
  POLY: { label: 'Polymath', symbol: null },
  POND: { label: 'Marlin', symbol: null },
  POWR: { label: 'Power Ledger', symbol: null },
  PRIME: { label: 'Prime', symbol: null },
  PRO: { label: 'Propy', symbol: null },
  PRQ: { label: 'PARSIQ', symbol: null },
  PUNDIX: { label: 'Pundi X', symbol: null },
  PYG: { label: 'Paraguayan guarani', symbol: 'Gs' },
  PYR: { label: 'Vulcan Forged PYR', symbol: null },
  PYUSD: { label: 'PayPal USD', symbol: null },
  QAR: { label: 'Qatari Rial', symbol: 'ر.ق' },
  QI: { label: 'BENQI', symbol: null },
  QNT: { label: 'Quant', symbol: null },
  QSP: { label: 'Quantstamp', symbol: null },
  QUICK: { label: 'QuickSwap', symbol: null },
  RAD: { label: 'Radicle', symbol: null },
  RAI: { label: 'Rai Reflex Index', symbol: null },
  RARE: { label: 'SuperRare', symbol: null },
  RARI: { label: 'Rarible', symbol: null },
  RBN: { label: 'Ribbon Finance', symbol: null },
  REN: { label: 'Ren', symbol: null },
  RENDER: { label: 'Render Token', symbol: null },
  REP: { label: 'Augur', symbol: null },
  REPV2: { label: 'Augur v2', symbol: null },
  REQ: { label: 'Request', symbol: null },
  RGT: { label: 'Rari Governance Token', symbol: null },
  RLC: { label: 'iExec RLC', symbol: null },
  RLY: { label: 'Rally', symbol: null },
  RNDR: { label: 'Render Token', symbol: null },
  RON: { label: 'Romanian leu', symbol: 'lei' },
  ROSE: { label: 'Oasis Network', symbol: null },
  RPL: { label: 'Rocket Pool', symbol: null },
  RSD: { label: 'Serbian dinar', symbol: 'дин.' },
  RUB: { label: 'Russian ruble', symbol: '₽' },
  RWF: { label: 'Rwandan Franc', symbol: 'FRw' },
  SAND: { label: 'The Sandbox', symbol: null },
  SAR: { label: 'Saudi riyal', symbol: 'ر.س' },
  SBD: { label: 'Solomon Islands dollar', symbol: '$' },
  SCR: { label: 'Seychellois rupee', symbol: '₨' },
  SDG: { label: 'Sudanese pound', symbol: 'ج.س.' },
  SEAM: { label: 'Seamless', symbol: null },
  SEI: { label: 'Sei', symbol: null },
  SEK: { label: 'Swedish krona', symbol: 'kr' },
  SGD: { label: 'Singapore dollar', symbol: '$' },
  SHIB: { label: 'Shiba Inu', symbol: null },
  SHP: { label: 'Saint Helena pound', symbol: '£' },
  SHPING: { label: 'Shping', symbol: null },
  SKK: { label: 'Slovak koruna', symbol: null },
  SKL: { label: 'SKALE', symbol: null },
  SLL: { label: 'Sierra Leonean leone', symbol: 'Le' },
  SLE: { label: 'Sierra Leonean leone', symbol: 'Le' },
  SNT: { label: 'Status', symbol: null },
  SNX: { label: 'Synthetix', symbol: null },
  SOL: { label: 'Solana', symbol: null },
  SOS: { label: 'Somali shilling', symbol: 'S' },
  SPA: { label: 'Sperax', symbol: null },
  SPELL: { label: 'Spell Token', symbol: null },
  SRD: { label: 'Surinamese dollar', symbol: '$' },
  SSP: { label: 'South Sudanese pound', symbol: '£' },
  STD: { label: 'São Tomé and Príncipe dobra', symbol: 'Db' },
  STG: { label: 'Stargate Finance', symbol: null },
  STORJ: { label: 'Storj', symbol: null },
  STRK: { label: 'Strike', symbol: null },
  STX: { label: 'Stacks', symbol: null },
  SUI: { label: 'Sui', symbol: null },
  SUKU: { label: 'SUKU', symbol: null },
  SUPER: { label: 'SuperFarm', symbol: null },
  SUSHI: { label: 'SushiSwap', symbol: null },
  SVC: { label: 'Salvadoran Colón', symbol: '$' },
  SWFTC: { label: 'SwftCoin', symbol: null },
  SYLO: { label: 'Sylo', symbol: null },
  SYN: { label: 'Synapse', symbol: null },
  SYP: { label: 'Syrian pound', symbol: '£S' },
  SZL: { label: 'Swazi lilangeni', symbol: 'L' },
  T: { label: 'Threshold', symbol: null },
  THB: { label: 'Thai baht', symbol: '฿' },
  TIA: { label: 'Celestia', symbol: null },
  TIME: { label: 'Chrono.tech', symbol: null },
  TJS: { label: 'Tajikistani somoni', symbol: 'ЅМ' },
  TMM: { label: 'Turkmenistani manat', symbol: 'm' },
  TMT: { label: 'Turkmenistani manat', symbol: 'T' },
  TND: { label: 'Tunisian dinar', symbol: 'د.ت' },
  TON: { label: 'Toncoin', symbol: null },
  TONE: { label: 'TE-FOOD', symbol: null },
  TOP: { label: "Tongan Pa'anga", symbol: 'T$' },
  TRAC: { label: 'OriginTrail', symbol: null },
  TRB: { label: 'Tellor', symbol: null },
  TRIBE: { label: 'Tribe', symbol: null },
  TRU: { label: 'TrueFi', symbol: null },
  TRUMP: { label: 'Official Trump Coin', symbol: null },
  TRY: { label: 'Turkish lira', symbol: '' },
  TTD: { label: 'Trinidad & Tobago Dollar', symbol: 'TT$' },
  TVK: { label: 'Terra Virtua Kolect', symbol: null },
  TWD: { label: 'New Taiwan dollar', symbol: 'NT$' },
  TZS: { label: 'Tanzanian shilling', symbol: 'TSh' },
  UAH: { label: 'Ukrainian hryvnia', symbol: '₴' },
  UGX: { label: 'Ugandan shilling', symbol: 'USh' },
  UMA: { label: 'UMA', symbol: null },
  UNFI: { label: 'Unifi Protocol DAO', symbol: null },
  UNI: { label: 'Uniswap', symbol: null },
  UPI: { label: 'Pawtocol', symbol: null },
  USD: { label: 'United States dollar', symbol: '$' },
  USDC: { label: 'USD Coin', symbol: null },
  USDT: { label: 'Tether', symbol: null },
  UST: { label: 'TerraUSD', symbol: null },
  UYU: { label: 'Uruguayan peso', symbol: '$U' },
  UZS: { label: 'Uzbekistani som', symbol: "so'm" },
  VARA: { label: 'Vara Network', symbol: null },
  VEF: { label: 'Venezuelan bolívar fuerte', symbol: 'Bs' },
  VELO: { label: 'Velo', symbol: null },
  VES: { label: 'Venezuelan bolívar soberano', symbol: 'Bs.S' },
  VET: { label: 'VeChain', symbol: null },
  VGX: { label: 'Voyager Token', symbol: null },
  VND: { label: 'Vietnamese đồng', symbol: '₫' },
  VOXEL: { label: 'Voxies', symbol: null },
  VTHO: { label: 'VeThor Token', symbol: null },
  VUV: { label: 'Vanuatu vatu', symbol: 'VT' },
  WAMPL: { label: 'Wrapped Ampleforth', symbol: null },
  WAXL: { label: 'Wrapped AXELAR', symbol: null },
  WBTC: { label: 'Wrapped Bitcoin', symbol: null },
  WCFG: { label: 'Wrapped Centrifuge', symbol: null },
  WLUNA: { label: 'Wrapped LUNA Token', symbol: null },
  WST: { label: 'Samoan tala', symbol: 'WS$' },
  XAF: { label: 'Central African CFA franc', symbol: 'FCFA' },
  XAG: { label: 'Silver (troy ounce)', symbol: null },
  XAU: { label: 'Gold (troy ounce)', symbol: null },
  XCD: { label: 'East Caribbean dollar', symbol: '$' },
  XCN: { label: 'Chain', symbol: null },
  XDR: { label: 'Special Drawing Rights', symbol: null },
  XLM: { label: 'Stellar Lumens', symbol: null },
  XMON: { label: 'XMON', symbol: null },
  XOF: { label: 'West African CFA franc', symbol: 'CFA' },
  XPD: { label: 'Palladium Ounce', symbol: null },
  XPF: { label: 'CFP franc', symbol: null },
  XPT: { label: 'Platinum Ounce', symbol: null },
  XRP: { label: 'XRP', symbol: null },
  XTZ: { label: 'Tezos', symbol: null },
  XYO: { label: 'XYO Network', symbol: null },
  YER: { label: 'Yemeni rial', symbol: '﷼' },
  YFI: { label: 'yearn.finance', symbol: null },
  YFII: { label: 'DFI.Money', symbol: null },
  ZAR: { label: 'South African rand', symbol: 'R' },
  ZEC: { label: 'Zcash', symbol: null },
  ZEN: { label: 'Horizen', symbol: null },
  ZETA: { label: 'Zeta Markets', symbol: null },
  ZMK: { label: 'Zambian kwacha', symbol: 'ZK' },
  ZMW: { label: 'Zambian kwacha', symbol: 'ZK' },
  ZRX: { label: '0x', symbol: null },
  ZWD: { label: 'Zimbabwean dollar', symbol: 'Z$' },
  FDUSD: { label: 'First Digital USD', symbol: null },
  AGX: { label: 'Agoric', symbol: null },
  AUX: { label: 'Auxiliary', symbol: null },
  BNB: { label: 'Binance Coin', symbol: null },
  CUBE: { label: 'Somnium Space Cubes', symbol: null },
  EMON: { label: 'EthermonToken', symbol: null },
  FDGT: { label: 'Fidget', symbol: null },
  KGLD: { label: 'Kitco Gold', symbol: null },
  LODE: { label: 'LODE', symbol: null },
  PASS: { label: 'Blockpass', symbol: null },
  PREMIA: { label: 'Premia', symbol: null },
  TAB1: { label: 'Tableland', symbol: null },
  'TD-USD': { label: 'TrueDollar', symbol: null },
  TRX: { label: 'TRON', symbol: null },
  TYUGA: { label: 'Tyuga', symbol: null },
  VIC: { label: 'Viction', symbol: null },
  XAI: { label: 'Xai', symbol: null },
  RUNE: { label: 'THORChain', symbol: null },
  THETA: { label: 'Theta Network', symbol: null },
  NPC: { label: 'NPC', symbol: null },
  EURA: { label: 'Euroback', symbol: null },
  EURT: { label: 'EuroT', symbol: null },
  ISLM: { label: 'Islem', symbol: null },
  KLAY: { label: 'Klaytn', symbol: null },
  ZIL: { label: 'Zilliqa', symbol: null },
  DYDX: { label: 'dYdX', symbol: null },
  IOTA: { label: 'IOTA', symbol: null },
  WAVES: { label: 'Waves', symbol: null },
  LUNA2: { label: 'LUNA2', symbol: null },
  UDI: { label: 'Unidad de Inversión', symbol: null },
}

export const CRYPTO_CURRENCIES_KEYS = [
  '1INCH',
  'AAVE',
  'ABT',
  'ACH',
  'ACS',
  'AERGO',
  'AERO',
  'AGLD',
  'AIOZ',
  'ALCX',
  'ALEPH',
  'ALGO',
  'ALICE',
  'AMP',
  'ANKR',
  'ANT',
  'APE',
  'API3',
  'APT',
  'ARB',
  'ARPA',
  'ASM',
  'AST',
  'ATA',
  'ATOM',
  'AUCTION',
  'AUDIO',
  'AURORA',
  'AVAX',
  'AVT',
  'AXL',
  'AXS',
  'BADGER',
  'BAL',
  'BAND',
  'BAT',
  'BCH',
  'BICO',
  'BIGTIME',
  'BIT',
  'BLUR',
  'BLZ',
  'BNT',
  'BOBA',
  'BOND',
  'BONK',
  'BSV',
  'BTC',
  'BTRST',
  'C98',
  'CBETH',
  'CELR',
  'CGLD',
  'CHZ',
  'CLV',
  'COMP',
  'COTI',
  'COVAL',
  'CRO',
  'CRPT',
  'CRV',
  'CTSI',
  'CTX',
  'CVC',
  'CVX',
  'DAI',
  'DAR',
  'DASH',
  'DDX',
  'DESO',
  'DEXT',
  'DIA',
  'DIMO',
  'DNT',
  'DOGE',
  'DOT',
  'DREP',
  'DYP',
  'EGLD',
  'ELA',
  'ENJ',
  'ENS',
  'EOS',
  'ERN',
  'ETC',
  'ETH',
  'ETH2',
  'EUROC',
  'FARM',
  'FET',
  'FIDA',
  'FIL',
  'FIS',
  'FLOW',
  'FLR',
  'FORT',
  'FORTH',
  'FOX',
  'FX',
  'GAL',
  'GALA',
  'GFI',
  'GHST',
  'GLM',
  'GMT',
  'GNO',
  'GODS',
  'GRT',
  'GST',
  'GTC',
  'GUSD',
  'GYEN',
  'HBAR',
  'HFT',
  'HIGH',
  'HNT',
  'HONEY',
  'HOPR',
  'ICP',
  'IDEX',
  'ILV',
  'IMX',
  'INDEX',
  'INJ',
  'INV',
  'IOTX',
  'JASMY',
  'ETHFI',
  'FTM',
  'PENGU',
  'POL',
  'RUNE',
  'THETA',
  'TRUMP',
  'PEPE',
  'EURC',
  'TON',
  'KLAY',
  'ZIL',
  'DYDX',
  'IOTA',
  'TON',
  'WAVES',
  'LUNA2',
  'NEO',
]

export type Currency = string

export const CURRENCIES = Object.entries(CURRENCY_OBJ).map(([code, info]) => ({
  value: code,
  label: `${code} (${info.label})`,
  symbol: info.symbol,
}))

export const CURRENCIES_SELECT_OPTIONS = CURRENCIES
