/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Activity = ActivityType & {
  ActivityAssociation: ActivityAssociationType
  ActivitySupportDocument?: ActivitySupportDocumentType
  /**
   * @minItems 6
   * @maxItems 1203
   */
  Party: [Party, Party, Party, Party, Party, Party, ...Party[]]
  SuspiciousActivity: SuspiciousActivity
  /**
   * @maxItems 99
   */
  ActivityIPAddress?: ActivityIPAddressType[]
  /**
   * @maxItems 99
   */
  CyberEventIndicators?: CyberEventIndicatorsType[]
  /**
   * @maxItems 31
   */
  Assets?: AssetsTableType[]
  /**
   * @maxItems 396
   */
  AssetsAttribute?: AssetsAttributeType[]
  /**
   * @maxItems 5
   */
  ActivityNarrativeInformation:
    | []
    | [ActivityNarrativeInformationType]
    | [ActivityNarrativeInformationType, ActivityNarrativeInformationType]
    | [
        ActivityNarrativeInformationType,
        ActivityNarrativeInformationType,
        ActivityNarrativeInformationType
      ]
    | [
        ActivityNarrativeInformationType,
        ActivityNarrativeInformationType,
        ActivityNarrativeInformationType,
        ActivityNarrativeInformationType
      ]
    | [
        ActivityNarrativeInformationType,
        ActivityNarrativeInformationType,
        ActivityNarrativeInformationType,
        ActivityNarrativeInformationType,
        ActivityNarrativeInformationType
      ]
  [k: string]: unknown
}
/**
 * The BSA Identifier (BSA ID) of the previously-filed FinCEN SAR when filing a correction/amendment and/or a continuing activity report. The value provided must adhere to the following requirements: 14-digit numeric BSA ID (if known); 14 consecutive zeros, i.e. “00000000000000” (if the BSA ID is unknown).
 */
export type PriorReportBSAIdentifierNumber = number
/**
 * The date in which the FinCEN SAR is being filed electronically through FinCEN’s BSA E-Filing System. The value provided must adhere to the following requirements: 8 numeric characters in the format YYYYMMDD where YYYY = year, MM = month, and DD = day. Single digit days or months must be prefaced by a zero
 */
export type FilingDate = string
/**
 * This element allows the filer to alert FinCEN that this FinCEN SAR is being filed in response to a current specific geographic targeting order (GTO) or advisory or other activity. The value provided must adhere to the following requirements: 50 characters or less.
 */
export type FilingInstitutionNoteToFinCEN = string
/**
 * This element declares that the FinCEN SAR being filed continues reporting on a previously-reported suspicious activity
 */
export type ContinuingActivityReportIndicator = 'Y' | ''
/**
 * This element declares that the FinCEN SAR being filed corrects or amends a previously-filed FinCEN SAR
 */
export type CorrectsAmendsPriorReportIndicator = 'Y' | ''
/**
 * This element declares that the FinCEN SAR being filed is the first report filed on the suspicious activity
 */
export type InitialReportIndicator = 'Y' | ''
/**
 * This element declares that the FinCEN SAR is being filed jointly by two or morefinancial institutions.
 */
export type JointReportIndicator = 'Y' | ''
export type RestrictString150 = string
export type Party = PartyType & {
  /**
   * @maxItems 100
   */
  PartyName?: PartyNameType[]
  /**
   * @maxItems 99
   */
  Address?: AddressType[]
  /**
   * @maxItems 99
   */
  PhoneNumber?: PhoneNumberType[]
  /**
   * @maxItems 100
   */
  PartyIdentification?: PartyIdentificationType[]
  /**
   * @maxItems 15
   */
  OrganizationClassificationTypeSubtype?:
    | []
    | [OrganizationClassificationTypeSubtypeType]
    | [
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType
      ]
    | [
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType
      ]
    | [
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType
      ]
    | [
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType
      ]
    | [
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType
      ]
    | [
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType
      ]
    | [
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType
      ]
    | [
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType
      ]
    | [
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType
      ]
    | [
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType
      ]
    | [
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType
      ]
    | [
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType
      ]
    | [
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType
      ]
    | [
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType,
        OrganizationClassificationTypeSubtypeType
      ]
  PartyOccupationBusiness?: PartyOccupationBusinessType
  /**
   * @maxItems 198
   */
  ElectronicAddress?: ElectronicAddressType[]
  /**
   * @maxItems 99
   */
  PartyAssociation?: PartyAssociation[]
  PartyAccountAssociation?: PartyAccountAssociation
  [k: string]: unknown
}
/**
 * Financial Institution in which account is held
 */
export type ValidateActivityPartyCodeType =
  | '35'
  | '37'
  | '30'
  | '33'
  | '34'
  | '8'
  | '46'
  | '18'
  | '19'
  | '41'
/**
 * This element declares that the subject individual has made no corroborative statement to the filer
 */
export type CorroborativeStatementToFilerNoIndicator = 'Y' | ''
/**
 *  This element declares that the subject individual has made a statement to the filer admitting to involvement in or otherwise substantiating the suspicious activity.
 */
export type CorroborativeStatementToFilerYesIndicator = 'Y' | ''
/**
 * This element declares that all critical subject information is unavailable
 */
export type AllCriticalSubjectInformationUnavailableIndicator = 'Y' | ''
export type DateOfBirthUnknownIndicator = 'Y' | ''
export type ValidateIndicatorType = 'Y' | ''
export type DateYYYYMMDDOrBlankType = string
export type DateYYYYMMDDOrBlankTypeDOB = string
export type RestrictString15 = string
/**
 * Not applicable
 */
export type ValidateFederalRegulatorCodeType =
  | '9'
  | '1'
  | '2'
  | '7'
  | '3'
  | '4'
  | '6'
  | '13'
  | '99'
/**
 * Doing business as (DBA)
 */
export type ValidatePartyNameCodeType = 'L' | 'AKA' | 'DBA'
export type RestrictString35 = string
export type RestrictString50 = string
export type RestrictString2 = string
export type RestrictString3 = string
export type RestrictString100 = string
export type RestrictString9 = string
export type RestrictString6 = string
export type RestrictString16 = string
/**
 * Work
 */
export type ValidatePhoneNumberCodeType = 'F' | 'M' | 'R' | 'W'
export type RestrictString25 = string
/**
 * Other
 */
export type ValidatePartyIdentificationCodeType =
  | '1'
  | '2'
  | '4'
  | '5'
  | '6'
  | '7'
  | '9'
  | '10'
  | '11'
  | '12'
  | '13'
  | '14'
  | '28'
  | '32'
  | '33'
  | '29'
  | '999'
/**
 * Other securities/futures
 */
export type ValidateOrganizationSubtypeCodeType =
  | '101'
  | '102'
  | '103'
  | '503'
  | '504'
  | '508'
  | '513'
  | '514'
  | '535'
  | '528'
  | '529'
  | '533'
  | '534'
  | '539'
  | '540'
  | '541'
  | '542'
  | '1999'
  | '5999'
/**
 * Other
 */
export type ValidateOrganizationCodeType =
  | '1'
  | '2'
  | '3'
  | '4'
  | '5'
  | '11'
  | '12'
  | '999'
export type RestrictString517 = string
/**
 * URL
 */
export type ValidateElectronicAddressTypeCode = 'E' | 'U'
export type PartyAssociation = PartyAssociationType & {
  Party?: unknown | unknown[]
  [k: string]: unknown
}
export type PartyAccountAssociation = PartyAccountAssociationType & {
  Party: unknown | [unknown, ...unknown[]]
  [k: string]: unknown
}
/**
 * Activity affected account
 */
export type ValidatePartyAccountAssociationCodeType = '5' | '7'
export type SuspiciousActivity = SuspiciousActivityType & {
  /**
   * @maxItems 99
   */
  SuspiciousActivityClassification: SuspiciousActivityClassificationType[]
  [k: string]: unknown
}
export type DateYYYYMMDDType = string
/**
 * Other
 */
export type ValidateSuspiciousActivitySubtypeID =
  | '106'
  | '111'
  | '112'
  | '113'
  | '114'
  | '301'
  | '304'
  | '305'
  | '308'
  | '309'
  | '310'
  | '312'
  | '320'
  | '321'
  | '322'
  | '323'
  | '324'
  | '325'
  | '401'
  | '402'
  | '403'
  | '404'
  | '405'
  | '409'
  | '501'
  | '502'
  | '504'
  | '505'
  | '506'
  | '507'
  | '601'
  | '603'
  | '604'
  | '608'
  | '609'
  | '701'
  | '801'
  | '804'
  | '805'
  | '806'
  | '807'
  | '808'
  | '809'
  | '812'
  | '820'
  | '821'
  | '822'
  | '823'
  | '824'
  | '901'
  | '903'
  | '904'
  | '905'
  | '907'
  | '908'
  | '909'
  | '910'
  | '911'
  | '913'
  | '917'
  | '920'
  | '921'
  | '922'
  | '924'
  | '925'
  | '926'
  | '927'
  | '928'
  | '1001'
  | '1003'
  | '1005'
  | '1006'
  | '1007'
  | '1101'
  | '1102'
  | '1201'
  | '1202'
  | '1203'
  | '1204'
  | '1999'
  | '3999'
  | '4999'
  | '5999'
  | '6999'
  | '7999'
  | '8999'
  | '9999'
  | '10999'
  | '11999'
  | '12999'
/**
 * Cyber event
 */
export type ValidateSuspiciousActivityTypeID =
  | '1'
  | '12'
  | '3'
  | '4'
  | '5'
  | '6'
  | '7'
  | '8'
  | '9'
  | '10'
  | '11'
export type ValidateTimeDataOrBlankType = string
export type RestrictString39 = string
/**
 * Other
 */
export type ValidateCyberEventIndicatorsTypeCode =
  | '1'
  | '2'
  | '3'
  | '4'
  | '5'
  | '6'
  | '7'
  | '8'
  | '9'
  | '10'
  | '999'
export type RestrictString4000 = string
/**
 * Microcap Securities
 */
export type ValidateAssetSubtypeIDTypeCode =
  | '1'
  | '2'
  | '3'
  | '4'
  | '5'
  | '6'
  | '7'
  | '8'
  | '9'
  | '10'
  | '11'
  | '12'
  | '13'
  | '14'
  | '16'
  | '17'
  | '18'
  | '19'
  | '20'
  | '30'
  | '31'
  | '32'
  | '33'
  | '34'
  | '35'
  | '36'
  | '37'
  | '38'
  | '39'
  | '41'
  | '46'
  | '47'
/**
 * Financial instrument or payment mechanism
 */
export type ValidateAssetTypeIDTypeCode = '5' | '6'
/**
 * Market Where Traded Code
 */
export type ValidateAssetAttributeTypeIDTypeCode = '1' | '2' | '3' | '4'
/**
 * Fifth block of narrative text (character set 16001-17000, if needed)
 */
export type ValidateActivityNarrativeSequenceNumber =
  | '1'
  | '2'
  | '3'
  | '4'
  | '5'

/**
 * Schema tag attributes: xmlns='www.fincen.gov/base' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:vc='http://www.w3.org/2007/XMLSchema-versioning' xmlns:fc2='www.fincen.gov/base' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' targetNamespace='www.fincen.gov/base' elementFormDefault='qualified' attributeFormDefault='unqualified' vc:minVersion='1.1'
 */
export interface ThisJSONSchemaFileWasGeneratedFromSchemaOnThuJul272023232138GMT0200CentralEuropeanSummerTimeForMoreInformationPleaseSeeHttpWwwXsd2JsonschemaOrg {
  EFilingBatchXML?: EFilingBatchXML
  [k: string]: unknown
}
export interface EFilingBatchXML {
  FormTypeCode: string
  Activity: Activity[]
  '@TotalAmount': number
  '@PartyCount': number
  '@ActivityCount': number
  '@ActivityAttachmentCount': number
  '@AttachmentCount': number
  [k: string]: unknown
}
export interface ActivityType {
  EFilingPriorDocumentNumber?: PriorReportBSAIdentifierNumber
  FilingDateText: FilingDate
  FilingInstitutionNotetoFinCEN?: FilingInstitutionNoteToFinCEN
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface ActivityAssociationType {
  ContinuingActivityReportIndicator?: ContinuingActivityReportIndicator
  CorrectsAmendsPriorReportIndicator?: CorrectsAmendsPriorReportIndicator
  InitialReportIndicator?: InitialReportIndicator
  JointReportIndicator?: JointReportIndicator
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface ActivitySupportDocumentType {
  OriginalAttachmentFileName: RestrictString150
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface PartyType {
  ActivityPartyTypeCode: ValidateActivityPartyCodeType
  AdmissionConfessionNoIndicator?: CorroborativeStatementToFilerNoIndicator
  AdmissionConfessionYesIndicator?: CorroborativeStatementToFilerYesIndicator
  AllCriticalSubjectInformationUnavailableIndicator?: AllCriticalSubjectInformationUnavailableIndicator
  BirthDateUnknownIndicator?: DateOfBirthUnknownIndicator
  BothPurchaserSenderPayeeReceiveIndicator?: ValidateIndicatorType
  ContactDateText?: DateYYYYMMDDOrBlankType
  FemaleGenderIndicator?: ValidateIndicatorType
  IndividualBirthDateText?: DateYYYYMMDDOrBlankTypeDOB
  LossToFinancialAmountText?: RestrictString15
  MaleGenderIndicator?: ValidateIndicatorType
  NoBranchActivityInvolvedIndicator?: ValidateIndicatorType
  NoKnownAccountInvolvedIndicator?: ValidateIndicatorType
  NonUSFinancialInstitutionIndicator?: ValidateIndicatorType
  PartyAsEntityOrganizationIndicator?: ValidateIndicatorType
  PayeeReceiverIndicator?: ValidateIndicatorType
  PayLocationIndicator?: ValidateIndicatorType
  PrimaryRegulatorTypeCode?: ValidateFederalRegulatorCodeType
  PurchaserSenderIndicator?: ValidateIndicatorType
  SellingLocationIndicator?: ValidateIndicatorType
  SellingPayingLocationIndicator?: ValidateIndicatorType
  UnknownGenderIndicator?: ValidateIndicatorType
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface PartyNameType {
  EntityLastNameUnknownIndicator?: ValidateIndicatorType
  FirstNameUnknownIndicator?: ValidateIndicatorType
  PartyNameTypeCode: ValidatePartyNameCodeType
  RawEntityIndividualLastName?: RestrictString150
  RawIndividualFirstName?: RestrictString35
  RawIndividualMiddleName?: RestrictString35
  RawIndividualNameSuffixText?: RestrictString35
  RawPartyFullName?: RestrictString150
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface AddressType {
  CityUnknownIndicator?: ValidateIndicatorType
  CountryCodeUnknownIndicator?: ValidateIndicatorType
  RawCityText?: RestrictString50
  RawCountryCodeText?: RestrictString2
  RawStateCodeText?: RestrictString3
  RawStreetAddress1Text?: RestrictString100
  RawZIPCode?: RestrictString9
  StateCodeUnknownIndicator?: ValidateIndicatorType
  StreetAddressUnknownIndicator?: ValidateIndicatorType
  ZIPCodeUnknownIndicator?: ValidateIndicatorType
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface PhoneNumberType {
  PhoneNumberExtensionText?: RestrictString6
  PhoneNumberText?: RestrictString16
  PhoneNumberTypeCode?: ValidatePhoneNumberCodeType
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface PartyIdentificationType {
  IdentificationPresentUnknownIndicator?: ValidateIndicatorType
  OtherIssuerCountryText?: RestrictString2
  OtherIssuerStateText?: RestrictString3
  OtherPartyIdentificationTypeText?: RestrictString50
  PartyIdentificationNumberText?: RestrictString25
  PartyIdentificationTypeCode?: ValidatePartyIdentificationCodeType
  TINUnknownIndicator?: ValidateIndicatorType
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface OrganizationClassificationTypeSubtypeType {
  OrganizationSubtypeID?: ValidateOrganizationSubtypeCodeType
  OrganizationTypeID: ValidateOrganizationCodeType
  OtherOrganizationSubTypeText?: RestrictString50
  OtherOrganizationTypeText?: RestrictString50
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface PartyOccupationBusinessType {
  NAICSCode?: RestrictString6
  OccupationBusinessText?: RestrictString50
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface ElectronicAddressType {
  ElectronicAddressText: RestrictString517
  ElectronicAddressTypeCode: ValidateElectronicAddressTypeCode
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface PartyAssociationType {
  AccountantIndicator?: ValidateIndicatorType
  ActionTakenDateText?: DateYYYYMMDDOrBlankType
  AgentIndicator?: ValidateIndicatorType
  AppraiserIndicator?: ValidateIndicatorType
  AttorneyIndicator?: ValidateIndicatorType
  BorrowerIndicator?: ValidateIndicatorType
  CustomerIndicator?: ValidateIndicatorType
  DirectorIndicator?: ValidateIndicatorType
  EmployeeIndicator?: ValidateIndicatorType
  NoRelationshipToInstitutionIndicator?: ValidateIndicatorType
  OfficerIndicator?: ValidateIndicatorType
  OtherPartyAssociationTypeText?: RestrictString50
  OtherRelationshipIndicator?: ValidateIndicatorType
  OwnerShareholderIndicator?: ValidateIndicatorType
  RelationshipContinuesIndicator?: ValidateIndicatorType
  ResignedIndicator?: ValidateIndicatorType
  SubjectRelationshipFinancialInstitutionTINText?: RestrictString25
  SuspendedBarredIndicator?: ValidateIndicatorType
  TerminatedIndicator?: ValidateIndicatorType
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface PartyAccountAssociationType {
  AccountClosedIndicator?: ValidateIndicatorType
  PartyAccountAssociationTypeCode: ValidatePartyAccountAssociationCodeType
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface SuspiciousActivityType {
  AmountUnknownIndicator?: ValidateIndicatorType
  CumulativeTotalViolationAmountText?: RestrictString15
  NoAmountInvolvedIndicator?: ValidateIndicatorType
  SuspiciousActivityFromDateText: DateYYYYMMDDType
  SuspiciousActivityToDateText?: DateYYYYMMDDOrBlankType
  TotalSuspiciousAmountText?: RestrictString15
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface SuspiciousActivityClassificationType {
  OtherSuspiciousActivityTypeText?: RestrictString50
  SuspiciousActivitySubtypeID: ValidateSuspiciousActivitySubtypeID
  SuspiciousActivityTypeID: ValidateSuspiciousActivityTypeID
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface ActivityIPAddressType {
  ActivityIPAddressDateText?: DateYYYYMMDDOrBlankType
  ActivityIPAddressTimeStampText?: ValidateTimeDataOrBlankType
  IPAddressText: RestrictString39
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface CyberEventIndicatorsType {
  CyberEventDateText?: DateYYYYMMDDOrBlankType
  CyberEventIndicatorsTypeCode: ValidateCyberEventIndicatorsTypeCode
  CyberEventTimeStampText?: ValidateTimeDataOrBlankType
  CyberEventTypeOtherText?: RestrictString50
  EventValueText: RestrictString4000
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface AssetsTableType {
  AssetSubtypeID: ValidateAssetSubtypeIDTypeCode
  AssetTypeID: ValidateAssetTypeIDTypeCode
  OtherAssetSubtypeText?: RestrictString50
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface AssetsAttributeType {
  AssetAttributeDescriptionText?: RestrictString50
  AssetAttributeTypeID: ValidateAssetAttributeTypeIDTypeCode
  '@SeqNum'?: undefined
  [k: string]: unknown
}
export interface ActivityNarrativeInformationType {
  ActivityNarrativeSequenceNumber: ValidateActivityNarrativeSequenceNumber
  ActivityNarrativeText: RestrictString4000
  '@SeqNum'?: undefined
  [k: string]: unknown
}
