/**
 * Generated by running ts-node US/SAR/scripts/xml-to-json.ts
 * IMPORTANT: Please don't update this file manually
 */

export const FincenJsonSchema = {
  $id: 'schema.json',
  $schema: 'http://json-schema.org/draft-07/schema#',
  title:
    'This JSON Schema file was generated from schema on Tue Jun 27 2023 11:37:18 GMT+0200 (Central European Summer Time).  For more information please see http://www.xsd2jsonschema.org',
  description:
    "Schema tag attributes: xmlns='www.fincen.gov/base' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:vc='http://www.w3.org/2007/XMLSchema-versioning' xmlns:fc2='www.fincen.gov/base' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' targetNamespace='www.fincen.gov/base' elementFormDefault='qualified' attributeFormDefault='unqualified' vc:minVersion='1.1'",
  properties: {
    EFilingBatchXML: {
      $ref: '#/definitions/EFilingBatchXML',
    },
  },
  type: 'object',
  definitions: {
    AccountType: {
      required: ['@SeqNum'],
      properties: {
        AccountNumberText: {
          $ref: '#/definitions/RestrictString40',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    ActivityAssociationType: {
      required: ['@SeqNum'],
      properties: {
        ContinuingActivityReportIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        CorrectsAmendsPriorReportIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        InitialReportIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        JointReportIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    ActivityIPAddressType: {
      required: ['IPAddressText', '@SeqNum'],
      properties: {
        ActivityIPAddressDateText: {
          $ref: '#/definitions/DateYYYYMMDDOrBlankType',
        },
        ActivityIPAddressTimeStampText: {
          $ref: '#/definitions/ValidateTimeDataOrBlankType',
        },
        IPAddressText: {
          $ref: '#/definitions/RestrictString39',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    ActivityNarrativeInformationType: {
      required: [
        'ActivityNarrativeSequenceNumber',
        'ActivityNarrativeText',
        '@SeqNum',
      ],
      properties: {
        ActivityNarrativeSequenceNumber: {
          $ref: '#/definitions/ValidateActivityNarrativeSequenceNumber',
        },
        ActivityNarrativeText: {
          $ref: '#/definitions/RestrictString4000',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    ActivitySupportDocumentType: {
      required: ['OriginalAttachmentFileName', '@SeqNum'],
      properties: {
        OriginalAttachmentFileName: {
          $ref: '#/definitions/RestrictString150',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    ActivityType: {
      required: ['FilingDateText', '@SeqNum'],
      properties: {
        EFilingPriorDocumentNumber: {
          $ref: '#/definitions/RestrictLong14',
        },
        FilingDateText: {
          $ref: '#/definitions/DateYYYYMMDDType',
        },
        FilingInstitutionNotetoFinCEN: {
          $ref: '#/definitions/RestrictString50',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    AddressType: {
      required: ['@SeqNum'],
      properties: {
        CityUnknownIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        CountryCodeUnknownIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        RawCityText: {
          $ref: '#/definitions/RestrictString50',
        },
        RawCountryCodeText: {
          $ref: '#/definitions/RestrictString2',
        },
        RawStateCodeText: {
          $ref: '#/definitions/RestrictString3',
        },
        RawStreetAddress1Text: {
          $ref: '#/definitions/RestrictString100',
        },
        RawZIPCode: {
          $ref: '#/definitions/RestrictString9',
        },
        StateCodeUnknownIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        StreetAddressUnknownIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        ZIPCodeUnknownIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    AssetsAttributeType: {
      required: ['AssetAttributeTypeID', '@SeqNum'],
      properties: {
        AssetAttributeDescriptionText: {
          $ref: '#/definitions/RestrictString50',
        },
        AssetAttributeTypeID: {
          $ref: '#/definitions/ValidateAssetAttributeTypeIDTypeCode',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    AssetsTableType: {
      required: ['AssetSubtypeID', 'AssetTypeID', '@SeqNum'],
      properties: {
        AssetSubtypeID: {
          $ref: '#/definitions/ValidateAssetSubtypeIDTypeCode',
        },
        AssetTypeID: {
          $ref: '#/definitions/ValidateAssetTypeIDTypeCode',
        },
        OtherAssetSubtypeText: {
          $ref: '#/definitions/RestrictString50',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    CyberEventIndicatorsType: {
      required: ['CyberEventIndicatorsTypeCode', 'EventValueText', '@SeqNum'],
      properties: {
        CyberEventDateText: {
          $ref: '#/definitions/DateYYYYMMDDOrBlankType',
        },
        CyberEventIndicatorsTypeCode: {
          $ref: '#/definitions/ValidateCyberEventIndicatorsTypeCode',
        },
        CyberEventTimeStampText: {
          $ref: '#/definitions/ValidateTimeDataOrBlankType',
        },
        CyberEventTypeOtherText: {
          $ref: '#/definitions/RestrictString50',
        },
        EventValueText: {
          $ref: '#/definitions/RestrictString4000',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    ElectronicAddressType: {
      required: [
        'ElectronicAddressText',
        'ElectronicAddressTypeCode',
        '@SeqNum',
      ],
      properties: {
        ElectronicAddressText: {
          $ref: '#/definitions/RestrictString517',
        },
        ElectronicAddressTypeCode: {
          $ref: '#/definitions/ValidateElectronicAddressTypeCode',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    OrganizationClassificationTypeSubtypeType: {
      required: ['OrganizationTypeID', '@SeqNum'],
      properties: {
        OrganizationSubtypeID: {
          $ref: '#/definitions/ValidateOrganizationSubtypeCodeType',
        },
        OrganizationTypeID: {
          $ref: '#/definitions/ValidateOrganizationCodeType',
        },
        OtherOrganizationSubTypeText: {
          $ref: '#/definitions/RestrictString50',
        },
        OtherOrganizationTypeText: {
          $ref: '#/definitions/RestrictString50',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    PartyAccountAssociationType: {
      required: ['PartyAccountAssociationTypeCode', '@SeqNum'],
      properties: {
        AccountClosedIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        PartyAccountAssociationTypeCode: {
          $ref: '#/definitions/ValidatePartyAccountAssociationCodeType',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    PartyAssociationType: {
      required: ['@SeqNum'],
      properties: {
        AccountantIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        ActionTakenDateText: {
          $ref: '#/definitions/DateYYYYMMDDOrBlankType',
        },
        AgentIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        AppraiserIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        AttorneyIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        BorrowerIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        CustomerIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        DirectorIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        EmployeeIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        NoRelationshipToInstitutionIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        OfficerIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        OtherPartyAssociationTypeText: {
          $ref: '#/definitions/RestrictString50',
        },
        OtherRelationshipIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        OwnerShareholderIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        RelationshipContinuesIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        ResignedIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        SubjectRelationshipFinancialInstitutionTINText: {
          $ref: '#/definitions/RestrictString25',
        },
        SuspendedBarredIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        TerminatedIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    PartyIdentificationType: {
      required: ['@SeqNum'],
      properties: {
        IdentificationPresentUnknownIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        OtherIssuerCountryText: {
          $ref: '#/definitions/RestrictString2',
        },
        OtherIssuerStateText: {
          $ref: '#/definitions/RestrictString3',
        },
        OtherPartyIdentificationTypeText: {
          $ref: '#/definitions/RestrictString50',
        },
        PartyIdentificationNumberText: {
          $ref: '#/definitions/RestrictString25',
        },
        PartyIdentificationTypeCode: {
          $ref: '#/definitions/ValidatePartyIdentificationCodeType',
        },
        TINUnknownIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    PartyNameType: {
      required: ['PartyNameTypeCode', '@SeqNum'],
      properties: {
        EntityLastNameUnknownIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        FirstNameUnknownIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        PartyNameTypeCode: {
          $ref: '#/definitions/ValidatePartyNameCodeType',
        },
        RawEntityIndividualLastName: {
          $ref: '#/definitions/RestrictString150',
        },
        RawIndividualFirstName: {
          $ref: '#/definitions/RestrictString35',
        },
        RawIndividualMiddleName: {
          $ref: '#/definitions/RestrictString35',
        },
        RawIndividualNameSuffixText: {
          $ref: '#/definitions/RestrictString35',
        },
        RawPartyFullName: {
          $ref: '#/definitions/RestrictString150',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    PartyOccupationBusinessType: {
      required: ['@SeqNum'],
      properties: {
        NAICSCode: {
          $ref: '#/definitions/RestrictString6',
        },
        OccupationBusinessText: {
          $ref: '#/definitions/RestrictString50',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    PartyType: {
      required: ['ActivityPartyTypeCode', '@SeqNum'],
      properties: {
        ActivityPartyTypeCode: {
          $ref: '#/definitions/ValidateActivityPartyCodeType',
        },
        AdmissionConfessionNoIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        AdmissionConfessionYesIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        AllCriticalSubjectInformationUnavailableIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        BirthDateUnknownIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        BothPurchaserSenderPayeeReceiveIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        ContactDateText: {
          $ref: '#/definitions/DateYYYYMMDDOrBlankType',
        },
        FemaleGenderIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        IndividualBirthDateText: {
          $ref: '#/definitions/DateYYYYMMDDOrBlankTypeDOB',
        },
        LossToFinancialAmountText: {
          $ref: '#/definitions/RestrictString15',
        },
        MaleGenderIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        NoBranchActivityInvolvedIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        NoKnownAccountInvolvedIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        NonUSFinancialInstitutionIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        PartyAsEntityOrganizationIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        PayeeReceiverIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        PayLocationIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        PrimaryRegulatorTypeCode: {
          $ref: '#/definitions/ValidateFederalRegulatorCodeType',
        },
        PurchaserSenderIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        SellingLocationIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        SellingPayingLocationIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        UnknownGenderIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    PhoneNumberType: {
      required: ['@SeqNum'],
      properties: {
        PhoneNumberExtensionText: {
          $ref: '#/definitions/RestrictString6',
        },
        PhoneNumberText: {
          $ref: '#/definitions/RestrictString16',
        },
        PhoneNumberTypeCode: {
          $ref: '#/definitions/ValidatePhoneNumberCodeType',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    SuspiciousActivityClassificationType: {
      required: [
        'SuspiciousActivitySubtypeID',
        'SuspiciousActivityTypeID',
        '@SeqNum',
      ],
      properties: {
        OtherSuspiciousActivityTypeText: {
          $ref: '#/definitions/RestrictString50',
        },
        SuspiciousActivitySubtypeID: {
          $ref: '#/definitions/ValidateSuspiciousActivitySubtypeID',
        },
        SuspiciousActivityTypeID: {
          $ref: '#/definitions/ValidateSuspiciousActivityTypeID',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    SuspiciousActivityType: {
      required: ['SuspiciousActivityFromDateText', '@SeqNum'],
      properties: {
        AmountUnknownIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        CumulativeTotalViolationAmountText: {
          $ref: '#/definitions/RestrictString15',
        },
        NoAmountInvolvedIndicator: {
          $ref: '#/definitions/ValidateIndicatorType',
        },
        SuspiciousActivityFromDateText: {
          $ref: '#/definitions/DateYYYYMMDDType',
        },
        SuspiciousActivityToDateText: {
          $ref: '#/definitions/DateYYYYMMDDOrBlankType',
        },
        TotalSuspiciousAmountText: {
          $ref: '#/definitions/RestrictString15',
        },
        '@SeqNum': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    EFilingBatchXML: {
      required: [
        'FormTypeCode',
        'Activity',
        '@TotalAmount',
        '@PartyCount',
        '@ActivityCount',
        '@ActivityAttachmentCount',
        '@AttachmentCount',
      ],
      properties: {
        FormTypeCode: {
          type: 'string',
        },
        Activity: {
          oneOf: [
            {
              $ref: '#/definitions/Activity',
            },
            {
              items: {
                $ref: '#/definitions/Activity',
              },
              type: 'array',
            },
          ],
        },
        '@TotalAmount': {
          type: 'number',
        },
        '@PartyCount': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
        '@ActivityCount': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
        '@ActivityAttachmentCount': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
        '@AttachmentCount': {
          maximum: 9223372036854776000,
          minimum: -9223372036854776000,
          type: 'integer',
        },
      },
      type: 'object',
    },
    Activity: {
      type: 'object',
      allOf: [
        {
          $ref: '#/definitions/ActivityType',
        },
        {
          required: [
            'ActivityAssociation',
            'Party',
            'SuspiciousActivity',
            'ActivityNarrativeInformation',
          ],
          properties: {
            ActivityAssociation: {
              $ref: '#/definitions/ActivityAssociationType',
            },
            ActivitySupportDocument: {
              $ref: '#/definitions/ActivitySupportDocumentType',
            },
            Party: {
              oneOf: [
                {
                  $ref: '#/definitions/Party',
                },
                {
                  items: {
                    $ref: '#/definitions/Party',
                  },
                  maxItems: 1203,
                  minItems: 6,
                  type: 'array',
                },
              ],
            },
            SuspiciousActivity: {
              $ref: '#/definitions/SuspiciousActivity',
            },
            ActivityIPAddress: {
              oneOf: [
                {
                  $ref: '#/definitions/ActivityIPAddressType',
                },
                {
                  items: {
                    $ref: '#/definitions/ActivityIPAddressType',
                  },
                  maxItems: 99,
                  type: 'array',
                },
              ],
            },
            CyberEventIndicators: {
              oneOf: [
                {
                  $ref: '#/definitions/CyberEventIndicatorsType',
                },
                {
                  items: {
                    $ref: '#/definitions/CyberEventIndicatorsType',
                  },
                  maxItems: 99,
                  type: 'array',
                },
              ],
            },
            Assets: {
              oneOf: [
                {
                  $ref: '#/definitions/AssetsTableType',
                },
                {
                  items: {
                    $ref: '#/definitions/AssetsTableType',
                  },
                  maxItems: 31,
                  type: 'array',
                },
              ],
            },
            AssetsAttribute: {
              oneOf: [
                {
                  $ref: '#/definitions/AssetsAttributeType',
                },
                {
                  items: {
                    $ref: '#/definitions/AssetsAttributeType',
                  },
                  maxItems: 396,
                  type: 'array',
                },
              ],
            },
            ActivityNarrativeInformation: {
              oneOf: [
                {
                  $ref: '#/definitions/ActivityNarrativeInformationType',
                },
                {
                  items: {
                    $ref: '#/definitions/ActivityNarrativeInformationType',
                  },
                  maxItems: 5,
                  type: 'array',
                },
              ],
            },
          },
        },
      ],
    },
    Party: {
      type: 'object',
      allOf: [
        {
          $ref: '#/definitions/PartyType',
        },
        {
          properties: {
            PartyName: {
              oneOf: [
                {
                  $ref: '#/definitions/PartyNameType',
                },
                {
                  items: {
                    $ref: '#/definitions/PartyNameType',
                  },
                  maxItems: 100,
                  type: 'array',
                },
              ],
            },
            Address: {
              oneOf: [
                {
                  $ref: '#/definitions/AddressType',
                },
                {
                  items: {
                    $ref: '#/definitions/AddressType',
                  },
                  maxItems: 99,
                  type: 'array',
                },
              ],
            },
            PhoneNumber: {
              oneOf: [
                {
                  $ref: '#/definitions/PhoneNumberType',
                },
                {
                  items: {
                    $ref: '#/definitions/PhoneNumberType',
                  },
                  maxItems: 99,
                  type: 'array',
                },
              ],
            },
            PartyIdentification: {
              oneOf: [
                {
                  $ref: '#/definitions/PartyIdentificationType',
                },
                {
                  items: {
                    $ref: '#/definitions/PartyIdentificationType',
                  },
                  maxItems: 100,
                  type: 'array',
                },
              ],
            },
            OrganizationClassificationTypeSubtype: {
              oneOf: [
                {
                  $ref: '#/definitions/OrganizationClassificationTypeSubtypeType',
                },
                {
                  items: {
                    $ref: '#/definitions/OrganizationClassificationTypeSubtypeType',
                  },
                  maxItems: 15,
                  type: 'array',
                },
              ],
            },
            PartyOccupationBusiness: {
              $ref: '#/definitions/PartyOccupationBusinessType',
            },
            ElectronicAddress: {
              oneOf: [
                {
                  $ref: '#/definitions/ElectronicAddressType',
                },
                {
                  items: {
                    $ref: '#/definitions/ElectronicAddressType',
                  },
                  maxItems: 198,
                  type: 'array',
                },
              ],
            },
            PartyAssociation: {
              oneOf: [
                {
                  $ref: '#/definitions/PartyAssociation',
                },
                {
                  items: {
                    $ref: '#/definitions/PartyAssociation',
                  },
                  maxItems: 99,
                  type: 'array',
                },
              ],
            },
            PartyAccountAssociation: {
              $ref: '#/definitions/PartyAccountAssociation',
            },
          },
        },
      ],
    },
    PartyAssociation: {
      type: 'object',
      allOf: [
        {
          $ref: '#/definitions/PartyAssociationType',
        },
        {
          properties: {
            Party: {
              oneOf: [
                {},
                {
                  items: {},
                  maxItems: 99,
                  type: 'array',
                },
              ],
            },
          },
        },
      ],
    },
    PartyAccountAssociation: {
      type: 'object',
      allOf: [
        {
          $ref: '#/definitions/PartyAccountAssociationType',
        },
        {
          required: ['Party'],
          properties: {
            Party: {
              oneOf: [
                {},
                {
                  items: {},
                  maxItems: 99,
                  minItems: 1,
                  type: 'array',
                },
              ],
            },
          },
        },
      ],
    },
    SuspiciousActivity: {
      type: 'object',
      allOf: [
        {
          $ref: '#/definitions/SuspiciousActivityType',
        },
        {
          required: ['SuspiciousActivityClassification'],
          properties: {
            SuspiciousActivityClassification: {
              oneOf: [
                {
                  $ref: '#/definitions/SuspiciousActivityClassificationType',
                },
                {
                  items: {
                    $ref: '#/definitions/SuspiciousActivityClassificationType',
                  },
                  maxItems: 99,
                  type: 'array',
                },
              ],
            },
          },
        },
      ],
    },
    ValidateIndicatorType: {
      enum: ['Y', ''],
      type: 'string',
    },
    DateYYYYMMDDType: {
      pattern: '(19|20)[0-9][0-9](0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[01])',
      type: 'string',
    },
    DateYYYYMMDDOrBlankType: {
      pattern: '(19|20)[0-9][0-9](0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[01])|',
      type: 'string',
    },
    ValidateTimeDataOrBlankType: {
      pattern: '([0-1][0-9]|(2[0-3])):[0-5][0-9]:[0-5][0-9]|',
      type: 'string',
    },
    DateYYYYMMDDOrBlankTypeDOB: {
      pattern: '(19|20)[0-9][0-9](0[0-9]|1[0-2])(0[0-9]|1[0-9]|2[0-9]|3[01])|',
      type: 'string',
    },
    RestrictString2: {
      maxLength: 2,
      pattern: '\\S+( +\\S+)*|',
      type: 'string',
    },
    RestrictString3: {
      maxLength: 3,
      pattern: '\\S+( +\\S+)*|',
      type: 'string',
    },
    RestrictString6: {
      maxLength: 6,
      pattern: '\\S+( +\\S+)*|',
      type: 'string',
    },
    RestrictString9: {
      maxLength: 9,
      pattern: '\\S+( +\\S+)*|',
      type: 'string',
    },
    RestrictLong14: {
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      type: 'integer',
    },
    RestrictString15: {
      maxLength: 15,
      pattern: '\\S+( +\\S+)*|',
      type: 'string',
    },
    RestrictString16: {
      maxLength: 16,
      pattern: '\\S+( +\\S+)*|',
      type: 'string',
    },
    RestrictString25: {
      maxLength: 25,
      pattern: '\\S+( +\\S+)*|',
      type: 'string',
    },
    RestrictString30: {
      maxLength: 30,
      pattern: '\\S+( +\\S+)*|',
      type: 'string',
    },
    RestrictString35: {
      maxLength: 35,
      pattern: '\\S+( +\\S+)*|',
      type: 'string',
    },
    RestrictString39: {
      maxLength: 39,
      pattern: '\\S+( +\\S+)*|',
      type: 'string',
    },
    RestrictString40: {
      maxLength: 40,
      pattern: '\\S+( +\\S+)*|',
      type: 'string',
    },
    RestrictString50: {
      maxLength: 50,
      pattern: '\\S+( +\\S+)*|',
      type: 'string',
    },
    RestrictString100: {
      maxLength: 100,
      pattern: '\\S+( +\\S+)*|',
      type: 'string',
    },
    RestrictString150: {
      maxLength: 150,
      pattern: '\\S+( +\\S+)*|',
      type: 'string',
    },
    RestrictString517: {
      maxLength: 517,
      pattern: '\\S+( +\\S+)*|',
      type: 'string',
    },
    RestrictString4000: {
      maxLength: 4000,
      type: 'string',
    },
    ValidateActivityPartyCodeType: {
      description: 'Financial Institution in which account is held',
      enum: ['35', '37', '30', '33', '34', '8', '46', '18', '19', '41'],
      type: 'string',
    },
    ValidateOrganizationCodeType: {
      description: 'Other',
      maximum: 2147483647,
      minimum: -2147483648,
      enum: ['1', '2', '3', '4', '5', '11', '12', '999'],
      type: 'integer',
    },
    ValidateOrganizationSubtypeCodeType: {
      description: 'Other securities/futures',
      maximum: 2147483647,
      minimum: -2147483648,
      enum: [
        '101',
        '102',
        '103',
        '503',
        '504',
        '508',
        '513',
        '514',
        '535',
        '528',
        '529',
        '533',
        '534',
        '539',
        '540',
        '541',
        '542',
        '1999',
        '5999',
      ],
      type: 'integer',
    },
    ValidatePartyNameCodeType: {
      description: 'Doing business as (DBA)',
      enum: ['L', 'AKA', 'DBA'],
      type: 'string',
    },
    ValidatePartyAccountAssociationCodeType: {
      description: 'Activity affected account',
      enum: ['5', '7'],
      type: 'string',
    },
    ValidateFederalRegulatorCodeType: {
      description: 'Not applicable',
      enum: ['9', '1', '2', '7', '3', '4', '6', '13', '99'],
      type: 'string',
    },
    ValidatePartyIdentificationCodeType: {
      description: 'Other',
      enum: [
        '1',
        '2',
        '4',
        '5',
        '6',
        '7',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '28',
        '32',
        '33',
        '29',
        '999',
      ],
      type: 'string',
    },
    ValidatePhoneNumberCodeType: {
      description: 'Work',
      enum: ['F', 'M', 'R', 'W'],
      type: 'string',
    },
    ValidateElectronicAddressTypeCode: {
      description: 'URL',
      enum: ['E', 'U'],
      type: 'string',
    },
    ValidateSuspiciousActivityTypeID: {
      description: 'Cyber event',
      maximum: 2147483647,
      minimum: -2147483648,
      enum: ['1', '12', '3', '4', '5', '6', '7', '8', '9', '10', '11'],
      type: 'integer',
    },
    ValidateSuspiciousActivitySubtypeID: {
      description: 'Other',
      maximum: 2147483647,
      minimum: -2147483648,
      enum: [
        '106',
        '111',
        '112',
        '113',
        '114',
        '301',
        '304',
        '305',
        '308',
        '309',
        '310',
        '312',
        '320',
        '321',
        '322',
        '323',
        '324',
        '325',
        '401',
        '402',
        '403',
        '404',
        '405',
        '409',
        '501',
        '502',
        '504',
        '505',
        '506',
        '507',
        '601',
        '603',
        '604',
        '608',
        '609',
        '701',
        '801',
        '804',
        '805',
        '806',
        '807',
        '808',
        '809',
        '812',
        '820',
        '821',
        '822',
        '823',
        '824',
        '901',
        '903',
        '904',
        '905',
        '907',
        '908',
        '909',
        '910',
        '911',
        '913',
        '917',
        '920',
        '921',
        '922',
        '924',
        '925',
        '926',
        '927',
        '928',
        '1001',
        '1003',
        '1005',
        '1006',
        '1007',
        '1101',
        '1102',
        '1201',
        '1202',
        '1203',
        '1204',
        '1999',
        '3999',
        '4999',
        '5999',
        '6999',
        '7999',
        '8999',
        '9999',
        '10999',
        '11999',
        '12999',
      ],
      type: 'integer',
    },
    ValidateAssetSubtypeIDTypeCode: {
      description: 'Microcap Securities',
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      enum: [
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9',
        '10',
        '11',
        '12',
        '13',
        '14',
        '16',
        '17',
        '18',
        '19',
        '20',
        '30',
        '31',
        '32',
        '33',
        '34',
        '35',
        '36',
        '37',
        '38',
        '39',
        '41',
        '46',
        '47',
      ],
      type: 'integer',
    },
    ValidateAssetTypeIDTypeCode: {
      description: 'Financial instrument or payment mechanism',
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      enum: ['5', '6'],
      type: 'integer',
    },
    ValidateAssetAttributeTypeIDTypeCode: {
      description: 'Market Where Traded Code',
      maximum: 9223372036854776000,
      minimum: -9223372036854776000,
      enum: ['1', '2', '3', '4'],
      type: 'integer',
    },
    ValidateCyberEventIndicatorsTypeCode: {
      description: 'Other',
      enum: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '999'],
      type: 'string',
    },
    ValidateActivityNarrativeSequenceNumber: {
      description:
        'Fifth block of narrative text (character set 16001-17000, if needed)',
      maximum: 2147483647,
      minimum: -2147483648,
      enum: ['1', '2', '3', '4', '5'],
      type: 'integer',
    },
  },
}
