export const enumType = {
  SuspReason: [
    'Advanced fee/scam',
    'ATM/cheque fraud',
    'Avoiding reporting obligations (also known as structuring)',
    'Corporate/investment fraud',
    'Counterfeit currency',
    'Country/jurisdiction risk',
    'Credit card fraud',
    'Credit/loan facility fraud',
    'Currency not declared at border',
    'Department of Foreign Affairs (DFAT) watch list',
    'False name/identity or documents',
    'Immigration related issue',
    'Inconsistent with customer profile',
    'Internet fraud',
    'National security concern',
    'Other watch list',
    'Phishing',
    'Refusal to show identification',
    'Social security issue',
    'Suspected or known criminal',
    'Suspicious behaviour',
    'Unauthorised account transactions',
    'Unusual account activity',
    'Unusual financial instrument',
    'Unusual gambling activity',
    'Unusual use/exchange of cash',
    'Unusually large cash transaction',
    'Unusually large foreign exchange (FX) transaction',
    'Unusually large transfer',
    'Others',
  ],
  OffenceType: [
    'Financing of terrorism',
    'Money laundering',
    'Offence against a Commonwealth, State or Territory law',
    'Person/agent is not who they claim to be',
    'Proceeds of crime',
    'Tax evasion',
  ],
  TransactionType: [
    'Account opening',
    'Account deposit',
    'Account withdrawal',
    'Issue of stored value card',
    'Top up of stored value card',
    'Withdrawal from stored value card',
    'Issue of cheque',
    'Cash a cheque',
    'Issue of bank cheque',
    'Cash a bank cheque',
    'Issue of bank draft',
    'Cash a bank draft',
    'Issue of money/postal order',
    'Cash a money/postal order',
    'Domestic electronic funds transfer into account',
    'Domestic electronic funds transfer out of account',
    'International funds transfer out of Australia',
    'International funds transfer into Australia',
    'Exchange of Australian dollar (AUD) notes',
    'Exchange of digital currency',
    'Sale of digital currency',
    'Purchase of digital currency',
    'Exchange of foreign currency',
    'Sale of foreign currency',
    'Purchase of foreign currency',
    "Issue of traveller's cheques', 'Purchase of traveller's cheques",
    'Sale of bullion',
    'Purchase of bullion',
    'Loan application',
    'Loan repayment',
    'Loan drawdown',
    'Hire purchase/finance lease payment',
    'Issue of life insurance policy',
    'Accept contribution/premium',
    'Benefit payment/payout',
    'Rollover received from another fund',
    'Rollover to another fund',
    'Issue of chips/tokens',
    'Chips/tokens cash out',
    'Place bet',
    'Buy in to a game',
    'Win payout',
    'Electronic gaming machine payout',
    'Dispose securities',
    'Acquire securities',
    'Facilitate the transfer of securities (on behalf of others)',
    'Facilitate the transfer of securities (on own behalf)',
    'Dispose derivatives/futures',
    'Acquire derivatives/futures',
    'Facilitate the transfer of derivatives/futures (on behalf of others)',
    'Facilitate the transfer of derivatives/futures (on own behalf)',
    'Issue of negotiable debt instrument',
    'Cash a negotiable debt instrument',
    'Facilitate the transfer of negotiable debt instrument (on behalf of others)',
    'Facilitate the transfer of negotiable debt instrument (on own behalf)',
    'Others',
  ],
  DesignatedSvc: [
    'Account and deposit taking services',
    'Australian financial service licence (AFSL) holder arranging a designated service',
    'Betting accounts',
    'Bullion dealing services',
    'Loan services',
    'Retirement savings accounts (RSA)',
    'Chequebook access facilities',
    'Debit card access facilities',
    'Currency exchange services',
    'Custodial or depository services',
    'Digital currency exchange services',
    'Debt instruments',
    'Electronic funds transfers (EFT)',
    'Games of chance or skill',
    'Gambling and betting services',
    'Chips/currency exchange services',
    'Gaming machines',
    'Lease/hire purchase services',
    'Life insurance services',
    'Money/postal orders',
    'Payroll services',
    'Pensions and annuity services',
    'Remittance services (money transfers)',
    'Securities market/investment services',
    'Superannuation/approved deposit funds',
    'Travellers cheque exchange services',
    'Stored value cards',
  ],
  DeviceType: [
    'International Mobile Equipment Identity',
    'International Mobile Subscriber Identity',
    'Internet Protocol address',
    'Media Access Control address',
    'Secure element ID',
    'Others',
  ],
  SMRAccountType: [
    'Betting account',
    'Bullion account',
    'Cheque or savings account',
    'Credit card account',
    'Custodial account',
    'Foreign currency account',
    'Insurance policy',
    'Investment account',
    'Lease/hire purchase account',
    'Loan or mortgage account',
    'Remittance account',
    'Stored value card account',
    'Superannuation or approved deposit fund account',
    'Trading account',
    'Others',
  ],
  OtherTransactionType: [
    'Other monetary value received',
    'Other monetary value provided',
  ],
  IdType: [
    'Bank account',
    'Credit card/debit card',
    'Driver’s licence',
    'Passport',
    'Telephone/fax number',
    'Alien registration number',
    'Customer account/ID',
    'Benefits card/ID',
    'Birth certificate',
    'Business registration/licence',
    'Employee number',
    'Employer number',
    'Identity card/number',
    'Membership ID',
    'Photo ID',
    'Security ID',
    'Social media account/user name',
    'Social security ID',
    'Student',
    'Tax number/ID',
    'Others',
  ],
  IndOccType: [
    'Australian standard industry code ASIC',
    'Australian New Zealand Standard Industrial Classification ANZSIC',
    'Australian Standard Classification of Occupations ASCO version I',
    'ASCO version II',
    'Others',
  ],
  BusinessStructure: [
    'Association',
    'Company',
    'Government Body',
    'Partnership',
    'Registered Body',
    'Trust',
  ],
}
