/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConsumerName } from './consumerName'

/**
 * Model for credit or debit card details
 */
export class CardDetails {
  'method'?: string
  /**
   * Unique card fingerprint that helps identify a specific card without having to use explicit card number. This is likely available at your card payment scheme provider
   */
  'cardFingerprint': string
  /**
   * The country of issuance for a specific card
   */
  'cardIssuedCountry': string
  /**
   * Reference for the transaction
   */
  'transactionReferenceField'?: string
  /**
   * Whether 3ds was successfully enforced for the transaction
   */
  '_3dsDone'?: boolean
  'nameOnCard'?: ConsumerName

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'method',
      baseName: 'method',
      type: 'string',
    },
    {
      name: 'cardFingerprint',
      baseName: 'cardFingerprint',
      type: 'string',
    },
    {
      name: 'cardIssuedCountry',
      baseName: 'cardIssuedCountry',
      type: 'string',
    },
    {
      name: 'transactionReferenceField',
      baseName: 'transactionReferenceField',
      type: 'string',
    },
    {
      name: '_3dsDone',
      baseName: '3dsDone',
      type: 'boolean',
    },
    {
      name: 'nameOnCard',
      baseName: 'nameOnCard',
      type: 'ConsumerName',
    },
  ]

  static getAttributeTypeMap() {
    return CardDetails.attributeTypeMap
  }
}
