/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Tag } from './tag'

export class CompanyRegistrationDetails {
  /**
   * Commercial registry registration number for the company in its registration country
   */
  'registrationIdentifier': string
  /**
   * Country of registration for the company
   */
  'registrationCountry': string
  /**
   * Additional information that can be added via tags
   */
  'tag'?: Array<Tag>

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'registrationIdentifier',
      baseName: 'registrationIdentifier',
      type: 'string',
    },
    {
      name: 'registrationCountry',
      baseName: 'registrationCountry',
      type: 'string',
    },
    {
      name: 'tag',
      baseName: 'tag',
      type: 'Array<Tag>',
    },
  ]

  static getAttributeTypeMap() {
    return CompanyRegistrationDetails.attributeTypeMap
  }
}
