/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Model for device data
 */
export class DeviceData {
  /**
   * Battery level of the device used for a transaction or event at a given timestamp
   */
  'batteryLevel'?: number
  /**
   * Device latitude at a give timestamp for an event or transaction
   */
  'deviceLatitude'?: number
  /**
   * Device longitude at a give timestamp for an event or transaction
   */
  'deviceLongitude'?: number
  /**
   * IP address of the device at a given timestamp for an event or transaction
   */
  'ipAddress'?: string
  /**
   * Device identifier number
   */
  'deviceIdentifier'?: string
  /**
   * Whether VPN was used at a given timestamp for an event or transaction
   */
  'vpnUsed'?: boolean
  /**
   * Operating system of the device at a given timestamp for an event or transaction
   */
  'operatingSystem'?: string
  /**
   * The maker of the device at a given timestamp for an event or transaction
   */
  'deviceMaker'?: string
  /**
   * The model of the device at a given timestamp for an event or transaction
   */
  'deviceModel'?: string
  /**
   * The year the device was manufactured at a given timestamp for an event or transaction
   */
  'deviceYear'?: string
  /**
   * The version of the app your user is using on their device at a given timestamp for an event or transaction
   */
  'appVersion'?: string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'batteryLevel',
      baseName: 'batteryLevel',
      type: 'number',
      format: '',
    },
    {
      name: 'deviceLatitude',
      baseName: 'deviceLatitude',
      type: 'number',
      format: '',
    },
    {
      name: 'deviceLongitude',
      baseName: 'deviceLongitude',
      type: 'number',
      format: '',
    },
    {
      name: 'ipAddress',
      baseName: 'ipAddress',
      type: 'string',
      format: '',
    },
    {
      name: 'deviceIdentifier',
      baseName: 'deviceIdentifier',
      type: 'string',
      format: '',
    },
    {
      name: 'vpnUsed',
      baseName: 'vpnUsed',
      type: 'boolean',
      format: '',
    },
    {
      name: 'operatingSystem',
      baseName: 'operatingSystem',
      type: 'string',
      format: '',
    },
    {
      name: 'deviceMaker',
      baseName: 'deviceMaker',
      type: 'string',
      format: '',
    },
    {
      name: 'deviceModel',
      baseName: 'deviceModel',
      type: 'string',
      format: '',
    },
    {
      name: 'deviceYear',
      baseName: 'deviceYear',
      type: 'string',
      format: '',
    },
    {
      name: 'appVersion',
      baseName: 'appVersion',
      type: 'string',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return DeviceData.attributeTypeMap
  }

  public constructor() {}
}
