/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RuleFailureException } from './ruleFailureException'

export class FailedRulesResult {
  /**
   * Unique rule identifier
   */
  'ruleId': string
  /**
   * Name of the rule
   */
  'ruleName': string
  /**
   * Description of the rule
   */
  'ruleDescription': string
  'failureException': RuleFailureException

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'ruleId',
      baseName: 'ruleId',
      type: 'string',
    },
    {
      name: 'ruleName',
      baseName: 'ruleName',
      type: 'string',
    },
    {
      name: 'ruleDescription',
      baseName: 'ruleDescription',
      type: 'string',
    },
    {
      name: 'failureException',
      baseName: 'failureException',
      type: 'RuleFailureException',
    },
  ]

  static getAttributeTypeMap() {
    return FailedRulesResult.attributeTypeMap
  }
}
