/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from './Address'
import { GeneralBankAccountPaymentMethod } from './GeneralBankAccountPaymentMethod'
/**
 * Model for any generic bank account
 */
export class GenericBankAccountDetails {
  'method': GeneralBankAccountPaymentMethod
  /**
   * Bank account number
   */
  'accountNumber'?: string
  /**
   * Bank account type. E.g. Checking, Savings etc.
   */
  'accountType'?: string
  /**
   * Name of the bank
   */
  'bankName'?: string
  /**
   * Unique identifier of the bank. In some countries, this can be the same as the bank's SWIFT code
   */
  'bankCode'?: string
  /**
   * Name of the account holder
   */
  'name'?: string
  'bankAddress'?: Address
  /**
   * Special instructions to be specified if any
   */
  'specialInstructions'?: string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'method',
      baseName: 'method',
      type: 'GeneralBankAccountPaymentMethod',
      format: '',
    },
    {
      name: 'accountNumber',
      baseName: 'accountNumber',
      type: 'string',
      format: '',
    },
    {
      name: 'accountType',
      baseName: 'accountType',
      type: 'string',
      format: '',
    },
    {
      name: 'bankName',
      baseName: 'bankName',
      type: 'string',
      format: '',
    },
    {
      name: 'bankCode',
      baseName: 'bankCode',
      type: 'string',
      format: '',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
      format: '',
    },
    {
      name: 'bankAddress',
      baseName: 'bankAddress',
      type: 'Address',
      format: '',
    },
    {
      name: 'specialInstructions',
      baseName: 'specialInstructions',
      type: 'string',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return GenericBankAccountDetails.attributeTypeMap
  }

  public constructor() {}
}
