/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RuleAction } from './RuleAction'
/**
 * Model for list of executed rules
 */
export class HitRulesResult {
  /**
   * Unique rule identifier
   */
  'ruleId': string
  /**
   * Name of the rule
   */
  'ruleName': string
  /**
   * Description of the rule
   */
  'ruleDescription': string
  'ruleAction': RuleAction

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'ruleId',
      baseName: 'ruleId',
      type: 'string',
      format: '',
    },
    {
      name: 'ruleName',
      baseName: 'ruleName',
      type: 'string',
      format: '',
    },
    {
      name: 'ruleDescription',
      baseName: 'ruleDescription',
      type: 'string',
      format: '',
    },
    {
      name: 'ruleAction',
      baseName: 'ruleAction',
      type: 'RuleAction',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return HitRulesResult.attributeTypeMap
  }

  public constructor() {}
}
