/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Internal user- employees
 */
export class InternalUser {
  'employeeID': string
  'employeeLevel'?: string
  'employeeDesignation'?: string
  'employeeName'?: string
  'employeeNationality'?: string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'employeeID',
      baseName: 'employeeID',
      type: 'string',
      format: '',
    },
    {
      name: 'employeeLevel',
      baseName: 'employeeLevel',
      type: 'string',
      format: '',
    },
    {
      name: 'employeeDesignation',
      baseName: 'employeeDesignation',
      type: 'string',
      format: '',
    },
    {
      name: 'employeeName',
      baseName: 'employeeName',
      type: 'string',
      format: '',
    },
    {
      name: 'employeeNationality',
      baseName: 'employeeNationality',
      type: 'string',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return InternalUser.attributeTypeMap
  }

  public constructor() {}
}
