/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContactDetails } from './contactDetails'
import { LegalDocument } from './legalDocument'
import { Tag } from './tag'
import { UserDetails } from './userDetails'

/**
 * Model for a generic individual - different from User model by not having userId field
 */
export class Person {
  'generalDetails': UserDetails
  /**
   * User\'s legal identity documents - See Document Model for details
   */
  'legalDocuments'?: Array<LegalDocument>
  'contactDetails'?: ContactDetails
  /**
   * Additional information that can be added via tags
   */
  'tags'?: Array<Tag>

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'generalDetails',
      baseName: 'generalDetails',
      type: 'UserDetails',
    },
    {
      name: 'legalDocuments',
      baseName: 'legalDocuments',
      type: 'Array<LegalDocument>',
    },
    {
      name: 'contactDetails',
      baseName: 'contactDetails',
      type: 'ContactDetails',
    },
    {
      name: 'tags',
      baseName: 'tags',
      type: 'Array<Tag>',
    },
  ]

  static getAttributeTypeMap() {
    return Person.attributeTypeMap
  }
}
