/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Model for results from Risk Scoring
 */
export class RiskScoringResult {
  /**
   * Quantified KYC risk score
   */
  'kycRiskScore': number
  /**
   * Quantified action risk score
   */
  'actionRiskScore': number
  /**
   * Quantified dynamic risk score
   */
  'dynamicRiskScore'?: number

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'kycRiskScore',
      baseName: 'kycRiskScore',
      type: 'number',
      format: '',
    },
    {
      name: 'actionRiskScore',
      baseName: 'actionRiskScore',
      type: 'number',
      format: '',
    },
    {
      name: 'dynamicRiskScore',
      baseName: 'dynamicRiskScore',
      type: 'number',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return RiskScoringResult.attributeTypeMap
  }

  public constructor() {}
}
