/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class RuleFailureException {
  /**
   * Unique rule identifier
   */
  'exceptionName': string
  /**
   * Name of the rule
   */
  'exceptionDescription': string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'exceptionName',
      baseName: 'exceptionName',
      type: 'string',
      format: '',
    },
    {
      name: 'exceptionDescription',
      baseName: 'exceptionDescription',
      type: 'string',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return RuleFailureException.attributeTypeMap
  }

  public constructor() {}
}
