/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Generic key-value pair model to append a custom variable being sent to Flagright API
 */
export class Tag {
  /**
   * Key value when you are creating a custom variable
   */
  'key': string
  /**
   * Value for a given key when you are creating a custom variable
   */
  'value': string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'key',
      baseName: 'key',
      type: 'string',
      format: '',
    },
    {
      name: 'value',
      baseName: 'value',
      type: 'string',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return Tag.attributeTypeMap
  }

  public constructor() {}
}
