/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Model to convey the results of transaction monitoring
 */
export class TransactionMonitoringResultAllOf {
  /**
   * Transaction ID that the results pertain to
   */
  'transactionId': string

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'transactionId',
      baseName: 'transactionId',
      type: 'string',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return TransactionMonitoringResultAllOf.attributeTypeMap
  }

  public constructor() {}
}
