/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Transaction } from './Transaction'
/**
 * Model to convey the results of transaction monitoring
 */
export class TransactionEventMonitoringResultAllOf {
  'eventId': string
  'transaction': Transaction

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'eventId',
      baseName: 'eventId',
      type: 'string',
      format: '',
    },
    {
      name: 'transaction',
      baseName: 'transaction',
      type: 'Transaction',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return TransactionEventMonitoringResultAllOf.attributeTypeMap
  }

  public constructor() {}
}
