/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Amount } from './amount'

export class TransactionLimits {
  'maximumDailyTransactionLimit'?: Amount
  'maximumWeeklyTransactionLimit'?: Amount
  'maximumMonthlyTransactionLimit'?: Amount
  'maximumQuarterlyTransactionLimit'?: Amount
  'maximumYearlyTransactionLimit'?: Amount

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'maximumDailyTransactionLimit',
      baseName: 'maximumDailyTransactionLimit',
      type: 'Amount',
    },
    {
      name: 'maximumWeeklyTransactionLimit',
      baseName: 'maximumWeeklyTransactionLimit',
      type: 'Amount',
    },
    {
      name: 'maximumMonthlyTransactionLimit',
      baseName: 'maximumMonthlyTransactionLimit',
      type: 'Amount',
    },
    {
      name: 'maximumQuarterlyTransactionLimit',
      baseName: 'maximumQuarterlyTransactionLimit',
      type: 'Amount',
    },
    {
      name: 'maximumYearlyTransactionLimit',
      baseName: 'maximumYearlyTransactionLimit',
      type: 'Amount',
    },
  ]

  static getAttributeTypeMap() {
    return TransactionLimits.attributeTypeMap
  }
}
