/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExecutedRulesResult } from './ExecutedRulesResult'
import { FailedRulesResult } from './FailedRulesResult'
export class TransactionMonitoringResult {
  /**
   * Unique transaction identifier
   */
  'transactionId': string
  /**
   * Unique transaction identifier
   */
  'executedRules'?: Array<ExecutedRulesResult>
  /**
   * Unique transaction identifier
   */
  'failedRules'?: Array<FailedRulesResult>

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'transactionId',
      baseName: 'transactionId',
      type: 'string',
      format: '',
    },
    {
      name: 'executedRules',
      baseName: 'executedRules',
      type: 'Array<ExecutedRulesResult>',
      format: '',
    },
    {
      name: 'failedRules',
      baseName: 'failedRules',
      type: 'Array<FailedRulesResult>',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return TransactionMonitoringResult.attributeTypeMap
  }

  public constructor() {}
}
