/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DeviceData } from './DeviceData'
import { Transaction } from './Transaction'
import { TransactionState } from './TransactionState'
export class TransactionEvent {
  'transactionState': TransactionState
  'timestamp': number
  'transactionId': string
  'eventId'?: string
  'eventDescription'?: string
  'employeeId'?: string
  'metaData'?: DeviceData
  'updatedTransactionAttributes'?: Transaction

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'transactionState',
      baseName: 'transactionState',
      type: 'TransactionState',
      format: '',
    },
    {
      name: 'timestamp',
      baseName: 'timestamp',
      type: 'number',
      format: '',
    },
    {
      name: 'transactionId',
      baseName: 'transactionId',
      type: 'string',
      format: '',
    },
    {
      name: 'eventId',
      baseName: 'eventId',
      type: 'string',
      format: '',
    },
    {
      name: 'eventDescription',
      baseName: 'eventDescription',
      type: 'string',
      format: '',
    },
    {
      name: 'employeeId',
      baseName: 'employeeId',
      type: 'string',
      format: '',
    },
    {
      name: 'metaData',
      baseName: 'metaData',
      type: 'DeviceData',
      format: '',
    },
    {
      name: 'updatedTransactionAttributes',
      baseName: 'updatedTransactionAttributes',
      type: 'Transaction',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return TransactionEvent.attributeTypeMap
  }

  public constructor() {}
}
