/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DeviceData } from './DeviceData'
/**
 * Model for user-related events
 */
export class UserEvent {
  /**
   * Type of events. E.g. Onboarding, Checkout etc.
   */
  'type': UserEventTypeEnum
  /**
   * Timestamp of the event
   */
  'timestamp': number
  /**
   * User ID the event pertains to
   */
  'userId': string
  /**
   * Unique event ID
   */
  'eventId'?: string
  /**
   * Event description
   */
  'eventDescription'?: string
  'metaData'?: DeviceData

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'type',
      baseName: 'type',
      type: 'UserEventTypeEnum',
      format: '',
    },
    {
      name: 'timestamp',
      baseName: 'timestamp',
      type: 'number',
      format: '',
    },
    {
      name: 'userId',
      baseName: 'userId',
      type: 'string',
      format: '',
    },
    {
      name: 'eventId',
      baseName: 'eventId',
      type: 'string',
      format: '',
    },
    {
      name: 'eventDescription',
      baseName: 'eventDescription',
      type: 'string',
      format: '',
    },
    {
      name: 'metaData',
      baseName: 'metaData',
      type: 'DeviceData',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return UserEvent.attributeTypeMap
  }

  public constructor() {}
}

export type UserEventTypeEnum = 'LOGGED_IN'
