/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DeviceData } from './DeviceData'
import { ExecutedRulesResult } from './ExecutedRulesResult'
import { FailedRulesResult } from './FailedRulesResult'
import { RuleAction } from './RuleAction'
import { UserEvent } from './UserEvent'
import { UserEventWithRulesResultAllOf } from './UserEventWithRulesResultAllOf'
/**
 * Model for user event payload with rules result
 */
export class UserEventWithRulesResult {
  'type': UserEventWithRulesResultTypeEnum
  'timestamp': number
  'userId': string
  'eventId'?: string
  'eventDescription'?: string
  'metaData'?: DeviceData
  'status'?: RuleAction
  'executedRules': Array<ExecutedRulesResult>
  'failedRules': Array<FailedRulesResult>

  static readonly discriminator: string | undefined = undefined

  static readonly attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
    format: string
  }> = [
    {
      name: 'type',
      baseName: 'type',
      type: 'UserEventWithRulesResultTypeEnum',
      format: '',
    },
    {
      name: 'timestamp',
      baseName: 'timestamp',
      type: 'number',
      format: '',
    },
    {
      name: 'userId',
      baseName: 'userId',
      type: 'string',
      format: '',
    },
    {
      name: 'eventId',
      baseName: 'eventId',
      type: 'string',
      format: '',
    },
    {
      name: 'eventDescription',
      baseName: 'eventDescription',
      type: 'string',
      format: '',
    },
    {
      name: 'metaData',
      baseName: 'metaData',
      type: 'DeviceData',
      format: '',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'RuleAction',
      format: '',
    },
    {
      name: 'executedRules',
      baseName: 'executedRules',
      type: 'Array<ExecutedRulesResult>',
      format: '',
    },
    {
      name: 'failedRules',
      baseName: 'failedRules',
      type: 'Array<FailedRulesResult>',
      format: '',
    },
  ]

  static getAttributeTypeMap() {
    return UserEventWithRulesResult.attributeTypeMap
  }

  public constructor() {}
}

export type UserEventWithRulesResultTypeEnum = 'LOGGED_IN'
