/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ConsumerName } from './consumerName'

export class UserDetails {
  'name': ConsumerName
  /**
   * Date of birth of the user
   */
  'dateOfBirth'?: number
  /**
   * Age of the user
   */
  'age'?: number
  /**
   * Country of residence of the user
   */
  'countryOfResidence'?: string
  /**
   * Country of nationality of the user
   */
  'countryOfNationality'?: string

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'name',
      baseName: 'name',
      type: 'ConsumerName',
    },
    {
      name: 'dateOfBirth',
      baseName: 'dateOfBirth',
      type: 'number',
    },
    {
      name: 'age',
      baseName: 'age',
      type: 'number',
    },
    {
      name: 'countryOfResidence',
      baseName: 'countryOfResidence',
      type: 'string',
    },
    {
      name: 'countryOfNationality',
      baseName: 'countryOfNationality',
      type: 'string',
    },
  ]

  static getAttributeTypeMap() {
    return UserDetails.attributeTypeMap
  }
}
