export const ActivitySectorCode = {
  type: 'string',
  enum: [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '9',
    '10',
    '11',
    '12',
    '13',
    '14',
    '15',
    '16',
    '17',
    '18',
    '19',
    '20',
    '21',
    '22',
    '23',
    '24',
    '25',
  ],
  enumNames: [
    'Accountant',
    'Bank',
    'Caisse populaire',
    'Crown agent',
    'Casino',
    'Co-op credit society',
    'Life insurance broker or agent',
    'Life insurance company',
    'Money services business',
    'Provincial savings office',
    'Real estate',
    'Credit union',
    'Securities dealer',
    'Trust and/or loan company',
    'British Columbia notary',
    'Dealer in precious metals and stones',
    'Credit union central',
    'Financial services cooperative',
    'Foreign money services business',
    'Mortgage administrators',
    'Armoured Cars',
    'Mortgage brokers',
    'Mortgage lenders',
  ],
}

export const MinisterialDirectiveCode = {
  type: 'string',
  enum: ['IR2020'],
  enumNames: ['IR2020'],
}

export const SuspicionTypeCode = {
  type: 'string',
  enum: ['1', '2', '3', '4', '5', '6', '7'],
  enumNames: [
    'Money laundering',
    'Terrorist financing',
    'Money laundering and terrorist financing',
    'Sanctions evasion',
    'Money laundering and sanctions evasion',
    'Terrorist financing and sanctions evasion',
    'Money laundering, terrorist financing, and sanctions evasion',
  ],
}

export const IdentifierTypeCode = {
  type: 'string',
  enum: [
    '1',
    '2',
    '3',
    '4',
    '5',
    '14',
    '15',
    '27',
    '32',
    '33',
    '34',
    '35',
    '36',
    '37',
    '38',
    '39',
    '40',
  ],
  enumNames: [
    'Birth certificate',
    'Passport',
    'Other',
    "Driver's licence",
    'Provincial health card',
    'Citizenship card',
    'Certificate of Indian Status',
    'Social Insurance Number card',
    'Permanent resident card',
    'Record of landing',
    'Credit file',
    'Government issued identification',
    'Insurance documents',
    'Provincial or territorial identity card',
    'Record of employment',
    'Travel visa',
    'Utility statement',
  ],
}

export const PublicPrivatePartnershipProjectNameCode = {
  type: 'string',
  enum: ['1', '2', '3', '5', '6', '7', '8'],
  enumNames: [
    'Project ANTON',
    'Project ATHENA',
    'Project CHAMELEON',
    'Project GUARDIAN',
    'Project LEGION',
    'Project PROTECT',
    'Project SHADOW',
  ],
}

export const AddressTypeCode = {
  type: 'string',
  enum: ['1', '2'],
  enumNames: ['Structured address', 'Unstructured address'],
}

export const IncorporationRegistrationTypeCode = {
  type: 'string',
  enum: ['1', '2', '4', '5'],
  enumNames: [
    'Registered',
    'Incorporated',
    'Registered and incorporated',
    'Unknown',
  ],
}

export const StructureTypeCode = {
  type: 'string',
  enum: ['1', '2', '3', '4'],
  enumNames: [
    'Corporation',
    'Entity other than a corporation or trust',
    'Trust',
    'Widely held or publicly traded trust',
  ],
}

export const MethodCode = {
  type: 'string',
  enum: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'],
  enumNames: [
    'In person',
    'Automated banking machine',
    'Armoured car',
    'Courier',
    'Mail deposit',
    'Telephone',
    'Other',
    'Night deposit',
    'Quick drop',
    'Self-redemption kiosk',
    'Virtual currency ATM',
    'Online',
  ],
}

export const DefinitionType12 = {
  type: 'string',
  enum: ['1', '2'],
  enumNames: ['Person name', 'Entity name'],
}

export const DefinitionType34 = {
  type: 'string',
  enum: ['5', '6'],
  enumNames: ['Person details', 'Entity details'],
}

export const DefinitionType56 = {
  type: 'string',
  enum: ['5', '6'],
  enumNames: [
    'Person and employer Details',
    'Entity and beneficial ownership details',
  ],
}

export const AccountType = {
  type: 'string',
  enum: ['1', '2', '3', '4', '5'],
  enumNames: ['Personal', 'Business', 'Trust', 'Other', 'Casino'],
}

export const TransactionDirection = {
  type: 'string',
  enum: ['1', '2'],
  enumNames: ['In', 'Out'],
}

export const DeviceType = {
  type: 'string',
  enum: ['1', '2', '3', '4'],
  enumNames: ['Computer/Laptop', 'Mobile phone', 'Tablet', 'Other'],
}

export const RelationshipOfConductorCode = {
  type: 'string',
  enum: [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '11',
    '12',
    '13',
    '14',
  ],
  enumNames: [
    'Accountant',
    'Agent',
    'Borrower',
    'Broker',
    'Customer',
    'Employee',
    'Friend',
    'Relative',
    'Other',
    'Legal counsel',
    'Employer',
    'Joint/Secondary owner',
    'Power of attorney',
    'Vendor/Supplier',
  ],
}

export const DispositionCode = {
  type: 'string',
  enum: [
    '1',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '11',
    '14',
    '15',
    '17',
    '18',
    '19',
    '20',
    '21',
    '22',
    '23',
    '24',
    '25',
    '26',
    '27',
    '28',
    '29',
    '30',
    '31',
    '32',
  ],
  enumNames: [
    'Deposit to account',
    'Exchange to fiat currency',
    'Purchase of casino product',
    'Purchase of bank draft',
    'Purchase of money order',
    'Life insurance policy purchase/deposit',
    'Investment product purchase/deposit',
    'Real estate purchase/deposit',
    'Cash out',
    'Other',
    'Purchase of jewellery',
    'Purchase precious metals',
    'Added to virtual currency wallet',
    'Exchange to virtual currency',
    'Outgoing virtual currency transfer',
    'Outgoing email money transfer',
    'Holding funds',
    'Purchase of precious stones',
    'Issued cheque',
    'Outgoing domestic funds transfer',
    'Outgoing international funds transfer',
    'Purchase of prepaid payment product/card',
    'Denomination exchange',
    'Payment to account',
    'Purchase of / Payment for goods',
    'Purchase of / Payment for services',
    'Outgoing mobile money transfer',
    'Cash withdrawal (account based)',
  ],
}

export const AccountStatusAtTimeOfTransaction = {
  type: 'string',
  enum: ['1', '2', '3', '4'],
  enumNames: ['Active', 'Inactive', 'Dormant', 'Closed'],
}

export const CurrencyCode = {
  type: 'string',
  enum: [
    '1INCH',
    'AAVE',
    'ABBC',
    'ADA',
    'ADX',
    'AE',
    'AERGO',
    'AGI',
    'AGVC',
    'AIB',
    'AION',
    'AKRO',
    'ALGO',
    'AMO',
    'AMP',
    'AMPL',
    'ANC',
    'ANCT',
    'ANKR',
    'ANT',
    'AOA',
    'APL',
    'APM',
    'AR',
    'ARDR',
    'ARK',
    'ARPA',
    'ARRR',
    'AST',
    'ATOM',
    'ATT',
    'AUDIO',
    'AVA',
    'AVAX',
    'AXC',
    'AXEL',
    'AXS',
    'B2B',
    'BAL',
    'BAND',
    'BASIC',
    'BASID',
    'BAT',
    'BCD',
    'BCH',
    'BCN',
    'BCZERO',
    'BDCC',
    'BDX',
    'BEAM',
    'BEL',
    'BHAO',
    'BHD',
    'BHP',
    'BHT',
    'BICO',
    'BIGONE',
    'BIKI',
    'BLCT',
    'BLOCK',
    'BLZ',
    'BNANA',
    'BNB',
    'BNK',
    'BNT',
    'BOA',
    'BONO',
    'BORA',
    'BOT',
    'BOTX',
    'BPS',
    'BRC',
    'BRG',
    'BRZE',
    'BSV',
    'BTC',
    'BTC2',
    'BTCB',
    'BTG',
    'BTM',
    'BTMX',
    'BTRS',
    'BTS',
    'BTT',
    'BTU',
    'BUSD',
    'BWF',
    'BXK',
    'BZ',
    'BZRX',
    'C20',
    'CADC',
    'CAKE',
    'CCA',
    'CCXX',
    'CEL',
    'CELO',
    'CELR',
    'CENNZ',
    'CHR',
    'CHSB',
    'CHZ',
    'CIPHC',
    'CIX100',
    'CKB',
    'CND',
    'CNX',
    'COCOS',
    'COMP',
    'CON',
    'CORE',
    'COS',
    'COTI',
    'CRE',
    'CRO',
    'CRPT',
    'CRV',
    'CTC',
    'CTCN',
    'CTK',
    'CTSI',
    'CTXC',
    'CUSD',
    'CVA',
    'CVC',
    'CVNT',
    'CVT',
    'CVX',
    'DAC',
    'DAD',
    'DAG',
    'DAI',
    'DASH',
    'DATA',
    'DCR',
    'DCY',
    'DEC',
    'DENT',
    'DFI',
    'DGB',
    'DGD',
    'DGTX',
    'DIA',
    'DIP',
    'DIVI',
    'DMCH',
    'DMG',
    'DNA',
    'DNT',
    'DOGE',
    'DOT',
    'DREP',
    'DRGN',
    'DRS',
    'DTR',
    'DUSK',
    'DX',
    'ECOREAL',
    'EDC',
    'EGLD',
    'ELA',
    'ELF',
    'ELON',
    'EMC2',
    'ENG',
    'ENJ',
    'ENS',
    'EOS',
    'ERC20',
    'ERG',
    'ETC',
    'ETH',
    'ETN',
    'EUM',
    'EURS',
    'EVN',
    'EVR',
    'EWT',
    'FAB',
    'FARM',
    'FET',
    'FIL',
    'FLG',
    'FLM',
    'FLOW',
    'FNB',
    'FSN',
    'FST',
    'FTM',
    'FTT',
    'FUN',
    'FX',
    'FXC',
    'GALA',
    'GARD',
    'GAS',
    'GBYTE',
    'GLEEC',
    'GNO',
    'GNT',
    'GRIN',
    'GRN',
    'GRS',
    'GRT',
    'GT',
    'GUSD',
    'GXC',
    'HBAR',
    'HBTC',
    'HC',
    'HEDG',
    'HEX',
    'HIVE',
    'HMR',
    'HNC',
    'HNS',
    'HNT',
    'HOD',
    'HOT',
    'HPT',
    'HSN',
    'HT',
    'HUSD',
    'HXRO',
    'HYN',
    'ICH',
    'ICP',
    'ICX',
    'IDEX',
    'IGNIS',
    'IHF',
    'ILV',
    'IMX',
    'INB',
    'INJ',
    'INO',
    'INSTAR',
    'IOST',
    'IOTX',
    'IPX',
    'IQ',
    'IRIS',
    'IZE',
    'JST',
    'JUL',
    'JWL',
    'KAI',
    'KAN',
    'KAVA',
    'KBC',
    'KCASH',
    'KCS',
    'KDA',
    'KDAG',
    'KEEP',
    'KIN',
    'KLAY',
    'KMD',
    'KNC',
    'KP3R',
    'KRT',
    'KSM',
    'LA',
    'LAMB',
    'LBC',
    'LCX',
    'LEO',
    'LEVL',
    'LINK',
    'LOKI',
    'LOOM',
    'LPT',
    'LRC',
    'LRG',
    'LSK',
    'LTC',
    'LTO',
    'LUNA',
    'LVX',
    'MAID',
    'MANA',
    'MASS',
    'MATH',
    'MATIC',
    'MBL',
    'MBN',
    'MCO',
    'MDA',
    'MED',
    'MFT',
    'MIN',
    'MIOTA',
    'MKR',
    'MLK',
    'MLN',
    'MOF',
    'MONA',
    'MRPH',
    'MTA',
    'MTC',
    'MTL',
    'MTXLT',
    'MUSD',
    'MVL',
    'MWC',
    'MX',
    'MXC',
    'NANO',
    'NAS',
    'NEAR',
    'NEC',
    'NEO',
    'NEST',
    'NEX',
    'NEXO',
    'NEXXO',
    'NIM',
    'NKN',
    'NMR',
    'NOIA',
    'NPXS',
    'NRG',
    'NU',
    'NULS',
    'NUT',
    'NVT',
    'NWC',
    'NXM',
    'NXS',
    'NYE',
    'OCEAN',
    'OCTO',
    'OGN',
    'OKB',
    'OMG',
    'ONE',
    'ONOT',
    'ONT',
    'ORBS',
    'ORC',
    'ORN',
    'OTH',
    'OXT',
    'PAI',
    'PAX',
    'PAXG',
    'PCN',
    'PCX',
    'PERL',
    'PERP',
    'PHA',
    'PIVX',
    'PLC',
    'PLF',
    'PNK',
    'POLS',
    'POLY',
    'POWR',
    'PPT',
    'PROM',
    'PRQ',
    'PZM',
    'QASH',
    'QC',
    'QKC',
    'QNT',
    'QQQ',
    'QRK',
    'QRL',
    'QSP',
    'QTUM',
    'RCHAINREV',
    'RCN',
    'RDD',
    'RDN',
    'REN',
    'RENBTC',
    'REP',
    'REPO',
    'REQ',
    'REV',
    'RIF',
    'RING',
    'RKN',
    'RLC',
    'RNDR',
    'ROSE',
    'RPL',
    'RSR',
    'RUNE',
    'RVN',
    'S4F',
    'SAFE',
    'SAND',
    'SAPP',
    'SC',
    'SCC',
    'SCRT',
    'SEELE',
    'SERO',
    'SFP',
    'SHIB',
    'SHPING',
    'SHR',
    'SLS',
    'SNB',
    'SNL',
    'SNT',
    'SNTVT',
    'SNX',
    'SOL',
    'SOLO',
    'SOLVE',
    'SPND',
    'SRM',
    'STAKE',
    'STEEM',
    'STMX',
    'STORJ',
    'STP',
    'STPT',
    'STRAT',
    'STRONG',
    'STX',
    'SUKU',
    'SUN',
    'SUSD',
    'SUSHI',
    'SWAP',
    'SWINGBY',
    'SWTH',
    'SXP',
    'SYS',
    'TCAD',
    'TEL',
    'TFUEL',
    'THETA',
    'THR',
    'THX',
    'TITAN',
    'TMTG',
    'TNC',
    'TOMO',
    'TONIC',
    'TRAC',
    'TRAT',
    'TRB',
    'TROY',
    'TRUE',
    'TRX',
    'TSHP',
    'TT',
    'TTT',
    'TUSD',
    'TWT',
    'UBT',
    'ULT',
    'UMA',
    'UNI',
    'UNICOIN',
    'UNO',
    'UOS',
    'UQC',
    'USDC',
    'USDJ',
    'USDK',
    'USDN',
    'USDP',
    'USDT',
    'UST',
    'UTK',
    'VEST',
    'VET',
    'VGX',
    'VIDT',
    'VITAE',
    'VLX',
    'VRSC',
    'VSYS',
    'VTHO',
    'VVS',
    'WAN',
    'WAVES',
    'WAXP',
    'WBNB',
    'WBTC',
    'WET',
    'WICC',
    'WIN',
    'WIX',
    'WOM',
    'WRX',
    'WTC',
    'WXT',
    'XCM',
    'XDC',
    'XEC',
    'XEM',
    'XHV',
    'XIN',
    'XLM',
    'XLT',
    'XMR',
    'XNC',
    'XOR',
    'XPR',
    'XRP',
    'XSN',
    'XSR',
    'XT',
    'XTP',
    'XTZ',
    'XVG',
    'XVS',
    'XWC',
    'XYM',
    'XYO',
    'XZC',
    'YEP',
    'YF-DAI',
    'YFI',
    'YFII',
    'YFL',
    'YGG',
    'YUSRA',
    'ZAP',
    'ZB',
    'ZCN',
    'ZEC',
    'ZEN',
    'ZIL',
    'ZLW',
    'ZNN',
    'ZRX',
    'ZT',
    'ZYN',
  ],
  enumNames: [
    'Canadian Dollar',
    'United States Dollar',
    'Andorran Peseta',
    'United Arab Emirates Dirham',
    'Afghani',
    'Lek',
    'Armenian Dram',
    'Netherlands Antillian Guilder',
    'Kwanza',
    'New Kwanza',
    'Argentine Peso',
    'Schilling',
    'Australian Dollar',
    'Aruba Florin',
    'Aruban Guilder',
    'Azerbaijanian Manat',
    'Azerbaijan Manat',
    'Convertible Mark',
    'Barbados Dollar',
    'Taka',
    'Belgian Franc',
    'Belgian Franc (convertible)',
    'Belgian Franc (financial)',
    'Lev',
    'Bulgarian Lev',
    'Bahraini Dinar',
    'Burundi Franc',
    'Bermudian Dollar',
    'Brunei Dollar',
    'Boliviano',
    'Bolivian Peso',
    'Mvdol',
    'Cruzeiro',
    'Brazilian Real',
    'Bahamian Dollar',
    'Ngultrum',
    'Bhutan Rupee',
    'Kyat',
    'Pula',
    'Belarusian Ruble',
    'Belize Dollar',
    'Congolese Franc',
    'New Zaire',
    'WIR Euro',
    'Swiss Franc',
    'WIR Franc',
    'Unidades de Formento',
    'Chilean Peso',
    'Yuan Renminbi',
    'Colombian Peso',
    'Unidad de Valor Real',
    'Costa Rican Colon',
    'Serbian Dinar',
    'Koruna',
    'Peso Convertible',
    'Cuban Peso',
    'Cape Verde Escudo',
    'Cyprus Pound',
    'Czech Koruna',
    'Mark der DDR',
    'Deutsche Mark',
    'Djibouti Franc',
    'Danish Krone',
    'Dominican Peso',
    'Algerian Dinar',
    'Sucre',
    'Kroon',
    'Egyptian Pound',
    'Nakfa',
    'Spanish Peseta',
    'Ethiopian Birr',
    'Euro',
    'Markka',
    'Fiji Dollar',
    'Falkland Islands Pound',
    'French Franc',
    'Pound Sterling',
    'Lari',
    'Cedi',
    'Gibraltar Pound',
    'Dalasi',
    'Guinean Franc',
    'Syli',
    'Ekwele',
    'Drachma',
    'Quetzal',
    'Guinea-Bissau Peso',
    'Guyana Dollar',
    'Hong Kong Dollar',
    'Lempira',
    'Croatian Kuna',
    'Gourde',
    'Forint',
    'Rupiah',
    'Irish Pound',
    'New Israeli Shekel',
    'Indian Rupee',
    'Iraqi Dinar',
    'Iranian Rial',
    'Iceland Krona',
    'Lira',
    'Jamaican Dollar',
    'Jordanian Dinar',
    'Yen',
    'Kenyan Shilling',
    'Som',
    'Riel',
    'Comorian Franc',
    'North Korean Won',
    'Won',
    'Kuwaiti Dinar',
    'Cayman Islands Dollar',
    'Tenge',
    'Lao Kip',
    'Lebanese Pound',
    'Sri Lankan Rupee',
    'Liberian Dollar',
    'Loti',
    'Maloti',
    'Lithuanian Litas',
    'Luxembourg Franc',
    'Latvian Lat',
    'Libyan Dinar',
    'Moroccan Dirham',
    'Moldovan Leu',
    'Malagasy Ariary',
    'Malagasy Franc',
    'Denar',
    'Mali Franc',
    'Tugrik',
    'Pataca',
    'Ouguiya',
    'Maltese Lira',
    'Maltese Pound',
    'Mauritian Rupee',
    'Rufiyaa',
    'Malawi Kwacha',
    'Mexican Peso',
    'Mexican Unidad de Inversion',
    'Malaysian Ringgit',
    'Metical',
    'Namibian Dollar',
    'Naira',
    'Cordoba',
    'Cordoba Oro',
    'Netherlands Guilder',
    'Norwegian Krone',
    'Nepalese Rupee',
    'New Zealand Dollar',
    'Omani Rial',
    'Balboa',
    'Sol',
    'Kina',
    'Philippine Peso',
    'Pakistan Rupee',
    'Zloty',
    'Portugese Escudo',
    'Guarani',
    'Qatari Rial',
    'Old Leu',
    'New Leu',
    'Russian Ruble',
    'Rwandan Franc',
    'Saudi Riyal',
    'Solomon Islands Dollar',
    'Luigino',
    'Seychelles Rupee',
    'Sudanese Dinar',
    'Sudanese Pound',
    'Swedish Krona',
    'Singapore Dollar',
    'Saint Helena Pound',
    'Tolar',
    'Slovak Koruna',
    'Leone',
    'Somalian Shilling',
    'Surinam Dollar',
    'Suriname Guilder',
    'South Sudanese Pound',
    'Dobra',
    'El Salvador Colon',
    'Syrian Pound',
    'Lilangeni',
    'Baht',
    'Tajik Ruble',
    'Somoni',
    'Manat',
    'Tunisian Dinar',
    "Pa'anga",
    'Timor Escudo',
    'Old Turkish Lira',
    'New Turkish Lira',
    'Trinidad and Tobago Dollar',
    'New Taiwan Dollar',
    'Tanzanian Shilling',
    'Hryvnia',
    'Uganda Shilling',
    'United States Dollar, next day',
    'US Dollar (same day)',
    'Uruguay Peso en Unidades Indexadas',
    'Uruguayan Peso',
    'Unidad Previsional',
    'Som (Uzbekistan)',
    'Bolivar',
    'Bolívar',
    'Bolívar Soberano',
    'Dong',
    'Vatu',
    'Tala',
    'CFA Franc BEAC',
    'Silver',
    'Gold',
    'European Composite Unit',
    'European Monetary Unit',
    'European Unit of Account 9',
    'European Unit of Account 17',
    'Bitcoin',
    'East Caribbean Dollar',
    'Special Drawing Rights',
    'European Currency Unit',
    'Gold-Franc',
    'UIC-Franc',
    'CFA Franc BCEAO',
    'Palladium',
    'CFP Franc',
    'Platinum',
    'SUCRE',
    'No currency code',
    'Yemeni Dinar',
    'Yemeni Rial',
    'Yugoslavian Dinar',
    'New Dinar',
    'Yugoslav New Dinar',
    'Rand',
    'Kwacha',
    'Zimbabwe Dollar',
    'Unknown',
  ],
}

export const VirtualCurrencyCode = {
  type: 'string',
  enum: [
    '1INCH',
    'AAVE',
    'ABBC',
    'ADA',
    'ADX',
    'AE',
    'AERGO',
    'AGI',
    'AGVC',
    'AIB',
    'AION',
    'AKRO',
    'ALGO',
    'AMO',
    'AMP',
    'AMPL',
    'ANC',
    'ANCT',
    'ANKR',
    'ANT',
    'AOA',
    'APL',
    'APM',
    'AR',
    'ARDR',
    'ARK',
    'ARPA',
    'ARRR',
    'AST',
    'ATOM',
    'ATT',
    'AUDIO',
    'AVA',
    'AVAX',
    'AXC',
    'AXEL',
    'AXS',
    'B2B',
    'BAL',
    'BAND',
    'BASIC',
    'BASID',
    'BAT',
    'BCD',
    'BCH',
    'BCN',
    'BCZERO',
    'BDCC',
    'BDX',
    'BEAM',
    'BEL',
    'BHAO',
    'BHD',
    'BHP',
    'BHT',
    'BICO',
    'BIGONE',
    'BIKI',
    'BLCT',
    'BLOCK',
    'BLZ',
    'BNANA',
    'BNB',
    'BNK',
    'BNT',
    'BOA',
    'BONO',
    'BORA',
    'BOT',
    'BOTX',
    'BPS',
    'BRC',
    'BRG',
    'BRZE',
    'BSV',
    'BTC',
    'BTC2',
    'BTCB',
    'BTG',
    'BTM',
    'BTMX',
    'BTRS',
    'BTS',
    'BTT',
    'BTU',
    'BUSD',
    'BWF',
    'BXK',
    'BZ',
    'BZRX',
    'C20',
    'CADC',
    'CAKE',
    'CCA',
    'CCXX',
    'CEL',
    'CELO',
    'CELR',
    'CENNZ',
    'CHR',
    'CHSB',
    'CHZ',
    'CIPHC',
    'CIX100',
    'CKB',
    'CND',
    'CNX',
    'COCOS',
    'COMP',
    'CON',
    'CORE',
    'COS',
    'COTI',
    'CRE',
    'CRO',
    'CRPT',
    'CRV',
    'CTC',
    'CTCN',
    'CTK',
    'CTSI',
    'CTXC',
    'CUSD',
    'CVA',
    'CVC',
    'CVNT',
    'CVT',
    'CVX',
    'DAC',
    'DAD',
    'DAG',
    'DAI',
    'DASH',
    'DATA',
    'DCR',
    'DCY',
    'DEC',
    'DENT',
    'DFI',
    'DGB',
    'DGD',
    'DGTX',
    'DIA',
    'DIP',
    'DIVI',
    'DMCH',
    'DMG',
    'DNA',
    'DNT',
    'DOGE',
    'DOT',
    'DREP',
    'DRGN',
    'DRS',
    'DTR',
    'DUSK',
    'DX',
    'ECOREAL',
    'EDC',
    'EGLD',
    'ELA',
    'ELF',
    'ELON',
    'EMC2',
    'ENG',
    'ENJ',
    'ENS',
    'EOS',
    'ERC20',
    'ERG',
    'ETC',
    'ETH',
    'ETN',
    'EUM',
    'EURS',
    'EVN',
    'EVR',
    'EWT',
    'FAB',
    'FARM',
    'FET',
    'FIL',
    'FLG',
    'FLM',
    'FLOW',
    'FNB',
    'FSN',
    'FST',
    'FTM',
    'FTT',
    'FUN',
    'FX',
    'FXC',
    'GALA',
    'GARD',
    'GAS',
    'GBYTE',
    'GLEEC',
    'GNO',
    'GNT',
    'GRIN',
    'GRN',
    'GRS',
    'GRT',
    'GT',
    'GUSD',
    'GXC',
    'HBAR',
    'HBTC',
    'HC',
    'HEDG',
    'HEX',
    'HIVE',
    'HMR',
    'HNC',
    'HNS',
    'HNT',
    'HOD',
    'HOT',
    'HPT',
    'HSN',
    'HT',
    'HUSD',
    'HXRO',
    'HYN',
    'ICH',
    'ICP',
    'ICX',
    'IDEX',
    'IGNIS',
    'IHF',
    'ILV',
    'IMX',
    'INB',
    'INJ',
    'INO',
    'INSTAR',
    'IOST',
    'IOTX',
    'IPX',
    'IQ',
    'IRIS',
    'IZE',
    'JST',
    'JUL',
    'JWL',
    'KAI',
    'KAN',
    'KAVA',
    'KBC',
    'KCASH',
    'KCS',
    'KDA',
    'KDAG',
    'KEEP',
    'KIN',
    'KLAY',
    'KMD',
    'KNC',
    'KP3R',
    'KRT',
    'KSM',
    'LA',
    'LAMB',
    'LBC',
    'LCX',
    'LEO',
    'LEVL',
    'LINK',
    'LOKI',
    'LOOM',
    'LPT',
    'LRC',
    'LRG',
    'LSK',
    'LTC',
    'LTO',
    'LUNA',
    'LVX',
    'MAID',
    'MANA',
    'MASS',
    'MATH',
    'MATIC',
    'MBL',
    'MBN',
    'MCO',
    'MDA',
    'MED',
    'MFT',
    'MIN',
    'MIOTA',
    'MKR',
    'MLK',
    'MLN',
    'MOF',
    'MONA',
    'MRPH',
    'MTA',
    'MTC',
    'MTL',
    'MTXLT',
    'MUSD',
    'MVL',
    'MWC',
    'MX',
    'MXC',
    'NANO',
    'NAS',
    'NEAR',
    'NEC',
    'NEO',
    'NEST',
    'NEX',
    'NEXO',
    'NEXXO',
    'NIM',
    'NKN',
    'NMR',
    'NOIA',
    'NPXS',
    'NRG',
    'NU',
    'NULS',
    'NUT',
    'NVT',
    'NWC',
    'NXM',
    'NXS',
    'NYE',
    'OCEAN',
    'OCTO',
    'OGN',
    'OKB',
    'OMG',
    'ONE',
    'ONOT',
    'ONT',
    'ORBS',
    'ORC',
    'ORN',
    'OTH',
    'OXT',
    'PAI',
    'PAX',
    'PAXG',
    'PCN',
    'PCX',
    'PERL',
    'PERP',
    'PHA',
    'PIVX',
    'PLC',
    'PLF',
    'PNK',
    'POLS',
    'POLY',
    'POWR',
    'PPT',
    'PROM',
    'PRQ',
    'PZM',
    'QASH',
    'QC',
    'QKC',
    'QNT',
    'QQQ',
    'QRK',
    'QRL',
    'QSP',
    'QTUM',
    'RCHAINREV',
    'RCN',
    'RDD',
    'RDN',
    'REN',
    'RENBTC',
    'REP',
    'REPO',
    'REQ',
    'REV',
    'RIF',
    'RING',
    'RKN',
    'RLC',
    'RNDR',
    'ROSE',
    'RPL',
    'RSR',
    'RUNE',
    'RVN',
    'S4F',
    'SAFE',
    'SAND',
    'SAPP',
    'SC',
    'SCC',
    'SCRT',
    'SEELE',
    'SERO',
    'SFP',
    'SHIB',
    'SHPING',
    'SHR',
    'SLS',
    'SNB',
    'SNL',
    'SNT',
    'SNTVT',
    'SNX',
    'SOL',
    'SOLO',
    'SOLVE',
    'SPND',
    'SRM',
    'STAKE',
    'STEEM',
    'STMX',
    'STORJ',
    'STP',
    'STPT',
    'STRAT',
    'STRONG',
    'STX',
    'SUKU',
    'SUN',
    'SUSD',
    'SUSHI',
    'SWAP',
    'SWINGBY',
    'SWTH',
    'SXP',
    'SYS',
    'TCAD',
    'TEL',
    'TFUEL',
    'THETA',
    'THR',
    'THX',
    'TITAN',
    'TMTG',
    'TNC',
    'TOMO',
    'TONIC',
    'TRAC',
    'TRAT',
    'TRB',
    'TROY',
    'TRUE',
    'TRX',
    'TSHP',
    'TT',
    'TTT',
    'TUSD',
    'TWT',
    'UBT',
    'ULT',
    'UMA',
    'UNI',
    'UNICOIN',
    'UNO',
    'UOS',
    'UQC',
    'USDC',
    'USDJ',
    'USDK',
    'USDN',
    'USDP',
    'USDT',
    'UST',
    'UTK',
    'VEST',
    'VET',
    'VGX',
    'VIDT',
    'VITAE',
    'VLX',
    'VRSC',
    'VSYS',
    'VTHO',
    'VVS',
    'WAN',
    'WAVES',
    'WAXP',
    'WBNB',
    'WBTC',
    'WET',
    'WICC',
    'WIN',
    'WIX',
    'WOM',
    'WRX',
    'WTC',
    'WXT',
    'XCM',
    'XDC',
    'XEC',
    'XEM',
    'XHV',
    'XIN',
    'XLM',
    'XLT',
    'XMR',
    'XNC',
    'XOR',
    'XPR',
    'XRP',
    'XSN',
    'XSR',
    'XT',
    'XTP',
    'XTZ',
    'XVG',
    'XVS',
    'XWC',
    'XYM',
    'XYO',
    'XZC',
    'YEP',
    'YF-DAI',
    'YFI',
    'YFII',
    'YFL',
    'YGG',
    'YUSRA',
    'ZAP',
    'ZB',
    'ZCN',
    'ZEC',
    'ZEN',
    'ZIL',
    'ZLW',
    'ZNN',
    'ZRX',
    'ZT',
    'ZYN',
  ],
  enumNames: [
    '1inch Network',
    'Aave',
    'ABBC Coin',
    'Cardano',
    'AdEx Network',
    'Aeternity',
    'Aergo',
    'SingularityNET',
    'AgaveCoin',
    'Advanced Internet Blocks',
    'Aion',
    'Akropolis',
    'Algorand',
    'AMO Coin',
    'Amp',
    'Ampleforth',
    'Anchor Protocol',
    'Anchor',
    'Ankr',
    'Aragon',
    'Aurora',
    'Apollo Currency',
    'apM Coin',
    'Arweave',
    'Ardor',
    'Ark',
    'ARPA Chain',
    'Pirate Chain',
    'AirSwap',
    'Cosmos',
    'Attila',
    'Audius',
    'Travala.com',
    'Avalanche',
    'AXIA Coin',
    'AXEL',
    'Axie Infinity',
    'B2BX',
    'Balancer',
    'Band Protocol',
    'BASIC',
    'Basid Coin',
    'Basic Attention Token',
    'Bitcoin Diamond',
    'Bitcoin Cash',
    'Bytecoin',
    'Buggyra Coin Zero',
    'BDCC Bitica COIN',
    'Beldex',
    'Beam',
    'Bella Protocol',
    'Bithao',
    'BitcoinHD',
    'BHPCoin',
    'BHEX Token',
    'Biconomy',
    'BigONE Token',
    'BIKI',
    'Bloomzed Loyalty Club Ticket',
    'Blocknet',
    'Bluzelle',
    'Chimpion',
    'Binance Coin',
    'Bankera',
    'Bancor',
    'BOSAGORA',
    'Bonorum',
    'BORA',
    'Bounce Token',
    'botXcoin',
    'BitcoinPoS',
    'Baer Chain',
    'Bridge Oracle',
    'Breezecoin',
    'Bitcoin SV',
    'Bitcoin',
    'Bitcoin 2',
    'Bitcoin BEP2',
    'Bitcoin Gold',
    'Bytom',
    'BitMax Token',
    'Bitball Treasure',
    'BitShares',
    'BitTorrent',
    'BTU Protocol',
    'Binance USD',
    'Beowulf',
    'Bitbook Gambling',
    'Bit-Z Token',
    'bZx Protocol',
    'CRYPTO20',
    'CAD Coin',
    'PancakeSwap',
    'Counos Coin',
    'Counos X',
    'Celsius',
    'Celo',
    'Celer Network',
    'Centrality',
    'Chromia',
    'SwissBorg',
    'Chiliz',
    'Cipher Core Token',
    'Cryptoindex.com 100',
    'Nervos Network',
    'Cindicator',
    'Cryptonex',
    'Cocos-BCX',
    'Compound',
    'CONUN',
    'cVault.finance',
    'Contentos',
    'COTI',
    'Carry',
    'Crypto.com Coin',
    'Crypterium',
    'Curve DAO Token',
    'Creditcoin',
    'CONTRACOIN',
    'CertiK',
    'Cartesi',
    'Cortex',
    'Celo Dollar',
    'Crypto Village Accelerator',
    'Civic',
    'Content Value Network',
    'CyberVein',
    'Convex Finance',
    'Davinci Coin',
    'DAD',
    'Constellation',
    'Dai',
    'Dash',
    'Streamr',
    'Decred',
    'Dinastycoin',
    'Darico Ecosystem Coin',
    'Dent',
    'DeFiChain',
    'DigiByte',
    'DigixDAO',
    'Digitex Futures',
    'DIA',
    'Etherisc DIP Token',
    'Divi',
    'Darma Cash',
    'DMM: Governance',
    'Metaverse Dualchain Network Architecture',
    'district0x',
    'Dogecoin',
    'Polkadot',
    'DREP',
    'Dragonchain',
    'Doctors Coin',
    'Dynamic Trading Rights',
    'Dusk Network',
    'DxChain Token',
    'Ecoreal Estate',
    'EDC Blockchain v1 [old]',
    'Elrond',
    'Elastos',
    'aelf',
    'Dogelon Mars',
    'Einsteinium',
    'Enigma',
    'Enjin Coin',
    'Ethereum Name Service',
    'EOS',
    'ERC20',
    'Ergo',
    'Ethereum Classic',
    'Ethereum',
    'Electroneum',
    'Elitium',
    'STASIS EURO',
    'Envion',
    'Everus',
    'Energy Web Token',
    'FABRK',
    'Harvest Finance',
    'Fetch.ai',
    'Filecoin',
    'Folgory Coin',
    'Flamingo',
    'Flow',
    'FNB Protocol',
    'Fusion',
    '1irstcoin',
    'Fantom',
    'FTX Token',
    'FunFair',
    'Function X',
    'Flexacoin',
    'Gala',
    'Hashgard',
    'Gas',
    'Obyte',
    'Gleec',
    'Gnosis',
    'Golem',
    'Grin',
    'GreenPower',
    'Groestlcoin',
    'The Graph',
    'GateToken',
    'Gemini Dollar',
    'GXChain',
    'Hedera Hashgraph',
    'Huobi BTC',
    'HyperCash',
    'HedgeTrade',
    'HEX',
    'Hive',
    'Homeros',
    'Hellenic Coin',
    'Handshake',
    'Helium',
    'HoDooi.com',
    'Holo',
    'Huobi Pool Token',
    'Helper Search Token',
    'Huobi Token',
    'HUSD',
    'Hxro',
    'Hyperion',
    'Idea Chain Coin',
    'Internet Computer',
    'ICON',
    'IDEX',
    'Ignis',
    'Invictus Hyperion Fund',
    'Illuvium',
    'Immutable X',
    'Insight Chain',
    'Injective Protocol',
    'INO COIN',
    'Insights Network',
    'IOST',
    'IoTeX',
    'Tachyon Protocol',
    'Everipedia',
    'IRISnet',
    'IZE',
    'JUST',
    'Joule',
    'Jewel',
    'KardiaChain',
    'BitKan',
    'Kava.io',
    'Karatgold Coin',
    'Kcash',
    'KuCoin Shares',
    'Kadena',
    'King DAG',
    'Keep Network',
    'Kin',
    'Klaytn',
    'Komodo',
    'Kyber Network',
    'Keep3rV1',
    'TerraKRW',
    'Kusama',
    'LATOKEN',
    'Lambda',
    'LBRY Credits',
    'LCX',
    'UNUS SED LEO',
    'Levolution',
    'Chainlink',
    'Loki',
    'Loom Network',
    'Livepeer',
    'Loopring',
    'Largo Coin',
    'Lisk',
    'Litecoin',
    'LTO Network',
    'Terra',
    'Level01',
    'MaidSafeCoin',
    'Decentraland',
    'Massnet',
    'MATH',
    'Matic Network',
    'MovieBloc',
    'Mobilian Coin',
    'MCO',
    'Moeda Loyalty Points',
    'MediBloc',
    'Mainframe',
    'MINDOL',
    'IOTA',
    'Maker',
    'MiL.k',
    'Melon',
    'Molecular Future',
    'MonaCoin',
    'Morpheus.Network',
    'Meta',
    'Metacoin',
    'Metal',
    'Tixl',
    'mStable USD',
    'MVL',
    'MimbleWimbleCoin',
    'MX Token',
    'MXC',
    'Nano',
    'Nebulas',
    'NEAR Protocol',
    'Nectar',
    'Neo',
    'NEST Protocol',
    'Nash Exchange',
    'Nexo',
    'Nexxo',
    'Nimiq',
    'NKN',
    'Numeraire',
    'NOIA Network',
    'Pundi X',
    'Energi',
    'NuCypher',
    'NULS',
    'Native Utility Token',
    'NerveNetwork',
    'Newscrypto',
    'NXM',
    'Nexus',
    'NewYork Exchange',
    'Ocean Protocol',
    'OctoFi',
    'Origin Protocol',
    'OKB',
    'OMG Network',
    'Harmony',
    'ONOToken',
    'Ontology',
    'Orbs',
    'Orbit Chain',
    'Orion Protocol',
    'Other',
    'Orchid',
    'Project Pai',
    'Paxos Standard',
    'PAX Gold',
    'PeepCoin',
    'ChainX',
    'Perlin',
    'Perpetual Protocol',
    'Phala.Network',
    'PIVX',
    'PLATINCOIN',
    'PlayFuel',
    'Kleros',
    'Polkastarter',
    'Polymath',
    'Power Ledger',
    'Populous',
    'Prometeus',
    'PARSIQ',
    'PRIZM',
    'QASH',
    'Qcash',
    'QuarkChain',
    'Quant',
    'Poseidon Network',
    'Quark',
    'Quantum Resistant Ledger',
    'Quantstamp',
    'Qtum',
    'RChain',
    'Ripio Credit Network',
    'ReddCoin',
    'Raiden Network Token',
    'Ren',
    'renBTC',
    'Augur',
    'REPO',
    'Request',
    'Revain',
    'RSK Infrastructure Framework',
    'Darwinia Network',
    'Rakon',
    'iExec RLC',
    'Render Token',
    'Oasis Network',
    'Rocket Pool',
    'Reserve Rights',
    'THORChain',
    'Ravencoin',
    'S4FE',
    'yieldfarming.insure',
    'The Sandbox',
    'Sapphire',
    'Siacoin',
    'STEM CELL COIN',
    'Secret',
    'Seele-N',
    'Super Zero Protocol',
    'SafePal',
    'Shiba Inu',
    'SHPING',
    'ShareToken',
    'SaluS',
    'SynchroBitcoin',
    'Sport and Leisure',
    'Status',
    'Sentivate',
    'Synthetix',
    'Solana',
    'Sologenic',
    'SOLVE',
    'Spendcoin',
    'Serum',
    'xDai',
    'Steem',
    'StormX',
    'Storj',
    'STPAY',
    'Standard Tokenization Protocol',
    'Stratis',
    'Strong',
    'Blockstack',
    'SUKU',
    'SUN',
    'sUSD',
    'SushiSwap',
    'TrustSwap',
    'Swingby',
    'Switcheo',
    'Swipe',
    'Syscoin',
    'TrueCAD',
    'Telcoin',
    'Theta Fuel',
    'THETA',
    'ThoreCoin',
    'ThoreNext',
    'TitanSwap',
    'The Midas Touch Gold',
    'TNC Coin',
    'TomoChain',
    'Tectonic',
    'OriginTrail',
    'Tratin',
    'Tellor',
    'TROY',
    'TrueChain',
    'TRON',
    '12Ships',
    'Thunder Token',
    'The Transfer Token',
    'TrueUSD',
    'Trust Wallet Token',
    'Unibright',
    'Ultiledger',
    'UMA',
    'Uniswap',
    'UNI COIN',
    'Unobtanium',
    'Ultra',
    'Uquid Coin',
    'USD Coin',
    'USDJ',
    'USDK',
    'Neutrino USD',
    'Pax Dollar',
    'Tether',
    'TerraUSD',
    'Utrust',
    'VestChain',
    'VeChain',
    'Voyager Token',
    'VIDT Datalink',
    'Vitae',
    'Velas',
    'VerusCoin',
    'v.systems',
    'VeThor Token',
    'VVS Finance',
    'Wanchain',
    'Waves',
    'WAX',
    'Wrapped BNB',
    'Wrapped Bitcoin',
    'WeShow Token',
    'WaykiChain',
    'WINk',
    'Wixlar',
    'WOM Protocol',
    'WazirX',
    'Waltonchain',
    'Wirex Token',
    'CoinMetro Token',
    'XinFin Network',
    'eCash',
    'NEM',
    'Haven Protocol',
    'Mixin',
    'Stellar',
    'Nexalt',
    'Monero',
    'XeniosCoin',
    'Sora',
    'Proton',
    'XRP',
    'Stakenet',
    'Xensor',
    'ExtStock Token',
    'Tap',
    'Tezos',
    'Verge',
    'Venus',
    'WhiteCoin',
    'Symbol',
    'XYO',
    'Zcoin',
    'YEP COIN',
    'YFDAI.FINANCE',
    'yearn.finance',
    'DFI.Money',
    'YF Link',
    'Yield Guild Games',
    'YUSRA',
    'Zap',
    'ZB Token',
    '0Chain',
    'Zcash',
    'Horizen',
    'Zilliqa',
    'Zelwin',
    'Zenon',
    '0x',
    'ZBG Token',
    'Zynecoin',
  ],
}

export const ProvinceStateCode = {
  type: 'string',
  enum: [
    'AB',
    'BC',
    'MB',
    'NB',
    'NL',
    'NT',
    'NS',
    'NU',
    'ON',
    'PE',
    'QC',
    'SK',
    'YT',
    'AL',
    'AK',
    'AZ',
    'AR',
    'CA',
    'CO',
    'CT',
    'DE',
    'DC',
    'FL',
    'GA',
    'HI',
    'ID',
    'IL',
    'IN',
    'IA',
    'KS',
    'KY',
    'LA',
    'ME',
    'MD',
    'MA',
    'MI',
    'MN',
    'MS',
    'MO',
    'MT',
    'NE',
    'NV',
    'NH',
    'NJ',
    'NM',
    'NY',
    'NC',
    'ND',
    'OH',
    'OK',
    'OR',
    'PA',
    'RI',
    'SC',
    'SD',
    'TN',
    'TX',
    'UT',
    'VT',
    'VA',
    'WA',
    'WV',
    'WI',
    'WY',
    'AG',
    'BA',
    'BJ',
    'CE',
    'CI',
    'CH',
    'CU',
    'CL',
    'DF',
    'DO',
    'GU',
    'GR',
    'HL',
    'JL',
    'MX',
    'MC',
    'MR',
    'NA',
    'NL',
    'OA',
    'PB',
    'QU',
    'QR',
    'SL',
    'SI',
    'SO',
    'TB',
    'TA',
    'TL',
    'VC',
    'YU',
    'ZA',
  ],
  enumNames: [
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Northwest Territories',
    'Nova Scotia',
    'Nunavut',
    'Ontario',
    'Prince Edward Island',
    'Quebec',
    'Saskatchewan',
    'Yukon',
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'District of Columbia',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
    'Aguascalientas',
    'Baja, Calif. (North)',
    'Baja, Calif. (South)',
    'Campeche',
    'Chiapas',
    'Chihuahua',
    'Coahuila de Zaragoza',
    'Colima',
    'Distrito',
    'Durango',
    'Guanajuato',
    'Guerreo',
    'Hidalgo',
    'Jalisco',
    'Mexico (State)',
    'Michoacan de Ocampo',
    'Morelos',
    'Nayarit',
    'Nuevo Leon',
    'Oaxaca',
    'Puebla',
    'Queretaro de Arteaga',
    'Quintana Roo',
    'San Luis Potosi',
    'Sinaloa',
    'Sonora',
    'Tabasco',
    'Tamaulipas',
    'Tlaxcala',
    'Veracruz-Llave',
    'Yucatan',
    'Zacatecas',
  ],
}

export const CountryOfResidenceCode = {
  type: 'string',
  enum: [
    'CA',
    'US',
    'AD',
    'AE',
    'AF',
    'AG',
    'AI',
    'AL',
    'AM',
    'AN',
    'AO',
    'AQ',
    'AR',
    'AS',
    'AT',
    'AU',
    'AW',
    'AX',
    'AZ',
    'BA',
    'BB',
    'BD',
    'BE',
    'BF',
    'BG',
    'BH',
    'BI',
    'BJ',
    'BL',
    'BM',
    'BN',
    'BO',
    'BQ',
    'BR',
    'BS',
    'BT',
    'BV',
    'BW',
    'BY',
    'BZ',
    'CC',
    'CD',
    'CF',
    'CG',
    'CH',
    'CI',
    'CK',
    'CL',
    'CM',
    'CN',
    'CO',
    'CR',
    'CS',
    'CU',
    'CV',
    'CW',
    'CX',
    'CY',
    'CZ',
    'DE',
    'DJ',
    'DK',
    'DM',
    'DO',
    'DZ',
    'EC',
    'EE',
    'EG',
    'EH',
    'ER',
    'ES',
    'ET',
    'FI',
    'FJ',
    'FK',
    'FM',
    'FO',
    'FR',
    'FX',
    'GA',
    'GB',
    'GD',
    'GE',
    'GF',
    'GG',
    'GH',
    'GI',
    'GL',
    'GM',
    'GN',
    'GP',
    'GQ',
    'GR',
    'GS',
    'GT',
    'GU',
    'GW',
    'GY',
    'HK',
    'HM',
    'HN',
    'HR',
    'HT',
    'HU',
    'ID',
    'IE',
    'IL',
    'IM',
    'IN',
    'IO',
    'IQ',
    'IR',
    'IS',
    'IT',
    'JE',
    'JM',
    'JO',
    'JP',
    'KE',
    'KG',
    'KH',
    'KI',
    'KM',
    'KN',
    'KP',
    'KR',
    'KW',
    'KY',
    'KZ',
    'LA',
    'LB',
    'LC',
    'LI',
    'LK',
    'LR',
    'LS',
    'LT',
    'LU',
    'LV',
    'LY',
    'MA',
    'MC',
    'MD',
    'ME',
    'MF',
    'MG',
    'MH',
    'MK',
    'ML',
    'MM',
    'MN',
    'MO',
    'MP',
    'MQ',
    'MR',
    'MS',
    'MT',
    'MU',
    'MV',
    'MW',
    'MX',
    'MY',
    'MZ',
    'NA',
    'NC',
    'NE',
    'NF',
    'NG',
    'NI',
    'NL',
    'NO',
    'NP',
    'NR',
    'NU',
    'NZ',
    'OM',
    'PA',
    'PE',
    'PF',
    'PG',
    'PH',
    'PK',
    'PL',
    'PM',
    'PN',
    'PR',
    'PS',
    'PT',
    'PW',
    'PY',
    'QA',
    'RE',
    'RO',
    'RS',
    'RU',
    'RW',
    'SA',
    'SB',
    'SC',
    'SD',
    'SE',
    'SG',
    'SH',
    'SI',
    'SJ',
    'SK',
    'SL',
    'SM',
    'SN',
    'SO',
    'SR',
    'SS',
    'ST',
    'SV',
    'SX',
    'SY',
    'SZ',
    'TC',
    'TD',
    'TF',
    'TG',
    'TH',
    'TJ',
    'TK',
    'TL',
    'TM',
    'TN',
    'TO',
    'TR',
    'TT',
    'TV',
    'TW',
    'TZ',
    'UA',
    'UG',
    'UM',
    'UY',
    'UZ',
    'VA',
    'VC',
    'VE',
    'VG',
    'VI',
    'VN',
    'VU',
    'WF',
    'WS',
    'YE',
    'YT',
    'ZA',
    'ZM',
    'ZW',
    'ZZ',
  ],
  enumNames: [
    'Canada',
    'United States',
    'Andorra',
    'United Arab Emirates (the)',
    'Afghanistan',
    'Antigua and Barbuda',
    'Anguilla',
    'Albania',
    'Armenia',
    'Netherlands Antilles',
    'Angola',
    'Antarctica',
    'Argentina',
    'American Samoa',
    'Austria',
    'Australia',
    'Aruba',
    'Åland Islands',
    'Azerbaijan',
    'Bosnia and Herzegovina',
    'Barbados',
    'Bangladesh',
    'Belgium',
    'Burkina Faso',
    'Bulgaria',
    'Bahrain',
    'Burundi',
    'Benin',
    'Saint Barthélemy',
    'Bermuda',
    'Brunei Darussalam',
    'Bolivia (Plurinational State of)',
    'Bonaire (Sint Eustatius and Saba)',
    'Brazil',
    'Bahamas',
    'Bhutan',
    'Bouvet Island',
    'Botswana',
    'Belarus',
    'Belize',
    'Cocos (Keeling) Islands',
    'Congo (the Democratic Republic of the)',
    'Central African Republic',
    'Congo (the)',
    'Switzerland',
    "Cote d'Ivoire",
    'Cook Islands',
    'Chile',
    'Cameroon',
    'China',
    'Colombia',
    'Costa Rica',
    'Serbia and Montenegro',
    'Cuba',
    'Cabo Verde',
    'Curaçao',
    'Christmas Island',
    'Cyprus',
    'Czech Republic',
    'Germany',
    'Djibouti',
    'Denmark',
    'Dominica',
    'Dominican Republic',
    'Algeria',
    'Ecuador',
    'Estonia',
    'Egypt',
    'Western Sahara',
    'Eritrea',
    'Spain',
    'Ethiopia',
    'Finland',
    'Fiji',
    'Falkland Islands (Malvinas)',
    'Micronesia (Federated States of)',
    'Faroe Islands',
    'France',
    'France, Metropolitan',
    'Gabon',
    'United Kingdom (the)',
    'Grenada',
    'Georgia',
    'French Guiana',
    'Guernsey, C.I.',
    'Ghana',
    'Gibraltar',
    'Greenland',
    'Gambia',
    'Guinea',
    'Guadeloupe',
    'Equatorial Guinea',
    'Greece',
    'So. Georgia and So. Sandwich Islands',
    'Guatemala',
    'Guam',
    'Guinea-Bissau',
    'Guyana',
    'Hong Kong',
    'Heard and McDonald Islands',
    'Honduras',
    'Croatia (Hrvatska)',
    'Haiti',
    'Hungary',
    'Indonesia',
    'Ireland',
    'Israel',
    'Isle of Man',
    'India',
    'British Indian Ocean Territory',
    'Iraq',
    'Iran (Islamic Republic of)',
    'Iceland',
    'Italy',
    'Jersey, C.I.',
    'Jamaica',
    'Jordan',
    'Japan',
    'Kenya',
    'Kyrgystan',
    'Cambodia',
    'Kiribati',
    'Comoros (the)',
    'Saint Kitts and Nevis',
    "Korea (Dem. People's Rep. of)",
    'Korea (the Republic of)',
    'Kuwait',
    'Cayman Islands',
    'Kazakhstan',
    "Lao People's Dem. Republic",
    'Lebanon',
    'Saint Lucia',
    'Liechtenstein',
    'Sri Lanka',
    'Liberia',
    'Lesotho',
    'Lithuania',
    'Luxembourg',
    'Latvia',
    'Libyan Arab Jamahiriya',
    'Morocco',
    'Monaco',
    'Moldova (the Republic of)',
    'Montenegro',
    'Saint Martin (French part)',
    'Madagascar',
    'Marshall Islands',
    'Macedonia (Former Yugoslav Republic)',
    'Mali',
    'Myanmar',
    'Mongolia',
    'Macao',
    'Northern Mariana Islands',
    'Martinique',
    'Mauritania',
    'Montserrat',
    'Malta',
    'Mauritius',
    'Maldives',
    'Malawi',
    'Mexico',
    'Malaysia',
    'Mozambique',
    'Namibia',
    'New Caledonia',
    'Niger',
    'Norfolk Island',
    'Nigeria',
    'Nicaragua',
    'Netherlands',
    'Norway',
    'Nepal',
    'Nauru',
    'Niue',
    'New Zealand',
    'Oman',
    'Panama',
    'Peru',
    'French Polynesia',
    'Papua New Guinea',
    'Philippines',
    'Pakistan',
    'Poland',
    'Saint Pierre and Miquelon',
    'Pitcairn',
    'Puerto Rico',
    'Palestine (State of)',
    'Portugal',
    'Palau',
    'Paraguay',
    'Qatar',
    'Reunion Island',
    'Romania',
    'Serbia',
    'Russian Federation (the)',
    'Rwanda',
    'Saudi Arabia',
    'Solomon Islands',
    'Seychelles',
    'Sudan',
    'Sweden',
    'Singapore',
    'Saint Helena',
    'Slovenia',
    'Svalbard and Jan Mayen Islands',
    'Slovakia (Slovak Republic)',
    'Sierra Leone',
    'San Marino',
    'Senegal',
    'Somalia',
    'Suriname',
    'South Sudan',
    'Sao Tome and Principe',
    'El Salvador',
    'Sint Maarten (Dutch part)',
    'Syrian Arab Republic',
    'Eswatini',
    'Turks and Caicos Islands (the)',
    'Chad',
    'French Southern Territories',
    'Togo',
    'Thailand',
    'Tajikistan',
    'Tokelau',
    'Timor-Leste',
    'Turkmenistan',
    'Tunisia',
    'Tonga',
    'Turkey',
    'Trinidad and Tobago',
    'Tuvalu',
    'Taiwan',
    'Tanzania (United Republic of)',
    'Ukraine',
    'Uganda',
    "United States Minor Outlying Is.'s",
    'Uruguay',
    'Uzbekistan',
    'Holy See (the)',
    'Saint Vincent and the Grenadines',
    'Venezuela (Bolivarian Republic of)',
    'Virgin Islands (British)',
    'Virgin Islands (U.S.)',
    'Viet Nam',
    'Vanuatu',
    'Wallis and Futuna Islands',
    'Samoa',
    'Yemen',
    'Mayotte',
    'South Africa',
    'Zambia',
    'Zimbabwe',
    'Unknown',
  ],
}
