#!/usr/bin/env ts-node
/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * This script injects AWS API Gateway specific settings into our public-management openapi and output to dist/openapi/openapi-public-management-autogenerated.yaml
 */

import * as fs from 'fs'
import * as yaml from 'js-yaml'
import _ from 'lodash'
import mkdirp from 'mkdirp'
import { StackConstants } from '../constants'
import { getAugmentedOpenapi } from './openapi-augmentor-util'

// We don't care about region
const env = (process.env.ENV || 'prod').split(':')[0]

const PathToLambda: any = {
  '/rules': StackConstants.CONSOLE_API_RULE_FUNCTION_NAME,
  '/rules/{ruleId}': StackConstants.CONSOLE_API_RULE_FUNCTION_NAME,
  '/rule-instances': StackConstants.CONSOLE_API_RULE_INSTANCE_FUNCTION_NAME,
  '/rule-instances/{ruleInstanceId}':
    StackConstants.CONSOLE_API_RULE_INSTANCE_FUNCTION_NAME,
}

const openapi = getAugmentedOpenapi(
  './lib/openapi/public-management/openapi-public-management-original.yaml',
  PathToLambda,
  'API_KEY'
)
mkdirp.sync(`./dist/openapi`)
fs.writeFileSync(
  `./dist/openapi/openapi-public-management-autogenerated-${env}.yaml`,
  yaml.dump(openapi)
)
