import { RiskParameterLevelKeyValue } from '@/apis';

export const DEFAULT_COUNTRY_RISK_VALUES: RiskParameterLevelKeyValue[] = [
  {
    parameterValue: {
      content: {
        kind: 'MULTIPLE',
        values: [
          { kind: 'LITERAL', content: 'AF' },
          { kind: 'LITERAL', content: 'BI' },
          { kind: 'LITERAL', content: 'CD' },
          { kind: 'LITERAL', content: 'CF' },
          { kind: 'LITERAL', content: 'CG' },
          { kind: 'LITERAL', content: 'CN' },
          { kind: 'LITERAL', content: 'EH' },
          { kind: 'LITERAL', content: 'ER' },
          { kind: 'LITERAL', content: 'GA' },
          { kind: 'LITERAL', content: 'GQ' },
          { kind: 'LITERAL', content: 'GW' },
          { kind: 'LITERAL', content: 'HT' },
          { kind: 'LITERAL', content: 'IQ' },
          { kind: 'LITERAL', content: 'IR' },
          { kind: 'LITERAL', content: 'KP' },
          { kind: 'LITERAL', content: 'LA' },
          { kind: 'LITERAL', content: 'LR' },
          { kind: 'LITERAL', content: 'LY' },
          { kind: 'LITERAL', content: 'MM' },
          { kind: 'LITERAL', content: 'MZ' },
          { kind: 'LITERAL', content: 'PS' },
          { kind: 'LITERAL', content: 'RU' },
          { kind: 'LITERAL', content: 'SD' },
          { kind: 'LITERAL', content: 'SO' },
          { kind: 'LITERAL', content: 'TD' },
          { kind: 'LITERAL', content: 'VE' },
          { kind: 'LITERAL', content: 'XK' },
        ],
      },
    },
    riskValue: {
      type: 'RISK_LEVEL',
      value: 'VERY_HIGH',
    },
  },
  {
    parameterValue: {
      content: {
        kind: 'MULTIPLE',
        values: [
          { kind: 'LITERAL', content: 'AE' },
          { kind: 'LITERAL', content: 'AO' },
          { kind: 'LITERAL', content: 'BF' },
          { kind: 'LITERAL', content: 'BG' },
          { kind: 'LITERAL', content: 'BJ' },
          { kind: 'LITERAL', content: 'BO' },
          { kind: 'LITERAL', content: 'CI' },
          { kind: 'LITERAL', content: 'CM' },
          { kind: 'LITERAL', content: 'DJ' },
          { kind: 'LITERAL', content: 'DZ' },
          { kind: 'LITERAL', content: 'GN' },
          { kind: 'LITERAL', content: 'GY' },
          { kind: 'LITERAL', content: 'KE' },
          { kind: 'LITERAL', content: 'KH' },
          { kind: 'LITERAL', content: 'KM' },
          { kind: 'LITERAL', content: 'KW' },
          { kind: 'LITERAL', content: 'KY' },
          { kind: 'LITERAL', content: 'LB' },
          { kind: 'LITERAL', content: 'MC' },
          { kind: 'LITERAL', content: 'MG' },
          { kind: 'LITERAL', content: 'MH' },
          { kind: 'LITERAL', content: 'ML' },
          { kind: 'LITERAL', content: 'MR' },
          { kind: 'LITERAL', content: 'NA' },
          { kind: 'LITERAL', content: 'NE' },
          { kind: 'LITERAL', content: 'NG' },
          { kind: 'LITERAL', content: 'NI' },
          { kind: 'LITERAL', content: 'NP' },
          { kind: 'LITERAL', content: 'PG' },
          { kind: 'LITERAL', content: 'SB' },
          { kind: 'LITERAL', content: 'SL' },
          { kind: 'LITERAL', content: 'SR' },
          { kind: 'LITERAL', content: 'SS' },
          { kind: 'LITERAL', content: 'ST' },
          { kind: 'LITERAL', content: 'SY' },
          { kind: 'LITERAL', content: 'SZ' },
          { kind: 'LITERAL', content: 'TG' },
          { kind: 'LITERAL', content: 'TH' },
          { kind: 'LITERAL', content: 'TJ' },
          { kind: 'LITERAL', content: 'TM' },
          { kind: 'LITERAL', content: 'TZ' },
          { kind: 'LITERAL', content: 'VG' },
          { kind: 'LITERAL', content: 'VN' },
          { kind: 'LITERAL', content: 'YE' },
          { kind: 'LITERAL', content: 'ZA' },
        ],
      },
    },
    riskValue: {
      type: 'RISK_LEVEL',
      value: 'HIGH',
    },
  },
  {
    parameterValue: {
      content: {
        kind: 'MULTIPLE',
        values: [
          { kind: 'LITERAL', content: 'AI' },
          { kind: 'LITERAL', content: 'AR' },
          { kind: 'LITERAL', content: 'AZ' },
          { kind: 'LITERAL', content: 'BA' },
          { kind: 'LITERAL', content: 'BD' },
          { kind: 'LITERAL', content: 'BH' },
          { kind: 'LITERAL', content: 'BR' },
          { kind: 'LITERAL', content: 'BS' },
          { kind: 'LITERAL', content: 'BT' },
          { kind: 'LITERAL', content: 'BY' },
          { kind: 'LITERAL', content: 'BZ' },
          { kind: 'LITERAL', content: 'CK' },
          { kind: 'LITERAL', content: 'CU' },
          { kind: 'LITERAL', content: 'CV' },
          { kind: 'LITERAL', content: 'CW' },
          { kind: 'LITERAL', content: 'EC' },
          { kind: 'LITERAL', content: 'EG' },
          { kind: 'LITERAL', content: 'ET' },
          { kind: 'LITERAL', content: 'FM' },
          { kind: 'LITERAL', content: 'GH' },
          { kind: 'LITERAL', content: 'GM' },
          { kind: 'LITERAL', content: 'GT' },
          { kind: 'LITERAL', content: 'HN' },
          { kind: 'LITERAL', content: 'HU' },
          { kind: 'LITERAL', content: 'ID' },
          { kind: 'LITERAL', content: 'IN' },
          { kind: 'LITERAL', content: 'KG' },
          { kind: 'LITERAL', content: 'KI' },
          { kind: 'LITERAL', content: 'KN' },
          { kind: 'LITERAL', content: 'LK' },
          { kind: 'LITERAL', content: 'LS' },
          { kind: 'LITERAL', content: 'MT' },
          { kind: 'LITERAL', content: 'MV' },
          { kind: 'LITERAL', content: 'MW' },
          { kind: 'LITERAL', content: 'MX' },
          { kind: 'LITERAL', content: 'MY' },
          { kind: 'LITERAL', content: 'N/A' },
          { kind: 'LITERAL', content: 'NR' },
          { kind: 'LITERAL', content: 'NU' },
          { kind: 'LITERAL', content: 'OM' },
          { kind: 'LITERAL', content: 'PA' },
          { kind: 'LITERAL', content: 'PH' },
          { kind: 'LITERAL', content: 'PK' },
          { kind: 'LITERAL', content: 'PW' },
          { kind: 'LITERAL', content: 'PY' },
          { kind: 'LITERAL', content: 'QA' },
          { kind: 'LITERAL', content: 'RW' },
          { kind: 'LITERAL', content: 'SA' },
          { kind: 'LITERAL', content: 'SN' },
          { kind: 'LITERAL', content: 'SV' },
          { kind: 'LITERAL', content: 'SX' },
          { kind: 'LITERAL', content: 'TC' },
          { kind: 'LITERAL', content: 'TL' },
          { kind: 'LITERAL', content: 'TO' },
          { kind: 'LITERAL', content: 'TR' },
          { kind: 'LITERAL', content: 'TV' },
          { kind: 'LITERAL', content: 'UA' },
          { kind: 'LITERAL', content: 'UG' },
          { kind: 'LITERAL', content: 'UZ' },
          { kind: 'LITERAL', content: 'VA' },
          { kind: 'LITERAL', content: 'VU' },
          { kind: 'LITERAL', content: 'XA' },
          { kind: 'LITERAL', content: 'XB' },
          { kind: 'LITERAL', content: 'XC' },
          { kind: 'LITERAL', content: 'XD' },
          { kind: 'LITERAL', content: 'XE' },
          { kind: 'LITERAL', content: 'XF' },
          { kind: 'LITERAL', content: 'XG' },
          { kind: 'LITERAL', content: 'XH' },
          { kind: 'LITERAL', content: 'XI' },
          { kind: 'LITERAL', content: 'XJ' },
          { kind: 'LITERAL', content: 'XL' },
          { kind: 'LITERAL', content: 'XM' },
          { kind: 'LITERAL', content: 'XN' },
          { kind: 'LITERAL', content: 'XO' },
          { kind: 'LITERAL', content: 'XP' },
          { kind: 'LITERAL', content: 'XQ' },
          { kind: 'LITERAL', content: 'XR' },
          { kind: 'LITERAL', content: 'XS' },
          { kind: 'LITERAL', content: 'XT' },
          { kind: 'LITERAL', content: 'XU' },
          { kind: 'LITERAL', content: 'XV' },
          { kind: 'LITERAL', content: 'XW' },
          { kind: 'LITERAL', content: 'XY' },
          { kind: 'LITERAL', content: 'XZ' },
          { kind: 'LITERAL', content: 'ZM' },
          { kind: 'LITERAL', content: 'ZW' },
        ],
      },
    },
    riskValue: {
      type: 'RISK_LEVEL',
      value: 'MEDIUM',
    },
  },
  {
    parameterValue: {
      content: {
        kind: 'MULTIPLE',
        values: [
          { kind: 'LITERAL', content: 'AG' },
          { kind: 'LITERAL', content: 'AL' },
          { kind: 'LITERAL', content: 'AM' },
          { kind: 'LITERAL', content: 'AS' },
          { kind: 'LITERAL', content: 'AT' },
          { kind: 'LITERAL', content: 'AU' },
          { kind: 'LITERAL', content: 'AW' },
          { kind: 'LITERAL', content: 'BB' },
          { kind: 'LITERAL', content: 'BE' },
          { kind: 'LITERAL', content: 'BL' },
          { kind: 'LITERAL', content: 'BM' },
          { kind: 'LITERAL', content: 'BN' },
          { kind: 'LITERAL', content: 'BQ' },
          { kind: 'LITERAL', content: 'BW' },
          { kind: 'LITERAL', content: 'CA' },
          { kind: 'LITERAL', content: 'CH' },
          { kind: 'LITERAL', content: 'CL' },
          { kind: 'LITERAL', content: 'CO' },
          { kind: 'LITERAL', content: 'CR' },
          { kind: 'LITERAL', content: 'CY' },
          { kind: 'LITERAL', content: 'CZ' },
          { kind: 'LITERAL', content: 'DE' },
          { kind: 'LITERAL', content: 'DM' },
          { kind: 'LITERAL', content: 'DO' },
          { kind: 'LITERAL', content: 'ES' },
          { kind: 'LITERAL', content: 'FJ' },
          { kind: 'LITERAL', content: 'GB' },
          { kind: 'LITERAL', content: 'GD' },
          { kind: 'LITERAL', content: 'GE' },
          { kind: 'LITERAL', content: 'GF' },
          { kind: 'LITERAL', content: 'GG' },
          { kind: 'LITERAL', content: 'GI' },
          { kind: 'LITERAL', content: 'GP' },
          { kind: 'LITERAL', content: 'GU' },
          { kind: 'LITERAL', content: 'HK' },
          { kind: 'LITERAL', content: 'HR' },
          { kind: 'LITERAL', content: 'IE' },
          { kind: 'LITERAL', content: 'IM' },
          { kind: 'LITERAL', content: 'IT' },
          { kind: 'LITERAL', content: 'JE' },
          { kind: 'LITERAL', content: 'JM' },
          { kind: 'LITERAL', content: 'JO' },
          { kind: 'LITERAL', content: 'JP' },
          { kind: 'LITERAL', content: 'KR' },
          { kind: 'LITERAL', content: 'KZ' },
          { kind: 'LITERAL', content: 'LC' },
          { kind: 'LITERAL', content: 'LI' },
          { kind: 'LITERAL', content: 'LV' },
          { kind: 'LITERAL', content: 'MA' },
          { kind: 'LITERAL', content: 'MD' },
          { kind: 'LITERAL', content: 'ME' },
          { kind: 'LITERAL', content: 'MF' },
          { kind: 'LITERAL', content: 'MK' },
          { kind: 'LITERAL', content: 'MN' },
          { kind: 'LITERAL', content: 'MO' },
          { kind: 'LITERAL', content: 'MP' },
          { kind: 'LITERAL', content: 'MQ' },
          { kind: 'LITERAL', content: 'MS' },
          { kind: 'LITERAL', content: 'MU' },
          { kind: 'LITERAL', content: 'NC' },
          { kind: 'LITERAL', content: 'NL' },
          { kind: 'LITERAL', content: 'PE' },
          { kind: 'LITERAL', content: 'PF' },
          { kind: 'LITERAL', content: 'PL' },
          { kind: 'LITERAL', content: 'PM' },
          { kind: 'LITERAL', content: 'PR' },
          { kind: 'LITERAL', content: 'PT' },
          { kind: 'LITERAL', content: 'RE' },
          { kind: 'LITERAL', content: 'RO' },
          { kind: 'LITERAL', content: 'RS' },
          { kind: 'LITERAL', content: 'SC' },
          { kind: 'LITERAL', content: 'SG' },
          { kind: 'LITERAL', content: 'SH' },
          { kind: 'LITERAL', content: 'SK' },
          { kind: 'LITERAL', content: 'TN' },
          { kind: 'LITERAL', content: 'TT' },
          { kind: 'LITERAL', content: 'TW' },
          { kind: 'LITERAL', content: 'US' },
          { kind: 'LITERAL', content: 'UY' },
          { kind: 'LITERAL', content: 'VC' },
          { kind: 'LITERAL', content: 'VI' },
          { kind: 'LITERAL', content: 'WF' },
          { kind: 'LITERAL', content: 'WS' },
          { kind: 'LITERAL', content: 'YT' },
        ],
      },
    },
    riskValue: {
      type: 'RISK_LEVEL',
      value: 'LOW',
    },
  },
  {
    parameterValue: {
      content: {
        kind: 'MULTIPLE',
        values: [
          { kind: 'LITERAL', content: 'AD' },
          { kind: 'LITERAL', content: 'AQ' },
          { kind: 'LITERAL', content: 'AX' },
          { kind: 'LITERAL', content: 'BV' },
          { kind: 'LITERAL', content: 'CC' },
          { kind: 'LITERAL', content: 'CX' },
          { kind: 'LITERAL', content: 'DK' },
          { kind: 'LITERAL', content: 'EE' },
          { kind: 'LITERAL', content: 'FI' },
          { kind: 'LITERAL', content: 'FK' },
          { kind: 'LITERAL', content: 'FO' },
          { kind: 'LITERAL', content: 'FR' },
          { kind: 'LITERAL', content: 'GL' },
          { kind: 'LITERAL', content: 'GR' },
          { kind: 'LITERAL', content: 'GS' },
          { kind: 'LITERAL', content: 'HM' },
          { kind: 'LITERAL', content: 'IL' },
          { kind: 'LITERAL', content: 'IO' },
          { kind: 'LITERAL', content: 'IS' },
          { kind: 'LITERAL', content: 'LT' },
          { kind: 'LITERAL', content: 'LU' },
          { kind: 'LITERAL', content: 'NF' },
          { kind: 'LITERAL', content: 'NO' },
          { kind: 'LITERAL', content: 'NZ' },
          { kind: 'LITERAL', content: 'PN' },
          { kind: 'LITERAL', content: 'SE' },
          { kind: 'LITERAL', content: 'SI' },
          { kind: 'LITERAL', content: 'SJ' },
          { kind: 'LITERAL', content: 'SM' },
          { kind: 'LITERAL', content: 'TF' },
          { kind: 'LITERAL', content: 'TK' },
          { kind: 'LITERAL', content: 'UM' },
        ],
      },
    },
    riskValue: {
      type: 'RISK_LEVEL',
      value: 'VERY_LOW',
    },
  },
];

export const DEFAULT_CPI_COUNTRY_RISK_VALUES: RiskParameterLevelKeyValue[] = [
  {
    parameterValue: {
      content: {
        kind: 'MULTIPLE',
        values: [
          { kind: 'LITERAL', content: 'SS' },
          { kind: 'LITERAL', content: 'SO' },
          { kind: 'LITERAL', content: 'VE' },
          { kind: 'LITERAL', content: 'SY' },
          { kind: 'LITERAL', content: 'YE' },
          { kind: 'LITERAL', content: 'LY' },
          { kind: 'LITERAL', content: 'ER' },
          { kind: 'LITERAL', content: 'GQ' },
          { kind: 'LITERAL', content: 'NI' },
          { kind: 'LITERAL', content: 'SD' },
          { kind: 'LITERAL', content: 'KP' },
          { kind: 'LITERAL', content: 'MM' },
          { kind: 'LITERAL', content: 'HT' },
          { kind: 'LITERAL', content: 'TM' },
          { kind: 'LITERAL', content: 'BI' },
          { kind: 'LITERAL', content: 'AF' },
          { kind: 'LITERAL', content: 'TJ' },
          { kind: 'LITERAL', content: 'CD' },
          { kind: 'LITERAL', content: 'ZW' },
          { kind: 'LITERAL', content: 'GW' },
          { kind: 'LITERAL', content: 'KM' },
          { kind: 'LITERAL', content: 'TD' },
          { kind: 'LITERAL', content: 'KH' },
          { kind: 'LITERAL', content: 'RU' },
          { kind: 'LITERAL', content: 'LB' },
          { kind: 'LITERAL', content: 'HN' },
          { kind: 'LITERAL', content: 'AZ' },
          { kind: 'LITERAL', content: 'IR' },
          { kind: 'LITERAL', content: 'CG' },
          { kind: 'LITERAL', content: 'BD' },
          { kind: 'LITERAL', content: 'PY' },
          { kind: 'LITERAL', content: 'CF' },
          { kind: 'LITERAL', content: 'MZ' },
          { kind: 'LITERAL', content: 'KG' },
          { kind: 'LITERAL', content: 'GT' },
          { kind: 'LITERAL', content: 'UG' },
        ],
      },
    },
    riskValue: {
      type: 'RISK_LEVEL',
      value: 'VERY_HIGH',
    },
  },
  {
    parameterValue: {
      content: {
        kind: 'MULTIPLE',
        values: [
          { kind: 'LITERAL', content: 'NG' },
          { kind: 'LITERAL', content: 'MX' },
          { kind: 'LITERAL', content: 'MG' },
          { kind: 'LITERAL', content: 'IQ' },
          { kind: 'LITERAL', content: 'CM' },
          { kind: 'LITERAL', content: 'PK' },
          { kind: 'LITERAL', content: 'ML' },
          { kind: 'LITERAL', content: 'LR' },
          { kind: 'LITERAL', content: 'GA' },
          { kind: 'LITERAL', content: 'SZ' },
          { kind: 'LITERAL', content: 'GN' },
          { kind: 'LITERAL', content: 'BO' },
          { kind: 'LITERAL', content: 'MR' },
          { kind: 'LITERAL', content: 'SV' },
          { kind: 'LITERAL', content: 'EG' },
          { kind: 'LITERAL', content: 'PE' },
          { kind: 'LITERAL', content: 'PG' },
          { kind: 'LITERAL', content: 'DJ' },
          { kind: 'LITERAL', content: 'UZ' },
          { kind: 'LITERAL', content: 'TG' },
          { kind: 'LITERAL', content: 'LK' },
          { kind: 'LITERAL', content: 'KE' },
          { kind: 'LITERAL', content: 'EC' },
          { kind: 'LITERAL', content: 'AO' },
          { kind: 'LITERAL', content: 'SL' },
          { kind: 'LITERAL', content: 'PH' },
          { kind: 'LITERAL', content: 'PA' },
          { kind: 'LITERAL', content: 'MN' },
          { kind: 'LITERAL', content: 'LA' },
          { kind: 'LITERAL', content: 'BA' },
          { kind: 'LITERAL', content: 'BY' },
          { kind: 'LITERAL', content: 'TR' },
          { kind: 'LITERAL', content: 'TH' },
          { kind: 'LITERAL', content: 'NE' },
          { kind: 'LITERAL', content: 'NP' },
          { kind: 'LITERAL', content: 'MW' },
          { kind: 'LITERAL', content: 'BR' },
          { kind: 'LITERAL', content: 'DZ' },
          { kind: 'LITERAL', content: 'UA' },
          { kind: 'LITERAL', content: 'RS' },
          { kind: 'LITERAL', content: 'DO' },
          { kind: 'LITERAL', content: 'MA' },
          { kind: 'LITERAL', content: 'LS' },
          { kind: 'LITERAL', content: 'ID' },
          { kind: 'LITERAL', content: 'ET' },
          { kind: 'LITERAL', content: 'AR' },
          { kind: 'LITERAL', content: 'MV' },
          { kind: 'LITERAL', content: 'IN' },
          { kind: 'LITERAL', content: 'GM' },
          { kind: 'LITERAL', content: 'ZM' },
          { kind: 'LITERAL', content: 'TN' },
          { kind: 'LITERAL', content: 'GY' },
          { kind: 'LITERAL', content: 'CO' },
        ],
      },
    },
    riskValue: {
      type: 'RISK_LEVEL',
      value: 'HIGH',
    },
  },
  {
    parameterValue: {
      content: {
        kind: 'MULTIPLE',
        values: [
          { kind: 'LITERAL', content: 'VN' },
          { kind: 'LITERAL', content: 'SR' },
          { kind: 'LITERAL', content: 'MK' },
          { kind: 'LITERAL', content: 'KZ' },
          { kind: 'LITERAL', content: 'TT' },
          { kind: 'LITERAL', content: 'TZ' },
          { kind: 'LITERAL', content: 'ZA' },
          { kind: 'LITERAL', content: 'HU' },
          { kind: 'LITERAL', content: 'CU' },
          { kind: 'LITERAL', content: 'BF' },
          { kind: 'LITERAL', content: 'GH' },
          { kind: 'LITERAL', content: 'AL' },
          { kind: 'LITERAL', content: 'SB' },
          { kind: 'LITERAL', content: 'MD' },
          { kind: 'LITERAL', content: 'CN' },
          { kind: 'LITERAL', content: 'BG' },
          { kind: 'LITERAL', content: 'TL' },
          { kind: 'LITERAL', content: 'XK' },
          { kind: 'LITERAL', content: 'JM' },
          { kind: 'LITERAL', content: 'SN' },
          { kind: 'LITERAL', content: 'ST' },
          { kind: 'LITERAL', content: 'CI' },
          { kind: 'LITERAL', content: 'BJ' },
          { kind: 'LITERAL', content: 'RO' },
          { kind: 'LITERAL', content: 'ME' },
          { kind: 'LITERAL', content: 'MT' },
          { kind: 'LITERAL', content: 'KW' },
          { kind: 'LITERAL', content: 'HR' },
          { kind: 'LITERAL', content: 'AM' },
          { kind: 'LITERAL', content: 'SK' },
          { kind: 'LITERAL', content: 'NA' },
          { kind: 'LITERAL', content: 'JO' },
          { kind: 'LITERAL', content: 'GR' },
        ],
      },
    },
    riskValue: {
      type: 'RISK_LEVEL',
      value: 'MEDIUM',
    },
  },
  {
    parameterValue: {
      content: {
        kind: 'MULTIPLE',
        values: [
          { kind: 'LITERAL', content: 'VU' },
          { kind: 'LITERAL', content: 'MY' },
          { kind: 'LITERAL', content: 'MU' },
          { kind: 'LITERAL', content: 'PL' },
          { kind: 'LITERAL', content: 'GE' },
          { kind: 'LITERAL', content: 'BH' },
          { kind: 'LITERAL', content: 'IT' },
          { kind: 'LITERAL', content: 'OM' },
          { kind: 'LITERAL', content: 'FJ' },
          { kind: 'LITERAL', content: 'ES' },
          { kind: 'LITERAL', content: 'GD' },
          { kind: 'LITERAL', content: 'CZ' },
          { kind: 'LITERAL', content: 'CY' },
          { kind: 'LITERAL', content: 'RW' },
          { kind: 'LITERAL', content: 'PT' },
          { kind: 'LITERAL', content: 'BW' },
          { kind: 'LITERAL', content: 'CR' },
          { kind: 'LITERAL', content: 'SA' },
          { kind: 'LITERAL', content: 'LC' },
          { kind: 'LITERAL', content: 'QA' },
          { kind: 'LITERAL', content: 'LV' },
          { kind: 'LITERAL', content: 'SI' },
          { kind: 'LITERAL', content: 'DM' },
          { kind: 'LITERAL', content: 'CV' },
          { kind: 'LITERAL', content: 'VC' },
          { kind: 'LITERAL', content: 'LT' },
          { kind: 'LITERAL', content: 'CL' },
          { kind: 'LITERAL', content: 'KR' },
          { kind: 'LITERAL', content: 'IL' },
          { kind: 'LITERAL', content: 'US' },
          { kind: 'LITERAL', content: 'BS' },
          { kind: 'LITERAL', content: 'TW' },
          { kind: 'LITERAL', content: 'FR' },
          { kind: 'LITERAL', content: 'AT' },
          { kind: 'LITERAL', content: 'AE' },
          { kind: 'LITERAL', content: 'BB' },
          { kind: 'LITERAL', content: 'BE' },
        ],
      },
    },
    riskValue: {
      type: 'RISK_LEVEL',
      value: 'LOW',
    },
  },
  {
    parameterValue: {
      content: {
        kind: 'MULTIPLE',
        values: [
          { kind: 'LITERAL', content: 'GB' },
          { kind: 'LITERAL', content: 'JP' },
          { kind: 'LITERAL', content: 'SC' },
          { kind: 'LITERAL', content: 'BT' },
          { kind: 'LITERAL', content: 'HK' },
          { kind: 'LITERAL', content: 'DE' },
          { kind: 'LITERAL', content: 'CA' },
          { kind: 'LITERAL', content: 'UY' },
          { kind: 'LITERAL', content: 'EE' },
          { kind: 'LITERAL', content: 'IE' },
          { kind: 'LITERAL', content: 'IS' },
          { kind: 'LITERAL', content: 'AU' },
          { kind: 'LITERAL', content: 'NL' },
          { kind: 'LITERAL', content: 'SE' },
          { kind: 'LITERAL', content: 'CH' },
          { kind: 'LITERAL', content: 'NO' },
          { kind: 'LITERAL', content: 'LU' },
          { kind: 'LITERAL', content: 'NZ' },
          { kind: 'LITERAL', content: 'SG' },
          { kind: 'LITERAL', content: 'FI' },
          { kind: 'LITERAL', content: 'DK' },
        ],
      },
    },
    riskValue: {
      type: 'RISK_LEVEL',
      value: 'VERY_LOW',
    },
  },
];
