export const COPILOT_QUESTIONS = {
  ALERTS: 'Alerts',
  ALERTS_RELATED_TO_TRANSACTION: 'Alerts related to transaction',
  ALERTS_THAT_RESULTED_IN_SAR: 'Alerts that resulted in SAR',
  CASES: 'Cases',
  CHECKED_TRANSACTIONS: 'Checked transactions',
  CLEARED_HITS: 'Cleared hits',
  OPEN_HITS: 'Human review hits',
  CRM_INSIGHTS: 'CRM insights',
  DIRECTORS: 'Directors',
  ONTOLOGY: 'Ontology',
  KYC_SCORING: 'KYC Scoring',
  LINKED_USERS: 'Linked users',
  PAYMENT_IDENTIFIERS: 'Payment identifiers transacted with',
  REFERENCES_WORD_COUNT: 'Transaction references word count',
  RECOMMENDATION: 'Recommendation',
  SHAREHOLDERS: 'Shareholders',
  TRANSACTION_INSIGHTS: 'Transaction insights',
  TRANSACTIONS: 'Transactions',
  TRANSACTIONS_BY_RULE_ACTION: 'Transactions by rule action',
  TRANSACTIONS_BY_TYPE: 'Transactions by type',
  TRS_SCORE: 'TRS score',
  TRANSACTION_COUNT: 'Transaction count',
  MAX_TRANSACTION_AMOUNT: 'Max transaction amount',
  MIN_TRANSACTION_AMOUNT: 'Min transaction amount',
  MEDIAN_TRANSACTION_AMOUNT: 'Median transaction amount',
  TOTAL_TRANSACTION_AMOUNT: 'Total transaction amount',
  TRANSACTION_LIMIT: 'Remaining transaction limit',
  AVERAGE_TRANSACTION_AMOUNT: 'Average transaction amount',
  USER_DETAILS: 'User details',
  USERS_TRANSACTED_WITH: 'Users transacted with',
  ALERT_TRANSACTIONS: 'Alert transactions',
  USER_TRANSACTIONS: 'Transactions',
  WEBSITE: 'Website',
  CARD_MERCHANT_IDENTIFIERS: 'Card merchants transacted with',
  TRANSACTIONS_BY_COUNTRY: 'Transactions by country',
} as const

export type QuestionId =
  (typeof COPILOT_QUESTIONS)[keyof typeof COPILOT_QUESTIONS]
