export const relevanceOptionsMap = {
  CURRENT: 'Current sanctions',
  FORMER: 'Former sanctions',
  POI: 'Profile of interest',
  PEP: 'PEP',
  RCA: 'Relatives and close associates (RCA)',
  TERRORISM: 'Terrorism',
  ORGANISED_CRIME: 'Organised crime',
  MODERN_SLAVERY: 'Modern slavery',
  FINANCIAL_CRIME_AND_FRAUD: 'Financial crime and fraud',
  BRIBERY_AND_CORRUPTION: 'Bribery and corruption',
  CYBERCRIMES: 'Cybercrimes',
  OTHER_ALLEGED_OFFENCES: 'Other alleged offences',
  REPUTATIONAL_RISK_EXPOSURE: 'Reputational risk exposure',
  FINANCIAL_REGULATOR: 'Financial regulator',
  LAW_ENFORCEMENT: 'Law enforcement',
  TAX_CRIME: 'Tax crime',
  ENHANCED_COUNTRY_RISK: 'Enhanced country risk',
  ORGANISED_CRIME_JAPAN: 'Organised crime (Japan)',
  WAR_CRIMES: 'War crimes',
  CORRUPTION: 'Corruption',
  FINANCIAL_CRIME: 'Financial crime',
  TERROR: 'Terror',
  TRAFFICKING: 'Trafficking',
  CHILD_SEXUAL_EXPLOITATION: 'Child sexual exploitation',
  crime: 'Crime',
  'crime.fraud': 'Fraud',
  'crime.cyber': 'Cybercrime',
  'crime.fin': 'Financial crime',
  'crime.env': 'Environmental violations',
  'crime.theft': 'Theft',
  'crime.war': 'War crimes',
  'crime.boss': 'Criminal leadership',
  'crime.terror': 'Terrorism',
  'crime.traffick': 'Trafficking',
  'crime.traffick.drug': 'Drug trafficking',
  'crime.traffick.human': 'Human trafficking',
  poi: 'Profile of interest',
  'role.rca': 'Relatives and close associates (RCA)',
  'role.pep': 'PEP',
  'role.oligarch': 'Oligarch',
  'role.judge': 'Judge',
  'role.diplo': 'Diplomat',
}

export const adverseMediaCategoryMap: Record<string, string> = {
  REPUTATIONAL_RISK_EXPOSURE: 'Reputational Risk Exposure',
  CYBERCRIMES: 'Cybercrime',
  FINANCIAL_CRIME_AND_FRAUD: 'Financial Crime and Fraud',
  BRIBERY_AND_CORRUPTION: 'Bribery and Corruption',
  TERRORISM: 'Terrorism',
  ORGANISED_CRIME: 'Organised Crime',
  MODERN_SLAVERY: 'Modern Slavery',
  OTHER_ALLEGED_OFFENCES: 'Other alleged offences',
  // DOW JONES
  ENHANCED_COUNTRY_RISK: 'Enhanced country risk',
  ORGANISED_CRIME_JAPAN: 'Organised crime (Japan)',
  WAR_CRIMES: 'War crimes',
  CORRUPTION: 'Corruption',
  FINANCIAL_CRIME: 'Financial crime',
  TERROR: 'Terror',
  TRAFFICKING: 'Trafficking',
  TAX_CRIME: 'Tax crime',
  CHILD_SEXUAL_EXPLOITATION: 'Child sexual exploitation',
}
