export const relevanceOptionsMap = {
  CURRENT: 'Current sanctions',
  FORMER: 'Former sanctions',
  POI: 'Profile of interest',
  PEP: 'PEP',
  RCA: 'Relatives and close associates (RCA)',
  TERRORISM: 'Terrorism',
  ORGANISED_CRIME: 'Organised crime',
  MODERN_SLAVERY: 'Modern slavery',
  FINANCIAL_CRIME_AND_FRAUD: 'Financial crime and fraud',
  BRIBERY_AND_CORRUPTION: 'Bribery and corruption',
  CYBERCRIMES: 'Cybercrimes',
  OTHER_ALLEGED_OFFENCES: 'Other alleged offences',
  REPUTATIONAL_RISK_EXPOSURE: 'Reputational risk exposure',
  FINANCIAL_REGULATOR: 'Financial regulator',
  LAW_ENFORCEMENT: 'Law enforcement',
  TAX_CRIME: 'Tax crime',
  ENHANCED_COUNTRY_RISK: 'Enhanced country risk',
  ORGANISED_CRIME_JAPAN: 'Organised crime (Japan)',
  WAR_CRIMES: 'War crimes',
  CORRUPTION: 'Corruption',
  FINANCIAL_CRIME: 'Financial crime',
  TERROR: 'Terror',
  TRAFFICKING: 'Trafficking',
  CHILD_SEXUAL_EXPLOITATION: 'Child sexual exploitation',
}

export const adverseMediaCategoryMap: Record<string, string> = {
  REPUTATIONAL_RISK_EXPOSURE: 'Reputational Risk Exposure',
  CYBERCRIMES: 'Cybercrime',
  FINANCIAL_CRIME_AND_FRAUD: 'Financial Crime and Fraud',
  BRIBERY_AND_CORRUPTION: 'Bribery and Corruption',
  TERRORISM: 'Terrorism',
  ORGANISED_CRIME: 'Organised Crime',
  MODERN_SLAVERY: 'Modern Slavery',
  OTHER_ALLEGED_OFFENCES: 'Other alleged offences',
  // DOW JONES
  ENHANCED_COUNTRY_RISK: 'Enhanced country risk',
  ORGANISED_CRIME_JAPAN: 'Organised crime (Japan)',
  WAR_CRIMES: 'War crimes',
  CORRUPTION: 'Corruption',
  FINANCIAL_CRIME: 'Financial crime',
  TERROR: 'Terror',
  TRAFFICKING: 'Trafficking',
  TAX_CRIME: 'Tax crime',
  CHILD_SEXUAL_EXPLOITATION: 'Child sexual exploitation',
}
