export const currencies: { value: string; label: string }[] = [
  { value: 'ADA', label: 'ADA (Cardano)' },
  { value: 'AED', label: 'AED (United Arab Emirates Dirham)' },
  { value: 'AFN', label: 'AFN (Afghan afghani)' },
  { value: 'ALGO', label: 'ALGO (Algorand)' },
  { value: 'ALL', label: 'ALL (Albanian lek)' },
  { value: 'AMD', label: 'AMD (Armenian dram)' },
  { value: 'ANG', label: 'ANG (Netherlands Antillean Guilder)' },
  { value: 'AOA', label: 'AOA (Angolan kwanza)' },
  { value: 'ARS', label: 'ARS (Argentine peso)' },
  { value: 'ATOM', label: 'ATOM (Atomic Coin)' },
  { value: 'AUD', label: 'AUD (Australian dollar)' },
  { value: 'AVAX', label: 'AVAX (Avalanche)' },
  { value: 'AWG', label: 'AWG (Aruban florin)' },
  { value: 'AZN', label: 'AZN (Azerbaijani manat)' },
  { value: 'BAM', label: 'BAM (Bosnia-Herzegovina Convertible Mark)' },
  { value: 'BBD', label: 'BBD (Bajan dollar)' },
  { value: 'BCH', label: 'BCH (Bitcoin Cash)' },
  { value: 'BDT', label: 'BDT (Bangladeshi taka)' },
  { value: 'BGN', label: 'BGN (Bulgarian lev)' },
  { value: 'BHD', label: 'BHD (Bahraini dinar)' },
  { value: 'BIF', label: 'BIF (Burundian Franc)' },
  { value: 'BMD', label: 'BMD (Bermudan dollar)' },
  { value: 'BNB', label: 'BNB (Binance Coin)' },
  { value: 'BND', label: 'BND (Brunei dollar)' },
  { value: 'BOB', label: 'BOB (Bolivian boliviano)' },
  { value: 'BRB', label: 'BRB (Brazilian real)' },
  { value: 'BSD', label: 'BSD (Bahamian dollar)' },
  { value: 'BTC', label: 'BTC (Bitcoin)' },
  { value: 'BTN', label: 'BTN (Bhutan currency)' },
  { value: 'BUSD', label: 'BUSD (Binance USD)' },
  { value: 'BWP', label: 'BWP (Botswanan Pula)' },
  { value: 'BYN', label: 'BYN (New Belarusian Ruble)' },
  { value: 'BYR', label: 'BYR (Belarusian Ruble)' },
  { value: 'BZD', label: 'BZD (Belize dollar)' },
  { value: 'CAD', label: 'CAD (Canadian dollar)' },
  { value: 'CDF', label: 'CDF (Congolese franc)' },
  { value: 'CHF', label: 'CHF (Swiss franc)' },
  { value: 'CHZ', label: 'CHZ (Chiliz)' },
  { value: 'CLF', label: 'CLF (Chilean Unit of Account (UF))' },
  { value: 'CLP', label: 'CLP (Chilean peso)' },
  { value: 'CNY', label: 'CNY (Chinese Yuan)' },
  { value: 'COP', label: 'COP (Colombian peso)' },
  { value: 'CRC', label: 'CRC (Costa Rican Colón)' },
  { value: 'CRO', label: 'CRO (Crypto.com Chain Token)' },
  { value: 'CUC', label: 'CUC (Cuban peso)' },
  { value: 'CUP', label: 'CUP (Cuban Peso)' },
  { value: 'CVE', label: 'CVE (Cape Verdean escudo)' },
  { value: 'CZK', label: 'CZK (Czech koruna)' },
  { value: 'DAI', label: 'DAI (Dai)' },
  { value: 'DIF', label: 'DIF (Djiboutian franc)' },
  { value: 'DKK', label: 'DKK (Danish krone)' },
  { value: 'DOGE', label: 'DOGE (Dogecoin)' },
  { value: 'DOP', label: 'DOP (Dominican peso)' },
  { value: 'DOT', label: 'DOT (Dotcoin)' },
  { value: 'DZD', label: 'DZD (Algerian dinar)' },
  { value: 'EGLD', label: 'EGLD (Elrond)' },
  { value: 'EGP', label: 'EGP (Egyptian pound)' },
  { value: 'ENJ', label: 'ENJ (Enjin Coin)' },
  { value: 'ERN', label: 'ERN (Eritrean nakfa)' },
  { value: 'ETB', label: 'ETB (Ethiopian birr)' },
  { value: 'ETC', label: 'ETC (Ethereum Classic)' },
  { value: 'ETH', label: 'ETH (Ether)' },
  { value: 'EUR', label: 'EUR (Euro)' },
  { value: 'FIL', label: 'FIL (FileCoin)' },
  { value: 'FJD', label: 'FJD (Fijian dollar)' },
  { value: 'FKP', label: 'FKP (Falkland Islands pound)' },
  { value: 'FTT', label: 'FTT (FarmaTrust)' },
  { value: 'GBP', label: 'GBP (Pound sterling)' },
  { value: 'GEL', label: 'GEL (Georgian lari)' },
  { value: 'GGP', label: 'GGP (GGPro)' },
  { value: 'GHS', label: 'GHS (Ghanaian cedi)' },
  { value: 'GIP', label: 'GIP (Gibraltar pound)' },
  { value: 'GMD', label: 'GMD (Gambian dalasi)' },
  { value: 'GNF', label: 'GNF (Guinean franc)' },
  { value: 'GRT', label: 'GRT (Golden Ratio Token)' },
  { value: 'GTQ', label: 'GTQ (Guatemalan quetzal)' },
  { value: 'GYD', label: 'GYD (Guyanaese Dollar)' },
  { value: 'HKD', label: 'HKD (Hong Kong dollar)' },
  { value: 'HNL', label: 'HNL (Honduran lempira)' },
  { value: 'HRK', label: 'HRK (Croatian kuna)' },
  { value: 'HTG', label: 'HTG (Haitian gourde)' },
  { value: 'HUF', label: 'HUF (Hungarian forint)' },
  { value: 'ICP', label: 'ICP (Internet Computer)' },
  { value: 'IDR', label: 'IDR (Indonesian rupiah)' },
  { value: 'ILS', label: 'ILS (Israeli New Shekel)' },
  { value: 'IMP', label: 'IMP (CoinIMP)' },
  { value: 'INJ', label: 'INJ (Injective)' },
  { value: 'INR', label: 'INR (Indian rupee)' },
  { value: 'IQD', label: 'IQD (Iraqi dinar)' },
  { value: 'IRR', label: 'IRR (Iranian rial)' },
  { value: 'ISK', label: 'ISK (Icelandic króna)' },
  { value: 'JEP', label: 'JEP (Jersey Pound)' },
  { value: 'JMD', label: 'JMD (Jamaican dollar)' },
  { value: 'JOD', label: 'JOD (Jordanian dinar)' },
  { value: 'JPY', label: 'JPY (Japanese yen)' },
  { value: 'KES', label: 'KES (Kenyan shilling)' },
  { value: 'KGS', label: 'KGS (Kyrgystani Som)' },
  { value: 'KHR', label: 'KHR (Cambodian riel)' },
  { value: 'KMF', label: 'KMF (Comorian franc)' },
  { value: 'KPW', label: 'KPW (North Korean won)' },
  { value: 'KRW', label: 'KRW (South Korean won)' },
  { value: 'KSM', label: 'KSM (Kusama)' },
  { value: 'KWD', label: 'KWD (Kuwaiti dinar)' },
  { value: 'KYD', label: 'KYD (Cayman Islands dollar)' },
  { value: 'KZT', label: 'KZT (Kazakhstani tenge)' },
  { value: 'LAK', label: 'LAK (Laotian Kip)' },
  { value: 'LBP', label: 'LBP (Lebanese pound)' },
  { value: 'LINK', label: 'LINK (ChainLink)' },
  { value: 'LKR', label: 'LKR (Sri Lankan rupee)' },
  { value: 'LRD', label: 'LRD (Liberian dollar)' },
  { value: 'LSR', label: 'LSR (Lesotho loti)' },
  { value: 'LTC', label: 'LTC (Litecoin)' },
  { value: 'LTL', label: 'LTL (Lithuanian litas)' },
  { value: 'LVL', label: 'LVL (Latvian lats)' },
  { value: 'LYD', label: 'LYD (Libyan dinar)' },
  { value: 'MAD', label: 'MAD (Moroccan dirham)' },
  { value: 'MATIC', label: 'MATIC (Polygon)' },
  { value: 'MDL', label: 'MDL (Moldovan leu)' },
  { value: 'MGA', label: 'MGA (Malagasy ariary)' },
  { value: 'MKD', label: 'MKD (Macedonian denar)' },
  { value: 'MMK', label: 'MMK (Myanmar Kyat)' },
  { value: 'MNT', label: 'MNT (Mongolian tugrik)' },
  { value: 'MOP', label: 'MOP (Macanese pataca)' },
  { value: 'MRO', label: 'MRO (Mauritanian ouguiya)' },
  { value: 'MUR', label: 'MUR (Mauritian rupee)' },
  { value: 'MVR', label: 'MVR (Maldivian rufiyaa)' },
  { value: 'MWK', label: 'MWK (Malawian kwacha)' },
  { value: 'MXN', label: 'MXN (Mexican peso)' },
  { value: 'MYR', label: 'MYR (Malaysian ringgit)' },
  { value: 'MZN', label: 'MZN (Mozambican Metical)' },
  { value: 'NAD', label: 'NAD (Namibian dollar)' },
  { value: 'NGN', label: 'NGN (Nigerian naira)' },
  { value: 'NIO', label: 'NIO (Nicaraguan córdoba)' },
  { value: 'NOK', label: 'NOK (Norwegian krone)' },
  { value: 'NPR', label: 'NPR (Nepalese rupee)' },
  { value: 'NZD', label: 'NZD (New Zealand dollar)' },
  { value: 'OMR', label: 'OMR (Omani rial)' },
  { value: 'ONE', label: 'ONE (Menlo One)' },
  { value: 'PAB', label: 'PAB (Panamanian balboa)' },
  { value: 'PEN', label: 'PEN (Sol)' },
  { value: 'PGK', label: 'PGK (Papua New Guinean kina)' },
  { value: 'PHP', label: 'PHP (Philippine peso)' },
  { value: 'PKR', label: 'PKR (Pakistani rupee)' },
  { value: 'PLN', label: 'PLN (Poland złoty)' },
  { value: 'PYG', label: 'PYG (Paraguayan guarani)' },
  { value: 'QAR', label: 'QAR (Qatari Rial)' },
  { value: 'RON', label: 'RON (Romanian leu)' },
  { value: 'RSD', label: 'RSD (Serbian dinar)' },
  { value: 'RUB', label: 'RUB (Russian ruble)' },
  { value: 'RWF', label: 'RWF (Rwandan Franc)' },
  { value: 'SAR', label: 'SAR (Saudi riyal)' },
  { value: 'SBD', label: 'SBD (Solomon Islands dollar)' },
  { value: 'SRC', label: 'SRC (Seychellois rupee)' },
  { value: 'SDG', label: 'SDG (Sudanese pound)' },
  { value: 'SEK', label: 'SEK (Swedish krona)' },
  { value: 'SGD', label: 'SGD (Singapore dollar)' },
  { value: 'SHIB', label: 'SHIB (Shiba Inu)' },
  { value: 'SHP', label: 'SHP (Saint Helena pound)' },
  { value: 'SLL', label: 'SLL (Sierra Leonean leone)' },
  { value: 'SOL', label: 'SOL (Sola)' },
  { value: 'SOS', label: 'SOS (Somali shilling)' },
  { value: 'SRD', label: 'SRD (Surinamese dollar)' },
  { value: 'STD', label: 'STD (São Tomé and Príncipe Dobra (pre-2018))' },
  { value: 'SVC', label: 'SVC (Salvadoran Colón)' },
  { value: 'SYP', label: 'SYP (Syrian pound)' },
  { value: 'SZL', label: 'SZL (Swazi lilangeni)' },
  { value: 'THB', label: 'THB (Thai baht)' },
  { value: 'THETA', label: 'THETA (Theta)' },
  { value: 'TJS', label: 'TJS (Tajikistani somoni)' },
  { value: 'TMT', label: 'TMT (Turkmenistani manat)' },
  { value: 'TND', label: 'TND (Tunisian dinar)' },
  { value: 'TOP', label: "TOP (Tongan Pa'anga)" },
  { value: 'TRX', label: 'TRX (TRON)' },
  { value: 'TRY', label: 'TRY (Turkish lira)' },
  { value: 'TTD', label: 'TTD (Trinidad & Tobago Dollar)' },
  { value: 'TWD', label: 'TWD (New Taiwan dollar)' },
  { value: 'TZS', label: 'TZS (Tanzanian shilling)' },
  { value: 'UAH', label: 'UAH (Ukrainian hryvnia)' },
  { value: 'UGX', label: 'UGX (Ugandan shilling)' },
  { value: 'UNI', label: 'UNI (Universe)' },
  { value: 'USD', label: 'USD (United States dollar)' },
  { value: 'USDC', label: 'USDC (USD Coin)' },
  { value: 'USDT', label: 'USDT (Tether)' },
  { value: 'UYU', label: 'UYU (Uruguayan peso)' },
  { value: 'UZS', label: 'UZS (Uzbekistani som)' },
  { value: 'VEF', label: 'VEF (Sovereign Bolivar)' },
  { value: 'VET', label: 'VET (Vechain)' },
  { value: 'VND', label: 'VND (Vietnamese dong)' },
  { value: 'VUV', label: 'VUV (Vanuatu vatu)' },
  { value: 'WBTC', label: 'WBTC (Wrapped Bitcoin)' },
  { value: 'WST', label: 'WST (Samoan tala)' },
  { value: 'XAF', label: 'XAF (Central African CFA franc)' },
  { value: 'XAG', label: 'XAG (Silver Ounce)' },
  { value: 'XAU', label: 'XAU (XauCoin)' },
  { value: 'XCD', label: 'XCD (East Cari,bbean dollar)' },
  { value: 'XDR', label: 'XDR (Special Drawing Rights)' },
  { value: 'XLM', label: 'XLM (Stellar)' },
  { value: 'XMR', label: 'XMR (Monero)' },
  { value: 'XOF', label: 'XOF (West African CFA franc)' },
  { value: 'XPF', label: 'XPF (CFP franc)' },
  { value: 'XRP', label: 'XRP (XRP)' },
  { value: 'YER', label: 'YER (Yemeni rial)' },
  { value: 'ZAR', label: 'ZAR (South African rand)' },
  { value: 'ZMK', label: 'ZMK (Zambian kwacha)' },
  { value: 'ZMW', label: 'ZMW (Zambian Kwacha)' },
  { value: 'ZWL', label: 'ZWL (Zimbabwean Dollar' },
];
