export enum RuleChecksForField {
  FirstTransaction = '1st transaction',
  TransactionAmount = 'Transaction amount',
  NumberOfTransactions = 'No. of transactions',
  UserAccountStatus = 'User account status',
  Time = 'Time',
  TransactionCurrency = 'Transaction currency',
  NumberOfUsers = 'No. of users',
  TransactionCountry = 'Transaction country',
  TransactionPaymentMethodCount = 'Transaction payment method count',
  TransactionPaymentMethodIssuedCountry = 'Transaction payment method issued country',
  UsersIPAddress = "User's IP address",
  TransactionPaymentIdentifier = 'Transaction payment identifier',
  UserCardFingerprintID = 'User card fingerprint ID',
  UserPaymentIdentifier = 'User payment identifier',
  Username = 'Username',
  BothPartiesUsername = 'Both parties username',
  TransactionState = 'Transaction state',
  CounterpartyCountryCount = 'Counterparty country count',
  TransactionPaymentDetails = 'Transaction payment details',
  UserDetails = 'User details',
  TransactionType = 'Transaction type',
  EntityName = 'Entity name',
  UsersBankName = 'User’s bank name',
  CounterpartyUsername = 'Counterparty username',
  CounterpartyBankName = 'Counterparty bank name',
  UsersYearOfBirth = 'User’s Y.O.B',
  UsersIndustry = 'User’s industry',
  UsersAddress = 'User’s address',
  TransactionDetails = 'Transaction details',
  Keywords = 'Keywords',
  accountHolderName = 'Account holder name',
  ScreeningPaymentDetails = 'Screening payment details',
}

export enum RuleTypeField {
  NewActivity = 'New activity',
  AnomalyDetection = 'Anomaly detection',
  RiskExposure = 'Risk exposure',
  Diversity = 'Diversity',
  PatternRecognition = 'Pattern recognition',
  Velocity = 'Velocity',
  TransactionDenstiy = 'Transaction density',
  VelocityComparison = 'Velocity comparison',
  Volume = 'Volume',
  VolumeComparison = 'Volume comparison',
  Blacklist = 'Blacklist',
  MerchantMonitoring = 'Merchant monitoring',
  Screening = 'Screening',
}

export enum RuleNature {
  AML = 'AML',
  FRAUD = 'FRAUD',
  SCREENING = 'SCREENING',
}

export enum RuleTypology {
  UnusualBehaviour = 'Unusual behaviour',
  MoneyMules = 'Money mules',
  AccountTakeoverFraud = 'Account takeover fraud',
  AcquiringFraud = 'Acquiring fraud',
  IssuingFraud = 'Issuing fraud',
  CardFraud = 'Card fraud',
  Structuring = 'Structuring',
  HiddenUnusualRelationships = 'Hidden/unusual relationships',
  Scams = 'Scams (romance, Nigerian Prince, inheritance and etc.)',
  TerroristFinancing = 'Terrorist financing',
  Layering = 'Layering',
  InternalBlacklists = 'Internal blacklists',
  ScreeningHits = 'Screening hits',
  HighRiskTransactions = 'High risk transactions',
}
