/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Tag } from './tag'

/**
 * Model for standardized address
 */
export class Address {
  /**
   * Address lines of the user\'s residence address
   */
  'addressLines': Array<any>
  /**
   * Post code of the user\'s residence address
   */
  'postcode': string
  /**
   * City of the user\'s residence address
   */
  'city': string
  /**
   * State of the user\'s residence address
   */
  'state'?: string
  /**
   * User\'s country of residence
   */
  'country': string
  /**
   * Additional information that can be added via tags
   */
  'tags'?: Array<Tag>

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'addressLines',
      baseName: 'addressLines',
      type: 'Array<any>',
    },
    {
      name: 'postcode',
      baseName: 'postcode',
      type: 'string',
    },
    {
      name: 'city',
      baseName: 'city',
      type: 'string',
    },
    {
      name: 'state',
      baseName: 'state',
      type: 'string',
    },
    {
      name: 'country',
      baseName: 'country',
      type: 'string',
    },
    {
      name: 'tags',
      baseName: 'tags',
      type: 'Array<Tag>',
    },
  ]

  static getAttributeTypeMap() {
    return Address.attributeTypeMap
  }
}
