/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class Amount {
  /**
   * Numerical value of the transaction
   */
  'amountValue': number
  /**
   * Currency of the transaction
   */
  'amountCurrency': string

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'amountValue',
      baseName: 'amountValue',
      type: 'number',
    },
    {
      name: 'amountCurrency',
      baseName: 'amountCurrency',
      type: 'string',
    },
  ]

  static getAttributeTypeMap() {
    return Amount.attributeTypeMap
  }
}
