/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LegalEntity } from './legalEntity'
import { Person } from './person'
import { Tag } from './tag'

export class Business {
  /**
   * Unique user ID for the user
   */
  'userId': string
  'legalEntity': LegalEntity
  /**
   * Shareholders (beneficiaries) of the company that hold at least 25% ownership. Can be another company or an individual
   */
  'shareHolders'?: Array<Person>
  /**
   * Director(s) of the company. Must be at least one
   */
  'directors'?: Array<Person>
  /**
   * Additional information that can be added via tags
   */
  'tags'?: Array<Tag>

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'userId',
      baseName: 'userId',
      type: 'string',
    },
    {
      name: 'legalEntity',
      baseName: 'legalEntity',
      type: 'LegalEntity',
    },
    {
      name: 'shareHolders',
      baseName: 'shareHolders',
      type: 'Array<Person>',
    },
    {
      name: 'directors',
      baseName: 'directors',
      type: 'Array<Person>',
    },
    {
      name: 'tags',
      baseName: 'tags',
      type: 'Array<Tag>',
    },
  ]

  static getAttributeTypeMap() {
    return Business.attributeTypeMap
  }
}
