/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class ExecutedRulesResult {
  /**
   * Unique rule identifier
   */
  'ruleId': string
  /**
   * Name of the rule
   */
  'ruleName': string
  /**
   * Description of the rule
   */
  'ruleDescription': string
  /**
   * The specific action a rule is configured to take if it\'s hit such as flag (passive monitoring), block transaction, terminate user, whitelist etc.
   */
  'ruleAction': string
  /**
   * Whether a rule was hit or not. When a rule is hit, it takes the pre-configured action on a transaction and/or user.
   */
  'ruleHit': boolean

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'ruleId',
      baseName: 'ruleId',
      type: 'string',
    },
    {
      name: 'ruleName',
      baseName: 'ruleName',
      type: 'string',
    },
    {
      name: 'ruleDescription',
      baseName: 'ruleDescription',
      type: 'string',
    },
    {
      name: 'ruleAction',
      baseName: 'ruleAction',
      type: 'string',
    },
    {
      name: 'ruleHit',
      baseName: 'ruleHit',
      type: 'boolean',
    },
  ]

  static getAttributeTypeMap() {
    return ExecutedRulesResult.attributeTypeMap
  }
}
