/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CompanyFinancialDetails } from './companyFinancialDetails'
import { CompanyGeneralDetails } from './companyGeneralDetails'
import { CompanyRegistrationDetails } from './companyRegistrationDetails'
import { ContactDetails } from './contactDetails'

export class LegalEntity {
  'companyGeneralDetails': CompanyGeneralDetails
  'companyFinancialDetails'?: CompanyFinancialDetails
  'companyRegistrationDetails'?: CompanyRegistrationDetails
  /**
   * Reason for opening the account at financial institution
   */
  'reasonForAccountOpening'?: Array<string>
  'contactDetails'?: ContactDetails

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'companyGeneralDetails',
      baseName: 'companyGeneralDetails',
      type: 'CompanyGeneralDetails',
    },
    {
      name: 'companyFinancialDetails',
      baseName: 'companyFinancialDetails',
      type: 'CompanyFinancialDetails',
    },
    {
      name: 'companyRegistrationDetails',
      baseName: 'companyRegistrationDetails',
      type: 'CompanyRegistrationDetails',
    },
    {
      name: 'reasonForAccountOpening',
      baseName: 'reasonForAccountOpening',
      type: 'Array<string>',
    },
    {
      name: 'contactDetails',
      baseName: 'contactDetails',
      type: 'ContactDetails',
    },
  ]

  static getAttributeTypeMap() {
    return LegalEntity.attributeTypeMap
  }
}
