/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Model for results from Risk Scoring
 */
export class RiskScoringResult {
  /**
   * KYC risk score quantified as \"safety score\"
   */
  'baseSafetyScore': number
  /**
   * Action risk score quantified as \"safety score\"
   */
  'actionSafetyScore': number
  /**
   * Dynamic risk score quantified as \"safety score\"
   */
  'dynamicSafetyScore'?: number

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'baseSafetyScore',
      baseName: 'baseSafetyScore',
      type: 'number',
    },
    {
      name: 'actionSafetyScore',
      baseName: 'actionSafetyScore',
      type: 'number',
    },
    {
      name: 'dynamicSafetyScore',
      baseName: 'dynamicSafetyScore',
      type: 'number',
    },
  ]

  static getAttributeTypeMap() {
    return RiskScoringResult.attributeTypeMap
  }
}
