/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BankDetails } from './bankDetails'
import { CardDetails } from './cardDetails'
import { DeviceData } from './deviceData'
import { Tag } from './tag'
import { TransactionAmountDetails } from './transactionAmountDetails'

/**
 * Model for transaction payload
 */
export class Transaction {
  /**
   * Unique transaction identifier
   */
  'transactionId'?: string
  'timestamp': number
  'senderUserId'?: string
  'receiverUserId'?: string
  'sendingAmountDetails': TransactionAmountDetails
  'receivingAmountDetails': TransactionAmountDetails
  'senderPaymentDetails'?: CardDetails | BankDetails | null
  'receiverPaymentDetails'?: CardDetails | BankDetails | null
  /**
   * Type of produce being used by the consumer (ex wallets, payments etc)
   */
  'productType'?: string
  /**
   * Whether a promotion code was used or not the transaction
   */
  'promotionCodeUsed'?: boolean
  /**
   * Reference field for the transaction indicating the purpose of the transaction etc.
   */
  'reference'?: string
  'deviceData'?: DeviceData
  /**
   * Additional information that can be added via tags
   */
  'tags'?: Array<Tag>

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'transactionId',
      baseName: 'transactionId',
      type: 'string',
    },
    {
      name: 'timestamp',
      baseName: 'timestamp',
      type: 'number',
    },
    {
      name: 'senderUserId',
      baseName: 'senderUserId',
      type: 'string',
    },
    {
      name: 'receiverUserId',
      baseName: 'receiverUserId',
      type: 'string',
    },
    {
      name: 'sendingAmountDetails',
      baseName: 'sendingAmountDetails',
      type: 'TransactionAmountDetails',
    },
    {
      name: 'receivingAmountDetails',
      baseName: 'receivingAmountDetails',
      type: 'TransactionAmountDetails',
    },
    {
      name: 'senderPaymentDetails',
      baseName: 'senderPaymentDetails',
      type: 'CardDetails | BankDetails',
    },
    {
      name: 'receiverPaymentDetails',
      baseName: 'receiverPaymentDetails',
      type: 'CardDetails | BankDetails',
    },
    {
      name: 'productType',
      baseName: 'productType',
      type: 'string',
    },
    {
      name: 'promotionCodeUsed',
      baseName: 'promotionCodeUsed',
      type: 'boolean',
    },
    {
      name: 'reference',
      baseName: 'reference',
      type: 'string',
    },
    {
      name: 'deviceData',
      baseName: 'deviceData',
      type: 'DeviceData',
    },
    {
      name: 'tags',
      baseName: 'tags',
      type: 'Array<Tag>',
    },
  ]

  static getAttributeTypeMap() {
    return Transaction.attributeTypeMap
  }
}
