/**
 * Flagright API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class UPIDetails {
  'method': string
  'upiID': string
  'bankProvider'?: string
  'interfaceProvider'?: string

  static discriminator: string | undefined = undefined

  static attributeTypeMap: Array<{
    name: string
    baseName: string
    type: string
  }> = [
    {
      name: 'method',
      baseName: 'method',
      type: 'string',
    },
    {
      name: 'upiID',
      baseName: 'upiID',
      type: 'string',
    },
    {
      name: 'bankProvider',
      baseName: 'bankProvider',
      type: 'string',
    },
    {
      name: 'interfaceProvider',
      baseName: 'interfaceProvider',
      type: 'string',
    },
  ]

  static getAttributeTypeMap() {
    return UPIDetails.attributeTypeMap
  }
}
