/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Account {
  'user_id': string;
  'created_at': string;
  'updated_at': string;
  'email': string;
  'email_verified': boolean;
  'name'?: string;
  'nickname'?: string;
  'picture'?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'user_id',
      baseName: 'user_id',
      type: 'string',
      format: '',
    },
    {
      name: 'created_at',
      baseName: 'created_at',
      type: 'string',
      format: '',
    },
    {
      name: 'updated_at',
      baseName: 'updated_at',
      type: 'string',
      format: '',
    },
    {
      name: 'email',
      baseName: 'email',
      type: 'string',
      format: '',
    },
    {
      name: 'email_verified',
      baseName: 'email_verified',
      type: 'boolean',
      format: '',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
      format: '',
    },
    {
      name: 'nickname',
      baseName: 'nickname',
      type: 'string',
      format: '',
    },
    {
      name: 'picture',
      baseName: 'picture',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return Account.attributeTypeMap;
  }

  public constructor() {}
}
