/* tslint:disable */
/* eslint-disable */
/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { Business, BusinessFromJSON, BusinessFromJSONTyped, BusinessToJSON } from './Business';

/**
 *
 * @export
 * @interface BusinessUsersListResponse
 */
export interface BusinessUsersListResponse {
  /**
   *
   * @type {number}
   * @memberof BusinessUsersListResponse
   */
  total: number;
  /**
   *
   * @type {Array<Business>}
   * @memberof BusinessUsersListResponse
   */
  data: Array<Business>;
}

export function BusinessUsersListResponseFromJSON(json: any): BusinessUsersListResponse {
  return BusinessUsersListResponseFromJSONTyped(json, false);
}

export function BusinessUsersListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BusinessUsersListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    total: json['total'],
    data: (json['data'] as Array<any>).map(BusinessFromJSON),
  };
}

export function BusinessUsersListResponseToJSON(value?: BusinessUsersListResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    total: value.total,
    data: (value.data as Array<any>).map(BusinessToJSON),
  };
}
