/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Tag } from './Tag';
import { HttpFile } from '../http/http';

/**
 * Model for business user company registration details
 */
export class CompanyRegistrationDetails {
  /**
   * Commercial registry registration number for the company in its registration country
   */
  'registrationIdentifier': string;
  /**
   * Country of registration for the company
   */
  'registrationCountry': string;
  /**
   * Additional information that can be added via tags
   */
  'tag'?: Array<Tag>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'registrationIdentifier',
      baseName: 'registrationIdentifier',
      type: 'string',
      format: '',
    },
    {
      name: 'registrationCountry',
      baseName: 'registrationCountry',
      type: 'string',
      format: '',
    },
    {
      name: 'tag',
      baseName: 'tag',
      type: 'Array<Tag>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return CompanyRegistrationDetails.attributeTypeMap;
  }

  public constructor() {}
}
