/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { User } from './User';
import { HttpFile } from '../http/http';

export class ConsumerUsersListResponse {
  'total': number;
  'data': Array<User>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'total',
      baseName: 'total',
      type: 'number',
      format: '',
    },
    {
      name: 'data',
      baseName: 'data',
      type: 'Array<User>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return ConsumerUsersListResponse.attributeTypeMap;
  }

  public constructor() {}
}
