/* tslint:disable */
/* eslint-disable */
/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { User, UserFromJSON, UserFromJSONTyped, UserToJSON } from './User';

/**
 *
 * @export
 * @interface ConsumerUsersListResponse
 */
export interface ConsumerUsersListResponse {
  /**
   *
   * @type {number}
   * @memberof ConsumerUsersListResponse
   */
  total: number;
  /**
   *
   * @type {Array<User>}
   * @memberof ConsumerUsersListResponse
   */
  data: Array<User>;
}

export function ConsumerUsersListResponseFromJSON(json: any): ConsumerUsersListResponse {
  return ConsumerUsersListResponseFromJSONTyped(json, false);
}

export function ConsumerUsersListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ConsumerUsersListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    total: json['total'],
    data: (json['data'] as Array<any>).map(UserFromJSON),
  };
}

export function ConsumerUsersListResponseToJSON(value?: ConsumerUsersListResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    total: value.total,
    data: (value.data as Array<any>).map(UserToJSON),
  };
}
