/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address2 } from './Address2';
import { HttpFile } from '../http/http';

export class ContactDetails1 {
  /**
   * Email addresses of the contacts for a given business customer
   */
  'emailIds'?: Array<string>;
  /**
   * Phone numbers to contact a given business customer
   */
  'contactNumbers'?: Array<string>;
  /**
   * Fax numbers to contact a business customer
   */
  'faxNumbers'?: Array<string>;
  /**
   * Website of the company
   */
  'websites'?: Array<string>;
  /**
   * Address(es) of the company
   */
  'addresses'?: Array<Address2>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'emailIds',
      baseName: 'emailIds',
      type: 'Array<string>',
      format: '',
    },
    {
      name: 'contactNumbers',
      baseName: 'contactNumbers',
      type: 'Array<string>',
      format: '',
    },
    {
      name: 'faxNumbers',
      baseName: 'faxNumbers',
      type: 'Array<string>',
      format: '',
    },
    {
      name: 'websites',
      baseName: 'websites',
      type: 'Array<string>',
      format: '',
    },
    {
      name: 'addresses',
      baseName: 'addresses',
      type: 'Array<Address2>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return ContactDetails1.attributeTypeMap;
  }

  public constructor() {}
}
