/* tslint:disable */
/* eslint-disable */
/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ExecutedRulesResult
 */
export interface ExecutedRulesResult {
  /**
   * Unique rule identifier
   * @type {string}
   * @memberof ExecutedRulesResult
   */
  ruleId: string;
  /**
   * Name of the rule
   * @type {string}
   * @memberof ExecutedRulesResult
   */
  ruleName: string;
  /**
   * Description of the rule
   * @type {string}
   * @memberof ExecutedRulesResult
   */
  ruleDescription: string;
  /**
   * The specific action a rule is configured to take if it's hit such as flag (passive monitoring), block transaction, terminate user, whitelist etc.
   * @type {string}
   * @memberof ExecutedRulesResult
   */
  ruleAction: string;
  /**
   * Whether a rule was hit or not. When a rule is hit, it takes the pre-configured action on a transaction and/or user.
   * @type {boolean}
   * @memberof ExecutedRulesResult
   */
  ruleHit: boolean;
}

export function ExecutedRulesResultFromJSON(json: any): ExecutedRulesResult {
  return ExecutedRulesResultFromJSONTyped(json, false);
}

export function ExecutedRulesResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ExecutedRulesResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ruleId: json['ruleId'],
    ruleName: json['ruleName'],
    ruleDescription: json['ruleDescription'],
    ruleAction: json['ruleAction'],
    ruleHit: json['ruleHit'],
  };
}

export function ExecutedRulesResultToJSON(value?: ExecutedRulesResult | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ruleId: value.ruleId,
    ruleName: value.ruleName,
    ruleDescription: value.ruleDescription,
    ruleAction: value.ruleAction,
    ruleHit: value.ruleHit,
  };
}
