/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ExecutedRulesResult {
  /**
   * Unique rule identifier
   */
  'ruleId': string;
  /**
   * Name of the rule
   */
  'ruleName': string;
  /**
   * Description of the rule
   */
  'ruleDescription': string;
  /**
   * The specific action a rule is configured to take if it's hit such as flag (passive monitoring), block transaction, terminate user, whitelist etc.
   */
  'ruleAction': string;
  /**
   * Whether a rule was hit or not. When a rule is hit, it takes the pre-configured action on a transaction and/or user.
   */
  'ruleHit': boolean;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'ruleId',
      baseName: 'ruleId',
      type: 'string',
      format: '',
    },
    {
      name: 'ruleName',
      baseName: 'ruleName',
      type: 'string',
      format: '',
    },
    {
      name: 'ruleDescription',
      baseName: 'ruleDescription',
      type: 'string',
      format: '',
    },
    {
      name: 'ruleAction',
      baseName: 'ruleAction',
      type: 'string',
      format: '',
    },
    {
      name: 'ruleHit',
      baseName: 'ruleHit',
      type: 'boolean',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return ExecutedRulesResult.attributeTypeMap;
  }

  public constructor() {}
}
