/* tslint:disable */
/* eslint-disable */
/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  RuleFailureException,
  RuleFailureExceptionFromJSON,
  RuleFailureExceptionFromJSONTyped,
  RuleFailureExceptionToJSON,
} from './RuleFailureException';

/**
 *
 * @export
 * @interface FailedRulesResult
 */
export interface FailedRulesResult {
  /**
   * Unique rule identifier
   * @type {string}
   * @memberof FailedRulesResult
   */
  ruleId: string;
  /**
   * Name of the rule
   * @type {string}
   * @memberof FailedRulesResult
   */
  ruleName: string;
  /**
   * Description of the rule
   * @type {string}
   * @memberof FailedRulesResult
   */
  ruleDescription: string;
  /**
   *
   * @type {RuleFailureException}
   * @memberof FailedRulesResult
   */
  failureException: RuleFailureException;
}

export function FailedRulesResultFromJSON(json: any): FailedRulesResult {
  return FailedRulesResultFromJSONTyped(json, false);
}

export function FailedRulesResultFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FailedRulesResult {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ruleId: json['ruleId'],
    ruleName: json['ruleName'],
    ruleDescription: json['ruleDescription'],
    failureException: RuleFailureExceptionFromJSON(json['failureException']),
  };
}

export function FailedRulesResultToJSON(value?: FailedRulesResult | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ruleId: value.ruleId,
    ruleName: value.ruleName,
    ruleDescription: value.ruleDescription,
    failureException: RuleFailureExceptionToJSON(value.failureException),
  };
}
