/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class FileImportStatusChange {
  'status': FileImportStatusChangeStatusEnum;
  'timestamp': number;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'status',
      baseName: 'status',
      type: 'FileImportStatusChangeStatusEnum',
      format: '',
    },
    {
      name: 'timestamp',
      baseName: 'timestamp',
      type: 'number',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return FileImportStatusChange.attributeTypeMap;
  }

  public constructor() {}
}

export type FileImportStatusChangeStatusEnum = 'IN_PROGRESS' | 'PENDING' | 'SUCCESS' | 'FAILED';
