/* tslint:disable */
/* eslint-disable */
/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ImportRequest
 */
export interface ImportRequest {
  /**
   *
   * @type {string}
   * @memberof ImportRequest
   */
  type: ImportRequestTypeEnum;
  /**
   *
   * @type {string}
   * @memberof ImportRequest
   */
  format: ImportRequestFormatEnum;
  /**
   *
   * @type {string}
   * @memberof ImportRequest
   */
  s3Key: string;
}

/**
 * @export
 * @enum {string}
 */
export enum ImportRequestTypeEnum {
  Transaction = 'TRANSACTION',
  User = 'USER',
  Business = 'BUSINESS',
}
/**
 * @export
 * @enum {string}
 */
export enum ImportRequestFormatEnum {
  Flagright = 'flagright',
  Custom = 'custom',
}

export function ImportRequestFromJSON(json: any): ImportRequest {
  return ImportRequestFromJSONTyped(json, false);
}

export function ImportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: json['type'],
    format: json['format'],
    s3Key: json['s3Key'],
  };
}

export function ImportRequestToJSON(value?: ImportRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
    format: value.format,
    s3Key: value.s3Key,
  };
}
