/* tslint:disable */
/* eslint-disable */
/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ImportResponse
 */
export interface ImportResponse {
  /**
   *
   * @type {number}
   * @memberof ImportResponse
   */
  importedCount: number;
}

export function ImportResponseFromJSON(json: any): ImportResponse {
  return ImportResponseFromJSONTyped(json, false);
}

export function ImportResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ImportResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    importedCount: json['importedCount'],
  };
}

export function ImportResponseToJSON(value?: ImportResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    importedCount: value.importedCount,
  };
}
