/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ImportRequest {
  'type': ImportRequestTypeEnum;
  'format': ImportRequestFormatEnum;
  's3Key': string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'type',
      baseName: 'type',
      type: 'ImportRequestTypeEnum',
      format: '',
    },
    {
      name: 'format',
      baseName: 'format',
      type: 'ImportRequestFormatEnum',
      format: '',
    },
    {
      name: 's3Key',
      baseName: 's3Key',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return ImportRequest.attributeTypeMap;
  }

  public constructor() {}
}

export type ImportRequestTypeEnum = 'TRANSACTION' | 'USER' | 'BUSINESS';
export type ImportRequestFormatEnum = 'flagright' | 'custom';
