/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContactDetails } from './ContactDetails';
import { InternalConsumerUserAllOf } from './InternalConsumerUserAllOf';
import { LegalDocument } from './LegalDocument';
import { Tag } from './Tag';
import { TransactionLimits } from './TransactionLimits';
import { User } from './User';
import { UserDetails } from './UserDetails';
import { HttpFile } from '../http/http';

export class InternalConsumerUser {
  /**
   * Unique user ID
   */
  'userId': string;
  'userDetails': UserDetails;
  /**
   * Timestamp when userId is created
   */
  'createdTimestamp': number;
  /**
   * User's legal identity documents - See Document Model for details
   */
  'legalDocuments'?: Array<LegalDocument>;
  'contactDetails'?: ContactDetails;
  /**
   * Additional information that can be added via tags
   */
  'tags'?: Array<Tag>;
  'transactionLimits'?: TransactionLimits;
  'type': InternalConsumerUserTypeEnum;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'userId',
      baseName: 'userId',
      type: 'string',
      format: '',
    },
    {
      name: 'userDetails',
      baseName: 'userDetails',
      type: 'UserDetails',
      format: '',
    },
    {
      name: 'createdTimestamp',
      baseName: 'createdTimestamp',
      type: 'number',
      format: '',
    },
    {
      name: 'legalDocuments',
      baseName: 'legalDocuments',
      type: 'Array<LegalDocument>',
      format: '',
    },
    {
      name: 'contactDetails',
      baseName: 'contactDetails',
      type: 'ContactDetails',
      format: '',
    },
    {
      name: 'tags',
      baseName: 'tags',
      type: 'Array<Tag>',
      format: '',
    },
    {
      name: 'transactionLimits',
      baseName: 'transactionLimits',
      type: 'TransactionLimits',
      format: '',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'InternalConsumerUserTypeEnum',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InternalConsumerUser.attributeTypeMap;
  }

  public constructor() {}
}

export type InternalConsumerUserTypeEnum = 'CONSUMER';
