/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContactDetails } from './ContactDetails';
import { FileInfo } from './FileInfo';
import { InternalConsumerUserAllOf } from './InternalConsumerUserAllOf';
import { InternalConsumerUserAllOfUserStatus } from './InternalConsumerUserAllOfUserStatus';
import { KYCStatusDetails } from './KYCStatusDetails';
import { LegalDocument } from './LegalDocument';
import { RiskLevel1 } from './RiskLevel1';
import { Tag } from './Tag';
import { TransactionLimits } from './TransactionLimits';
import { User } from './User';
import { UserDetails } from './UserDetails';
import { UserStatusDetails } from './UserStatusDetails';
import { HttpFile } from '../http/http';

export class InternalConsumerUser {
  /**
   * Unique user ID
   */
  'userId': string;
  'userDetails': UserDetails;
  /**
   * Timestamp when userId is created
   */
  'createdTimestamp': number;
  'userStatusDetails'?: UserStatusDetails;
  'kycStatusDetails'?: KYCStatusDetails;
  /**
   * User's legal identity documents - See Document Model for details
   */
  'legalDocuments'?: Array<LegalDocument>;
  'contactDetails'?: ContactDetails;
  /**
   * Additional information that can be added via tags
   */
  'tags'?: Array<Tag>;
  'transactionLimits'?: TransactionLimits;
  'riskLevel'?: RiskLevel1;
  'type': InternalConsumerUserTypeEnum;
  'files'?: Array<FileInfo>;
  'userStatus'?: InternalConsumerUserAllOfUserStatus;
  'kycStatus'?: InternalConsumerUserAllOfUserStatus;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'userId',
      baseName: 'userId',
      type: 'string',
      format: '',
    },
    {
      name: 'userDetails',
      baseName: 'userDetails',
      type: 'UserDetails',
      format: '',
    },
    {
      name: 'createdTimestamp',
      baseName: 'createdTimestamp',
      type: 'number',
      format: '',
    },
    {
      name: 'userStatusDetails',
      baseName: 'userStatusDetails',
      type: 'UserStatusDetails',
      format: '',
    },
    {
      name: 'kycStatusDetails',
      baseName: 'kycStatusDetails',
      type: 'KYCStatusDetails',
      format: '',
    },
    {
      name: 'legalDocuments',
      baseName: 'legalDocuments',
      type: 'Array<LegalDocument>',
      format: '',
    },
    {
      name: 'contactDetails',
      baseName: 'contactDetails',
      type: 'ContactDetails',
      format: '',
    },
    {
      name: 'tags',
      baseName: 'tags',
      type: 'Array<Tag>',
      format: '',
    },
    {
      name: 'transactionLimits',
      baseName: 'transactionLimits',
      type: 'TransactionLimits',
      format: '',
    },
    {
      name: 'riskLevel',
      baseName: 'riskLevel',
      type: 'RiskLevel1',
      format: '',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'InternalConsumerUserTypeEnum',
      format: '',
    },
    {
      name: 'files',
      baseName: 'files',
      type: 'Array<FileInfo>',
      format: '',
    },
    {
      name: 'userStatus',
      baseName: 'userStatus',
      type: 'InternalConsumerUserAllOfUserStatus',
      format: '',
    },
    {
      name: 'kycStatus',
      baseName: 'kycStatus',
      type: 'InternalConsumerUserAllOfUserStatus',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return InternalConsumerUser.attributeTypeMap;
  }

  public constructor() {}
}

export type InternalConsumerUserTypeEnum = 'CONSUMER';
