/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KYCStatus } from './KYCStatus';
import { HttpFile } from '../http/http';

export class KYCStatusDetails1 {
  'statusReason'?: string;
  'status'?: KYCStatus;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'statusReason',
      baseName: 'statusReason',
      type: 'string',
      format: '',
    },
    {
      name: 'status',
      baseName: 'status',
      type: 'KYCStatus',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return KYCStatusDetails1.attributeTypeMap;
  }

  public constructor() {}
}
