/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ListImportRequest {
  'listName': string;
  'indexName': string;
  'data': string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'listName',
      baseName: 'listName',
      type: 'string',
      format: '',
    },
    {
      name: 'indexName',
      baseName: 'indexName',
      type: 'string',
      format: '',
    },
    {
      name: 'data',
      baseName: 'data',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return ListImportRequest.attributeTypeMap;
  }

  public constructor() {}
}
