/* tslint:disable */
/* eslint-disable */
/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PresignedUrlResponse
 */
export interface PresignedUrlResponse {
  /**
   *
   * @type {string}
   * @memberof PresignedUrlResponse
   */
  presignedUrl: string;
  /**
   *
   * @type {string}
   * @memberof PresignedUrlResponse
   */
  s3Key: string;
}

export function PresignedUrlResponseFromJSON(json: any): PresignedUrlResponse {
  return PresignedUrlResponseFromJSONTyped(json, false);
}

export function PresignedUrlResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PresignedUrlResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    presignedUrl: json['presignedUrl'],
    s3Key: json['s3Key'],
  };
}

export function PresignedUrlResponseToJSON(value?: PresignedUrlResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    presignedUrl: value.presignedUrl,
    s3Key: value.s3Key,
  };
}
