/* tslint:disable */
/* eslint-disable */
/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Rule
 */
export interface Rule {
  /**
   *
   * @type {string}
   * @memberof Rule
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof Rule
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Rule
   */
  description: string;
  /**
   *
   * @type {object}
   * @memberof Rule
   */
  parametersSchema: object;
  /**
   *
   * @type {object}
   * @memberof Rule
   */
  defaultParameters: object;
  /**
   *
   * @type {string}
   * @memberof Rule
   */
  ruleImplementationFilename: string;
  /**
   *
   * @type {number}
   * @memberof Rule
   */
  createdAt?: number;
  /**
   *
   * @type {number}
   * @memberof Rule
   */
  updatedAt?: number;
}

export function RuleFromJSON(json: any): Rule {
  return RuleFromJSONTyped(json, false);
}

export function RuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Rule {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    name: json['name'],
    description: json['description'],
    parametersSchema: json['parametersSchema'],
    defaultParameters: json['defaultParameters'],
    ruleImplementationFilename: json['ruleImplementationFilename'],
    createdAt: !exists(json, 'createdAt') ? undefined : json['createdAt'],
    updatedAt: !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
  };
}

export function RuleToJSON(value?: Rule | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    description: value.description,
    parametersSchema: value.parametersSchema,
    defaultParameters: value.defaultParameters,
    ruleImplementationFilename: value.ruleImplementationFilename,
    createdAt: value.createdAt,
    updatedAt: value.updatedAt,
  };
}
