/* tslint:disable */
/* eslint-disable */
/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum RuleAction {
  Flag = 'FLAG',
  Block = 'BLOCK',
  Whitelist = 'WHITELIST',
  Allow = 'ALLOW',
}

export function RuleActionFromJSON(json: any): RuleAction {
  return RuleActionFromJSONTyped(json, false);
}

export function RuleActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuleAction {
  return json as RuleAction;
}

export function RuleActionToJSON(value?: RuleAction | null): any {
  return value as any;
}
