/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RuleAction } from './RuleAction';
import { HttpFile } from '../http/http';

export class RuleActionAlias {
  'action': RuleAction;
  'alias': string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'action',
      baseName: 'action',
      type: 'RuleAction',
      format: '',
    },
    {
      name: 'alias',
      baseName: 'alias',
      type: 'string',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return RuleActionAlias.attributeTypeMap;
  }

  public constructor() {}
}
