/* tslint:disable */
/* eslint-disable */
/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RuleFailureException
 */
export interface RuleFailureException {
  /**
   * Unique rule identifier
   * @type {string}
   * @memberof RuleFailureException
   */
  exceptionName: string;
  /**
   * Name of the rule
   * @type {string}
   * @memberof RuleFailureException
   */
  exceptionDescription: string;
}

export function RuleFailureExceptionFromJSON(json: any): RuleFailureException {
  return RuleFailureExceptionFromJSONTyped(json, false);
}

export function RuleFailureExceptionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RuleFailureException {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    exceptionName: json['exceptionName'],
    exceptionDescription: json['exceptionDescription'],
  };
}

export function RuleFailureExceptionToJSON(value?: RuleFailureException | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    exceptionName: value.exceptionName,
    exceptionDescription: value.exceptionDescription,
  };
}
