/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RuleAction } from './RuleAction';
import { HttpFile } from '../http/http';

export class Rule {
  'id': string;
  'type': RuleTypeEnum;
  'name': string;
  'description': string;
  'defaultParameters': any;
  'defaultAction': RuleAction;
  'ruleImplementationName': string;
  'labels': Array<string>;
  'createdAt'?: number;
  'updatedAt'?: number;
  'tenantIds'?: Array<string>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'id',
      baseName: 'id',
      type: 'string',
      format: '',
    },
    {
      name: 'type',
      baseName: 'type',
      type: 'RuleTypeEnum',
      format: '',
    },
    {
      name: 'name',
      baseName: 'name',
      type: 'string',
      format: '',
    },
    {
      name: 'description',
      baseName: 'description',
      type: 'string',
      format: '',
    },
    {
      name: 'defaultParameters',
      baseName: 'defaultParameters',
      type: 'any',
      format: '',
    },
    {
      name: 'defaultAction',
      baseName: 'defaultAction',
      type: 'RuleAction',
      format: '',
    },
    {
      name: 'ruleImplementationName',
      baseName: 'ruleImplementationName',
      type: 'string',
      format: '',
    },
    {
      name: 'labels',
      baseName: 'labels',
      type: 'Array<string>',
      format: '',
    },
    {
      name: 'createdAt',
      baseName: 'createdAt',
      type: 'number',
      format: '',
    },
    {
      name: 'updatedAt',
      baseName: 'updatedAt',
      type: 'number',
      format: '',
    },
    {
      name: 'tenantIds',
      baseName: 'tenantIds',
      type: 'Array<string>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return Rule.attributeTypeMap;
  }

  public constructor() {}
}

export type RuleTypeEnum = 'TRANSACTION' | 'USER';
