/* tslint:disable */
/* eslint-disable */
/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { Amount, AmountFromJSON, AmountFromJSONTyped, AmountToJSON } from './Amount';

/**
 *
 * @export
 * @interface TransactionLimits
 */
export interface TransactionLimits {
  /**
   *
   * @type {Amount}
   * @memberof TransactionLimits
   */
  maximumDailyTransactionLimit?: Amount;
  /**
   *
   * @type {Amount}
   * @memberof TransactionLimits
   */
  maximumWeeklyTransactionLimit?: Amount;
  /**
   *
   * @type {Amount}
   * @memberof TransactionLimits
   */
  maximumMonthlyTransactionLimit?: Amount;
  /**
   *
   * @type {Amount}
   * @memberof TransactionLimits
   */
  maximumQuarterlyTransactionLimit?: Amount;
  /**
   *
   * @type {Amount}
   * @memberof TransactionLimits
   */
  maximumYearlyTransactionLimit?: Amount;
}

export function TransactionLimitsFromJSON(json: any): TransactionLimits {
  return TransactionLimitsFromJSONTyped(json, false);
}

export function TransactionLimitsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TransactionLimits {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    maximumDailyTransactionLimit: !exists(json, 'maximumDailyTransactionLimit')
      ? undefined
      : AmountFromJSON(json['maximumDailyTransactionLimit']),
    maximumWeeklyTransactionLimit: !exists(json, 'maximumWeeklyTransactionLimit')
      ? undefined
      : AmountFromJSON(json['maximumWeeklyTransactionLimit']),
    maximumMonthlyTransactionLimit: !exists(json, 'maximumMonthlyTransactionLimit')
      ? undefined
      : AmountFromJSON(json['maximumMonthlyTransactionLimit']),
    maximumQuarterlyTransactionLimit: !exists(json, 'maximumQuarterlyTransactionLimit')
      ? undefined
      : AmountFromJSON(json['maximumQuarterlyTransactionLimit']),
    maximumYearlyTransactionLimit: !exists(json, 'maximumYearlyTransactionLimit')
      ? undefined
      : AmountFromJSON(json['maximumYearlyTransactionLimit']),
  };
}

export function TransactionLimitsToJSON(value?: TransactionLimits | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    maximumDailyTransactionLimit: AmountToJSON(value.maximumDailyTransactionLimit),
    maximumWeeklyTransactionLimit: AmountToJSON(value.maximumWeeklyTransactionLimit),
    maximumMonthlyTransactionLimit: AmountToJSON(value.maximumMonthlyTransactionLimit),
    maximumQuarterlyTransactionLimit: AmountToJSON(value.maximumQuarterlyTransactionLimit),
    maximumYearlyTransactionLimit: AmountToJSON(value.maximumYearlyTransactionLimit),
  };
}
