/* tslint:disable */
/* eslint-disable */
/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { Comment, CommentFromJSON, CommentFromJSONTyped, CommentToJSON } from './Comment';

/**
 *
 * @export
 * @interface TransactionCaseManagementAllOf
 */
export interface TransactionCaseManagementAllOf {
  /**
   *
   * @type {Array<Comment>}
   * @memberof TransactionCaseManagementAllOf
   */
  comments?: Array<Comment>;
}

export function TransactionCaseManagementAllOfFromJSON(json: any): TransactionCaseManagementAllOf {
  return TransactionCaseManagementAllOfFromJSONTyped(json, false);
}

export function TransactionCaseManagementAllOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TransactionCaseManagementAllOf {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    comments: !exists(json, 'comments')
      ? undefined
      : (json['comments'] as Array<any>).map(CommentFromJSON),
  };
}

export function TransactionCaseManagementAllOfToJSON(
  value?: TransactionCaseManagementAllOf | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    comments:
      value.comments === undefined ? undefined : (value.comments as Array<any>).map(CommentToJSON),
  };
}
