/* tslint:disable */
/* eslint-disable */
/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  TransactionCaseManagement,
  TransactionCaseManagementFromJSON,
  TransactionCaseManagementFromJSONTyped,
  TransactionCaseManagementToJSON,
} from './TransactionCaseManagement';

/**
 *
 * @export
 * @interface TransactionsListResponse
 */
export interface TransactionsListResponse {
  /**
   *
   * @type {number}
   * @memberof TransactionsListResponse
   */
  total: number;
  /**
   *
   * @type {Array<TransactionCaseManagement>}
   * @memberof TransactionsListResponse
   */
  data: Array<TransactionCaseManagement>;
}

export function TransactionsListResponseFromJSON(json: any): TransactionsListResponse {
  return TransactionsListResponseFromJSONTyped(json, false);
}

export function TransactionsListResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TransactionsListResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    total: json['total'],
    data: (json['data'] as Array<any>).map(TransactionCaseManagementFromJSON),
  };
}

export function TransactionsListResponseToJSON(value?: TransactionsListResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    total: value.total,
    data: (value.data as Array<any>).map(TransactionCaseManagementToJSON),
  };
}
