/* tslint:disable */
/* eslint-disable */
/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  ExecutedRulesResult,
  ExecutedRulesResultFromJSON,
  ExecutedRulesResultFromJSONTyped,
  ExecutedRulesResultToJSON,
} from './ExecutedRulesResult';
import {
  FailedRulesResult,
  FailedRulesResultFromJSON,
  FailedRulesResultFromJSONTyped,
  FailedRulesResultToJSON,
} from './FailedRulesResult';

/**
 *
 * @export
 * @interface TransactionWithRulesResultAllOf
 */
export interface TransactionWithRulesResultAllOf {
  /**
   *
   * @type {Array<ExecutedRulesResult>}
   * @memberof TransactionWithRulesResultAllOf
   */
  executedRules: Array<ExecutedRulesResult>;
  /**
   *
   * @type {Array<FailedRulesResult>}
   * @memberof TransactionWithRulesResultAllOf
   */
  failedRules: Array<FailedRulesResult>;
}

export function TransactionWithRulesResultAllOfFromJSON(
  json: any,
): TransactionWithRulesResultAllOf {
  return TransactionWithRulesResultAllOfFromJSONTyped(json, false);
}

export function TransactionWithRulesResultAllOfFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TransactionWithRulesResultAllOf {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    executedRules: (json['executedRules'] as Array<any>).map(ExecutedRulesResultFromJSON),
    failedRules: (json['failedRules'] as Array<any>).map(FailedRulesResultFromJSON),
  };
}

export function TransactionWithRulesResultAllOfToJSON(
  value?: TransactionWithRulesResultAllOf | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    executedRules: (value.executedRules as Array<any>).map(ExecutedRulesResultToJSON),
    failedRules: (value.failedRules as Array<any>).map(FailedRulesResultToJSON),
  };
}
