/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Comment } from './Comment';
import { HttpFile } from '../http/http';

export class TransactionCaseManagementAllOf {
  'comments'?: Array<Comment>;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
    format: string;
  }> = [
    {
      name: 'comments',
      baseName: 'comments',
      type: 'Array<Comment>',
      format: '',
    },
  ];

  static getAttributeTypeMap() {
    return TransactionCaseManagementAllOf.attributeTypeMap;
  }

  public constructor() {}
}
