/* tslint:disable */
/* eslint-disable */
/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UPIDetails
 */
export interface UPIDetails {
  /**
   *
   * @type {string}
   * @memberof UPIDetails
   */
  method: string;
  /**
   *
   * @type {string}
   * @memberof UPIDetails
   */
  upiID: string;
  /**
   *
   * @type {string}
   * @memberof UPIDetails
   */
  bankProvider?: string;
  /**
   *
   * @type {string}
   * @memberof UPIDetails
   */
  interfaceProvider?: string;
}

export function UPIDetailsFromJSON(json: any): UPIDetails {
  return UPIDetailsFromJSONTyped(json, false);
}

export function UPIDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UPIDetails {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    method: json['method'],
    upiID: json['upiID'],
    bankProvider: !exists(json, 'bankProvider') ? undefined : json['bankProvider'],
    interfaceProvider: !exists(json, 'interfaceProvider') ? undefined : json['interfaceProvider'],
  };
}

export function UPIDetailsToJSON(value?: UPIDetails | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    method: value.method,
    upiID: value.upiID,
    bankProvider: value.bankProvider,
    interfaceProvider: value.interfaceProvider,
  };
}
