/**
 * Tarpon Console API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export type UserStatus =
  | 'UNACCEPTABLE'
  | 'UNDECIDED'
  | 'TERMINATED'
  | 'ACTIVE'
  | 'INACTIVE'
  | 'DORMANT'
  | 'CREATED'
  | 'DELETED'
  | 'SUSPENDED - ALL'
  | 'SUSPENDED - CREDITS'
  | 'SUSPENDED - DEBITS'
  | 'SUSPENDED - CARDS'
  | 'SUSPENDED - STOCKS'
  | 'SUSPENDED - CRYPTO'
  | 'SUSPENDED - LOG IN';
