import { AccountRoleName } from '@/@types/openapi-internal/AccountRoleName'
import { Permission } from '@/@types/openapi-internal/Permission'
import { PERMISSIONS } from '@/@types/openapi-internal-custom/Permission'

export const DEFAULT_ROLES: {
  role: AccountRoleName
  permissions: Permission[]
}[] = [
  {
    role: 'admin',
    permissions: PERMISSIONS,
  },
  {
    // Legacy role. It has all permissions since the important things have a
    // check for "root" already.
    role: 'user',
    permissions: PERMISSIONS,
  },
  {
    role: 'auditor',
    permissions: [
      'case-management:case-overview:read',
      'case-management:case-details:read',
      'case-management:download:read',
      'rules:my-rules:read',
      'rules:library:read',
      'risk-scoring:risk-levels:read',
      'risk-scoring:risk-factors:read',
      'risk-scoring:risk-algorithms:read',
      'dashboard:download-data:read',
      'settings:nomenclature:read',
      'settings:alerts:read',
      'transactions:overview:read',
      'transactions:details:read',
      'transactions:download:read',
      'audit-log:download:read',
      'lists:whitelist:read',
      'lists:blacklist:read',
      'lists:download:read',
      'simulation:rules:read',
      'simulation:risk-scoring:read',
    ],
  },
  {
    role: 'analyst',
    permissions: [
      'case-management:case-overview:read',
      'case-management:case-overview:write',
      'case-management:case-details:read',
      'case-management:case-details:write',
      'case-management:download:read',
      'rules:my-rules:read',
      'rules:library:read',
      'risk-scoring:risk-levels:read',
      'risk-scoring:risk-factors:read',
      'risk-scoring:risk-algorithms:read',
      'transactions:overview:read',
      'transactions:details:read',
      'transactions:download:read',
    ],
  },
  {
    role: 'approver',
    permissions: [
      'case-management:case-overview:read',
      'case-management:case-details:read',
      'case-management:download:read',
      'rules:my-rules:read',
      'rules:library:read',
      'risk-scoring:risk-levels:read',
      'risk-scoring:risk-factors:read',
      'risk-scoring:risk-algorithms:read',
      'dashboard:download-data:read',
      'settings:nomenclature:read',
      'settings:alerts:read',
      'transactions:overview:read',
      'transactions:details:read',
      'transactions:download:read',
      'audit-log:download:read',
      'lists:whitelist:read',
      'lists:blacklist:read',
      'lists:download:read',
      'simulation:rules:read',
      'simulation:risk-scoring:read',
    ],
  },
  {
    role: 'developer',
    permissions: [
      'case-management:case-overview:read',
      'case-management:case-details:read',
      'case-management:download:read',
      'rules:my-rules:read',
      'rules:library:read',
      'risk-scoring:risk-levels:read',
      'risk-scoring:risk-factors:read',
      'risk-scoring:risk-algorithms:read',
      'users:user-overview:read',
      'users:user-details:read',
      'dashboard:download-data:read',
      'settings:organisation:read',
      'settings:billing:read',
      'settings:nomenclature:read',
      'settings:addons:read',
      'settings:alerts:read',
      'settings:developers:read',
      'settings:developers:write',
      'transactions:overview:read',
      'transactions:details:read',
      'transactions:download:read',
      'team-management:download:read',
      'audit-log:download:read',
      'lists:whitelist:read',
      'lists:blacklist:read',
      'lists:download:read',
      'simulation:rules:read',
      'simulation:risk-scoring:read',
    ],
  },
]
