import { CaseReasons } from '@/@types/openapi-internal/CaseReasons'

export const reasonNarrativesCasesAlerts = (
  type: 'CASE' | 'ALERT',
  commentsAvailable: boolean
): Record<CaseReasons, string> => {
  const entityGenerationDate =
    type === 'CASE' ? 'caseGenerationDate' : 'alertGenerationDate'
  const entityActionDate =
    type === 'CASE' ? 'caseActionDate' : 'alertActionDate'
  const entity = type === 'CASE' ? 'Case' : 'Alert'
  const commentAttributeKey = type === 'CASE' ? 'caseComments' : 'alertComments'
  const commentsPrompt = commentsAvailable
    ? `${entity} comments that were referred to perform this action [${commentAttributeKey}].`
    : ''

  return {
    'Investigation completed': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). The activity was reviewed and transactions from [${entityGenerationDate}] to [${entityActionDate}] were analysed totalling [totalOriginAmount]. The customer was requested to provide additional information/documentation to explain the activity. The customer explained that [Customer explanation] and has provided [Supporting documentation]. The activity is clear and is fully supported by customer responses and documentation provided. ${entity} closed. ${commentsPrompt}`,
    'False positive': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). [Why is it false positive]. ${entity} can be closed as false positive. ${commentsPrompt}`,
    'Documents collected': `The customer provided the following documents and explanations: [List of uploaded documents]. ${commentsPrompt}`,
    'Transaction Rejected': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). Upon conducting a review of the activity there is a high probability that the transaction in question is associated with [fraud/money laundering/terrorist financing/sanctions evasion] and it is therefore being rejected. ${commentsPrompt}`,
    'Transaction Refunded': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). The transaction is being refunded back to the originator of the transaction. ${commentsPrompt}`,
    'Suspicious activity reported (SAR)': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s).  Upon conducting an investigation it was identified that the activity was suspicious. SAR was filed [${entityActionDate}] to [Name of the FIU].${commentsPrompt} ${commentsPrompt}`,
    'Documents not collected': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s).  When conducting an investigation the customer was asked to provide explanations and supporting documentation on [Date customer asked to provider documentation]. The customer did not provide the requested information to date. ${commentsPrompt}`,
    Escalated: `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s).  the activity was reviewed and transactions from [${entityGenerationDate}] to [${entityActionDate}] were analysed totalling [totalOriginAmount]. The activity does not match the customer profile and is therefore being escalated for further review. ${commentsPrompt}`,
    Fraud: `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s).  The activity was reviewed and transactions from [${entityGenerationDate}] to [${entityActionDate}] were analysed totalling [totalOriginAmount]. The customer was requested to provide additional information/documentation to explain the activity. The customer explained that [Interaction with the customer] and has provided [List of supporting documentation]. The activity does not make economic sense at is likely associated with fraud due to [Provide reason it may be fraud]. ${commentsPrompt}`,
    'Anti-money laundering': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s).  The activity was reviewed and transactions from [${entityGenerationDate}] to [${entityActionDate}] were analysed totalling [totalOriginAmount]. The customer was requested to provide additional information/documentation to explain the activity. The customer explained that [Interaction with the customer] and has provided [List of supporting documentation]. The activity does not make economic sense at is likely associated with money laundering due to [Provide reason it may be money laundering]. ${commentsPrompt}`,
    'Terrorist financing': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s).  The activity was reviewed and transactions from [${entityGenerationDate}] to [${entityActionDate}] were analysed totalling [totalOriginAmount]. The customer was requested to provide additional information/documentation to explain the activity. The customer explained that [Interaction with the customer] and has provided [List of supporting documentation]. The activity does not make economic sense at is likely associated with terrorist financing due to [Provide reason it may be terrorist financing]. ${commentsPrompt}`,
    'User Blacklisted': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s).  The activity was reviewed and transactions from [${entityGenerationDate}] to [${entityActionDate}] were analysed totalling [totalOriginAmount]. The customer was requested to provide additional information/documentation to explain the activity. The customer explained that  XXXX ( from interaction with the customer) and has provided XXXXXXX ( list of supporting documentation). The customer was put on black list in order to prevent any future dealings with the customer. ${commentsPrompt}`,
    'User Terminated': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). The activity was reviewed and transactions from [${entityGenerationDate}] to [${entityActionDate}] were analysed totalling [totalOriginAmount]. The customer was requested to provide additional information/documentation to explain the activity. The customer explained that  XXXX ( from interaction with the customer) and has provided XXXXXXX ( list of supporting documentation). The activity was identified as being suspicious and as a result customer account was terminated. ${commentsPrompt}`,
    'Internal referral': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). The reason for referral was [Why is the case internally referred]. The customer could not explain the purpose and nature of the transactions therefore the activity was referred for review by the compliance department. ${commentsPrompt}`,
    'External referral': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s).  The reason for referral was [Why is the case externally referred]. Customer activity is unusual therefore it was referred for review by the compliance department. ${commentsPrompt}`,
    'Confirmed fraud': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). Transactions from [${entityGenerationDate}] to [${entityActionDate}] were analyzed totaling [totalOriginAmount]. Upon review, the activity was confirmed to be fraudulent due to [details of fraudulent activity]. The customer was informed, and appropriate actions were taken, including account closure and reporting to the relevant authorities. ${commentsPrompt}`,
    'Confirmed genuine': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). After thorough analysis of transactions from [${entityGenerationDate}] to [${entityActionDate}], and reviewing the customer’s explanation and supporting documentation, the activity was confirmed to be legitimate. No further action was required, and the case was closed. ${commentsPrompt}`,
    'Suspected fraud': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). After reviewing transactions and supporting documentation from [${entityGenerationDate}] to [${entityActionDate}], the activity raised concerns of potential fraudulent behavior. However, more evidence is required to confirm fraud. As a precaution, the case has been flagged for further investigation and monitoring. ${commentsPrompt}`,
    'True positive': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). Transactions between [${entityGenerationDate}] and [${entityActionDate}] were reviewed, and it was determined that the alert was a true positive. The customer’s activity was found to match patterns associated with [specific risk type]. As a result, the case was escalated for appropriate action by the compliance department. ${commentsPrompt}`,
    Other: `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). The activity was reviewed and transactions from [${entityGenerationDate}] to [${entityActionDate}] were analysed totalling [totalOriginAmount]. The customer was requested to provide additional information/documentation to explain the activity. The customer explained that [Interaction with the customer] and has provided [List of supporting documentation]. The activity is clear and is fully supported by customer responses and documentation provided. ${entity} closed. ${commentsPrompt}`,
  }
}

export const reasonNarrativeScreening = (
  type: 'CASE' | 'ALERT',
  commentsAvailable: boolean
): Record<CaseReasons, string> => {
  const entityGenerationDate =
    type === 'CASE' ? 'caseGenerationDate' : 'alertGenerationDate'
  const entityActionDate =
    type === 'CASE' ? 'caseActionDate' : 'alertActionDate'
  const entity = type === 'CASE' ? 'Case' : 'Alert'
  const commentAttributeKey = type === 'CASE' ? 'caseComments' : 'alertComments'
  const commentsPrompt = commentsAvailable
    ? `${entity} comments that were referred to perform this action [${commentAttributeKey}].`
    : ''
  return {
    'Investigation completed': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). The activity was reviewed and screening details from [${entityGenerationDate}] to [${entityActionDate}] were analysed [Details of screening]. The customer was requested to provide additional information/documentation to explain the activity. The customer explained that [Customer explanation] and has provided [Supporting documentation]. The activity is clear and is fully supported by customer responses and documentation provided. ${entity} closed.${commentsPrompt}`,
    'False positive': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). [Why is it false positive]. ${entity} can be closed as false positive.${commentsPrompt}`,
    'Documents collected': `The customer provided the following documents and explanations: [List of uploaded documents]. ${commentsPrompt}`,
    'Transaction Rejected': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). Upon conducting a review the screening details of the customers / counterparty related to the transaction were found to be [Screening details]. The transaction was rejected.${commentsPrompt}`,
    'Transaction Refunded': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). Upon conducting a review the screening details of the customers / counterparty related to the transaction were found to be [Screening details]. The transaction was refunded.${commentsPrompt}`,
    'Suspicious activity reported (SAR)': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). Upon conducting a review the screening details of the customers / counterparty related to the [Details of screening] were found to be [Screening details]. SAR was filed [${entityActionDate}] to [Name of the FIU]. ${commentsPrompt}`,
    'Documents not collected': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). Upon conducting a review the screening details of the customers / counterparty related to the [Details of screening] were found to be [Screening details]. The customer was asked to provide additional information/documentation to explain the activity. The customer did not provide the requested information to date.${commentsPrompt}`,
    Escalated: `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). Upon conducting a review the screening details of the customers / counterparty related to the [Details of screening] were found to be [Screening details]. The activity was reviewed and [Screening details] from [${entityGenerationDate}] to [${entityActionDate}] were of [name] and found to be crtical to be reviewed hence the activity was escalated for further review.${commentsPrompt}`,
    Fraud: `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). Upon conducting a review the screening details of the customers / counterparty related to the [Details of screening] were found to be [Screening details]. The activity was reviewed and [Screening details] from [${entityGenerationDate}] to [${entityActionDate}] were of [name] and found to be crtical to be reviewed hence the activity was escalated for further review.${commentsPrompt}`,
    'Anti-money laundering': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). Upon conducting a review the screening details of the customers / counterparty related to the [Details of screening] were found to be [Screening details]. The activity was reviewed and [Screening details] from [${entityGenerationDate}] to [${entityActionDate}] were of [name] and found to be crtical to be reviewed hence the activity was escalated for further review.${commentsPrompt}`,
    'Terrorist financing': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). Upon conducting a review the screening details of the customers / counterparty related to the [Details of screening] were found to be [Screening details]. The activity was reviewed and [Screening details] from [${entityGenerationDate}] to [${entityActionDate}] were of [name] and found to be crtical to be reviewed hence the activity was escalated for further review.${commentsPrompt}`,
    Other: `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). Upon conducting a review the screening details of the customers / counterparty related to the [Details of screening] were found to be [Screening details]. The activity was reviewed and [Screening details] from [${entityGenerationDate}] to [${entityActionDate}] were of [name] and found to be crtical to be reviewed hence the activity was escalated for further review.${commentsPrompt}`,
    'Confirmed fraud': `Customer actiity was alerted and found to be fraudulent due to [Screening details]. The customer was informed and appropriate actions were taken, including account closure and reporting to the relevant authorities.${commentsPrompt}`,
    'Confirmed genuine': `Customer actiity was alerted by [ruleHitNames] rule(s) and found to be legitimate. No further action was required, and the case was closed.${commentsPrompt}`,
    'Suspected fraud': `Customer actiity was alerted by [ruleHitNames] rule(s) and found to be fraudulent due to [Screening details]. However, more evidence is required to confirm fraud. As a precaution, the case has been flagged for further investigation and monitoring.${commentsPrompt}`,
    'True positive': `Customer actiity was alerted by [ruleHitNames] rule(s) and found to be fraudulent due to [Screening details]. The customer’s activity was found to match patterns associated with [specific risk type]. As a result, the case was escalated for appropriate action by the compliance department.${commentsPrompt}`,
    'Internal referral': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). The reason for referral was [Why is the case internally referred]. The customer could not explain the presence of [Screening details] in their profile.${commentsPrompt}`,
    'External referral': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). The reason for referral was [Why is the case externally referred]. The customer could not explain the presence of [Screening details] in their profile.${commentsPrompt}`,
    'User Blacklisted': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). The customer was found to be associated with [Screening details]. The customer was put on black list in order to prevent any future dealings with the customer.${commentsPrompt}`,
    'User Terminated': `Customer activity was alerted on [${entityGenerationDate}] due to [ruleHitNames] rule(s). The customer was found to be associated with [Screening details]. The customer was terminated as a result of the activity.${commentsPrompt}`,
  }
}
