export const ENGINEERING_HELP_CHANNEL_ID = 'C03BN4GQALA'
export const ENGINEERING_GROUP_ID = 'S03EY0EMJQN'
export const ENGINEERING_ON_CALL_GROUP_ID = 'S063WMNMSCD'
export const INCIDENTS_BUGS_CHANNEL_ID = 'C03AE1RQM88'
