import memoize from 'lodash/memoize'
import invert from 'lodash/invert'
import { MONGO_TABLE_SUFFIX_MAP } from '../mongo/table-suffix'
import { CLICKHOUSE_DEFINITIONS } from './definitions'
import { ClickhouseTableNames } from '@/@types/clickhouse/table-names'

export const MONGO_COLLECTION_SUFFIX_MAP_TO_CLICKHOUSE: Record<
  string,
  ClickhouseTableNames
> = {
  [MONGO_TABLE_SUFFIX_MAP.TRANSACTIONS]:
    CLICKHOUSE_DEFINITIONS.TRANSACTIONS.tableName,
  [MONGO_TABLE_SUFFIX_MAP.USERS]: CLICKHOUSE_DEFINITIONS.USERS.tableName,
  [MONGO_TABLE_SUFFIX_MAP.TRANSACTION_EVENTS]:
    CLICKHOUSE_DEFINITIONS.TRANSACTION_EVENTS.tableName,
  [MONGO_TABLE_SUFFIX_MAP.USER_EVENTS]:
    CLICKHOUSE_DEFINITIONS.USER_EVENTS.tableName,
  [MONGO_TABLE_SUFFIX_MAP.CASES]: CLICKHOUSE_DEFINITIONS.CASES.tableName,
  [MONGO_TABLE_SUFFIX_MAP.KRS_SCORE]:
    CLICKHOUSE_DEFINITIONS.KRS_SCORE.tableName,
  [MONGO_TABLE_SUFFIX_MAP.DRS_SCORE]:
    CLICKHOUSE_DEFINITIONS.DRS_SCORE.tableName,
  [MONGO_TABLE_SUFFIX_MAP.ARS_SCORE]:
    CLICKHOUSE_DEFINITIONS.ARS_SCORE.tableName,
  [MONGO_TABLE_SUFFIX_MAP.SANCTIONS_SCREENING_DETAILS]:
    CLICKHOUSE_DEFINITIONS.SANCTIONS_SCREENING_DETAILS.tableName,
  [MONGO_TABLE_SUFFIX_MAP.SANCTIONS_SCREENING_DETAILS_V2]:
    CLICKHOUSE_DEFINITIONS.SANCTIONS_SCREENING_DETAILS_V2.tableName,
  [MONGO_TABLE_SUFFIX_MAP.REPORTS]: CLICKHOUSE_DEFINITIONS.REPORTS.tableName,
}
export const CLICKHOUSE_TABLE_SUFFIX_MAP_TO_MONGO = memoize(() =>
  invert(MONGO_COLLECTION_SUFFIX_MAP_TO_CLICKHOUSE)
)
