import { ClickhouseTableNames } from '@/@types/clickhouse/table-names'

export const CLICKHOUSE_ID_COLUMN_MAP: Record<ClickhouseTableNames, string> = {
  webhook: '_id',
  transactions_v2: 'id',
  transactions: 'transactionId',
  transactions_desc: 'transactionId',
  users: 'userId',
  transaction_events: 'eventId',
  user_events: 'eventId',
  cases: 'caseId',
  cases_v2: 'caseId',
  reports: '_id',
  krs_score: 'userId',
  drs_score: 'userId',
  ars_score: 'transactionId',
  sanctions_screening_details: 'searchId',
  sanctions_screening_details_v2: 'screeningId',
  alerts: 'alertId',
  crm_records: 'id',
  crm_user_record_link: 'id',
  dynamic_permissions_items: 'id',
  audit_logs: 'auditlogId',
  alerts_qa_sampling: 'samplingId',
  api_request_logs: 'requestId',
  notifications: 'id',
  gpt_request_logs: '_id',
  metrics: '_id',
  webhook_deliveries: '_id',
  transactions_by_id: 'id',
  transactions_by_type: 'id',
  transactions_by_type_daily: 'id',
  users_by_id: 'id',
  user_monthly_stats: 'id',
  user_hourly_stats: 'id',
  user_daily_stats: 'id',
  sanctions_screening_details_by_id: 'id',
  sanctions_screening_details_v2_by_id: 'id',
  cloudwatch_logs: 'requestId',
  cloudwatch_logs_correlated: 'requestId',
}
