export enum ClickhouseTableMaterializedViews {
  TransactionsById = 'transactions_by_id_mv',
  TransactionsMonthlyStats = 'transactions_monthly_stats_mv',
  TransactionsHourlyStats = 'transactions_hourly_stats_mv',
  TransactionsDailyStats = 'transactions_daily_stats_mv',
  RuleStatsHourlyTransactions = 'rule_stats_hourly_transactions_mv',
  TransactionsByType = 'transactions_by_type_mv',
  TransactionsByTypeDaily = 'transactions_by_type_daily_mv',
  UsersById = 'users_by_id_mv',
  UserMonthlyStats = 'user_monthly_stats_mv',
  UserHourlyStats = 'user_hourly_stats_mv',
  UserDailyStats = 'user_daily_stats_mv',
  CasesInvestigationTimesHourly = 'cases_investigation_times_hourly_mv',
  SanctionsScreeningDetailsById = 'sanctions_screening_details_by_id_mv',
  SanctionsScreeningDetailsV2ById = 'sanctions_screening_details_v2_by_id_mv',
  AlertsQaSampling = 'alerts_qa_sampling_mv',
  ApiRequestLogs = 'api_request_logs_mv',
  Notifications = 'notifications_mv',
  GptRequests = 'gpt_request_logs_mv',
  Metrics = 'metrics_mv',
  Webhook = 'webhook_mv',
  WebhookDelivery = 'webhook_deliveries_mv',
}
