export enum ClickhouseTableMaterializedViews {
  TransactionsById = 'transactions_by_id_mv',
  TransactionsByType = 'transactions_by_type_mv',
  TransactionsByTypeDaily = 'transactions_by_type_daily_mv',
  UsersById = 'users_by_id_mv',
  SanctionsScreeningDetailsById = 'sanctions_screening_details_by_id_mv',
  SanctionsScreeningDetailsV2ById = 'sanctions_screening_details_v2_by_id_mv',
  AlertsQaSampling = 'alerts_qa_sampling_mv',
  ApiRequestLogs = 'api_request_logs_mv',
  Notifications = 'notifications_mv',
  GptRequests = 'gpt_request_logs_mv',
  Metrics = 'metrics_mv',
  Webhook = 'webhook_mv',
  WebhookDelivery = 'webhook_deliveries_mv',
}
