export const schema = {
  $id: 'schema.json',
  $schema: 'http://json-schema.org/draft-07/schema#',
  title:
    'This JSON Schema file was generated from schema on Tue Sep 19 2023 22:48:00 GMT+0530 (India Standard Time).  For more information please see http://www.xsd2jsonschema.org',
  description:
    "Schema tag attributes: xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns:xmime='http://www.w3.org/2005/05/xmlmime' xmlns='urn:lt:fntt:exchange:model:str' elementFormDefault='qualified' targetNamespace='urn:lt:fntt:exchange:model:str'",
  properties: {
    ProviderType: {
      $ref: '#/definitions/ProviderType',
    },
    StrDataType: {
      $ref: '#/definitions/StrDataType',
    },
    SuspiciousTransactionReport: {
      $ref: '#/definitions/SuspiciousTransactionReport',
    },
  },
  type: 'object',
  definitions: {
    SuspiciousTransactionReport: {
      required: ['Provider', 'StrData'],
      properties: {
        Provider: {
          $ref: '#/definitions/ProviderType',
        },
        StrData: {
          items: {
            $ref: '#/definitions/StrDataType',
          },
          minItems: 1,
          type: 'array',
        },
      },
      type: 'object',
    },
    ProviderType: {
      required: ['Code'],
      properties: {
        Code: {
          $ref: '#/definitions/Max20Text',
        },
      },
      type: 'object',
    },
    StrDataType: {
      required: [
        'TransactionDate',
        'ReportNumber',
        'ReportType',
        'OperationType',
        'Description',
        'Suspicion',
        'TransactionValue',
        'TransactionSubject',
        'Account',
      ],
      properties: {
        TransactionDate: {
          $ref: '#/definitions/DateType',
        },
        ReportNumber: {
          $ref: '#/definitions/Max50Text',
        },
        RelatedReports: {
          $ref: '#/definitions/Max500Text',
        },
        ReportType: {
          $ref: '#/definitions/Max255Text',
        },
        OperationType: {
          $ref: '#/definitions/Max255Text',
        },
        StopDate: {
          $ref: '#/definitions/DateType',
        },
        NonStopReason: {
          $ref: '#/definitions/Max500Text',
        },
        Description: {
          $ref: '#/definitions/Max4000Text',
        },
        Suspicion: {
          items: {
            $ref: '#/definitions/SuspicionType',
          },
          minItems: 1,
          type: 'array',
        },
        TransactionValue: {
          items: {
            $ref: '#/definitions/TransactionValueType',
          },
          minItems: 1,
          type: 'array',
        },
        TransactionSubject: {
          items: {
            $ref: '#/definitions/TransactionSubjectType',
          },
          minItems: 1,
          type: 'array',
        },
        Account: {
          items: {
            $ref: '#/definitions/AccountType',
          },
          minItems: 1,
          type: 'array',
        },
        StrFiles: {
          oneOf: [
            {},
            {
              items: {},
              type: 'array',
            },
          ],
        },
      },
      type: 'object',
    },
    SuspicionType: {
      required: ['SuspicionCode', 'SuspicionTitle'],
      properties: {
        SuspicionCode: {
          $ref: '#/definitions/Max50Text',
        },
        SuspicionTitle: {
          $ref: '#/definitions/Max4000TextMinZero',
        },
      },
      type: 'object',
    },
    TransactionValueType: {
      required: ['Sum', 'Currency'],
      properties: {
        Sum: {
          $ref: '#/definitions/Decimal20Type',
        },
        Currency: {
          $ref: '#/definitions/Max11Text',
          enum: [
            '1INCH',
            'AAVE',
            'ADA',
            'AED',
            'AFN',
            'ALGO',
            'ALL',
            'AMD',
            'AMP',
            'ANG',
            'AOA',
            'AR',
            'ARS',
            'ATOM',
            'AUD',
            'AVAX',
            'AWG',
            'AXS',
            'AZN',
            'BAM',
            'BAT',
            'BBD',
            'BCH',
            'BDT',
            'BGN',
            'BHD',
            'BIF',
            'BMD',
            'BNB',
            'BND',
            'BOB',
            'BRL',
            'BSD',
            'BSV',
            'BTC',
            'BTCB',
            'BTG',
            'BTN',
            'BUSD',
            'BWP',
            'BYN',
            'BYR',
            'BZD',
            'CAD',
            'CAKE',
            'CDF',
            'CELO',
            'CHF',
            'CHZ',
            'CLF',
            'CLP',
            'CNY',
            'COMP',
            'COP',
            'CRC',
            'CRO',
            'CRV',
            'CUC',
            'CUP',
            'CVE',
            'CVX',
            'CZK',
            'DAI',
            'DASH',
            'DCR',
            'DFI',
            'DJF',
            'DKK',
            'DOGE',
            'DOP',
            'DOT',
            'DZD',
            'EGLD',
            'EGP',
            'ENJ',
            'EOS',
            'ERN',
            'ETB',
            'ETC',
            'ETH',
            'EUR',
            'FEI',
            'FIL',
            'FJD',
            'FKP',
            'FLOW',
            'FRAX',
            'FTM',
            'FTT',
            'GALA',
            'GBP',
            'GEL',
            'GGP',
            'GHS',
            'GIP',
            'GMD',
            'GNF',
            'GNO',
            'GRT',
            'GT',
            'GTQ',
            'GYD',
            'HBAR',
            'HKD',
            'HNL',
            'HNT',
            'HOT',
            'HRK',
            'HT',
            'HTG',
            'HUF',
            'ICP',
            'IDR',
            'ILS',
            'IMP',
            'INJ',
            'INR',
            'IQD',
            'IRR',
            'ISK',
            'JEP',
            'JMD',
            'JOD',
            'JPY',
            'KAVA',
            'KCS',
            'KDA',
            'KES',
            'KGS',
            'KHR',
            'KLAY',
            'KMF',
            'KNC',
            'KPW',
            'KRW',
            'KSM',
            'KWD',
            'KYD',
            'KZT',
            'LAK',
            'LBP',
            'LEO',
            'LINK',
            'LKR',
            'LRC',
            'LRD',
            'LSL',
            'LTC',
            'LTL',
            'LUNA',
            'LVL',
            'LYD',
            'MAD',
            'MANA',
            'MATIC',
            'MDL',
            'MGA',
            'MINA',
            'MIOTA',
            'MKD',
            'MKR',
            'MMK',
            'MNT',
            'MOP',
            'MRO',
            'MUR',
            'MVR',
            'MWK',
            'MXN',
            'MYR',
            'MZN',
            'NAD',
            'NEAR',
            'NEO',
            'NEXO',
            'NGN',
            'NIO',
            'NOK',
            'NPR',
            'NZD',
            'OKB',
            'OMR',
            'ONE',
            'PAB',
            'PAXG',
            'PEN',
            'PGK',
            'PHP',
            'PKR',
            'PLN',
            'PYG',
            'QAR',
            'QNT',
            'QTUM',
            'RON',
            'RSD',
            'RUB',
            'RUNE',
            'RWF',
            'SAND',
            'SAR',
            'SBD',
            'SCR',
            'SDG',
            'SEK',
            'SGD',
            'SHIB',
            'SHP',
            'SLE',
            'SLL',
            'SOL',
            'SOS',
            'SRD',
            'STD',
            'STX',
            'SVC',
            'SYP',
            'SZL',
            'THB',
            'THETA',
            'TJS',
            'TMT',
            'TND',
            'TOP',
            'TRX',
            'TRY',
            'TTD',
            'TTT',
            'TUSD',
            'TWD',
            'TZS',
            'UAH',
            'UGX',
            'UNI',
            'USD',
            'USDC',
            'USDP',
            'USDT',
            'UYU',
            'UZS',
            'VEF',
            'VET',
            'VND',
            'VUV',
            'WAVES',
            'WBTC',
            'WEMIX',
            'WST',
            'XAF',
            'XAG',
            'XAU',
            'XCD',
            'XCH',
            'XDC',
            'XDR',
            'XEC',
            'XEM',
            'XLM',
            'XMR',
            'XOF',
            'XPF',
            'XRP',
            'XTZ',
            'YER',
            'ZAR',
            'ZEC',
            'ZIL',
            'ZMK',
            'ZMW',
            'ZWL',
          ],
          'ui:schema': {
            'ui:subtype': 'CURRENCY',
          },
        },
        StoppingDate: {
          $ref: '#/definitions/DateType',
        },
      },
      type: 'object',
    },
    TransactionSubjectType: {
      required: ['SubjectType', 'Country', 'Code'],
      properties: {
        SubjectType: {
          $ref: '#/definitions/SubjectTypeCode',
        },
        Country: {
          $ref: '#/definitions/Max100Text',
          enum: [
            'AF',
            'AL',
            'DZ',
            'AS',
            'AD',
            'AO',
            'AI',
            'AQ',
            'AG',
            'AR',
            'AM',
            'AW',
            'AU',
            'AT',
            'AZ',
            'BS',
            'BH',
            'BD',
            'BB',
            'BY',
            'BE',
            'BZ',
            'BJ',
            'BM',
            'BT',
            'BO',
            'BQ',
            'BA',
            'BW',
            'BV',
            'BR',
            'IO',
            'BN',
            'BG',
            'BF',
            'BI',
            'CV',
            'KH',
            'CM',
            'CA',
            'KY',
            'CF',
            'TD',
            'CL',
            'CN',
            'CX',
            'CC',
            'CO',
            'KM',
            'CD',
            'CG',
            'CK',
            'CR',
            'HR',
            'CU',
            'CW',
            'CY',
            'CZ',
            'CI',
            'DK',
            'DJ',
            'DM',
            'DO',
            'EC',
            'EG',
            'SV',
            'GQ',
            'ER',
            'EE',
            'SZ',
            'ET',
            'FK',
            'FO',
            'FJ',
            'FI',
            'FR',
            'GF',
            'PF',
            'TF',
            'GA',
            'GM',
            'GE',
            'DE',
            'GH',
            'GI',
            'GR',
            'GL',
            'GD',
            'GP',
            'GU',
            'GT',
            'GG',
            'GN',
            'GW',
            'GY',
            'HT',
            'HM',
            'VA',
            'HN',
            'HK',
            'HU',
            'IS',
            'IN',
            'ID',
            'IR',
            'IQ',
            'IE',
            'IM',
            'IL',
            'IT',
            'JM',
            'JP',
            'JE',
            'JO',
            'KZ',
            'KE',
            'KI',
            'KP',
            'KR',
            'KW',
            'KG',
            'LA',
            'LV',
            'LB',
            'LS',
            'LR',
            'LY',
            'LI',
            'LT',
            'LU',
            'MO',
            'MG',
            'MW',
            'MY',
            'MV',
            'ML',
            'MT',
            'MH',
            'MQ',
            'MR',
            'MU',
            'YT',
            'MX',
            'FM',
            'MD',
            'MC',
            'MN',
            'ME',
            'MS',
            'MA',
            'MZ',
            'MM',
            'NA',
            'NR',
            'NP',
            'NL',
            'NC',
            'NZ',
            'NI',
            'NE',
            'NG',
            'NU',
            'NF',
            'MK',
            'MP',
            'NO',
            'OM',
            'PK',
            'PW',
            'PS',
            'PA',
            'PG',
            'PY',
            'PE',
            'PH',
            'PN',
            'PL',
            'PT',
            'PR',
            'QA',
            'RO',
            'RU',
            'RW',
            'RE',
            'BL',
            'SH',
            'KN',
            'LC',
            'MF',
            'PM',
            'VC',
            'WS',
            'SM',
            'ST',
            'SA',
            'SN',
            'RS',
            'SC',
            'SL',
            'SG',
            'SX',
            'SK',
            'SI',
            'SB',
            'SO',
            'ZA',
            'GS',
            'SS',
            'ES',
            'LK',
            'SD',
            'SR',
            'SJ',
            'SE',
            'CH',
            'SY',
            'TW',
            'TJ',
            'TZ',
            'TH',
            'TL',
            'TG',
            'TK',
            'TO',
            'TT',
            'TN',
            'TM',
            'TC',
            'TV',
            'TR',
            'UG',
            'UA',
            'AE',
            'GB',
            'UM',
            'US',
            'UY',
            'UZ',
            'VU',
            'VE',
            'VN',
            'VG',
            'VI',
            'WF',
            'EH',
            'YE',
            'ZM',
            'ZW',
            'AX',
            'XE',
            'EEA',
          ],
          'ui:schema': {
            'ui:subtype': 'COUNTRY',
          },
        },
        Citizenship: {
          $ref: '#/definitions/Max100Text',
        },
        Code: {
          $ref: '#/definitions/Max50Text',
        },
        BirthDate: {
          $ref: '#/definitions/DateType',
        },
        Title: {
          $ref: '#/definitions/Max255Text',
        },
        FirstName: {
          $ref: '#/definitions/Max50Text',
        },
        LastName: {
          $ref: '#/definitions/Max50Text',
        },
        DocumentType: {
          $ref: '#/definitions/Max100Text',
        },
        DocumentNumber: {
          $ref: '#/definitions/Max100Text',
        },
        DocumentIssueDate: {
          $ref: '#/definitions/DateType',
        },
        Address: {
          $ref: '#/definitions/Max500Text',
        },
        PhoneNumber: {
          $ref: '#/definitions/Max50Text',
        },
        MainActivity: {
          $ref: '#/definitions/Max500Text',
        },
      },
      type: 'object',
    },
    AccountType: {
      required: ['Bank', 'IBAN', 'AccountOwner', 'SubjectCode'],
      properties: {
        Bank: {
          $ref: '#/definitions/Max255Text',
        },
        IBAN: {
          $ref: '#/definitions/IBANType',
        },
        AccountOwner: {
          $ref: '#/definitions/Max255Text',
        },
        OpeningDate: {
          $ref: '#/definitions/DateType',
        },
        ClosingDate: {
          $ref: '#/definitions/DateType',
        },
        OtherInformation: {
          $ref: '#/definitions/Max500Text',
        },
        SubjectCode: {
          $ref: '#/definitions/Max50Text',
        },
      },
      type: 'object',
    },
    Max11Text: {
      maxLength: 11,
      minLength: 1,
      type: 'string',
    },
    Max20Text: {
      maxLength: 20,
      minLength: 1,
      type: 'string',
    },
    Max50Text: {
      maxLength: 50,
      minLength: 1,
      type: 'string',
    },
    Max100Text: {
      maxLength: 100,
      minLength: 1,
      type: 'string',
    },
    Max255Text: {
      maxLength: 255,
      minLength: 1,
      type: 'string',
    },
    Max500Text: {
      maxLength: 500,
      minLength: 1,
      type: 'string',
    },
    Max4000Text: {
      maxLength: 4000,
      minLength: 1,
      type: 'string',
    },
    Max4000TextMinZero: {
      maxLength: 4000,
      type: 'string',
    },
    SubjectTypeCode: {
      enum: ['PERSON', 'COMPANY'],
      type: 'string',
    },
    DateType: {
      type: 'string',
      format: 'date',
    },
    Decimal20Type: {
      type: 'number',
    },
    CurrencyType: {
      pattern: '[A-Z]{3,3}',
      type: 'string',
    },
    IBANType: {
      pattern: '[A-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,50}',
      type: 'string',
    },
  },
}
