name: Deploy to QA

defaults:
  run:
    shell: bash

on:
  issue_comment:
    types: [ created ]

jobs:
  deploy:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-20.04
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '/deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_PAT }}
      - name: Get PR branch
        if: steps.check.outputs.triggered == 'true'
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch
      - name: Set latest commit status as pending
        if: steps.check.outputs.triggered == 'true'
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.DEPLOY_PAT }}
          status: pending
          context: Deploy to QA
      - name: Checkout tarpon
        if: steps.check.outputs.triggered == 'true'
        uses: actions/checkout@master
        with:
          repository: flagright/tarpon
          token: ${{ secrets.DEPLOY_PAT }}
          path: "tarpon"
      - name: Use Node.js ${{ matrix.node-version }}
        if: steps.check.outputs.triggered == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: "tarpon/package-lock.json"
      - run: npm ci
        if: steps.check.outputs.triggered == 'true'
        working-directory: "tarpon"
      - run: npm run openapi:prepare
        if: steps.check.outputs.triggered == 'true'
        working-directory: "tarpon"
      - name: Checkout PR branch
        if: steps.check.outputs.triggered == 'true'
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
          path: "phytoplankton-console"
          clean: false
      - name: Use Node.js ${{ matrix.node-version }}
        if: steps.check.outputs.triggered == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: "phytoplankton-console/yarn.lock"
      - name: Deploy
        if: steps.check.outputs.triggered == 'true'
        id: deploy
        run: |
          export QA=true
          echo "Create default AWS profile"
          mkdir ~/.aws
          printf "[default]\nregion = eu-central-1\naws_access_key_id=${{ secrets.DEV_AWS_ACCESS_KEY_ID }}\naws_secret_access_key=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials
          cat ~/.aws/credentials
          export GITHUB_USER="qa-$(echo "${{ steps.comment-branch.outputs.head_ref }}" | shasum | head -c5)"
          export S_NO=1

          comment="${{ github.event.comment.body }}"
          commentArgs=($comment)
          TARPON_BRANCH_UNTRIMMED=${commentArgs[1]}
          export TARPON_BRANCH=${TARPON_BRANCH_UNTRIMMED##*( )}
          cd tarpon
          if [ -n "$TARPON_BRANCH" ]
          then
            echo "Deploying tarpon with branch: $TARPON_BRANCH"
            git fetch origin $TARPON_BRANCH
            git checkout origin/$TARPON_BRANCH
            npm run deploy:qa
            echo "tarpon=${GITHUB_USER}-${S_NO}.api" >> $GITHUB_OUTPUT
          else
            echo "Not deploying tarpon, using api.flagright.dev instead."
            echo "tarpon=api" >> $GITHUB_OUTPUT
          fi

          echo "Deploying Phytoplankton"
          npm run openapi:prepare
          cd ../phytoplankton-console
          yarn run deploy:qa
          echo "phyto=${GITHUB_USER}-${S_NO}" >> $GITHUB_OUTPUT
      - name: Comment PR
        if: steps.check.outputs.triggered == 'true'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Branch deployed!
            Frontend: https://${{ steps.deploy.outputs.phyto }}.console.flagright.dev
            Backend: https://${{ steps.deploy.outputs.tarpon }}.flagright.dev
      - name: Set latest commit status as ${{ job.status }}
        if: steps.check.outputs.triggered == 'true'
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.DEPLOY_PAT }}
          status: ${{ job.status }}
          context: Deploy to QA
