name: Deploy Tarpon
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "tarpon/**"
jobs:
  test:
    uses: ./.github/workflows/test_tarpon.yml
  deploy:
    name: Deploy Tarpon
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        with:
          aws-region: "eu-central-1"
          aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
          pipeline-name: "tarpon-pipeline"
