name: Deploy Orca
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  test_tarpon:
    if: github.event.pull_request.merged == true
    uses: "./.github/workflows/test_tarpon.yml"
    secrets: inherit
    with:
      llm: true
  test_phytoplankton:
    if: github.event.pull_request.merged == true
    uses: "./.github/workflows/test_phyto.yml"
    secrets: inherit
  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy Orca
    runs-on: ubuntu-latest
    needs: [test_tarpon, test_phytoplankton]
    steps:
      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        with:
          aws-region: "eu-central-1"
          aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
          pipeline-name: "orca-pipeline"
        
