name: Destroy QA Env

defaults:
  run:
    shell: bash

on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  destroy:
    if: github.event.pull_request.merged == true
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Destroy
        run: |
          echo "Creating default AWS profile"
          mkdir ~/.aws
          printf "[default]\nregion = us-east-2\naws_access_key_id=${{ secrets.DEV_AWS_ACCESS_KEY_ID }}\naws_secret_access_key=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials
          cat ~/.aws/credentials

          export GITHUB_USER=${{ github.head_ref }}
          export S_NO=1

          echo "Destroying QA deploy for $GITHUB_USER-$S_NO.console.flagright.dev"
          yarn run destroy:qa

