name: Destroy QA Env

defaults:
  run:
    shell: bash

on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  destroy:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Destroy
        run: |
          echo "Creating default AWS profile"
          export NODE_OPTIONS=--max_old_space_size=8192
          mkdir ~/.aws
          printf "[default]\nregion = us-east-2\naws_access_key_id=${{ secrets.DEV_AWS_ACCESS_KEY_ID }}\naws_secret_access_key=${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials
          cat ~/.aws/credentials

          export QA_SUBDOMAIN="qa$(echo "${{ github.head_ref }}" | shasum | head -c5)"
          echo "Destroying QA deploy for $QA_SUBDOMAIN.console.flagright.dev"
          yarn run destroy:qa
