name: No test phytoplankton
on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "phytoplankton-console/**"
jobs:
  test:
    name: test-phytoplankton
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
