name: phytoplankton
on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'phytoplankton-console/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
