# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Basic CI for testing

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm run synth:local
      - run: npm run tsc
      - run: npm run lint
      - name: Setup DynamoDB localy
        uses: rrainn/dynamodb-action@v2.0.1
        with:
          port: 8000
          cors: '*'
      - name: Start MongoDB localy
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 4.4.0
          mongodb-port: 27018
      - run: npm run test:silent -- --ci
  # If we'll have more than one job in the future and we require all jobs to pass before we can
  # merge a PR. Consider to use https://github.com/marketplace/actions/alls-green (related to: https://github.com/orgs/community/discussions/26733).
  # Otherwise we'll need to manually add any new jobs to be required for the branch protection settings in the GitHub repo.
