name: Test databricks

#defaults:
#  run:
#    shell: bash
#
#concurrency:
#  group: ${{ github.ref }}-${{ github.workflow }}
#  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  pull_request:
    branches: [main]
  workflow_call:
jobs:
  test:
    timeout-minutes: 30
    name: test-databricks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Use Node.js 18x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: "databricks"
        run: poetry install
      - name: Generate sources
        working-directory: "databricks"
        run: make generate
      - name: Run checks
        working-directory: "databricks"
        run: make all_checks
