# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Basic CI for testing

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn run build:dev
      - run: yarn run lint
      - run: yarn run tsc
  # If we have more than one job in the future and we require all jobs to pass before we can
  # merge a PR. Consider to use https://github.com/marketplace/actions/alls-green (related to: https://github.com/orgs/community/discussions/26733).
  # Otherwise we'll need to manually add any new jobs to be required for the branch protection settings in the GitHub repo.
