# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Basic CI for testing

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build:local
      - run: npm run synth:local
      - run: npm run tsc
      - run: npm run lint
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v2.0.1
        with:
          port: 8000
          cors: '*'
      - run: npm run test -- --ci
  all-checks-passed:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - run: echo "All checks passed!"
