# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tarpon

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [main]
    paths:
      - "tarpon/**"
jobs:
  test:
    name: test-tarpon
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "tarpon/package-lock.json"
      - name: Cache jest results
        uses: actions/cache@v3
        with:
          path: ~/.jest-cache
          key: jest-cache
      - run: npm ci
        working-directory: "tarpon"
      - run: npm run build:local
        working-directory: "tarpon"
      - run: npm run tsc
        working-directory: "tarpon"
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
      - run: npm run lint
        working-directory: "tarpon"
      - run: npm run format:check
        working-directory: "tarpon"
      - name: Setup DynamoDB localy
        uses: rrainn/dynamodb-action@v2.0.1
        with:
          port: 7999
          cors: "*"
      - name: Start MongoDB localy
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0.18
          mongodb-port: 27018
      - name: Run Tests
        env:
          NODE_OPTIONS: --max-old-space-size=8192
        run: npm run test:ci
        working-directory: "tarpon"
  # If we'll have more than one job in the future and we require all jobs to pass before we can
  # merge a PR. Consider to use https://github.com/marketplace/actions/alls-green (related to: https://github.com/orgs/community/discussions/26733).
  # Otherwise we'll need to manually add any new jobs to be required for the branch protection settings in the GitHub repo.
