# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test tarpon

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  pull_request:
    branches: [main]
    paths:
      - "tarpon/**"
  workflow_call:
jobs:
  test:
    runs-on: large
    timeout-minutes: 30
    name: test-tarpon
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 18x
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1
          cache: "npm"
          cache-dependency-path: "tarpon/package-lock.json"
      - name: Cache jest results
        uses: actions/cache@v3
        with:
          path: ~/.jest-cache
          key: jest-cache
      - name: Build Flagright Lib
        run: npm ci
        working-directory: "lib"
      - run: npm ci
        working-directory: "tarpon"
      - run: npm run build:local
        working-directory: "tarpon"
      - run: npm run tsc:ci
        working-directory: "tarpon"
      - run: npm run lint:ci
        working-directory: "tarpon"
      - run: npm run format:check
        working-directory: "tarpon"
      - name: Setup DynamoDB localy
        uses: rrainn/dynamodb-action@v2.0.1
        with:
          port: 7999
          cors: "*"
      - name: Start MongoDB localy
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0.18
          mongodb-port: 27018
      - name: Run Tests
        run: npm run test:ci
        working-directory: "tarpon"
      - name: Post to a Slack channel on failure
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        if: ${{ failure() && github.ref_name == 'main' }}
        with:
          channel-id: "C03L5KRE2E8"
          payload: |
            {
              "text": "main branch failed for tarpon!"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
